import type { SilverQuestion } from "../quizTypes";

/** 例外処理・標準 API の論点を拡充する追加問題（id 301 以降） */
export const extraQuestions4: SilverQuestion[] = [
  // ======================================================= 例外 (exceptions)
  {
    id: 301,
    topic: "exceptions",
    variantOf: "exceptions-hierarchy",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Hierarchy",
    code: [
      "public class Hierarchy {",
      "    public static void main(String[] args) {",
      "        try {",
      '            throw new IllegalArgumentException("x");',
      "        } catch (Exception e) {",
      "            System.out.print(e instanceof RuntimeException);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["true", "false", "コンパイルエラーになる", "実行時に例外がスローされて終了する"],
    correct: [0],
    expected: { kind: "output", stdout: "true" },
    explanation:
      "例外の階層は Throwable を頂点に Error と Exception に分かれ、Exception の下に RuntimeException があります。IllegalArgumentException は RuntimeException の派生なので instanceof は true です。catch (Exception) が非検査例外まで捕まえてしまうのはこの階層構造のためで、意図せず握りつぶす原因になります。Error（OutOfMemoryError など）は Exception の系統ではないため catch (Exception) では捕まりません。回復不能な異常は捕まえるべきではない、という考えが階層に反映されています。",
  },
  {
    id: 302,
    topic: "exceptions",
    variantOf: "exceptions-catch-order-unreachable",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "CatchOrder",
    code: [
      "public class CatchOrder {",
      "    public static void main(String[] args) {",
      "        try {",
      '            System.out.print("t");',
      "        } catch (Exception e) {",
      '            System.out.print("e");',
      "        } catch (IllegalStateException e) {",
      '            System.out.print("i");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "7行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、t が出力される",
      "コンパイルは成功し、ti が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "catch 節は上から順に照合されるため、先に Exception を捕まえると、その派生型である IllegalStateException の catch には決して到達できません。コンパイラはこれを到達不能コードとしてエラーにします。書き間違いを実行時ではなくコンパイル時に潰せるのは、例外の型階層が静的に分かっているからこそです。したがって catch は必ず「具体的な型から順に、広い型は最後に」並べます。マルチキャッチ（|）で並べる型に継承関係がある場合も、同じ理由でコンパイルエラーになります。",
  },
  {
    id: 303,
    topic: "exceptions",
    variantOf: "exceptions-finally-after-return",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Always",
    code: [
      "public class Always {",
      "    static void run() {",
      "        try {",
      '            throw new RuntimeException("x");',
      "        } catch (RuntimeException e) {",
      '            System.out.print("c");',
      "            return;",
      "        } finally {",
      '            System.out.print("f");',
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        run();",
      "    }",
      "}",
    ],
    choices: ["cf", "c", "fc", "cfc", "実行時に例外がスローされて終了する"],
    correct: [0],
    expected: { kind: "output", stdout: "cf" },
    explanation:
      "catch の中で return しても、メソッドを抜ける直前に finally が実行されます。出力は c のあと f です。finally が「必ず通る」ことを言語が保証しているからこそ、リソース解放やロック解除を安心して置けます。例外的に実行されないのは System.exit を呼んだ場合や JVM 自体が落ちた場合だけです。この保証を逆手に取って finally で return や throw を書くと、本来の戻り値や例外を上書きしてしまうため、finally には後始末以外を書かないのが鉄則です。",
  },
  {
    id: 304,
    topic: "exceptions",
    variantOf: "exceptions-custom-exception",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Custom",
    code: [
      "class AppException extends Exception {",
      "    AppException(String message) {",
      "        super(message);",
      "    }",
      "}",
      "",
      "public class Custom {",
      "    static void run() throws AppException {",
      '        throw new AppException("failed");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        try {",
      "            run();",
      "        } catch (AppException e) {",
      "            System.out.print(e.getMessage());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["failed", "null", "AppException", "コンパイルエラーになる", "実行時に例外がスローされて終了する"],
    correct: [0],
    expected: { kind: "output", stdout: "failed" },
    explanation:
      "Exception を継承すると検査例外になり、呼び出し側は catch か throws を強制されます。メッセージは super(message) で親に渡すことで getMessage() から取り出せます。独自例外を定義する価値は、呼び出し側が「どの失敗か」を型で判別でき、catch を書き分けられる点にあります。汎用的な RuntimeException を投げてメッセージだけで区別させると、呼び出し側は文字列比較に頼らざるを得ません。なお回復の余地がない失敗なら、RuntimeException を継承して非検査例外にする選択も一般的です。",
  },
  {
    id: 305,
    topic: "exceptions",
    variantOf: "exceptions-throws-override",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Impl2",
    code: [
      "import java.io.IOException;",
      "",
      "class Base {",
      "    void run() {",
      "    }",
      "}",
      "",
      "public class Impl2 extends Base {",
      "    @Override",
      "    void run() throws IOException {",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "    }",
      "}",
    ],
    choices: [
      "親が宣言していない検査例外を追加できないためコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "@Override が付いているためコンパイルエラーになる",
      "実行時に IOException がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "オーバーライドでは、親が宣言していない検査例外を新たに投げると宣言できません。Base 型の変数経由で run() を呼ぶ利用者は例外処理を書いていないため、実体が Impl2 のときだけ想定外の例外が飛んでくると破綻するからです。例外を減らす（宣言しない、または派生型に狭める）のは許されます。戻り値やアクセス修飾子の規則と同じく、「派生型は基底型として通用しなければならない」という原則の現れです。なお非検査例外にはこの制限がなく、いつでも投げられます。",
  },
  {
    id: 306,
    topic: "exceptions",
    variantOf: "exceptions-nested-try",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Nested",
    code: [
      "public class Nested {",
      "    public static void main(String[] args) {",
      "        try {",
      "            try {",
      '                throw new RuntimeException("inner");',
      "            } finally {",
      '                System.out.print("if ");',
      "            }",
      "        } catch (RuntimeException e) {",
      '            System.out.print("outer");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["if outer", "outer if", "if", "outer", "実行時に例外がスローされて終了する"],
    correct: [0],
    expected: { kind: "output", stdout: "if outer" },
    explanation:
      "内側の try には catch が無いので、finally を実行してから例外が外側へ伝播します。そのため if が先、outer が後になります。例外は捕捉されるまで呼び出し階層を遡り、その過程で通過する finally は必ず実行されます。この「伝播の途中でも後始末は行われる」仕組みがあるおかげで、途中の階層は例外を捕まえずに素通りさせつつ、自分が確保した資源だけを確実に解放できます。捕まえられる場所でだけ catch する、という設計が可能になっています。",
  },
  {
    id: 307,
    topic: "exceptions",
    variantOf: "exceptions-propagation",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Propagate",
    code: [
      "public class Propagate {",
      "    static void outer() {",
      "        inner();",
      "    }",
      "",
      "    static void inner() {",
      '        throw new IllegalStateException("x");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        try {",
      "            outer();",
      "        } catch (IllegalStateException e) {",
      '            System.out.print("caught");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "caught",
      "outer と inner に throws が無いためコンパイルエラーになる",
      "実行時に IllegalStateException がスローされて終了する",
      "何も出力されない",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "caught" },
    explanation:
      "例外は捕捉されるまで呼び出し元へ遡ります。inner で発生した例外は outer を素通りし、main の catch で捕まります。IllegalStateException は非検査例外なので、途中のメソッドに throws 宣言は不要です。この仕組みの利点は、失敗の検出地点と対処地点を分離できることにあります。低レベルの処理は「できない」ことを投げるだけでよく、どう扱うかを知っている上位の層が判断できます。戻り値でエラーコードを返す方式と違い、途中の階層が伝播を書き忘れて握りつぶすことがありません。",
  },
  {
    id: 308,
    topic: "exceptions",
    variantOf: "exceptions-twr-final",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Reassign",
    code: [
      "class Handle2 implements AutoCloseable {",
      "    @Override",
      "    public void close() {",
      "    }",
      "}",
      "",
      "public class Reassign {",
      "    public static void main(String[] args) {",
      "        try (Handle2 h = new Handle2()) {",
      "            h = new Handle2();",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "リソース変数は暗黙的に final のためコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "実行時に例外がスローされる",
      "close() が 2 回呼ばれる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "try-with-resources で宣言した変数は暗黙的に final となり、再代入できません。もし差し替えを許すと、try を抜けるときに閉じるべき対象が最初に確保したものか差し替え後のものか曖昧になり、確実にクローズするという保証が崩れるからです。この制約により「括弧内で確保したものを、括弧を出るときに必ず閉じる」という対応関係が守られます。Java 9 以降は、すでに実質的 final なローカル変数であれば try (existing) のように変数名だけを書くこともできます。",
  },
  {
    id: 309,
    topic: "exceptions",
    variantOf: "exceptions-arithmetic-division",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Zero",
    code: [
      "public class Zero {",
      "    public static void main(String[] args) {",
      "        System.out.print(1.0 / 0);",
      '        System.out.print(" ");',
      "        System.out.print(1 / 0);",
      "    }",
      "}",
    ],
    choices: [
      "Infinity と出力されたあと ArithmeticException がスローされる",
      "Infinity 0 と出力される",
      "Infinity Infinity と出力される",
      "コンパイルエラーになる",
      "0.0 と出力されたあと ArithmeticException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ArithmeticException" },
    explanation:
      "浮動小数点数の除算は IEEE 754 に従い、0 で割ると例外ではなく Infinity（0.0 / 0.0 なら NaN）になります。一方、整数の除算に対応する値は存在しないため ArithmeticException が投げられます。浮動小数点が例外を投げないのは、数値計算では途中で停止するより無限大や NaN を伝播させて最後に判定する方が都合がよいという設計思想によるものです。同じ「0 で割る」という操作でも型によって結果が根本的に変わるため、除算前のゼロチェックは整数演算でこそ重要になります。",
  },

  // ================================================================= API (api)
  {
    id: 311,
    topic: "api",
    variantOf: "api-arraylist-insert",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Basic",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Basic {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>();",
      '        list.add("a");',
      '        list.add(0, "b");',
      '        System.out.println(list.get(0) + " " + list.size() + " " + list.contains("a"));',
      "    }",
      "}",
    ],
    choices: ["b 2 true", "a 2 true", "b 2 false", "a 1 true", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "b 2 true" },
    explanation:
      'add(E) は末尾に追加し、add(int, E) は指定位置に挿入して以降の要素を後ろへずらします。結果は ["b", "a"] なので、先頭は b、サイズは 2、"a" は含まれるので true です。contains が内容で判定できるのは、String が equals を正しく実装しているからで、内部では equals による線形探索が行われています。ArrayList は配列を土台にしているため末尾への追加は高速ですが、先頭への挿入は後続要素の移動が必要で、要素数に比例したコストがかかる点も押さえておきましょう。',
  },
  {
    id: 312,
    topic: "api",
    variantOf: "api-string-split",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Split",
    code: [
      "public class Split {",
      "    public static void main(String[] args) {",
      '        String csv = "a,b,,c";',
      '        String[] parts = csv.split(",");',
      '        System.out.println(parts.length + " [" + parts[2] + "]");',
      "    }",
      "}",
    ],
    choices: ["4 []", "3 [c]", "4 [c]", "3 []", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "4 []" },
    explanation:
      '区切り文字が連続している箇所は、長さ 0 の文字列として要素になります。したがって ["a", "b", "", "c"] の 4 要素で、添字 2 は空文字列です。ただし末尾の空要素は既定で取り除かれるため "a,b,,".split(",") は 3 要素になります（第 2 引数に -1 を渡すと残ります）。split の引数は単なる文字ではなく正規表現である点も重要で、"." や "|" で区切りたい場合はエスケープが必要です。この二つの落とし穴は CSV の解析でよく問題になります。',
  },
  {
    id: 313,
    topic: "api",
    variantOf: "api-string-format",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Fmt",
    code: [
      "public class Fmt {",
      "    public static void main(String[] args) {",
      '        System.out.println(String.format("%s=%d%%", "rate", 50));',
      "    }",
      "}",
    ],
    choices: ["rate=50%", "rate=50%%", "%s=%d%%", "rate=50", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "rate=50%" },
    explanation:
      "%s は文字列、%d は整数に置き換わり、%% はパーセント記号そのものを表します。書式指定子が特別な意味を持つ以上、記号自身を出したいときはエスケープが必要になる、という一般的な設計です。%d に文字列を渡すなど型が合わないと、コンパイルは通るのに実行時に IllegalFormatConversionException になる点に注意してください。書式文字列は実行時に解釈されるため、コンパイラが引数の対応を検査できないからです。可読性の面では、単純な連結より意図が明確になる利点があります。",
  },
  {
    id: 314,
    topic: "api",
    variantOf: "api-math-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MathUse",
    code: [
      "public class MathUse {",
      "    public static void main(String[] args) {",
      '        System.out.println(Math.max(2, 3) + " " + Math.abs(-4) + " " + Math.round(2.5));',
      "    }",
      "}",
    ],
    choices: ["3 4 3", "3 4 2", "3 -4 3", "2 4 3", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 4 3" },
    explanation:
      "Math.round は「最も近い整数、ちょうど中間なら正の無限大方向」へ丸めるため 2.5 は 3 になります（-2.5 は -2 になる点が四捨五入と異なります）。実装上は floor(x + 0.5) と等価で、この定義のおかげで分岐なしに計算できます。Math のメソッドはすべて static で、インスタンスを作らずに使う純粋な関数として提供されています。なお round の戻り値は引数が double なら long、float なら int になるため、int 変数へ代入する際はキャストが必要になることがあります。",
  },
  {
    id: 315,
    topic: "api",
    variantOf: "api-localdate-month-end",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MonthEnd",
    code: [
      "import java.time.LocalDate;",
      "",
      "public class MonthEnd {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2026, 1, 31).plusMonths(1);",
      "        System.out.println(date);",
      "    }",
      "}",
    ],
    choices: ["2026-02-28", "2026-03-03", "2026-02-31", "実行時に DateTimeException がスローされる", "2026-01-31"],
    correct: [0],
    expected: { kind: "output", stdout: "2026-02-28" },
    explanation:
      "1 月 31 日の 1 か月後にあたる 2 月 31 日は存在しないため、その月の最終日に補正されて 2 月 28 日になります（2026 年は閏年ではありません）。例外にせず補正するのは、「1 か月後」という人間の感覚に沿った結果を返すためです。ただしこの補正は不可逆で、さらに 1 か月戻しても 1 月 31 日には戻りません。月単位の加減算を繰り返すと日付がずれていくため、月末を基準にした計算では意図を明示できる TemporalAdjusters.lastDayOfMonth などを使う方が安全です。",
  },
  {
    id: 316,
    topic: "api",
    variantOf: "api-contains-equals",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Lookup",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Lookup {",
      "    public static void main(String[] args) {",
      "        List<StringBuilder> list = new ArrayList<>();",
      '        list.add(new StringBuilder("a"));',
      '        System.out.println(list.contains(new StringBuilder("a")));',
      "    }",
      "}",
    ],
    choices: ["false", "true", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "false" },
    explanation:
      "contains は内部で equals による比較を行います。StringBuilder は equals をオーバーライドしておらず参照の同一性で判定されるため、中身が同じでも別インスタンスなら false です。コレクションの検索・重複判定はすべて格納する型の equals（ハッシュ系なら hashCode も）に依存している、という点がここでの本質です。自作クラスを List や Set に入れて「入れたはずの値が見つからない」という症状に遭遇したら、まず equals と hashCode を実装しているかを疑ってください。",
  },
  {
    id: 317,
    topic: "api",
    variantOf: "api-integer-overflow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Limit",
    code: [
      "public class Limit {",
      "    public static void main(String[] args) {",
      "        System.out.println(Integer.MAX_VALUE + 1);",
      "    }",
      "}",
    ],
    choices: [
      "-2147483648",
      "2147483648",
      "2147483647",
      "実行時に ArithmeticException がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "-2147483648" },
    explanation:
      "int は 32 ビットで表せる範囲を超えると、例外を投げずに最小値へ回り込みます（ラップアラウンド）。最大値に 1 を足すと最小値になるのはそのためです。オーバーフローを検出しないのは、検査のコストを避けて CPU の演算をそのまま使うという性能上の判断です。この挙動は、経過時間の計算やインデックスの加算で静かに誤った値を生みます。検出したい場合は Math.addExact を使うと ArithmeticException が投げられ、大きな値を扱うなら long や BigInteger を選びます。",
  },
  {
    id: 318,
    topic: "api",
    variantOf: "api-remove-index-shift",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Shrink",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Shrink {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>();",
      '        list.add("a");',
      '        list.add("b");',
      '        list.add("c");',
      "        for (int i = 0; i < list.size(); i++) {",
      "            list.remove(i);",
      "        }",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[b]",
      "[]",
      "[a, b, c]",
      "実行時に IndexOutOfBoundsException がスローされる",
      "実行時に ConcurrentModificationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[b]" },
    explanation:
      "要素を削除すると後続が前に詰まり、同時に size も減ります。i=0 で a を削除すると残りは [b, c]、i=1 では c が削除されて [b] となり、i=2 では条件 i < 1 が偽になって終了します。結果として b が削除されずに残ります。添字を進めながら削除すると 1 つ飛ばしになる、という典型的な不具合で、例外が出ないぶん気づきにくいのが厄介です。削除しながら走査するなら、末尾から逆向きに回すか、イテレータの remove、あるいは removeIf を使います。",
  },
];
