import type { SilverQuestion } from "../quizTypes";

/**
 * 出題範囲にあるのに未カバーだった論点の補充（id 401 以降）。
 * 対策教材で繰り返し扱われる頻出の引っかけどころを中心に追加している。
 */
export const extraQuestions6: SilverQuestion[] = [
  // ============================================================ 基本 (basics)
  {
    id: 401,
    topic: "basics",
    variantOf: "basics-wildcard-import",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Wild",
    code: [
      "import java.util.*;",
      "",
      "public class Wild {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>();",
      "        TimeUnit unit = TimeUnit.SECONDS;",
      "        System.out.println(list.size());",
      "    }",
      "}",
    ],
    choices: [
      "TimeUnit が解決できないためコンパイルエラーになる",
      "コンパイルは成功し、0 が出力される",
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、SECONDS が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "アスタリスクのインポートが対象とするのは、そのパッケージ直下の型だけです。TimeUnit は java.util.concurrent という別のパッケージにあるため、java.util.* では解決できません。サブパッケージが自動的に含まれないのは、パッケージが階層構造ではなく「名前が . を含む平たい識別子」として扱われているからです。java.util と java.util.concurrent は名前が似ているだけの別パッケージであり、親子関係はありません。この前提を知っていると、インポート漏れの原因を素早く特定できます。",
  },
  {
    id: 402,
    topic: "basics",
    variantOf: "basics-class-access-modifier",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Outer",
    code: [
      "public class Outer {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Internal().value);",
      "    }",
      "}",
      "",
      "private class Internal {",
      "    int value = 1;",
      "}",
    ],
    choices: [
      "トップレベルのクラスに private を付けられないためコンパイルエラーになる",
      "コンパイルは成功し、1 が出力される",
      "3行目でコンパイルエラーになる",
      "コンパイルは成功し、0 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "トップレベルのクラスに付けられるアクセス修飾子は public か、修飾子なし（パッケージプライベート）だけです。private や protected は付けられません。private は「囲んでいる型の中だけで見える」という意味ですが、トップレベルのクラスには囲む型が存在せず、誰からも参照できない宣言になってしまうため禁止されています。protected も「サブクラスから見える」という継承関係を前提とした修飾子で、トップレベルでは意味を持ちません。ネストしたクラスであれば private を付けられます。",
  },
  {
    id: 403,
    topic: "basics",
    variantOf: "basics-source-file-mode",
    question:
      "Java SE 11 で、次の内容を持つファイル Hello.java がある。このファイルの実行方法として正しいものはどれか。1つ選びなさい。",
    code: [
      "public class Hello {",
      "    public static void main(String[] args) {",
      '        System.out.println("hello");',
      "    }",
      "}",
    ],
    choices: [
      "javac を実行せずに java Hello.java とすると、コンパイルされて実行される",
      "java Hello.java とすると、必ず先に javac Hello.java が必要だというエラーになる",
      "javac Hello.java のあとに java Hello.class と指定して実行する",
      "java Hello.java は Java SE 11 では使用できない",
    ],
    correct: [0],
    className: "Hello",
    expected: { kind: "output", stdout: "hello" },
    // javac を介さず java Hello.java として実行し、実際に動くことを確認する
    runAsSourceFile: true,
    explanation:
      "Java SE 11 で追加されたソースファイルモードにより、単一ファイルのプログラムは javac を挟まず java Hello.java で直接実行できます。内部ではメモリ上でコンパイルされ、class ファイルは生成されません。これは学習用の小さなプログラムや使い捨てのスクリプトのために用意された機能で、Java を試す際の敷居を下げる狙いがあります。複数ファイルに分かれたプログラムや外部ライブラリを使う場合は従来どおり javac が必要です。なお実行時に指定するのはソースファイル名（拡張子付き）である点に注意してください。",
  },

  // ==================================================== データ型 (datatypes)
  {
    id: 404,
    topic: "datatypes",
    variantOf: "datatypes-implicit-widening",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Widen",
    code: [
      "public class Widen {",
      "    public static void main(String[] args) {",
      "        int i = 10;",
      "        long l = i;",
      "        float f = l;",
      "        double d = f;",
      '        System.out.println(l + " " + f + " " + d);',
      "    }",
      "}",
    ],
    choices: [
      "10 10.0 10.0",
      "10 10 10",
      "キャストが必要なためコンパイルエラーになる",
      "10.0 10.0 10.0",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "10 10.0 10.0" },
    explanation:
      "byte → short → int → long → float → double の順に、情報が失われない方向への変換は暗黙に行われます（拡大変換）。long から float は桁数が落ちる可能性があるのに暗黙変換が許されるのは、表現できる値の範囲が広がるためで、精度と範囲を区別しているからです。逆方向は明示的なキャストが必要になります。なお char は int 以上へ暗黙変換されますが、char と short は互いに暗黙変換できません。符号の有無が異なり、どちらも相手の全範囲を表現できないためです。",
  },
  {
    id: 405,
    topic: "datatypes",
    variantOf: "datatypes-int-literal-narrowing",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Small",
    code: [
      "public class Small {",
      "    public static void main(String[] args) {",
      "        byte a = 10;",
      "        final int limit = 20;",
      "        byte b = limit;",
      "        int value = 30;",
      "        byte c = value;",
      '        System.out.println(a + " " + b + " " + c);',
      "    }",
      "}",
    ],
    choices: [
      "7行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、10 20 30 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "int のリテラルや定数式は、値が byte の範囲に収まることをコンパイラが確認できる場合に限り、キャストなしで代入できます。10 も final int の 20 もコンパイル時に値が確定するため通ります。一方 7 行目の value は final ではない変数で、代入時点の値をコンパイラが保証できないためエラーになります。「実際の値が範囲内かどうか」ではなく「コンパイル時に確定しているか」が判断基準である点が要点で、final を外すだけで通っていたコードが壊れるのはこのためです。",
  },
  {
    id: 406,
    topic: "datatypes",
    variantOf: "datatypes-null-primitive",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Empty",
    code: [
      "public class Empty {",
      "    public static void main(String[] args) {",
      "        Integer boxed = null;",
      "        int primitive = null;",
      "        System.out.println(boxed);",
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "コンパイルは成功し、null が出力される",
      "コンパイルは成功し、実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "null は参照型の変数にしか代入できません。プリミティブ型の変数は値そのものを保持する領域であり、「どこも指していない」という状態を表現できないからです。ラッパー型は参照型なので null を保持できます。この違いがあるため、null の入った Integer を int に代入（アンボクシング）すると実行時に NullPointerException が発生します。数値を扱う API でラッパー型が返る場合、null チェックを怠ると意外な箇所で NullPointerException になるのはこの仕組みによるものです。",
  },
  {
    id: 407,
    topic: "datatypes",
    variantOf: "datatypes-null-concat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Label",
    code: [
      "public class Label {",
      "    public static void main(String[] args) {",
      "        String value = null;",
      '        System.out.println("x" + value);',
      "    }",
      "}",
    ],
    choices: [
      "xnull",
      "x",
      "実行時に NullPointerException がスローされる",
      "xnullptr",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "xnull" },
    explanation:
      '文字列連結では、null は文字列 "null" に変換されて連結されます。例外にならないのは、連結が内部的に String.valueOf を経由し、そこで null が特別扱いされているためです。一方 "x".concat(value) のようにメソッドを呼ぶ形では、引数の null をそのまま扱おうとして NullPointerException になります。同じ「文字列をつなぐ」操作でも、演算子とメソッドで null の扱いが異なるということです。ログ出力で意図せず null という文字が現れるのはこの仕様によるもので、値の不在を検出したいなら明示的に判定する必要があります。',
  },
  {
    id: 408,
    topic: "datatypes",
    variantOf: "datatypes-literal-suffix",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Suffix",
    code: [
      "public class Suffix {",
      "    public static void main(String[] args) {",
      "        long big = 10000000000L;",
      "        float ratio = 1.5F;",
      "        double d = 1.5;",
      "        long wrong = 10000000000;",
      '        System.out.println(big + " " + ratio + " " + d);',
      "    }",
      "}",
    ],
    choices: [
      "6行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、10000000000 1.5 1.5 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "整数リテラルは既定で int として扱われるため、int の範囲を超える値には L を付けて long リテラルにする必要があります。6 行目は代入先が long であっても、リテラル自体が int として解釈される時点で範囲を超えておりエラーになります。同様に小数リテラルは既定で double なので、float に代入するには F が必要です。リテラルの型が「代入先ではなくリテラルの書き方で決まる」という原則を押さえておくと、この種のエラーを予測できます。",
  },
  {
    id: 409,
    topic: "datatypes",
    variantOf: "datatypes-stringbuilder-capacity",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Capacity",
    code: [
      "public class Capacity {",
      "    public static void main(String[] args) {",
      "        StringBuilder empty = new StringBuilder();",
      '        StringBuilder text = new StringBuilder("abc");',
      '        System.out.println(empty.length() + " " + text.length() + " " + empty.capacity());',
      "    }",
      "}",
    ],
    choices: ["0 3 16", "16 3 16", "0 3 0", "0 3 19", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "0 3 16" },
    explanation:
      "length() は実際に保持している文字数、capacity() は再確保せずに格納できる容量です。引数なしのコンストラクタでは容量 16 で始まり、長さは 0 です。両者が別概念なのは、StringBuilder が内部で配列を使っており、追記のたびに配列を作り直さずに済むよう余裕を持たせているからです。容量が足りなくなると、より大きな配列へ確保し直してコピーします。あらかじめ必要な大きさが分かっているなら new StringBuilder(1000) のように指定すると、この再確保を避けられます。",
  },

  // ======================================================== 制御構造 (control)
  {
    id: 410,
    topic: "control",
    variantOf: "control-if-without-braces",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Braces",
    code: [
      "public class Braces {",
      "    public static void main(String[] args) {",
      "        int value = 10;",
      "        if (value > 100)",
      '            System.out.print("big ");',
      '            System.out.print("done");',
      "    }",
      "}",
    ],
    choices: ["done", "big done", "何も出力されない", "big", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "done" },
    explanation:
      "波括弧を省略した if が支配するのは直後の 1 文だけです。インデントは人間が読むための体裁にすぎず、コンパイラには意味を持ちません。したがって 2 つ目の出力は if の外にあり、条件に関係なく実行されます。この挙動は、条件分岐に文を追加したつもりが実は無条件に実行されていた、という重大なバグを生みます（有名な goto fail 脆弱性も同種の誤りでした）。1 文であっても常に波括弧を書く、というコーディング規約が広く採用されているのはこのためです。",
  },
  {
    id: 411,
    topic: "control",
    variantOf: "control-switch-case-constant",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "CaseValue",
    code: [
      "public class CaseValue {",
      "    public static void main(String[] args) {",
      "        final int allowed = 1;",
      "        int denied = 2;",
      "        int input = 1;",
      "        switch (input) {",
      "            case allowed:",
      '                System.out.print("a");',
      "                break;",
      "            case denied:",
      '                System.out.print("d");',
      "                break;",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "10行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "コンパイルは成功し、a が出力される",
      "コンパイルは成功し、d が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 10 },
    explanation:
      "case に書けるのはコンパイル時に値が確定する定数式だけです。final で初期化済みの allowed は定数として扱えますが、final でない denied は実行時まで値が分からないため使えません。この制約があるのは、switch が値から飛び先を決める表に変換される仕組みで、飛び先の対応表をコンパイル時に作る必要があるからです。同じ理由で case の値が重複していてもコンパイルエラーになります。条件が実行時にしか決まらないなら if-else で書く必要があります。",
  },
  {
    id: 412,
    topic: "control",
    variantOf: "control-switch-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SwitchNull",
    code: [
      "public class SwitchNull {",
      "    public static void main(String[] args) {",
      "        String command = null;",
      "        switch (command) {",
      '            case "run":',
      '                System.out.print("r");',
      "                break;",
      "            default:",
      '                System.out.print("d");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "実行時に NullPointerException がスローされる",
      "d と出力される",
      "何も出力されない",
      "コンパイルエラーになる",
      "r と出力される",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException" },
    explanation:
      "String を使った switch は、内部でハッシュ値を求めて比較する仕組みのため、対象が null だとその時点で NullPointerException になります。default があっても捕まりません。default は「どの case にも一致しなかった場合」であって「値が無い場合」ではない、という区別が重要です。文字列で分岐する箇所では switch に渡す前に null を弾く必要があります。なお Java 21 以降のパターンマッチングでは case null を書けるようになりましたが、SE 11 では不可です。",
  },
  {
    id: 413,
    topic: "control",
    variantOf: "control-for-type-mixing",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "MixedFor",
    code: [
      "public class MixedFor {",
      "    public static void main(String[] args) {",
      "        for (int i = 0, long j = 0; i < 3; i++) {",
      '            System.out.print("*");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "初期化部で複数の型を宣言できないためコンパイルエラーになる",
      "コンパイルは成功し、*** が出力される",
      "コンパイルは成功し、* が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "for 文の初期化部で変数を宣言する場合、書けるのは 1 つの型だけです。カンマで区切って複数の変数を宣言できますが、すべて同じ型でなければなりません。これは通常の変数宣言文（int a = 1, b = 2;）と同じ規則で、for 文だけが特別なわけではありません。異なる型が必要なら、片方を for 文の外で宣言します。なお初期化部には宣言だけでなく代入式も書けるため、外で宣言した変数に対して for (i = 0, j = 0; ...) とするのは可能です。",
  },
];
