import type { SilverQuestion } from "../quizTypes";

/** 未カバーだった論点の補充・後半（id 421 以降） */
export const extraQuestions7: SilverQuestion[] = [
  // ============================================================ 配列 (arrays)
  {
    id: 421,
    topic: "arrays",
    variantOf: "arrays-size-required",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "NoSize",
    code: [
      "public class NoSize {",
      "    public static void main(String[] args) {",
      "        int[] values = new int[];",
      "        System.out.println(values.length);",
      "    }",
      "}",
    ],
    choices: [
      "要素数が指定されていないためコンパイルエラーになる",
      "コンパイルは成功し、0 が出力される",
      "実行時に NegativeArraySizeException がスローされる",
      "コンパイルは成功し、要素数 0 の配列が作られる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 3 },
    explanation:
      "new による配列生成では必ず要素数を指定します。要素数 0 の配列が欲しい場合は new int[0] と明示します。配列は生成時に長さが決まり、以後変更できない構造なので、長さを決めずに確保することはできません。要素を並べて書く new int[] {1, 2} の形では、並べた個数から長さが決まるため要素数を書きません（むしろ書くとエラーになります）。「長さは必ずどこかで確定させる」という一貫した規則になっています。",
  },
  {
    id: 422,
    topic: "arrays",
    variantOf: "arrays-clone-shallow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CloneArray",
    code: [
      "public class CloneArray {",
      "    public static void main(String[] args) {",
      "        int[][] original = {{1, 2}, {3, 4}};",
      "        int[][] copy = original.clone();",
      "        copy[0][0] = 9;",
      '        System.out.println(original[0][0] + " " + (original[0] == copy[0]));',
      "    }",
      "}",
    ],
    choices: ["9 true", "1 false", "1 true", "9 false", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "9 true" },
    explanation:
      "配列の clone() は浅いコピーです。多次元配列の実体は「配列を要素に持つ配列」なので、コピーされるのは内側の配列への参照だけで、内側そのものは共有されます。そのため copy 経由の書き換えが original からも見え、参照比較も true になります。深くコピーしたいなら各要素を個別に clone する必要があります。要素が参照型であれば 1 次元配列でも同じことが起こるため、「コピーしたから安全」と考えるのは危険です。Arrays.copyOf も同じく浅いコピーです。",
  },

  // ========================================================== メソッド (methods)
  {
    id: 423,
    topic: "methods",
    variantOf: "methods-protected-access",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "AccessCheck",
    code: [
      "class Settings {",
      "    protected int value = 1;",
      "    int packagePrivate = 2;",
      "    private int secret = 3;",
      "}",
      "",
      "public class AccessCheck extends Settings {",
      "    public static void main(String[] args) {",
      "        AccessCheck c = new AccessCheck();",
      '        System.out.println(c.value + " " + c.packagePrivate + " " + c.secret);',
      "    }",
      "}",
    ],
    choices: [
      "10行目でコンパイルエラーになる",
      "コンパイルは成功し、1 2 3 が出力される",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功し、1 2 0 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 10 },
    explanation:
      "protected はサブクラスと同一パッケージから、修飾子なしは同一パッケージから参照できますが、private は宣言したクラスの中だけです。ここでは同じファイル（同じパッケージ）なので protected と修飾子なしは参照でき、secret だけがエラーになります。アクセス修飾子は public → protected → 修飾子なし → private の順に範囲が狭まりますが、protected と修飾子なしは「サブクラスを含むか」という軸が加わるため単純な包含関係ではない点に注意してください。別パッケージのサブクラスからは protected だけが見えます。",
  },

  // ==================================================== 継承 (inheritance)
  {
    id: 424,
    topic: "inheritance",
    variantOf: "inheritance-constructor-not-inherited",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "UseChild",
    code: [
      "class Machine {",
      "    Machine(int value) {",
      "    }",
      "",
      "    Machine() {",
      "    }",
      "}",
      "",
      "class Robot extends Machine {",
      "}",
      "",
      "public class UseChild {",
      "    public static void main(String[] args) {",
      "        new Robot(5);",
      "    }",
      "}",
    ],
    choices: [
      "コンストラクタは継承されないためコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "Robot にコンストラクタが無いためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 14 },
    explanation:
      "コンストラクタは継承されません。Robot には引数なしの既定コンストラクタだけが自動生成されるため、new Robot(5) は該当するコンストラクタが無くエラーになります。継承されないのは、コンストラクタが「その型を正しく初期化する手順」であり、フィールドが増えたサブクラスに親の手順をそのまま適用しても初期化が完結しないからです。親の引数を受け取りたい場合は、子で同じ形のコンストラクタを定義して super(value) を呼ぶ必要があります。",
  },
  {
    id: 425,
    topic: "inheritance",
    variantOf: "inheritance-interface-super",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Resolver",
    code: [
      "interface Left {",
      "    default String name() {",
      '        return "left";',
      "    }",
      "}",
      "",
      "interface Right {",
      "    default String name() {",
      '        return "right";',
      "    }",
      "}",
      "",
      "public class Resolver implements Left, Right {",
      "    @Override",
      "    public String name() {",
      "        return Left.super.name();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Resolver().name());",
      "    }",
      "}",
    ],
    choices: ["left", "right", "あいまいなためコンパイルエラーになる", "leftright"],
    correct: [0],
    expected: { kind: "output", stdout: "left" },
    explanation:
      "複数のインタフェースで default メソッドが衝突した場合は、実装クラスでオーバーライドして解決します。その際 インタフェース名.super.メソッド名() と書けば、特定のインタフェースの実装を選んで呼べます。単なる super では、クラス階層の親を指すのか、どのインタフェースを指すのかが決められないため、インタフェース名で限定する構文が用意されました。このように「曖昧なら人間が明示する」形にしたことで、多重継承の利点を取り入れつつ、暗黙のうちに予期しない実装が選ばれる事態を防いでいます。",
  },
  {
    id: 426,
    topic: "inheritance",
    variantOf: "inheritance-abstract-chain",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Concrete",
    code: [
      "abstract class Component {",
      "    abstract String describe();",
      "}",
      "",
      "abstract class Middle extends Component {",
      "    void helper() {",
      "    }",
      "}",
      "",
      "public class Concrete extends Middle {",
      "    @Override",
      "    String describe() {",
      '        return "ok";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Concrete().describe());",
      "    }",
      "}",
    ],
    choices: [
      "ok",
      "Middle が describe を実装していないためコンパイルエラーになる",
      "抽象クラスは抽象クラスを継承できないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "ok" },
    explanation:
      "抽象クラスが抽象クラスを継承する場合、途中のクラスは抽象メソッドを実装しなくて構いません。実装の義務が生じるのは、インスタンス化される最初の具象クラスです。Middle 自身は new できないため、未実装のメソッドが残っていても危険はありません。この仕組みにより、階層の途中に共通処理だけを持つ中間クラスを差し込めます。テンプレートメソッドパターンのように、段階的に実装を足していく設計はこの性質を利用しています。",
  },
  {
    id: 427,
    topic: "inheritance",
    variantOf: "inheritance-interface-private",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Messenger",
    code: [
      "interface Messages {",
      "    default String hello() {",
      '        return prefix() + "hello";',
      "    }",
      "",
      "    default String bye() {",
      '        return prefix() + "bye";',
      "    }",
      "",
      "    private String prefix() {",
      '        return "> ";',
      "    }",
      "}",
      "",
      "public class Messenger implements Messages {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Messenger().hello());",
      "    }",
      "}",
    ],
    choices: [
      "> hello",
      "インタフェースに private メソッドは定義できないためコンパイルエラーになる",
      "hello",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "> hello" },
    explanation:
      "Java 9 以降、インタフェースに private メソッドを定義できます。これは default メソッドどうしで共通する処理をまとめるための仕組みで、外部には公開されません。default メソッドが導入された結果インタフェースが実装を持つようになり、その実装の中に重複が生まれたため、公開 API を増やさずに切り出す手段が必要になった、という経緯です。private メソッドは実装クラスから呼べず、オーバーライドもできないため、インタフェースの契約には影響しません。",
  },

  // ============================================================ ラムダ (lambda)
  {
    id: 428,
    topic: "lambda",
    variantOf: "lambda-name-conflict",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Conflict",
    code: [
      "import java.util.function.Predicate;",
      "",
      "public class Conflict {",
      "    public static void main(String[] args) {",
      "        int value = 10;",
      "        Predicate<Integer> check = value -> value > 5;",
      "        System.out.println(check.test(7));",
      "    }",
      "}",
    ],
    choices: [
      "6行目でコンパイルエラーになる",
      "コンパイルは成功し、true が出力される",
      "コンパイルは成功し、false が出力される",
      "5行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "ラムダ式の引数名が、同じスコープにあるローカル変数と重複しているためエラーになります。ラムダ式は匿名クラスと違って新しいスコープを作らず、外側のスコープをそのまま共有するからです（この性質を「ラムダは透明である」と言います）。そのため外側の value を隠すことはできません。同じ理由で、ラムダの中の this は匿名クラスと異なり外側のインスタンスを指します。名前が衝突したら引数名を変えるだけで解決します。",
  },

  // ================================================================= API (api)
  {
    id: 429,
    topic: "api",
    variantOf: "api-hashmap-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Nulls",
    code: [
      "import java.util.HashMap;",
      "import java.util.Map;",
      "",
      "public class Nulls {",
      "    public static void main(String[] args) {",
      "        Map<String, String> map = new HashMap<>();",
      '        map.put(null, "value");',
      '        map.put("key", null);',
      '        System.out.println(map.get(null) + " " + map.get("key") + " " + map.size());',
      "    }",
      "}",
    ],
    choices: [
      "value null 2",
      "実行時に NullPointerException がスローされる",
      "null null 2",
      "value null 1",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "value null 2" },
    explanation:
      "HashMap はキーに null を 1 つ、値に null を何個でも格納できます。null キーはハッシュ値を 0 として特別扱いされます。ただし値の null は「キーが存在しない」場合の戻り値と区別が付かないため、get の結果だけで存在判定はできず、containsKey を使う必要があります。この曖昧さを嫌って、後発の並行版 ConcurrentHashMap や不変版の Map.of は null を一切許容しません。用途によって null の扱いが異なるので、使う実装クラスの仕様を確認することが重要です。",
  },
  {
    id: 430,
    topic: "api",
    variantOf: "api-foreach-consumer",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "EachItem",
    code: [
      "import java.util.List;",
      "",
      "public class EachItem {",
      "    public static void main(String[] args) {",
      '        List<String> items = List.of("a", "b");',
      "        items.forEach(item -> System.out.print(item));",
      '        System.out.print(" " + items.size());',
      "    }",
      "}",
    ],
    choices: ["ab 2", "a 2", "ab2", "[a, b] 2", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ab 2" },
    explanation:
      "forEach は Consumer を受け取り、各要素に対して処理を適用します。Consumer は引数を 1 つ受け取って何も返さない関数型インタフェースなので、ラムダ式をそのまま渡せます。List.of で作った不変リストでも、要素を読むだけの forEach は問題なく使えます（変更操作だけが拒否されます）。forEach は Iterable インタフェースの default メソッドとして追加されたもので、既存の実装クラスを一切変更せずに新しい機能を配れる、という default メソッドの利点を活かした例です。",
  },
  {
    id: 431,
    topic: "api",
    variantOf: "api-comparator-contract",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Ordering",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Ordering {",
      "    public static void main(String[] args) {",
      "        List<String> names = new ArrayList<>();",
      '        names.add("banana");',
      '        names.add("apple");',
      "        names.sort((a, b) -> b.compareTo(a));",
      "        System.out.println(names);",
      "    }",
      "}",
    ],
    choices: [
      "[banana, apple]",
      "[apple, banana]",
      "[]",
      "実行時に例外がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[banana, apple]" },
    explanation:
      "Comparator は「第 1 引数が小さければ負、等しければ 0、大きければ正」を返す契約です。ここでは b.compareTo(a) と左右を入れ替えているため、通常とは逆の降順に並びます。戻り値が真偽値ではなく符号付きの整数なのは、3 通りの関係を 1 回の呼び出しで表現するためで、比較回数を減らせます。返す値は -1 や 1 である必要はなく符号だけが意味を持ちます。なお sort はリストそのものを並べ替える破壊的操作で、戻り値はありません。",
  },

  // ======================================================= 例外 (exceptions)
  {
    id: 432,
    topic: "exceptions",
    variantOf: "exceptions-clause-order",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "WrongOrder",
    code: [
      "public class WrongOrder {",
      "    public static void main(String[] args) {",
      "        try {",
      '            System.out.print("t");',
      "        } finally {",
      '            System.out.print("f");',
      "        } catch (RuntimeException e) {",
      '            System.out.print("c");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "finally より後ろに catch を書けないためコンパイルエラーになる",
      "コンパイルは成功し、tf が出力される",
      "コンパイルは成功し、tfc が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "try 文の構成は try → catch（0 個以上）→ finally（省略可）という順序に固定されており、finally の後ろに catch は書けません。この順序が決まっているのは、例外が発生したときの流れ（まず捕捉を試み、最後に後始末をする）がそのまま構文の並びとして表れるようにするためです。読み手は上から順に読むだけで処理の順序を追えます。なお catch と finally の両方を省略することはできず、try-with-resources でリソースを宣言した場合のみ、どちらも無い形が許されます。",
  },
];
