import type { SilverQuestion } from "../quizTypes";

/**
 * 論点を拡充するための追加問題（id 201 以降）。
 * ここに入るのは「新しい論点」であり、既存論点の言い換え（亜種）ではない。
 */
export const extraQuestions1: SilverQuestion[] = [
  // ============================================================ 基本 (basics)
  {
    id: 201,
    topic: "basics",
    variantOf: "basics-comments",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Doc",
    code: [
      "public class Doc {",
      "    public static void main(String[] args) {",
      '        // System.out.print("a");',
      '        /* System.out.print("b"); */',
      '        System.out.print("c"); // /* まだコメントの中',
      "    }",
      "}",
    ],
    choices: ["c", "abc", "bc", "ac", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "c" },
    explanation:
      "// は行末までを、/* */ は対応する */ までをコメントにします。5 行目の // 以降に /* が現れても、既に行コメントの中なのでブロックコメントは開始しません。コメントの解釈はコンパイルの最初期（字句解析）に行われ、コメント部分はトークンとしてコードの一部にならずパーサには渡りません。逆に言えば /* の中に */ が現れるとそこでコメントが終わってしまうため、コードを一時的に無効化する目的でブロックコメントを使うと入れ子で破綻することがあります。",
  },
  {
    id: 202,
    topic: "basics",
    variantOf: "basics-source-structure",
    question: "次のコードを 1 つのファイル Main.java に記述してコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Main",
    code: [
      "public class Main {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Helper().value());",
      "    }",
      "}",
      "",
      "class Helper {",
      "    int value() {",
      "        return 7;",
      "    }",
      "}",
    ],
    choices: [
      "7",
      "public でないクラスを同じファイルに書けないためコンパイルエラーになる",
      "Helper.java が必要なためコンパイルエラーになる",
      "実行時に ClassNotFoundException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "7" },
    explanation:
      "1 つのソースファイルに複数のクラスを書けます。制約は「public なクラスは 1 つまでで、その名前はファイル名と一致させる」という点だけです。この規則があるのは、コンパイラや IDE が「型 Foo を探すなら Foo.java を読めばよい」と機械的に判断できるようにするためで、外部から参照される public 型だけが対象になります。public でない補助クラスは同じファイルに置けますが、そのクラスは同一パッケージからしか見えません。コンパイル後は Main.class と Helper.class の 2 つが生成されます。",
  },
  {
    id: 203,
    topic: "basics",
    variantOf: "basics-initialization-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Boot",
    code: [
      "public class Boot {",
      "    static {",
      '        System.out.print("static ");',
      "    }",
      "",
      "    {",
      '        System.out.print("instance ");',
      "    }",
      "",
      "    Boot() {",
      '        System.out.print("ctor");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Boot();",
      "    }",
      "}",
    ],
    choices: [
      "static instance ctor",
      "instance static ctor",
      "static ctor instance",
      "ctor instance static",
      "instance ctor static",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "static instance ctor" },
    explanation:
      "static 初期化ブロックはクラスの初期化時に 1 度だけ実行され（ロードだけでは走らない）、この Boot クラスでは main が動く前に完了します。インスタンス初期化ブロックは new のたびにコンストラクタ本体より前に実行されます。この順序は「クラス全体の準備 → インスタンスごとの準備 → 固有の初期化」という依存関係に沿っており、後の段階から前の段階の結果を安全に参照できるよう設計されています。インスタンス初期化ブロックは、複数のコンストラクタで共通する初期化をまとめる用途で使われますが、実行順が読みにくくなるため、多くの場合はコンストラクタの委譲（this(...)）の方が明快です。",
  },
  {
    id: 204,
    topic: "basics",
    variantOf: "basics-println-chararray",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Output",
    code: [
      "public class Output {",
      "    public static void main(String[] args) {",
      "        char[] chars = {'a', 'b'};",
      "        int[] numbers = {1, 2};",
      "        System.out.print(chars);",
      '        System.out.print(" ");',
      "        System.out.print(numbers.length);",
      "    }",
      "}",
    ],
    choices: ["ab 2", "[C@... のような文字列と 2", "ab 12", "a 2", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ab 2" },
    explanation:
      "print / println には char[] を受け取る専用のオーバーロードがあり、配列の中身を文字列として出力します。他の配列型（int[] など）には専用版が無いため Object 版が選ばれ、toString() の既定実装であるクラス名@16進表記（例: [I@...）が出てしまいます。char[] だけが特別扱いされているのは、文字列が本質的に文字の並びであり、出力したい対象として頻度が高いからです。配列の中身を見たい場合は Arrays.toString(numbers) を使うのが定石で、多次元なら Arrays.deepToString を使います。",
  },

  // ==================================================== データ型 (datatypes)
  {
    id: 211,
    topic: "datatypes",
    variantOf: "datatypes-integer-cache",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Cache",
    code: [
      "public class Cache {",
      "    public static void main(String[] args) {",
      "        Integer a = 127;",
      "        Integer b = 127;",
      "        Integer c = 128;",
      "        Integer d = 128;",
      '        System.out.println((a == b) + " " + (c == d));',
      "    }",
      "}",
    ],
    choices: ["true false", "true true", "false false", "false true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true false" },
    explanation:
      "オートボクシングは内部で Integer.valueOf を呼びます。-128〜127 は言語仕様でキャッシュされるため 127 同士は == で true になります。128 は既定のキャッシュ上限（127）を超えるため別インスタンスになり、JDK 11 では false です（JVM オプション -XX:AutoBoxCacheMax で上限を上げると true になり得ます）。== の結果が値や環境に依存する落とし穴があるため、ラッパー型の比較には equals を使う、あるいはプリミティブで扱うのが安全です。",
  },
  {
    id: 212,
    topic: "datatypes",
    variantOf: "datatypes-literals",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Literals",
    code: [
      "public class Literals {",
      "    public static void main(String[] args) {",
      "        int bin = 0b1010;",
      "        int oct = 010;",
      "        int hex = 0xFF;",
      "        int sep = 1_000;",
      '        System.out.println(bin + " " + oct + " " + hex + " " + sep);',
      "    }",
      "}",
    ],
    choices: ["10 8 255 1000", "1010 10 255 1000", "10 10 255 1000", "10 8 255 1_000", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "10 8 255 1000" },
    explanation:
      "接頭辞が基数を表し、0b は 2 進数、0x は 16 進数です。0 の直後に 0〜7 が 1 桁以上続く整数リテラル（010 など）は 8 進として解釈され、リテラル 0 単体は 10 進です。0b1010 は 10、010 は 8、0xFF は 255 です。8 や 9 を含む 08 のような書き方はコンパイルエラーになります。アンダースコアは桁区切りの見やすさのための記法で、値には影響しません。ゼロ埋めのつもりで 010 と書くと意図せず 8 になる典型例に注意し、日付などは文字列として扱うか先頭のゼロを付けないのが安全です。",
  },
  {
    id: 213,
    topic: "datatypes",
    variantOf: "datatypes-float-precision",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Money",
    code: [
      "public class Money {",
      "    public static void main(String[] args) {",
      "        System.out.println(0.1 + 0.2 == 0.3);",
      "    }",
      "}",
    ],
    choices: ["false", "true", "0.3", "0.30000000000000004", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false" },
    explanation:
      "double は 2 進数の浮動小数点表現なので、0.1 や 0.2 のような 10 進の小数を正確に表せません。誤差を含んだ値同士を足すと 0.30000000000000004 となり、0.3 とは一致しないため false になります。これは Java 固有の欠陥ではなく IEEE 754 に従う言語すべてに共通する性質です。金額のように誤差が許されない計算では double を使わず、BigDecimal（文字列から生成する）や、最小単位の整数（円や銭）で扱うのが原則です。",
  },
  {
    id: 214,
    topic: "datatypes",
    variantOf: "datatypes-integer-division",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Div",
    code: [
      "public class Div {",
      "    public static void main(String[] args) {",
      '        System.out.println(7 / 2 + " " + 7 % 2 + " " + (-7) / 2 + " " + (-7) % 2);',
      "    }",
      "}",
    ],
    choices: ["3 1 -3 -1", "3.5 1 -3.5 -1", "3 1 -4 1", "4 1 -3 -1", "実行時に ArithmeticException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 1 -3 -1" },
    explanation:
      "整数同士の / は整数除算となり、小数部は切り捨てられます。切り捨ての方向は「0 に近づける」であり、-7 / 2 は -3.5 が -3 になります。% の結果は「被除数と同じ符号」になるよう定義されており -1 です。これは a == (a / b) * b + (a % b) という関係を保つためで、剰余の符号が除数に従う Math.floorMod とは異なります。負数を扱う剰余で偶奇判定や循環インデックスを計算すると符号で破綻することがあるため、Math.floorMod を使うと除数の符号に合わせた剰余が得られます。",
  },
  {
    id: 215,
    topic: "datatypes",
    variantOf: "datatypes-string-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Sub",
    code: [
      "public class Sub {",
      "    public static void main(String[] args) {",
      '        String s = "Hello";',
      '        System.out.println(s.substring(1, 3) + " " + s.indexOf(\'l\') + " " + s.charAt(0));',
      "    }",
      "}",
    ],
    choices: ["el 2 H", "ell 2 H", "el 3 H", "el 2 e", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "el 2 H" },
    explanation:
      'substring(1, 3) は添字 1 以上 3 未満、つまり "el" を返します。indexOf は最初に見つかった位置を 0 始まりで返すので、"Hello" の l は添字 2 です。charAt(0) は先頭の文字 H を返します。添字が 0 始まりで終端が排他的という規則は配列やコレクションと共通しており、この一貫性のおかげで end - start がそのまま長さになります。範囲外を指定すると StringIndexOutOfBoundsException になりますが、substring(5, 5) のように長さ 0 の範囲は空文字列として有効です。',
  },
  {
    id: 216,
    topic: "datatypes",
    variantOf: "datatypes-string-immutable-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Fixedly",
    code: [
      "public class Fixedly {",
      "    public static void main(String[] args) {",
      '        String s = "java";',
      "        s.toUpperCase();",
      '        s.concat("!");',
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["java", "JAVA", "JAVA!", "java!", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "java" },
    explanation:
      "String は不変クラスなので、toUpperCase も concat も自分自身を書き換えず、新しい文字列を返すだけです。戻り値を受け取っていないため結果は捨てられ、s は元のままです。String を不変にしたのは、文字列が定数プールで共有され、マップのキーやスレッド間で頻繁に受け渡されるからで、もし可変なら共有した全員に影響が及びます。この性質のおかげでハッシュ値をキャッシュでき、防御的コピーも不要になります。「値を変えるメソッド」ではなく「変えた値を返すメソッド」だと捉えてください。",
  },
  {
    id: 217,
    topic: "datatypes",
    variantOf: "datatypes-se11-string-api",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Modern",
    code: [
      "public class Modern {",
      "    public static void main(String[] args) {",
      '        String s = "  ab  ";',
      '        System.out.println(s.strip() + "|" + "x".repeat(3) + "|" + "  ".isBlank());',
      "    }",
      "}",
    ],
    choices: ["ab|xxx|true", "  ab  |xxx|true", "ab|xxx|false", "ab|x|true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ab|xxx|true" },
    explanation:
      "Java 11 で追加された String のメソッドです。strip は前後の空白を除去し、repeat は文字列を指定回数繰り返し、isBlank は空白だけ（または空）なら true を返します。strip が従来の trim と別に用意されたのは、trim がコードポイント U+0020 以下（半角スペースや制御文字など）だけを除去するのに対し、strip は Character.isWhitespace に従い Unicode の空白（全角スペースなど trim では除けないものも含む）を扱えるためです。既存メソッドの挙動を変えると互換性を壊すため、正しい仕様を新しい名前で追加する、という標準ライブラリの進化のしかたが表れています。",
  },
  {
    id: 218,
    topic: "datatypes",
    variantOf: "datatypes-explicit-cast",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Narrow",
    code: [
      "public class Narrow {",
      "    public static void main(String[] args) {",
      "        double d = 3.99;",
      "        int i = (int) d;",
      "        long big = 3000000000L;",
      "        int overflow = (int) big;",
      '        System.out.println(i + " " + overflow);',
      "    }",
      "}",
    ],
    choices: ["3 -1294967296", "4 -1294967296", "3 2147483647", "3 3000000000", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 -1294967296" },
    explanation:
      "double から int へのキャストは四捨五入ではなく、0 方向へ小数部を切り詰める（truncate toward zero）ため 3 になります。long から int へは値が int の範囲に収まっても暗黙変換できず、(int) が必要です。ここでは 3000000000 を狭めるとビット列が符号付き 32 ビットとして解釈され -1294967296 になります。byte / short / char への代入は、int / byte / short / char 型のコンパイル時定数で範囲内ならキャストなしでも通りますが、long や double の定数は値が収まっても不可です。この問題の double→int や long→int は明示的なキャストが要り、書いた時点で値の破損はプログラマの責任になります。正の小数を整数に丸めるなら (int) Math.round(d) も使えます（round(double) の戻り値は long。同点は正の無限大方向で、例として round(-1.5) は -1）。",
  },
  {
    id: 219,
    topic: "datatypes",
    variantOf: "datatypes-boolean-cast",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Flag",
    code: [
      "public class Flag {",
      "    public static void main(String[] args) {",
      "        boolean b = true;",
      "        int i = (int) b;",
      "        System.out.println(i);",
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、1 が出力される",
      "コンパイルは成功し、0 が出力される",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "boolean は他のどのプリミティブ型とも変換できません。キャストを書いてもコンパイルエラーになります。C 言語では 0 が偽、それ以外が真として整数と真偽値が地続きでしたが、Java はこれを断ち切りました。if (x = 1) のように代入式の型が boolean / Boolean 以外だとコンパイルエラーになります。代入式の型が boolean または Boolean なら if (flag = true) や if (a = b) のように条件に書けます。真偽値を数値にしたい場合は b ? 1 : 0 のように明示的に書く必要があります。",
  },
  {
    id: 220,
    topic: "datatypes",
    variantOf: "datatypes-wrapper-conversion",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Convert",
    code: [
      "public class Convert {",
      "    public static void main(String[] args) {",
      '        int a = Integer.parseInt("42");',
      '        Integer b = Integer.valueOf("42");',
      "        String c = String.valueOf(42);",
      "        System.out.println(a + b + c.length());",
      "    }",
      "}",
    ],
    choices: ["86", "4242 2", "424242", "実行時に NumberFormatException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "86" },
    explanation:
      'parseInt は int を、valueOf は Integer を返します。b は自動アンボクシングされて計算に参加し、42 + 42 + 2（"42" の長さ）で 86 になります。すべて数値なので加算であり、文字列連結にはなりません。parseInt と valueOf が並立しているのは、プリミティブが必要な場面でラッパーを経由する無駄を避けるためです。なお数字以外の文字列を渡すと NumberFormatException（非検査例外）になるため、外部入力を変換する箇所では必ず例外処理を考える必要があります。',
  },
];
