import type { SilverQuestion } from "../quizTypes";

/** メソッド・継承の論点を拡充する追加問題（id 261 以降） */
export const extraQuestions3: SilverQuestion[] = [
  // ========================================================== メソッド (methods)
  {
    id: 261,
    topic: "methods",
    variantOf: "methods-pass-by-value",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Swap",
    code: [
      "public class Swap {",
      "    static void change(int value, int[] array) {",
      "        value = 99;",
      "        array[0] = 99;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        int v = 1;",
      "        int[] a = {1};",
      "        change(v, a);",
      '        System.out.println(v + " " + a[0]);',
      "    }",
      "}",
    ],
    choices: ["1 99", "99 99", "1 1", "99 1", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 99" },
    explanation:
      "Java の引数は常に値渡しです。int の場合は値そのものが複製されるので、呼び出し先での代入は呼び出し元に影響しません。配列の場合に複製されるのは「参照という値」であり、参照先の実体は共有されているため、要素の書き換えは呼び出し元から見えます。array = new int[]{0} のように参照自体を差し替えても呼び出し元は変わりません。「オブジェクトは参照渡し」と表現されることがありますが、正確には「参照の値渡し」で、この区別ができていると引数経由の副作用を正しく予測できます。",
  },
  {
    id: 262,
    topic: "methods",
    variantOf: "methods-return-type-overload",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Ambiguous",
    code: [
      "public class Ambiguous {",
      "    static int get() {",
      "        return 1;",
      "    }",
      "",
      "    static String get() {",
      '        return "a";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(get());",
      "    }",
      "}",
    ],
    choices: [
      "戻り値の型だけが異なる多重定義はできないためコンパイルエラーになる",
      "コンパイルは成功し、1 が出力される",
      "コンパイルは成功し、a が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "オーバーロードを区別する材料はメソッド名と引数の型・個数・順序だけで、戻り値の型は含まれません。同じシグネチャのメソッドが 2 つあるとみなされてコンパイルエラーになります。呼び出し側は get() と書くだけで戻り値を使わないこともできるため、戻り値で区別しようとすると「どちらを呼ぶか決められない」状況が生まれてしまうからです。同様の理由で、引数名だけを変えても別のメソッドにはなりません。",
  },
  {
    id: 263,
    topic: "methods",
    variantOf: "methods-private-access",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Client",
    code: [
      "class Service {",
      "    private void internal() {",
      '        System.out.print("internal");',
      "    }",
      "",
      "    void open() {",
      "        internal();",
      "    }",
      "}",
      "",
      "public class Client {",
      "    public static void main(String[] args) {",
      "        new Service().internal();",
      "    }",
      "}",
    ],
    choices: [
      "13行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "コンパイルは成功し、internal が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 13 },
    explanation:
      "private メンバーはそのクラスの中からしか参照できないため、別クラスの Client から internal() を呼ぶとコンパイルエラーになります。同じクラス内の open() からは問題なく呼べます。アクセス修飾子はクラスに「外部へ約束する範囲」を宣言させる仕組みで、private を付けた部分は後からいつ変えても外部に影響しないと保証できます。この境界がないとすべての実装詳細が事実上の公開 API になり、内部を変更するたびに利用側が壊れます。",
  },
  {
    id: 264,
    topic: "methods",
    variantOf: "methods-static-via-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Util",
    code: [
      "public class Util {",
      "    static int twice(int n) {",
      "        return n * 2;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Util helper = null;",
      "        System.out.println(helper.twice(3));",
      "    }",
      "}",
    ],
    choices: [
      "6",
      "実行時に NullPointerException がスローされる",
      "8行目でコンパイルエラーになる",
      "0",
      "3",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "6" },
    explanation:
      "static メソッドの呼び出し先はコンパイル時に変数の型だけで決まり、実行時にインスタンスを参照しません。そのため変数が null でも NullPointerException にならず、Util.twice(3) と書いたのと同じ結果になります。直感に反するこの挙動こそが、static メソッドをインスタンス変数経由で呼ぶべきでない理由です。読み手はインスタンスに依存した処理だと誤解しますし、null の可能性を考えてしまいます。static メンバーは必ずクラス名で修飾して呼びましょう。",
  },
  {
    id: 265,
    topic: "methods",
    variantOf: "methods-this-shadowing",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Point",
    code: [
      "public class Point {",
      "    int x;",
      "",
      "    Point(int x) {",
      "        x = x;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Point(5).x);",
      "    }",
      "}",
    ],
    choices: ["0", "5", "コンパイルエラーになる", "実行時に NullPointerException がスローされる", "null"],
    correct: [0],
    expected: { kind: "output", stdout: "0" },
    explanation:
      "引数 x はフィールド x を覆い隠す（シャドーイング）ため、x = x は引数に引数自身を代入しているだけで、フィールドは初期値の 0 のままです。フィールドへ代入するには this.x = x と書く必要があります。スコープの狭い宣言が優先される規則は一貫していますが、引数とフィールドに同じ名前を使う慣習と噛み合うとこの罠になります。コンパイラは構文として正しいため何も言いませんが、多くの静的解析ツールは自己代入として警告します。this を付ける癖をつけるのが確実な対策です。",
  },
  {
    id: 266,
    topic: "methods",
    variantOf: "methods-varargs-priority",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Choose",
    code: [
      "public class Choose {",
      '    static void run(int... values) { System.out.print("varargs"); }',
      "",
      '    static void run(int a, int b) { System.out.print("two"); }',
      "",
      "    public static void main(String[] args) {",
      "        run(1, 2);",
      "    }",
      "}",
    ],
    choices: ["two", "varargs", "あいまいなためコンパイルエラーになる", "twovarargs"],
    correct: [0],
    expected: { kind: "output", stdout: "two" },
    explanation:
      "オーバーロードの解決では可変長引数が最後に検討されます。まず可変長を使わずに適合する候補が探され、run(int, int) が見つかった時点で決まるため two が出力されます。この順序は、可変長引数が後から言語に追加された際、既存のコードの呼び出し先が変わってしまわないようにするための配慮でもあります。逆に言えば、可変長版が呼ばれることを期待して書いたコードが、固定引数版の追加によって静かに振る舞いを変える危険があるということです。曖昧な多重定義は避けるのが安全です。",
  },
  {
    id: 267,
    topic: "methods",
    variantOf: "methods-void-return",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Early",
    code: [
      "public class Early {",
      "    static void check(int n) {",
      "        if (n < 0) {",
      "            return;",
      "        }",
      '        System.out.print("ok");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        check(-1);",
      "        check(1);",
      "    }",
      "}",
    ],
    choices: ["ok", "okok", "何も出力されない", "戻り値が無いのに return があるためコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ok" },
    explanation:
      "戻り値が void のメソッドでも、値を伴わない return でその場から抜けられます。check(-1) は出力せずに戻り、check(1) だけが ok を出力します。この早期リターンは、条件を満たさない場合を先に片付けて本筋のネストを浅く保つための定石です。逆に void 以外のメソッドで値のない return を書いたり、void のメソッドで値を返そうとするとコンパイルエラーになります。コンパイラは「すべての経路で値を返すか」を検査するため、戻り値のあるメソッドでは分岐の取りこぼしも検出されます。",
  },
  {
    id: 268,
    topic: "methods",
    variantOf: "methods-final-parameter",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Adder",
    code: [
      "public class Adder {",
      "    static int add(final int a, int b) {",
      "        b = b + 1;",
      "        return a + b;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(add(1, 2));",
      "    }",
      "}",
    ],
    choices: ["4", "3", "final 引数があるためコンパイルエラーになる", "5", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "4" },
    explanation:
      "final が付いた引数 a は再代入できませんが、a を読むこと自体に制限はありません。b は通常の引数なので再代入でき、3 になってから a と足されて 4 になります。引数への再代入は呼び出し元には影響しない（値渡しのため）ので、final を付ける意味は「このメソッド内で値が変わらない」と読み手に示すことと、ラムダや匿名クラスから参照できるようにすることにあります。Java 8 以降は実質的 final でも参照できるため、final を明示する必要性は薄れました。",
  },
  {
    id: 269,
    topic: "methods",
    variantOf: "methods-field-defaults",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Defaults",
    code: [
      "public class Defaults {",
      "    int number;",
      "    String text;",
      "    boolean flag;",
      "",
      "    public static void main(String[] args) {",
      "        Defaults d = new Defaults();",
      '        System.out.println(d.number + " " + d.text + " " + d.flag);',
      "    }",
      "}",
    ],
    choices: [
      "0 null false",
      "0 空文字 false",
      "初期化されていないためコンパイルエラーになる",
      "実行時に NullPointerException がスローされる",
      "null null null",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "0 null false" },
    explanation:
      "フィールドは明示的に初期化しなくても、数値型は 0、boolean は false、参照型は null という既定値が自動的に設定されます。一方ローカル変数には既定値が無く、代入前に読もうとするとコンパイルエラーになります。この違いは、フィールドがオブジェクト生成時にメモリを確保する段階でまとめてゼロクリアされるのに対し、ローカル変数は使い方が静的に追跡できるためです。初期化漏れを検出できる場所では厳しくし、できない場所では安全な既定値を与える、という使い分けになっています。",
  },
  {
    id: 270,
    topic: "methods",
    variantOf: "methods-recursion",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Fact",
    code: [
      "public class Fact {",
      "    static int factorial(int n) {",
      "        return n <= 1 ? 1 : n * factorial(n - 1);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(factorial(5));",
      "    }",
      "}",
    ],
    choices: ["120", "24", "15", "実行時に StackOverflowError が発生する", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "120" },
    explanation:
      "5 * 4 * 3 * 2 * 1 で 120 になります。再帰では「これ以上潜らない条件（基底条件）」が必ず必要で、ここでは n <= 1 がそれにあたります。基底条件が無いか到達できないと、呼び出しごとに積まれるスタックフレームが上限を超えて StackOverflowError になります。Java は末尾呼び出し最適化を行わないため、再帰の深さがそのままスタック消費になる点も実務上は重要で、深い再帰が予想される処理はループや明示的なスタックで書き直すのが定石です。",
  },
  {
    id: 271,
    topic: "methods",
    variantOf: "methods-encapsulation",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Temperature",
    code: [
      "public class Temperature {",
      "    private int celsius;",
      "",
      "    void setCelsius(int value) {",
      "        if (value < -273) {",
      "            return;",
      "        }",
      "        this.celsius = value;",
      "    }",
      "",
      "    int getCelsius() {",
      "        return celsius;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Temperature t = new Temperature();",
      "        t.setCelsius(-300);",
      "        t.setCelsius(25);",
      "        System.out.println(t.getCelsius());",
      "    }",
      "}",
    ],
    choices: ["25", "-300", "0", "実行時に例外がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "25" },
    explanation:
      "フィールドを private にし、変更をメソッド経由に限定しているため、絶対零度を下回る値は弾かれて無視されます。結果として最後に成功した 25 が残ります。カプセル化の価値は「値を隠すこと」自体ではなく、オブジェクトが常に妥当な状態であり続けるという不変条件をクラス自身が守れる点にあります。フィールドが public ならこの検査を素通りして不正な値が入り込み、どこで壊れたかを追跡できなくなります。なお不正値を黙って無視するか例外を投げるかは設計判断で、実務では例外を選ぶことも多くあります。",
  },

  // ==================================================== 継承 (inheritance)
  {
    id: 281,
    topic: "inheritance",
    variantOf: "inheritance-super-implicit",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Child",
    code: [
      "class Parent {",
      "    Parent() {",
      '        System.out.print("P ");',
      "    }",
      "}",
      "",
      "public class Child extends Parent {",
      "    Child() {",
      '        System.out.print("C");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Child();",
      "    }",
      "}",
    ],
    choices: ["P C", "C P", "C", "P", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "P C" },
    explanation:
      "コンストラクタの先頭で super(...) も this(...) も書かなければ、引数なしの super() が暗黙に挿入されます。そのため親のコンストラクタが先に実行され、P のあとに C が出力されます。この順序は必然で、親クラスの初期化が終わっていない状態で子の初期化を始めると、子が親のフィールドに依存していた場合に未初期化の値を読むことになるからです。継承階層をたどって Object から順に初期化される、という流れを押さえておくと、初期化順にまつわる問題を追いやすくなります。",
  },
  {
    id: 282,
    topic: "inheritance",
    variantOf: "inheritance-missing-super",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Derived",
    code: [
      "class Base {",
      "    Base(int value) {",
      "    }",
      "}",
      "",
      "public class Derived extends Base {",
      "    Derived() {",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Derived();",
      "    }",
      "}",
    ],
    choices: [
      "親に引数なしのコンストラクタが無いためコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "実行時に例外がスローされる",
      "11行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "引数付きのコンストラクタを定義すると、既定のコンストラクタは自動生成されません。子クラスは暗黙に super() を呼ぼうとしますが、親に該当するコンストラクタが無いためコンパイルエラーになります。解決するには子で super(0) のように明示的に呼ぶか、親に引数なしのコンストラクタを用意します。既定コンストラクタが「何も定義していないときだけ」補われるのは、初期化に引数が必要だと宣言したクラスを、引数なしで中途半端に生成されないようにするためです。",
  },
  {
    id: 283,
    topic: "inheritance",
    variantOf: "inheritance-covariant-return",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Dog",
    code: [
      "class Animal {",
      "    Animal reproduce() {",
      "        return new Animal();",
      "    }",
      "}",
      "",
      "public class Dog extends Animal {",
      "    @Override",
      "    Dog reproduce() {",
      "        return new Dog();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Animal a = new Dog();",
      "        System.out.println(a.reproduce().getClass().getSimpleName());",
      "    }",
      "}",
    ],
    choices: [
      "Dog",
      "Animal",
      "戻り値の型が異なるためコンパイルエラーになる",
      "実行時に ClassCastException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Dog" },
    explanation:
      "オーバーライドでは、戻り値の型を元の型の派生型に狭めることが許されます（共変戻り値）。呼び出し側が期待する Animal として扱える以上、より具体的な Dog を返しても契約は破られないためです。実行時の型は Dog なので Dog 版が呼ばれ、Dog が返ります。この緩和が無かった時代は、返した直後にキャストする定型コードが必要でした。逆に引数の型を広げたり狭めたりするとオーバーライドとは認識されず、別のメソッド（オーバーロード）になってしまう点は対照的です。",
  },
  {
    id: 284,
    topic: "inheritance",
    variantOf: "inheritance-override-access",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Impl",
    code: [
      "class Base {",
      "    public void run() {",
      "    }",
      "}",
      "",
      "public class Impl extends Base {",
      "    @Override",
      "    void run() {",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Impl().run();",
      "    }",
      "}",
    ],
    choices: [
      "アクセス範囲を狭められないためコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "@Override が不要なためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "オーバーライドではアクセス範囲を狭められません。public を修飾子なし（パッケージプライベート）にすると、Base 型として呼べていた利用者が Impl のインスタンスでは呼べなくなり、置き換え可能性が壊れるからです。逆に広げる（protected を public にする）のは許されます。これはリスコフの置換原則を言語仕様として強制したもので、「派生型は基底型として通用しなければならない」という制約が、例外の宣言（広げられない）や戻り値の型（狭められる）にも一貫して現れています。",
  },
  {
    id: 285,
    topic: "inheritance",
    variantOf: "inheritance-final-method",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Sub",
    code: [
      "class Base {",
      "    final void run() {",
      "    }",
      "}",
      "",
      "public class Sub extends Base {",
      "    void run() {",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Sub().run();",
      "    }",
      "}",
    ],
    choices: [
      "final メソッドはオーバーライドできないためコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "実行時に例外がスローされる",
      "final クラスでないため問題なくオーバーライドできる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "final メソッドはオーバーライドを禁止します。これは「この振る舞いは派生クラスに変更させない」という設計上の宣言で、クラスの不変条件がサブクラスによって壊されるのを防ぎます。たとえばコンストラクタから呼ばれるメソッドや、セキュリティ上の検査を行うメソッドを final にしておけば、派生クラスが検査を素通りさせる実装に差し替えることはできません。クラス自体に final を付ければ継承そのものを禁止でき、String が final なのは不変性を保証するためです。",
  },
  {
    id: 286,
    topic: "inheritance",
    variantOf: "inheritance-interface-constant",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "App",
    code: [
      "interface Config {",
      "    int MAX = 10;",
      "}",
      "",
      "public class App implements Config {",
      "    public static void main(String[] args) {",
      "        System.out.println(MAX);",
      "    }",
      "}",
    ],
    choices: [
      "10",
      "修飾子が無いためコンパイルエラーになる",
      "0",
      "インタフェースのフィールドは参照できないためコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "10" },
    explanation:
      "インタフェースに書いたフィールドは、記述しなくても暗黙に public static final になります。そのため MAX は定数として扱われ、実装クラスから修飾なしで参照できます。インタフェースが「実装を持たない契約」である以上、インスタンスごとの状態を持てないため、フィールドは必然的に定数になります。同様にメソッドも暗黙に public abstract です（default や static を付けた場合を除く）。なお定数をインタフェースで配布する手法は現在では推奨されず、enum や final クラスの static フィールドを使うのが定石です。",
  },
  {
    id: 287,
    topic: "inheritance",
    variantOf: "inheritance-interface-static",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Use",
    code: [
      "interface Helper {",
      "    static String name() {",
      '        return "helper";',
      "    }",
      "}",
      "",
      "public class Use implements Helper {",
      "    public static void main(String[] args) {",
      "        System.out.println(Helper.name());",
      "    }",
      "}",
    ],
    choices: [
      "helper",
      "インタフェースに static メソッドは定義できないためコンパイルエラーになる",
      "Use.name() と書かなければならないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "helper" },
    explanation:
      "Java 8 以降、インタフェースに static メソッドを定義できます。ただし実装クラスには継承されないため、必ず Helper.name() のようにインタフェース名で呼びます。継承されない仕様なのは、複数のインタフェースを実装したときに static メソッドが衝突して、どれを指すか決められなくなるのを避けるためです。この機能によって、従来 Collections のような別のユーティリティクラスに置いていた補助メソッドを、関係するインタフェース自身に同居させられるようになりました（List.of などがその例です）。",
  },
  {
    id: 288,
    topic: "inheritance",
    variantOf: "inheritance-abstract-without-abstract-method",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Circle",
    code: [
      "abstract class Shape {",
      "    void draw() {",
      '        System.out.print("draw");',
      "    }",
      "}",
      "",
      "public class Circle extends Shape {",
      "    public static void main(String[] args) {",
      "        new Circle().draw();",
      "    }",
      "}",
    ],
    choices: [
      "draw",
      "抽象メソッドが無い抽象クラスは定義できないためコンパイルエラーになる",
      "Circle が draw を実装していないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "draw" },
    explanation:
      "抽象クラスに抽象メソッドが 1 つも無くても構いません。abstract を付ける本質は「このクラス自体はインスタンス化させない」という宣言であり、抽象メソッドの有無とは独立しています。共通の実装だけを提供し、単独で使われることを想定しないクラス（テンプレートや基底の骨組み）を表現する際に使います。逆に、抽象メソッドが 1 つでもあればそのクラスは必ず abstract でなければなりません。new できない型として扱わせたいかどうか、が判断基準になります。",
  },
  {
    id: 289,
    topic: "inheritance",
    variantOf: "inheritance-reference-type-methods",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Zoo",
    code: [
      "class Animal {",
      "    void eat() {",
      "    }",
      "}",
      "",
      "class Dog extends Animal {",
      "    void bark() {",
      "    }",
      "}",
      "",
      "public class Zoo {",
      "    public static void main(String[] args) {",
      "        Animal animal = new Dog();",
      "        animal.bark();",
      "    }",
      "}",
    ],
    choices: [
      "14行目でコンパイルエラーになる",
      "コンパイルは成功し、何も出力されずに終了する",
      "13行目でコンパイルエラーになる",
      "実行時に ClassCastException がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 14 },
    explanation:
      "呼び出せるメソッドは変数の宣言型（ここでは Animal）で決まります。実体が Dog でも、Animal 型の変数からは Dog 固有の bark() を呼べません。コンパイラは実行時にどのインスタンスが入るか分からないため、宣言型が保証する範囲でしか呼び出しを許さないからです。呼びたい場合は ((Dog) animal).bark() とキャストしますが、その必要が頻繁に生じるなら、そもそも抽象化の切り方が適切でない可能性を疑うべきです。実行時の型で処理を分岐させるより、ポリモーフィズムで解くのが本筋です。",
  },
  {
    id: 290,
    topic: "inheritance",
    variantOf: "inheritance-super-call",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Extended",
    code: [
      "class Base {",
      "    String greet() {",
      '        return "base";',
      "    }",
      "}",
      "",
      "public class Extended extends Base {",
      "    @Override",
      "    String greet() {",
      '        return super.greet() + "+extended";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Extended().greet());",
      "    }",
      "}",
    ],
    choices: ["base+extended", "extended", "base", "実行時に StackOverflowError が発生する", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "base+extended" },
    explanation:
      "super.greet() は動的束縛を経由せず、親クラスの実装を直接呼び出します。もし this.greet() と書けば自分自身が再帰的に呼ばれ、StackOverflowError になります。super による呼び出しだけが例外的に静的に解決されるのは、オーバーライドした側から元の実装を利用する道を残すためです。これにより「親の処理に前後の処理を足す」という拡張が書けます。ただし親の実装に依存する設計は結合を強めるため、親側は拡張点を意図的に設計しておくのが望ましい形です。",
  },
  {
    id: 291,
    topic: "inheritance",
    variantOf: "inheritance-interface-multiple-impl",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Service",
    code: [
      "interface Printable {",
      "    default String mode() {",
      '        return "read";',
      "    }",
      "}",
      "",
      "interface Trackable {",
      "}",
      "",
      "public class Service implements Printable, Trackable {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Service().mode());",
      "    }",
      "}",
    ],
    choices: [
      "read",
      "複数のインタフェースを実装できないためコンパイルエラーになる",
      "Trackable が mode を持たないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "read" },
    explanation:
      "クラスは複数のインタフェースを同時に実装できます。競合するのは同じシグネチャの default メソッドが複数ある場合だけで、ここでは Trackable が何も持たないため衝突しません。クラスの多重継承が禁止されている一方でインタフェースは複数実装できるのは、インタフェースが原則として状態（フィールド）を持たず、「どの実装を継承するか」という曖昧さが生じにくいからです。default メソッドの導入でその境界が少し曖昧になったため、衝突時だけ明示的な解決を求める規則が追加されました。",
  },
  {
    id: 292,
    topic: "inheritance",
    variantOf: "inheritance-object-equals-default",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Thing",
    code: [
      "public class Thing {",
      "    private final int id;",
      "",
      "    Thing(int id) {",
      "        this.id = id;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Thing a = new Thing(1);",
      "        Thing b = new Thing(1);",
      '        System.out.println(a.equals(b) + " " + a.equals(a));',
      "    }",
      "}",
    ],
    choices: ["false true", "true true", "false false", "true false", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false true" },
    explanation:
      "equals をオーバーライドしていないため、Object の既定実装である参照の同一性比較が使われます。中身が同じでも別インスタンスなら false、同一インスタンスなら true です。既定が同一性比較なのは、Object の立場では「何が等しいか」を決められないからで、値としての等価性が必要なクラスは自分で定義する責任を負います。その際は hashCode も必ず一緒にオーバーライドしないと、HashMap や HashSet で同じ値の要素が別物として扱われ、取り出せなくなります。",
  },
];
