import type { SilverQuestion } from "../quizTypes";

/** 演算子・制御構造・配列の論点を拡充する追加問題（id 231 以降） */
export const extraQuestions2: SilverQuestion[] = [
  // ====================================================== 演算子 (operators)
  {
    id: 231,
    topic: "operators",
    variantOf: "operators-ternary",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Ternary",
    code: [
      "public class Ternary {",
      "    public static void main(String[] args) {",
      "        int x = 5;",
      '        String result = x > 3 ? x > 4 ? "big" : "mid" : "small";',
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: ["big", "mid", "small", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "big" },
    explanation:
      '条件演算子は右結合なので、x > 3 ? (x > 4 ? "big" : "mid") : "small" と解釈されます。x は 5 なので両方の条件が真となり "big" になります。条件演算子が右結合なのは、else if の連鎖と同じ形（条件を上から順に試す）を自然に表現できるからです。ただしネストすると読み手の負担が大きいため、3 段以上になるなら if 文に展開する方が保守しやすくなります。なお条件演算子は文ではなく式なので、値を返す必要がある場所でしか使えません。',
  },
  {
    id: 232,
    topic: "operators",
    variantOf: "operators-precedence",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Priority",
    code: [
      "public class Priority {",
      "    public static void main(String[] args) {",
      "        int result = 2 + 3 * 4 - 6 / 3;",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: ["12", "14", "4", "6", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "12" },
    explanation:
      "* と / は + と - より優先順位が高いため、先に 3 * 4 = 12 と 6 / 3 = 2 が計算され、2 + 12 - 2 で 12 になります。同じ優先順位の演算子（+ と -）は左から順に評価されます。この優先順位は算数の規則をそのまま持ち込んだもので、多くの言語で共通です。優先順位を暗記するより、意図を括弧で明示する方が読み手に優しく、特に && と ||、ビット演算子が混ざる式では括弧の有無で結果が変わることがあります。",
  },
  {
    id: 233,
    topic: "operators",
    variantOf: "operators-object-equality",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Same",
    code: [
      "public class Same {",
      "    public static void main(String[] args) {",
      '        StringBuilder a = new StringBuilder("x");',
      '        StringBuilder b = new StringBuilder("x");',
      '        System.out.println((a == b) + " " + a.equals(b) + " " + a.toString().equals(b.toString()));',
      "    }",
      "}",
    ],
    choices: ["false false true", "false true true", "true true true", "false false false"],
    correct: [0],
    expected: { kind: "output", stdout: "false false true" },
    explanation:
      "別々に new した以上 == は false です。見落としやすいのは StringBuilder が equals をオーバーライドしていない点で、Object の実装（参照の同一性）がそのまま使われるため中身が同じでも false になります。toString() で String に変換すれば、String は equals を内容比較として実装しているので true です。equals は「そのクラスにとって等しいとは何か」をクラス自身が定義するものであり、定義していなければ同一性のままである、という原則を示す例です。可変オブジェクトは等価性を定義しにくく、意図的にオーバーライドしていないケースもあります。",
  },
  {
    id: 234,
    topic: "operators",
    variantOf: "operators-assignment-chain",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Chain",
    code: [
      "public class Chain {",
      "    public static void main(String[] args) {",
      "        int a;",
      "        int b;",
      "        a = b = 5;",
      '        System.out.println(a + " " + b);',
      "    }",
      "}",
    ],
    choices: ["5 5", "5 0", "0 5", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "5 5" },
    explanation:
      "代入式（= を含む式）は値を返す式であり、単独では式文として文になります。代入した値そのものが式の結果です。さらに代入は右結合なので a = (b = 5) と解釈され、b に 5 が入り、その結果である 5 が a にも入ります。代入が値を返す仕様のおかげで while ((line = read()) != null) のような書き方ができます。一方で if (a = b) のような書き間違いも生みますが、Java では条件式に boolean しか書けないため、この種の typo は boolean 変数どうしでない限りコンパイルエラーで検出されます。",
  },
  {
    id: 235,
    topic: "operators",
    variantOf: "operators-bitwise",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Bits",
    code: [
      "public class Bits {",
      "    public static void main(String[] args) {",
      "        int a = 6;",
      "        int b = 3;",
      '        System.out.println((a & b) + " " + (a | b) + " " + (a ^ b) + " " + (a << 1));',
      "    }",
      "}",
    ],
    choices: ["2 7 5 12", "2 7 5 3", "6 3 5 12", "0 9 5 12", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 7 5 12" },
    explanation:
      "6 は 2 進で 110、3 は 011 です。& は両方 1 のビットだけ残して 010（2）、| はどちらかが 1 なら立てて 111（7）、^ は異なるビットだけ立てて 101（5）になります。<< 1 は全ビットを左へ 1 つずらす操作で、2 倍と同じ意味になり 12 です。ビット演算はフラグの集合を 1 つの整数で表す用途で今も使われており、シフトが乗除算より高速だった時代の名残でもあります。boolean に対する & と | は短絡しない論理演算として働く点も押さえておいてください。",
  },
  {
    id: 236,
    topic: "operators",
    variantOf: "operators-instanceof-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Nullable",
    code: [
      "public class Nullable {",
      "    public static void main(String[] args) {",
      "        String s = null;",
      "        System.out.println(s instanceof String);",
      "    }",
      "}",
    ],
    choices: ["false", "true", "実行時に NullPointerException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false" },
    explanation:
      "instanceof は null に対して常に false を返し、例外は投げません。null は「どのインスタンスでもない」ので、どの型のインスタンスかと問われれば否、という一貫した扱いです。この仕様のおかげで、if (o instanceof String) でキャストの可否を調べる際に、事前の null チェックを別途書く必要がありません。equals の実装で instanceof を使うのが定石なのも、引数が null でも例外にならず false を返せるからです。逆に getClass() を使う実装では、事前の null チェックが別途必要になります。",
  },
  {
    id: 237,
    topic: "operators",
    variantOf: "operators-compound-concat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Append",
    code: [
      "public class Append {",
      "    public static void main(String[] args) {",
      '        String s = "a";',
      "        s += 1 + 2;",
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["a3", "a12", "3a", "a1 2", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "a3" },
    explanation:
      's += X は s = s + (X) と同じ意味で、右辺全体が先に評価されます。そのため 1 + 2 が算術加算されて 3 になり、"a" と連結して "a3" です。一方 s = s + 1 + 2 と書けば左から評価されるので "a12" になります。複合代入が右辺をひとまとまりとして扱うのは、b *= 2 + 3 が b = b * 5 を意味してほしい（b = b * 2 + 3 ではない）という直感に沿わせるためです。+ が連結と加算を兼ねる Java では、この違いが出力の差になって現れます。',
  },
  {
    id: 238,
    topic: "operators",
    variantOf: "operators-unary",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Unary",
    code: [
      "public class Unary {",
      "    public static void main(String[] args) {",
      "        int a = 5;",
      "        boolean flag = false;",
      '        System.out.println(-a + " " + (~a) + " " + (!flag));',
      "    }",
      "}",
    ],
    choices: ["-5 -6 true", "-5 -5 true", "-5 -6 false", "5 -6 true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "-5 -6 true" },
    explanation:
      "- は符号反転、~ は全ビット反転、! は真偽の反転です。~ が -6 になるのは、Java の整数が 2 の補数表現を採るためで、~x は常に -(x + 1) と等しくなります。2 の補数が採用されているのは、加算回路だけで減算も扱えて表現に重複（+0 と -0）が生じないからです。なお ! は boolean 専用で、! を整数に使ったり ~ を boolean に使ったりはできません。C 言語と違って型が厳密に分かれている点が Java の特徴です。",
  },

  // ======================================================== 制御構造 (control)
  {
    id: 241,
    topic: "control",
    variantOf: "control-for-multiple",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Converge",
    code: [
      "public class Converge {",
      "    public static void main(String[] args) {",
      "        int count = 0;",
      "        for (int i = 0, j = 10; i < j; i++, j--) {",
      "            count++;",
      "        }",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: ["5", "10", "6", "4", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "5" },
    explanation:
      "for 文の初期化部と更新部にはカンマ区切りで複数の式を書けます。i と j は 1 回の繰り返しごとに互いに近づき、(0,10) (1,9) (2,8) (3,7) (4,6) の 5 回実行された時点で (5,5) となり条件が偽になります。初期化部で宣言できる変数は同じ型に限られ、スコープはその for 文の中だけです。両端から挟み込む走査は、回文判定や二分探索の実装で頻出する形なので、この書き方に慣れておくと読みやすくなります。",
  },
  {
    id: 242,
    topic: "control",
    variantOf: "control-infinite-for",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Endless",
    code: [
      "public class Endless {",
      "    public static void main(String[] args) {",
      "        int i = 0;",
      "        for (;;) {",
      "            if (i >= 3) {",
      "                break;",
      "            }",
      "            i++;",
      "        }",
      "        System.out.println(i);",
      "    }",
      "}",
    ],
    choices: ["3", "0", "4", "無限ループになる", "条件式が無いためコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3" },
    explanation:
      "for 文の 3 つの部分はいずれも省略でき、条件式を省略した場合は「常に真」とみなされます。したがって for (;;) は無限ループで、break で抜ける設計になります。while (true) と機能的には同じで、どちらを使うかは慣習の問題です。条件を省略できる仕様は、ループの終了判定が先頭では書けない場合（読み込んでみて初めて終端が分かる、など）に役立ちます。ただし脱出条件が本体の奥に埋もれると読み解きづらくなるため、break は早い位置に置くのが読みやすさの鉄則です。",
  },
  {
    id: 243,
    topic: "control",
    variantOf: "control-switch-types",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Switchable",
    code: [
      "public class Switchable {",
      "    public static void main(String[] args) {",
      "        long value = 2;",
      "        switch (value) {",
      "            case 2:",
      '                System.out.println("two");',
      "                break;",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、two が出力される",
      "コンパイルは成功し、何も出力されない",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "switch の式に使えるのは byte・short・char・int とそのラッパー型、String、enum に限られ、long・float・double・boolean は使えません。long が除外されているのは、switch が内部的に表引き（tableswitch / lookupswitch）へコンパイルされ、その添字が int 幅を前提としているためです。long を扱いたい場合は int へキャストするか if 文に置き換えます。boolean が使えないのは、分岐が 2 通りしかなく if で十分だからという実用上の判断です。",
  },
  {
    id: 244,
    topic: "control",
    variantOf: "control-switch-default-position",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Fallback",
    code: [
      "public class Fallback {",
      "    public static void main(String[] args) {",
      "        int x = 9;",
      "        switch (x) {",
      "            default:",
      '                System.out.print("D");',
      "            case 1:",
      '                System.out.print("1");',
      "                break;",
      "            case 2:",
      '                System.out.print("2");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["D1", "D", "D12", "1", "default を先頭に書けないためコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "D1" },
    explanation:
      "default はどの case にも一致しなかったときの入口で、書く位置は自由です。x が 9 なのでここから実行が始まり、D を出力したあと break が無いため case 1 に流れ込んで 1 を出力し、break で抜けます。default が「最後に書くもの」と思い込んでいると読み違えます。これは switch が「条件分岐」ではなく「ラベルへのジャンプ」であることの帰結で、case も default も入口を示すラベルにすぎません。慣習的には末尾に置くのが読みやすく、多くのコーディング規約もそう定めています。",
  },
  {
    id: 245,
    topic: "control",
    variantOf: "control-continue-basic",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Skip",
    code: [
      "public class Skip {",
      "    public static void main(String[] args) {",
      "        int sum = 0;",
      "        for (int i = 1; i <= 5; i++) {",
      "            if (i % 2 == 0) {",
      "                continue;",
      "            }",
      "            sum += i;",
      "        }",
      "        System.out.println(sum);",
      "    }",
      "}",
    ],
    choices: ["9", "15", "6", "5", "無限ループになる"],
    correct: [0],
    expected: { kind: "output", stdout: "9" },
    explanation:
      "continue は残りの本体を飛ばして次の繰り返しへ進みます。偶数のとき加算をスキップするので、1 + 3 + 5 で 9 です。重要なのは for 文では continue しても更新部（i++）が必ず実行される点で、while 文の中で同じつもりで continue を書くと、更新処理を飛ばして無限ループになります。ループの制御変数の更新が構文上決まった場所にある、というのが for 文の安全性であり、回数が決まった繰り返しで for が好まれる理由でもあります。",
  },
  {
    id: 246,
    topic: "control",
    variantOf: "control-loop-scope",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Scope",
    code: [
      "public class Scope {",
      "    public static void main(String[] args) {",
      "        for (int i = 0; i < 3; i++) {",
      '            System.out.print("*");',
      "        }",
      "        System.out.println(i);",
      "    }",
      "}",
    ],
    choices: [
      "6行目でコンパイルエラーになる",
      "コンパイルは成功し、***3 が出力される",
      "コンパイルは成功し、***0 が出力される",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "for 文の初期化部で宣言した変数のスコープはその for 文の中だけなので、ループの外から i を参照できません。スコープを最小限に限定するのは、変数の寿命と用途を一致させて読み手の追跡範囲を狭めるためです。ループ後も値が必要なら、for の外で宣言して for (i = 0; ...) と書きます。ただしその場合、i はメソッド全体で生き続けるため、後続の処理で意図せず再利用される危険と引き換えになります。必要な範囲でだけ変数を見えるようにする、という原則はローカル変数設計の基本です。",
  },
  {
    id: 247,
    topic: "control",
    variantOf: "control-concurrent-modification",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Purge",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Purge {",
      "    public static void main(String[] args) {",
      "        List<String> items = new ArrayList<>();",
      '        items.add("a");',
      '        items.add("b");',
      '        items.add("c");',
      "        for (String item : items) {",
      "            items.remove(item);",
      "        }",
      "        System.out.println(items);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ConcurrentModificationException がスローされる",
      "[] と出力される",
      "[b] と出力される",
      "コンパイルエラーになる",
      "実行時に IndexOutOfBoundsException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "java.util.ConcurrentModificationException" },
    explanation:
      "拡張 for 文は内部でイテレータを使っており、イテレータは生成時点のリストの変更回数を記憶しています。ループ中にリスト側の remove を呼ぶと変更回数が食い違い、次の走査時に ConcurrentModificationException になります。これは「壊れた結果を黙って返すより、早く確実に失敗させる」というフェイルファストの設計です。要素を消しながら走査したい場合は、イテレータ自身の remove を使うか、removeIf を使います。名前に Concurrent とありますが、単一スレッドでも発生する点に注意してください。",
  },

  // ============================================================ 配列 (arrays)
  {
    id: 251,
    topic: "arrays",
    variantOf: "arrays-length-member",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Size",
    code: [
      "public class Size {",
      "    public static void main(String[] args) {",
      "        int[] numbers = {1, 2, 3};",
      '        String text = "abcd";',
      "        System.out.println(numbers.length + text.length());",
      "    }",
      "}",
    ],
    choices: ["7", "34", "コンパイルエラーになる", "12", "3"],
    correct: [0],
    expected: { kind: "output", stdout: "7" },
    explanation:
      "配列の length は括弧の付かないフィールド、String の length() はメソッドです。どちらも int なので 3 + 4 で 7 になります。配列だけフィールドなのは、配列が言語組み込みの特別な型で、長さが生成時に確定して二度と変わらない値として JVM が直接保持しているためです。一方 String はクラスなので、内部表現に依存しないようメソッドとして公開しています。片方に括弧を付け間違えるとコンパイルエラーになるので、迷ったら「配列は素の値、オブジェクトは問い合わせ」と覚えると間違えません。",
  },
  {
    id: 252,
    topic: "arrays",
    variantOf: "arrays-index-bounds",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Bound",
    code: [
      "public class Bound {",
      "    public static void main(String[] args) {",
      "        int[] numbers = new int[3];",
      "        numbers[3] = 1;",
      "        System.out.println(numbers[0]);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ArrayIndexOutOfBoundsException がスローされる",
      "0 と出力される",
      "1 と出力される",
      "4行目でコンパイルエラーになる",
      "実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ArrayIndexOutOfBoundsException" },
    explanation:
      "長さ 3 の配列で有効な添字は 0 から 2 までなので、numbers[3] は範囲外です。添字が定数であってもコンパイル時には基本的に検査されず、実行時に例外になります。JVM が毎回境界を検査するのは、範囲外アクセスによって他のメモリ領域を破壊することを防ぐためで、C 言語のバッファオーバーフローに相当する脆弱性を言語レベルで封じています。この検査コストを払ってでも安全性を取る、という設計判断が Java の特徴です。ループでは i < array.length と書き、<= を使わないのが定石です。",
  },
  {
    id: 253,
    topic: "arrays",
    variantOf: "arrays-copyof",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Copy",
    code: [
      "import java.util.Arrays;",
      "",
      "public class Copy {",
      "    public static void main(String[] args) {",
      "        int[] source = {1, 2, 3};",
      "        int[] copied = Arrays.copyOf(source, 5);",
      "        source[0] = 9;",
      '        System.out.println(copied[0] + " " + copied.length + " " + copied[4]);',
      "    }",
      "}",
    ],
    choices: ["1 5 0", "9 5 0", "1 3 0", "9 3 0", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 5 0" },
    explanation:
      "Arrays.copyOf は新しい配列を作って中身をコピーするため、元の配列を後から変更してもコピー側には影響しません。指定した長さが元より大きい場合、余った領域は型の既定値（int なら 0）で埋められます。配列は生成後に長さを変えられないので、「拡張」は必ず新しい配列を作って詰め替えることになります。ArrayList が内部でやっているのもまさにこれで、容量が足りなくなるたびに大きい配列へコピーしています。なお要素が参照型の場合、コピーされるのは参照だけで、指す先のオブジェクトは共有されます（浅いコピー）。",
  },
  {
    id: 254,
    topic: "arrays",
    variantOf: "arrays-reference-sharing",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Share",
    code: [
      "public class Share {",
      "    public static void main(String[] args) {",
      "        int[] a = {1, 2};",
      "        int[] b = a;",
      "        b[0] = 9;",
      '        System.out.println(a[0] + " " + (a == b));',
      "    }",
      "}",
    ],
    choices: ["9 true", "1 false", "9 false", "1 true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "9 true" },
    explanation:
      "配列はオブジェクトなので、b = a は中身の複製ではなく同じ配列への参照のコピーです。したがって b 経由の変更は a からも見え、== も同一インスタンスなので true になります。内容を複製したいなら clone() や Arrays.copyOf を使います。この「代入しても実体は 1 つ」という性質は、配列をメソッドの引数として渡したときにも同じで、呼び出し先での変更が呼び出し元に反映されます。意図せぬ共有を避けたい場面では、渡す側・受け取る側のどちらかで防御的にコピーするのが定石です。",
  },
  {
    id: 255,
    topic: "arrays",
    variantOf: "arrays-declaration-syntax",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Decl",
    code: [
      "public class Decl {",
      "    public static void main(String[] args) {",
      "        int[] a = new int[2];",
      "        int b[] = new int[2];",
      "        int[] c[] = new int[2][2];",
      "        System.out.println(a.length + b.length + c[0].length);",
      "    }",
      "}",
    ],
    choices: ["6", "4行目でコンパイルエラーになる", "5行目でコンパイルエラーになる", "222", "8"],
    correct: [0],
    expected: { kind: "output", stdout: "6" },
    explanation:
      "角括弧は型の側（int[] a）にも変数の側（int b[]）にも書けます。int[] c[] は両方に書いた形で、結果として 2 次元配列になります。変数側に書けるのは C 言語からの構文互換のためですが、Java では型の一部として扱う int[] a の書き方が推奨されます。int a[], b; と書くと a だけが配列で b は int になる、という混乱が起きるからです。読み手が「この変数の型は何か」を宣言の左側だけで判断できるようにする、という意味で型側に寄せた書き方が優れています。",
  },
  {
    id: 256,
    topic: "arrays",
    variantOf: "arrays-sort-tostring",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Sorted",
    code: [
      "import java.util.Arrays;",
      "",
      "public class Sorted {",
      "    public static void main(String[] args) {",
      "        int[] numbers = {3, 1, 2};",
      "        Arrays.sort(numbers);",
      "        System.out.println(Arrays.toString(numbers));",
      "    }",
      "}",
    ],
    choices: ["[1, 2, 3]", "[3, 1, 2]", "123", "[3, 2, 1]", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 2, 3]" },
    explanation:
      "Arrays.sort は渡された配列そのものを並べ替えます（破壊的操作）。戻り値は無く、元の配列が変わる点に注意してください。Arrays.toString は要素をカンマ区切りで整形した文字列を返すメソッドで、配列を直接 println に渡すとクラス名@16進表記が出てしまう問題を回避できます。配列が toString をまともに実装していないのは、配列が言語組み込みの型で Object の既定実装をそのまま使うためです。この不便さを補うために Arrays クラスにユーティリティが集められている、という関係を理解しておくと API を探しやすくなります。",
  },
];
