import type { SilverQuestion } from "../quizTypes";

/** 各分野を厚くするための追加問題（id 12 以降） */
export const moreQuestions: SilverQuestion[] = [
  // ============================================================ 基本 (basics)
  {
    id: 12,
    topic: "basics",
    variantOf: "basics-declaration-order",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Order",
    code: [
      "import java.util.List;",
      "package com.example;",
      "",
      "public class Order {",
      "    public static void main(String[] args) {",
      "        System.out.println(List.of(1).size());",
      "    }",
      "}",
    ],
    choices: [
      "2行目でコンパイルエラーになる",
      "1行目でコンパイルエラーになる",
      "コンパイルは成功し、1 が出力される",
      "コンパイルは成功し、実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 2 },
    explanation:
      "ソースファイルの要素の順序は「package 宣言 → import 宣言 → 型宣言」と決められています。package 宣言は必ず先頭（コメントを除く）に書かなければならないため、import のあとに package を書いた 2 行目でコンパイルエラーになります。",
  },
  {
    id: 13,
    topic: "basics",
    variantOf: "basics-args",
    question: "次のコードをコンパイルし、java Args とだけ入力して実行した場合の結果はどれか。1つ選びなさい。",
    className: "Args",
    code: [
      "public class Args {",
      "    public static void main(String[] args) {",
      "        System.out.println(args.length);",
      "    }",
      "}",
    ],
    choices: [
      "0",
      "1",
      "実行時に NullPointerException がスローされる",
      "実行時に ArrayIndexOutOfBoundsException がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "0" },
    explanation:
      "コマンドライン引数を渡さずに実行した場合、args には null ではなく要素数 0 の配列が渡されます。そのため args.length は 0 になり、NullPointerException は発生しません。args[0] のように要素を参照すると ArrayIndexOutOfBoundsException になります。",
  },

  // ==================================================== データ型 (datatypes)
  {
    id: 14,
    topic: "datatypes",
    variantOf: "datatypes-string-identity",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Text",
    code: [
      "public class Text {",
      "    public static void main(String[] args) {",
      '        String a = "java";',
      '        String b = "java";',
      '        String c = new String("java");',
      '        System.out.println((a == b) + " " + (a == c) + " " + a.equals(c));',
      "    }",
      "}",
    ],
    choices: [
      "true false true",
      "true true true",
      "false false true",
      "true false false",
      "false false false",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "true false true" },
    explanation:
      "同じ内容の文字列リテラルは文字列定数プールで共有されるため、a と b は同一のインスタンスを参照し a == b は true になります。一方 new String(...) は常に新しいインスタンスを生成するので a == c は false です。equals は内容を比較するため true になります。文字列の比較に == を使ってはいけない理由がここにあります。",
  },
  {
    id: 15,
    topic: "datatypes",
    variantOf: "datatypes-stringbuilder",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Builder",
    code: [
      "public class Builder {",
      "    public static void main(String[] args) {",
      '        StringBuilder sb = new StringBuilder("Java");',
      '        sb.append(11).insert(0, ">").reverse();',
      "        System.out.println(sb);",
      "    }",
      "}",
    ],
    choices: ["11avaJ>", ">Java11", "11avaJ", "Java11>", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "11avaJ>" },
    explanation:
      'StringBuilder のメソッドは自分自身を返すため、メソッドチェーンで順番に適用されます。"Java" に append(11) で "Java11"、insert(0, ">") で ">Java11"、reverse() で "11avaJ>" となります。StringBuilder は String と違って可変であり、変更は同じインスタンスに対して行われます。',
  },
  {
    id: 16,
    topic: "datatypes",
    variantOf: "datatypes-char-arithmetic",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Chars",
    code: [
      "public class Chars {",
      "    public static void main(String[] args) {",
      "        char c = 'A';",
      "        c += 2;",
      "        int i = c + 1;",
      '        System.out.println(c + " " + i);',
      "    }",
      "}",
    ],
    choices: ["C 68", "C 67", "67 68", "A2 68", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "C 68" },
    explanation:
      "char は内部的に数値（Unicode のコードポイント）として扱われます。'A' は 65 で、複合代入 c += 2 により 67、つまり 'C' になります。char を println に単独で渡すと文字として出力されるため C と表示されます。一方 c + 1 は算術演算で int に昇格するため 68 という数値になります。",
  },
  {
    id: 17,
    topic: "datatypes",
    variantOf: "datatypes-var",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Inference",
    code: [
      "public class Inference {",
      "    public static void main(String[] args) {",
      "        var count = 10;",
      "        var name = null;",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "コンパイルは成功し、10 が出力される",
      "コンパイルは成功し、実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "var はローカル変数の型を初期化子から推論する仕組みです。null は型を決められないため、var name = null; はコンパイルエラーになります。同様に、初期化子のない var、配列初期化子（var a = {1,2};）、ラムダ式の直接代入も型を推論できないためエラーになります。",
  },

  // ====================================================== 演算子 (operators)
  {
    id: 18,
    topic: "operators",
    variantOf: "operators-short-circuit",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Guard",
    code: [
      "public class Guard {",
      "    static int calls = 0;",
      "",
      "    static boolean check() {",
      "        calls++;",
      "        return true;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        boolean a = false && check();",
      "        boolean b = false & check();",
      '        System.out.println(calls + " " + a + " " + b);',
      "    }",
      "}",
    ],
    choices: ["1 false false", "2 false false", "0 false false", "1 false true", "2 true true"],
    correct: [0],
    expected: { kind: "output", stdout: "1 false false" },
    explanation:
      "&& は短絡評価を行い、左辺が false の時点で結果が確定するため右辺の check() は呼び出されません。一方 & は短絡評価を行わず両辺を必ず評価するため check() が呼ばれ、calls は 1 になります。結果はどちらも false です。|| と | にも同じ関係があります。",
  },
  {
    id: 19,
    topic: "operators",
    variantOf: "operators-string-concat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Concat",
    code: [
      "public class Concat {",
      "    public static void main(String[] args) {",
      '        System.out.println(1 + 2 + "3" + 4 + 5);',
      "    }",
      "}",
    ],
    choices: ["3345", "12345", "1545", "33 45", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3345" },
    explanation:
      '+ 演算子は左から順に評価されます。最初の 1 + 2 は両方とも数値なので算術加算となり 3 になります。次に 3 + "3" で文字列連結が始まり "33" となり、以降はすべて文字列連結として扱われるため "334"、"3345" となります。',
  },

  // ======================================================== 制御構造 (control)
  {
    id: 20,
    topic: "control",
    variantOf: "control-labeled-break",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Search",
    code: [
      "public class Search {",
      "    public static void main(String[] args) {",
      "        int found = -1;",
      "        outer:",
      "        for (int i = 0; i < 3; i++) {",
      "            for (int j = 0; j < 3; j++) {",
      "                if (i * j == 2) {",
      "                    found = i * 10 + j;",
      "                    break outer;",
      "                }",
      "            }",
      "        }",
      "        System.out.println(found);",
      "    }",
      "}",
    ],
    choices: ["12", "21", "-1", "2", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "12" },
    explanation:
      "ラベル付き break は指定したラベルのループごと抜けます。i=0 のときは積が常に 0、i=1 のとき j=2 で積が 2 となり条件が成立するため、found は 1 * 10 + 2 で 12 になり、外側のループごと終了します。ラベルなしの break では内側のループしか抜けられません。",
  },
  {
    id: 21,
    topic: "control",
    variantOf: "control-enhanced-for",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Loop",
    code: [
      "public class Loop {",
      "    public static void main(String[] args) {",
      "        int[] nums = {1, 2, 3};",
      "        for (int n : nums) {",
      "            n = n * 2;",
      "        }",
      '        System.out.println(nums[0] + " " + nums[1]);',
      "    }",
      "}",
    ],
    choices: ["1 2", "2 4", "1 4", "2 2", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 2" },
    explanation:
      "拡張 for 文のループ変数には、各要素の値がコピーされます。そのためループ変数に代入しても元の配列の要素は変わりません。配列の中身を書き換えたい場合は、通常の for 文でインデックスを使って nums[i] = nums[i] * 2 のように代入する必要があります。",
  },
  {
    id: 22,
    topic: "control",
    variantOf: "control-do-while",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Retry",
    code: [
      "public class Retry {",
      "    public static void main(String[] args) {",
      "        int i = 5;",
      "        do {",
      "            System.out.print(i);",
      "            i++;",
      "        } while (i < 3);",
      "    }",
      "}",
    ],
    choices: ["5", "何も出力されない", "56", "567", "無限ループになる"],
    correct: [0],
    expected: { kind: "output", stdout: "5" },
    explanation:
      "do-while 文は条件判定より先に本体を実行するため、条件が最初から偽でも必ず 1 回は実行されます。したがって 5 が出力され、その後 i が 6 になり条件 i < 3 が偽なのでループを抜けます。while 文であれば 1 回も実行されません。",
  },

  // ============================================================ 配列 (arrays)
  {
    id: 23,
    topic: "arrays",
    variantOf: "arrays-initializer",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Init",
    code: [
      "public class Init {",
      "    public static void main(String[] args) {",
      "        int[] a = {1, 2, 3};",
      "        int[] b;",
      "        b = {4, 5, 6};",
      "        System.out.println(a.length + b.length);",
      "    }",
      "}",
    ],
    choices: [
      "5行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "コンパイルは成功し、6 が出力される",
      "コンパイルは成功し、33 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 5 },
    explanation:
      "{1, 2, 3} という配列初期化子は、宣言と同時に初期化する場合にしか使えません。宣言済みの変数へあとから代入するには b = new int[] {4, 5, 6}; のように new を伴う配列生成式を使う必要があります。",
  },
  {
    id: 24,
    topic: "arrays",
    variantOf: "arrays-covariance",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Store",
    code: [
      "public class Store {",
      "    public static void main(String[] args) {",
      "        Object[] objects = new String[2];",
      '        objects[0] = "ok";',
      "        objects[1] = 42;",
      "        System.out.println(objects[0]);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ArrayStoreException がスローされる",
      "ok と出力される",
      "5行目でコンパイルエラーになる",
      "実行時に ClassCastException がスローされる",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ArrayStoreException" },
    explanation:
      "配列は共変であるため String[] を Object[] 型の変数に代入でき、コンパイルも通ります。しかし実行時の実体は String[] なので、String 以外の値（オートボクシングされた Integer）を格納しようとすると ArrayStoreException がスローされます。配列の型安全性が実行時にしか検出されない例です。",
  },

  // ========================================================== メソッド (methods)
  {
    id: 25,
    topic: "methods",
    variantOf: "methods-varargs",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Sum",
    code: [
      "public class Sum {",
      "    static int total(int... values) {",
      "        int sum = 0;",
      "        for (int v : values) {",
      "            sum += v;",
      "        }",
      "        return sum;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(total() + " " + total(1, 2) + " " + total(new int[] {3, 4}));',
      "    }",
      "}",
    ],
    choices: ["0 3 7", "0 3 2", "実行時に NullPointerException がスローされる", "0 12 34", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "0 3 7" },
    explanation:
      "可変長引数は呼び出し側で配列として受け取られます。引数を渡さない場合は null ではなく長さ 0 の配列になるため合計は 0 です。値を並べて渡した場合も、配列を直接渡した場合も同じように扱われるため、それぞれ 3 と 7 になります。",
  },
  {
    id: 26,
    topic: "methods",
    variantOf: "methods-static-context",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Account",
    code: [
      "public class Account {",
      "    private int balance = 100;",
      "",
      "    static int peek() {",
      "        return balance;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(peek());",
      "    }",
      "}",
    ],
    choices: [
      "5行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功し、100 が出力される",
      "コンパイルは成功し、0 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 5 },
    explanation:
      "static メソッドはインスタンスに属さないため、インスタンスフィールドを直接参照できません。balance はインスタンスフィールドなので「non-static variable balance cannot be referenced from a static context」というコンパイルエラーになります。参照するにはインスタンスを生成するか、フィールドを static にする必要があります。",
  },
  {
    id: 27,
    topic: "methods",
    variantOf: "methods-constructor-chaining",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Box",
    code: [
      "public class Box {",
      "    private final String label;",
      "",
      "    Box() {",
      '        this("empty");',
      '        System.out.print("no-arg ");',
      "    }",
      "",
      "    Box(String label) {",
      "        this.label = label;",
      '        System.out.print("arg ");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Box box = new Box();",
      "        System.out.println(box.label);",
      "    }",
      "}",
    ],
    choices: ["arg no-arg empty", "no-arg arg empty", "arg empty", "no-arg empty", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "arg no-arg empty" },
    explanation:
      "this(...) による他のコンストラクタの呼び出しは、コンストラクタ本体の最初の文でなければなりません。new Box() はまず Box(String) を実行して arg を出力し、そのあと呼び出し元である Box() の残りの処理で no-arg を出力します。最後に label の値 empty が出力されます。",
  },

  // ==================================================== 継承 (inheritance)
  {
    id: 28,
    topic: "inheritance",
    variantOf: "inheritance-abstract-anonymous",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Runner",
    code: [
      "abstract class Task {",
      "    abstract String name();",
      "",
      "    void run() {",
      '        System.out.print("run:" + name());',
      "    }",
      "}",
      "",
      "public class Runner {",
      "    public static void main(String[] args) {",
      "        Task task = new Task() {",
      "            @Override",
      "            String name() {",
      '                return "anon";',
      "            }",
      "        };",
      "        task.run();",
      "    }",
      "}",
    ],
    choices: [
      "run:anon",
      "抽象クラスはインスタンス化できないためコンパイルエラーになる",
      "run:null",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "run:anon" },
    explanation:
      "抽象クラスは直接 new できませんが、匿名クラスとして抽象メソッドを実装すればインスタンスを生成できます。new Task() { ... } は「Task を継承した名前のないクラス」を定義してインスタンス化する構文であり、抽象クラス自体のインスタンス化ではありません。",
  },
  {
    id: 29,
    topic: "inheritance",
    variantOf: "inheritance-class-wins",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Service",
    code: [
      "interface Greeting {",
      "    default String hello() {",
      '        return "interface";',
      "    }",
      "}",
      "",
      "class Base {",
      "    public String hello() {",
      '        return "class";',
      "    }",
      "}",
      "",
      "public class Service extends Base implements Greeting {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Service().hello());",
      "    }",
      "}",
    ],
    choices: ["class", "interface", "あいまいなためコンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "class" },
    explanation:
      "スーパークラスのメソッドとインタフェースの default メソッドが競合した場合、「クラスが勝つ」というルールが適用されます。そのため Base の hello() が使われ class が出力されます。あいまいでコンパイルエラーになるのは、競合するのが複数のインタフェースの default メソッド同士の場合です。",
  },
  {
    id: 30,
    topic: "inheritance",
    variantOf: "inheritance-cast",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Zoo",
    code: [
      "class Animal {",
      "}",
      "",
      "class Dog extends Animal {",
      "}",
      "",
      "class Cat extends Animal {",
      "}",
      "",
      "public class Zoo {",
      "    public static void main(String[] args) {",
      "        Animal animal = new Dog();",
      "        Cat cat = (Cat) animal;",
      "        System.out.println(cat);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ClassCastException がスローされる",
      "13行目でコンパイルエラーになる",
      "null と出力される",
      "実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ClassCastException" },
    explanation:
      "Animal 型の変数を Cat にキャストする記述は、継承関係があるためコンパイル時には許容されます。しかし実行時の実体は Dog であり Cat ではないため、ClassCastException がスローされます。キャストの前に instanceof で型を確認するのが安全です。",
  },

  // ============================================================ ラムダ (lambda)
  {
    id: 31,
    topic: "lambda",
    variantOf: "lambda-effectively-final",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Capture",
    code: [
      "interface Action {",
      "    void run();",
      "}",
      "",
      "public class Capture {",
      "    public static void main(String[] args) {",
      "        int count = 0;",
      "        Action action = () -> System.out.println(count);",
      "        count = 1;",
      "        action.run();",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "コンパイルは成功し、0 が出力される",
      "コンパイルは成功し、1 が出力される",
      "10行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "ラムダ式が参照するローカル変数は「実質的に final」でなければなりません。count はラムダ式のあとで再代入されているため実質的に final ではなくなり、参照している 8 行目でコンパイルエラーになります。再代入をやめるか、値を別の変数にコピーして使う必要があります。",
  },
  {
    id: 32,
    topic: "lambda",
    variantOf: "lambda-builtin-interfaces",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Picker",
    code: [
      "import java.util.function.Predicate;",
      "import java.util.function.Supplier;",
      "",
      "public class Picker {",
      "    public static void main(String[] args) {",
      '        Supplier<String> supplier = () -> "value";',
      "        Predicate<String> isLong = s -> s.length() > 3;",
      '        System.out.println(isLong.test(supplier.get()) + " " + isLong.negate().test("ab"));',
      "    }",
      "}",
    ],
    choices: ["true true", "true false", "false true", "false false", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true true" },
    explanation:
      'Supplier は引数を取らず値を返す関数型インタフェースで、get() は "value" を返します。その長さは 5 なので isLong.test(...) は true です。negate() は判定を反転する default メソッドで、"ab" は長さ 2 なので元の判定は false、反転して true になります。',
  },

  // ================================================================= API (api)
  {
    id: 33,
    topic: "api",
    variantOf: "api-immutable-list",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Immutable",
    code: [
      "import java.util.List;",
      "",
      "public class Immutable {",
      "    public static void main(String[] args) {",
      '        List<String> names = List.of("a", "b");',
      '        names.add("c");',
      "        System.out.println(names);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に UnsupportedOperationException がスローされる",
      "[a, b, c] と出力される",
      "6行目でコンパイルエラーになる",
      "[a, b] と出力される",
      "実行時に IllegalStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedOperationException" },
    explanation:
      "List.of(...) が返すのは変更不可能なリストです。add や remove などの変更操作を呼び出すと UnsupportedOperationException がスローされます。要素を追加したい場合は new ArrayList<>(List.of(...)) のように可変のリストへコピーする必要があります。",
  },
  {
    id: 34,
    topic: "api",
    variantOf: "api-localdate-immutable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Schedule",
    code: [
      "import java.time.LocalDate;",
      "",
      "public class Schedule {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2026, 1, 31);",
      "        date.plusMonths(1);",
      "        System.out.println(date);",
      "    }",
      "}",
    ],
    choices: ["2026-01-31", "2026-02-28", "2026-02-31", "実行時に例外がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2026-01-31" },
    explanation:
      "LocalDate は不変クラスです。plusMonths などのメソッドは自身を変更せず、新しいインスタンスを返します。戻り値を変数に代入していないため date は元のままで 2026-01-31 が出力されます。なお date = date.plusMonths(1) とした場合は、2 月に 31 日が存在しないため月末に補正され 2026-02-28 になります。",
  },

  // ======================================================= 例外 (exceptions)
  {
    id: 35,
    topic: "exceptions",
    variantOf: "exceptions-checked",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Loader",
    code: [
      "import java.io.IOException;",
      "",
      "public class Loader {",
      "    static void load() throws IOException {",
      '        throw new IOException("failed");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        load();",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、実行時に IOException がスローされる",
      "コンパイルは成功し、何も出力されずに終了する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "IOException は検査例外なので、呼び出し側は try-catch で捕捉するか、throws 句で再送出を宣言しなければなりません。main メソッドはどちらも行っていないため、呼び出している 9 行目でコンパイルエラーになります。RuntimeException のような非検査例外ではこの制約はありません。",
  },
  {
    id: 36,
    topic: "exceptions",
    variantOf: "exceptions-twr-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Closer",
    code: [
      "class Handle implements AutoCloseable {",
      "    private final String name;",
      "",
      "    Handle(String name) {",
      "        this.name = name;",
      "    }",
      "",
      "    @Override",
      "    public void close() {",
      '        System.out.print("close:" + name + " ");',
      "    }",
      "}",
      "",
      "public class Closer {",
      "    public static void main(String[] args) {",
      '        try (Handle a = new Handle("A"); Handle b = new Handle("B")) {',
      '            System.out.print("body ");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "body close:B close:A",
      "body close:A close:B",
      "close:A close:B body",
      "body",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "body close:B close:A" },
    explanation:
      "try-with-resources では、try ブロックの終了時にリソースが自動的にクローズされます。閉じる順序は宣言と逆順（後に宣言したものから先）です。そのため本体の出力のあと、B、A の順に close() が呼ばれます。リソースは AutoCloseable を実装している必要があります。",
  },
  {
    id: 37,
    topic: "exceptions",
    variantOf: "exceptions-multicatch",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Divider",
    code: [
      "public class Divider {",
      "    public static void main(String[] args) {",
      "        try {",
      "            int result = 10 / 0;",
      "            System.out.print(result);",
      "        } catch (ArithmeticException | NullPointerException e) {",
      '            System.out.print("caught ");',
      "        } finally {",
      '            System.out.print("done");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["caught done", "done", "caught", "実行時に ArithmeticException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "caught done" },
    explanation:
      "整数の 0 除算は ArithmeticException を発生させます。マルチキャッチ（|）は関係のない複数の例外型をまとめて捕捉する構文で、ここでは ArithmeticException が捕捉され caught が出力されます。finally は必ず実行されるため done が続きます。なお浮動小数点数の 0.0 除算では例外は起きず Infinity になります。",
  },
];
