import type { SilverQuestion } from "../quizTypes";

/** 亜種の追加・その6（例外 / API / モジュール、id 601 以降）。これで全論点に亜種が揃う */
export const variantQuestions8: SilverQuestion[] = [
  // ======================================================= 例外 (exceptions)
  {
    id: 601,
    topic: "exceptions",
    variantOf: "exceptions-hierarchy",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "CatchError",
    code: [
      "public class CatchError {",
      "    public static void main(String[] args) {",
      "        try {",
      '            throw new java.io.IOException("x");',
      "        } catch (RuntimeException e) {",
      '            System.out.print("runtime");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "IOException が捕捉されず throws も無いためコンパイルエラーになる",
      "コンパイルは成功し、runtime が出力される",
      "コンパイルは成功し、実行時に IOException がスローされる",
      "コンパイルは成功し、何も出力されない",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "IOException は検査例外なので、捕捉するか throws で宣言しなければなりません。catch しているのは RuntimeException だけで IOException の系統ではないため、要件を満たさずコンパイルエラーになります。検査例外と非検査例外を分ける境界が RuntimeException（と Error）であり、そこから外れる Exception の派生型はすべて検査例外です。「catch を書いたから大丈夫」ではなく、捕まえている型が実際に投げられる型を含むかどうかが問われます。",
  },
  {
    id: 602,
    topic: "exceptions",
    variantOf: "exceptions-catch-order-unreachable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Specific",
    code: [
      "public class Specific {",
      "    public static void main(String[] args) {",
      "        try {",
      "            Object o = null;",
      "            o.toString();",
      "        } catch (NullPointerException e) {",
      '            System.out.print("npe");',
      "        } catch (RuntimeException e) {",
      '            System.out.print("runtime");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["npe", "runtime", "npeuntime", "コンパイルエラーになる", "何も出力されない"],
    correct: [0],
    expected: { kind: "output", stdout: "npe" },
    explanation:
      "具体的な型を先に書いているため、この順序は正しくコンパイルできます。最初に一致した catch だけが実行されるので npe が出力され、後続の catch は評価されません。逆順に書くと、後ろの catch が到達不能となりコンパイルエラーです。例外処理は「該当する最初のハンドラに任せる」という単純な規則で動いており、複数の catch が連鎖して実行されることはありません。共通の後処理が必要なら finally にまとめます。",
  },
  {
    id: 603,
    topic: "exceptions",
    variantOf: "exceptions-finally-after-return",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Override2",
    code: [
      "public class Override2 {",
      "    static int compute() {",
      "        try {",
      "            return 1;",
      "        } finally {",
      "            return 2;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(compute());",
      "    }",
      "}",
    ],
    choices: ["2", "1", "12", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2" },
    explanation:
      "finally の中に return を書くと、try で確定していた戻り値を上書きしてしまいます。そのため 1 ではなく 2 が返ります。さらに恐ろしいのは、try 内で例外が発生していた場合でも finally の return がそれを握りつぶし、呼び出し元は異常に気づけなくなる点です。finally は後始末のための場所であり、制御フローを変える構文を置くべきではありません。多くの静的解析ツールが finally 内の return を警告するのはこのためです。",
  },
  {
    id: 604,
    topic: "exceptions",
    variantOf: "exceptions-custom-exception",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Unchecked",
    code: [
      "class ConfigError extends RuntimeException {",
      "    ConfigError(String message) {",
      "        super(message);",
      "    }",
      "}",
      "",
      "public class Unchecked {",
      "    static void load() {",
      '        throw new ConfigError("broken");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        try {",
      "            load();",
      "        } catch (RuntimeException e) {",
      "            System.out.print(e.getMessage());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["broken", "null", "ConfigError", "throws が無いためコンパイルエラーになる", "実行時に終了する"],
    correct: [0],
    expected: { kind: "output", stdout: "broken" },
    explanation:
      "RuntimeException を継承した独自例外は非検査例外なので、throws 宣言なしで投げられます。捕捉する際は親である RuntimeException でも受けられ、getMessage() で渡したメッセージを取り出せます。検査例外にするか非検査例外にするかは、呼び出し側が回復できる見込みがあるかで決めるのが基本です。設定不備のようにプログラムの前提が崩れている場合は、各所で catch を強制するより、起動時にまとめて失敗させる方が扱いやすいという判断もあります。",
  },
  {
    id: 605,
    topic: "exceptions",
    variantOf: "exceptions-throws-override",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Narrower",
    code: [
      "import java.io.IOException;",
      "",
      "class Reader2 {",
      "    void read() throws Exception {",
      "    }",
      "}",
      "",
      "public class Narrower extends Reader2 {",
      "    @Override",
      "    void read() throws IOException {",
      '        System.out.print("ok");',
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        new Narrower().read();",
      "    }",
      "}",
    ],
    choices: ["ok", "コンパイルエラーになる", "実行時に IOException がスローされる", "何も出力されない"],
    correct: [0],
    expected: { kind: "output", stdout: "ok" },
    explanation:
      "オーバーライドで宣言する検査例外は、親が宣言したものと同じか、その派生型に狭める分には問題ありません。IOException は Exception の派生型なので許されます。呼び出し側は親の宣言を前提に例外処理を書いているため、実際に投げられる範囲が狭まる分には困らないからです。まったく宣言しない（例外を投げない）ことも可能です。逆に広げることだけが禁止されており、戻り値やアクセス修飾子と同じく「利用者が困らない方向」だけが許されています。",
  },
  {
    id: 606,
    topic: "exceptions",
    variantOf: "exceptions-nested-try",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "InnerCatch",
    code: [
      "public class InnerCatch {",
      "    public static void main(String[] args) {",
      "        try {",
      "            try {",
      '                throw new IllegalStateException("x");',
      "            } catch (IllegalStateException e) {",
      '                System.out.print("inner ");',
      "            } finally {",
      '                System.out.print("if ");',
      "            }",
      "        } catch (RuntimeException e) {",
      '            System.out.print("outer");',
      "        }",
      '        System.out.print("end");',
      "    }",
      "}",
    ],
    choices: ["inner if end", "inner if outer end", "if inner end", "outer end", "inner end"],
    correct: [0],
    expected: { kind: "output", stdout: "inner if end" },
    explanation:
      "内側の catch が例外を捕まえて処理を完了しているため、外側へは伝播しません。内側の finally は実行され、外側の catch は呼ばれずに後続の処理へ進みます。例外は「捕捉された時点で流れが正常へ戻る」という点が重要で、捕まえた以上は外側に伝わりません。もし外側にも知らせたいなら、catch の中で再スローする必要があります。どの階層で例外を処理するかを設計する際は、この「捕まえたら止まる」性質が判断の基礎になります。",
  },
  {
    id: 607,
    topic: "exceptions",
    variantOf: "exceptions-propagation",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Rethrow",
    code: [
      "public class Rethrow {",
      "    static void inner() {",
      '        throw new IllegalArgumentException("bad");',
      "    }",
      "",
      "    static void middle() {",
      "        try {",
      "            inner();",
      "        } catch (IllegalArgumentException e) {",
      '            System.out.print("logged ");',
      "            throw e;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        try {",
      "            middle();",
      "        } catch (RuntimeException e) {",
      "            System.out.print(e.getMessage());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["logged bad", "bad", "logged", "logged badbad", "実行時に終了する"],
    correct: [0],
    expected: { kind: "output", stdout: "logged bad" },
    explanation:
      "catch した例外を throw で再スローすると、記録などの処理を挟みつつ上位へ伝播させられます。middle が logged を出力してから例外を投げ直し、main で捕まえてメッセージを出力します。再スローは「自分では対処しきれないが、通過したことは残したい」場面で使われます。ただし各階層で記録すると同じ例外が何度も出力されるため、実務では最終的に処理する場所でまとめて記録するのが一般的です。",
  },
  {
    id: 608,
    topic: "exceptions",
    variantOf: "exceptions-twr-final",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Existing",
    code: [
      "class Conn implements AutoCloseable {",
      "    @Override",
      "    public void close() {",
      '        System.out.print("closed");',
      "    }",
      "}",
      "",
      "public class Existing {",
      "    public static void main(String[] args) {",
      "        Conn conn = new Conn();",
      "        try (conn) {",
      '            System.out.print("use ");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "use closed",
      "closed use",
      "use",
      "既存の変数は try に書けないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "use closed" },
    explanation:
      "Java 9 以降、すでに宣言済みで実質的に final なローカル変数であれば、try (conn) のように変数名だけを書いてリソースとして扱えます。従来は try の括弧内で必ず宣言し直す必要があり、外で作ったリソースを渡すのに余分な変数が要りました。実質的に final であることが条件なのは、閉じる対象が途中で差し替わらないことを保証するためです。閉じる責任が try 文にあるという点は従来と同じで、ブロックを抜けるときに close が呼ばれます。",
  },
  {
    id: 609,
    topic: "exceptions",
    variantOf: "exceptions-arithmetic-division",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NotANumber",
    code: [
      "public class NotANumber {",
      "    public static void main(String[] args) {",
      "        double result = 0.0 / 0.0;",
      '        System.out.println(result + " " + (result == result));',
      "    }",
      "}",
    ],
    choices: [
      "NaN false",
      "NaN true",
      "0.0 true",
      "実行時に ArithmeticException がスローされる",
      "Infinity false",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "NaN false" },
    explanation:
      "0.0 / 0.0 は数学的に定義できないため NaN（非数）になります。NaN は自分自身とも等しくないと定められており、result == result が false になるのはそのためです。この性質は IEEE 754 の規定で、「未定義の値どうしを等しいと見なせない」という考えに基づきます。そのため NaN の判定には == ではなく Double.isNaN を使います。整数の 0 除算が例外になるのと違い、浮動小数点は計算を止めずに特別な値を伝播させる設計になっています。",
  },
  {
    id: 610,
    topic: "exceptions",
    variantOf: "exceptions-clause-order",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "OnlyTry",
    code: [
      "public class OnlyTry {",
      "    public static void main(String[] args) {",
      "        try {",
      '            System.out.print("t");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "catch も finally も無いためコンパイルエラーになる",
      "コンパイルは成功し、t が出力される",
      "コンパイルは成功し、何も出力されない",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "try 文には catch か finally の少なくとも一方が必要です。どちらも無いと、例外が起きたときの扱いも後始末も指定していないことになり、try で囲む意味がありません。例外なのは try-with-resources で、リソースを宣言していればクローズ処理が暗黙の finally として機能するため、catch も finally も省略できます。構文が「必ず何らかの対処を書かせる」形になっているのは、囲っただけで安心してしまう誤りを防ぐためです。",
  },

  // ================================================================= API (api)
  {
    id: 611,
    topic: "api",
    variantOf: "api-arraylist-insert",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Replace",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Replace {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>();",
      '        list.add("a");',
      '        list.add("b");',
      '        list.set(1, "c");',
      '        System.out.println(list + " " + list.size());',
      "    }",
      "}",
    ],
    choices: ["[a, c] 2", "[a, b, c] 3", "[c, b] 2", "[a, c] 3", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[a, c] 2" },
    explanation:
      "set は指定位置の要素を置き換えるだけで、要素数は変わりません。add(int, E) が挿入して後続をずらすのとは別の操作です。名前が似ていて紛らわしいですが、「set は上書き、add は追加」と区別します。set は存在する位置にしか使えないため、リストの末尾を超える添字を指定すると IndexOutOfBoundsException になります。空のリストに対して set(0, x) が失敗するのはこのためで、追加したいときは必ず add を使います。",
  },
  {
    id: 612,
    topic: "api",
    variantOf: "api-string-split",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TrailingEmpty",
    code: [
      "public class TrailingEmpty {",
      "    public static void main(String[] args) {",
      '        String text = "a,b,,";',
      '        System.out.println(text.split(",").length + " " + text.split(",", -1).length);',
      "    }",
      "}",
    ],
    choices: ["2 4", "4 4", "2 2", "3 4", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 4" },
    explanation:
      "split は既定で末尾の空要素を取り除くため、\"a,b,,\" は 2 要素になります。第 2 引数に -1 を渡すと制限なしとなり、末尾の空要素も残って 4 要素です。既定で切り捨てるのは、区切り文字で終わる文字列を扱う際に余計な空文字列を気にしなくて済むようにという配慮ですが、列数が固定の CSV を解析するときは逆に困ります。データの形を保ったまま扱いたい場合は -1 を明示するのが定石です。",
  },
  {
    id: 613,
    topic: "api",
    variantOf: "api-string-format",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Padding",
    code: [
      "public class Padding {",
      "    public static void main(String[] args) {",
      '        System.out.println(String.format("[%5d][%-5s]", 42, "ab"));',
      "    }",
      "}",
    ],
    choices: ["[   42][ab   ]", "[42   ][   ab]", "[42][ab]", "[   42][   ab]", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[   42][ab   ]" },
    explanation:
      "数字は最小幅を指定すると既定で右寄せになり、%5d は空白 3 つを前に付けて 5 文字幅にします。マイナス記号を付けた %-5s は左寄せになるため、文字列の後ろが空白で埋められます。数値が右寄せなのは桁を揃えて読むため、文字列が左寄せにしやすいのは先頭を揃えて読むため、という用途の違いが既定値に反映されています。表形式の出力を整える際によく使う書式なので、幅とマイナス記号の組み合わせは押さえておくと便利です。",
  },
  {
    id: 614,
    topic: "api",
    variantOf: "api-math-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Rounding",
    code: [
      "public class Rounding {",
      "    public static void main(String[] args) {",
      '        System.out.println(Math.round(-2.5) + " " + Math.ceil(2.1) + " " + Math.floor(-2.1));',
      "    }",
      "}",
    ],
    choices: ["-2 3.0 -3.0", "-3 3.0 -3.0", "-2 2.0 -2.0", "-3 3.0 -2.0", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "-2 3.0 -3.0" },
    explanation:
      "Math.round は中間値を正の無限大方向へ寄せるため、-2.5 は -2 になります（-3 ではありません）。ceil は正の無限大方向へ、floor は負の無限大方向へ丸めるので、それぞれ 3.0 と -3.0 です。round だけが long や int を返し、ceil と floor は double を返すため、出力に小数点が付くかどうかも変わります。負数を扱うときに「四捨五入」という日本語の感覚と結果がずれる点が、この 3 つを混同しやすい理由です。",
  },
  {
    id: 615,
    topic: "api",
    variantOf: "api-localdate-month-end",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Leap",
    code: [
      "import java.time.LocalDate;",
      "",
      "public class Leap {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2024, 2, 29);",
      "        System.out.println(date.plusYears(1));",
      "    }",
      "}",
    ],
    choices: [
      "2025-02-28",
      "2025-03-01",
      "2025-02-29",
      "実行時に DateTimeException がスローされる",
      "2024-02-29",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "2025-02-28" },
    explanation:
      "2025 年は閏年ではないため 2 月 29 日が存在せず、月末である 28 日に補正されます。例外にせず補正するのは、「1 年後」という人間の感覚に沿った結果を返すためです。ただしこの補正は不可逆で、そこからさらに 1 年戻しても 2 月 29 日には戻りません。閏日を基準にした期間計算や、月末起算の契約日を扱う処理では、補正によって日付がずれていく点を考慮する必要があります。",
  },
  {
    id: 616,
    topic: "api",
    variantOf: "api-contains-equals",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "IndexSearch",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class IndexSearch {",
      "    public static void main(String[] args) {",
      "        List<String> items = new ArrayList<>();",
      '        items.add("a");',
      '        items.add("b");',
      '        System.out.println(items.indexOf("b") + " " + items.indexOf("z"));',
      "    }",
      "}",
    ],
    choices: ["1 -1", "1 0", "2 -1", "1 null", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 -1" },
    explanation:
      "indexOf は equals による比較で最初に一致した位置を返し、見つからなければ -1 を返します。String は equals を内容比較として実装しているため期待どおりに動きます。自作クラスで equals を実装していないと、内容が同じでも見つからず -1 になります。「見つからない」を例外ではなく -1 で表すのは、探索の失敗が通常の結果だからです。戻り値を確認せずに添字として使うと範囲外アクセスになるため、必ず判定してから使います。",
  },
  {
    id: 617,
    topic: "api",
    variantOf: "api-integer-overflow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Widened2",
    code: [
      "public class Widened2 {",
      "    public static void main(String[] args) {",
      "        long result = Integer.MAX_VALUE + 1L;",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: [
      "2147483648",
      "-2147483648",
      "2147483647",
      "実行時に ArithmeticException がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "2147483648" },
    explanation:
      "片方が long リテラル（1L）なので、演算の前に int が long へ拡大変換され、long の範囲で計算されます。そのためオーバーフローせず正しい値になります。もし 1 と書いていれば int どうしの計算となり、代入先が long でも桁あふれした後の値が入ります。「代入先の型ではなく、演算する時点の型で結果が決まる」というのが要点です。大きな値を扱う計算では、演算の前に long へ広げておくのが定石になります。",
  },
  {
    id: 618,
    topic: "api",
    variantOf: "api-remove-index-shift",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Backwards",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Backwards {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>();",
      '        list.add("a");',
      '        list.add("b");',
      '        list.add("c");',
      "        for (int i = list.size() - 1; i >= 0; i--) {",
      "            list.remove(i);",
      "        }",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[]",
      "[b]",
      "[a]",
      "実行時に IndexOutOfBoundsException がスローされる",
      "実行時に ConcurrentModificationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[]" },
    explanation:
      "末尾から先頭へ向かって削除すれば、削除によって前に詰まるのは常に「すでに処理した位置より後ろ」なので、まだ見ていない要素の添字がずれません。結果としてすべて削除できます。前から削除すると 1 つ飛ばしになるのと対照的で、走査方向を変えるだけで問題が消えるのが要点です。拡張 for 文では添字を扱えないため、同じことをするならイテレータの remove か removeIf を使います。",
  },
  {
    id: 619,
    topic: "api",
    variantOf: "api-hashmap-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Missing",
    code: [
      "import java.util.HashMap;",
      "import java.util.Map;",
      "",
      "public class Missing {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> map = new HashMap<>();",
      '        map.put("a", 1);',
      '        System.out.println(map.get("z") + " " + map.getOrDefault("z", 0) + " " + map.containsKey("z"));',
      "    }",
      "}",
    ],
    choices: ["null 0 false", "0 0 false", "null null false", "null 0 true", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "null 0 false" },
    explanation:
      "存在しないキーに対して get は null を返します。値の型が Integer（参照型）なので null を返せますが、これを int に代入するとアンボクシングで NullPointerException になります。getOrDefault を使えば既定値を指定でき、この危険を避けられます。値として null を格納できる HashMap では、get の結果が null でも「キーが無い」のか「値が null」なのか区別できないため、存在確認には containsKey を使うのが確実です。",
  },
  {
    id: 620,
    topic: "api",
    variantOf: "api-foreach-consumer",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Mutation",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Mutation {",
      "    public static void main(String[] args) {",
      "        List<String> items = new ArrayList<>();",
      '        items.add("a");',
      '        items.add("b");',
      '        items.removeIf(item -> item.equals("a"));',
      "        System.out.println(items);",
      "    }",
      "}",
    ],
    choices: [
      "[b]",
      "[a]",
      "[a, b]",
      "実行時に ConcurrentModificationException がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[b]" },
    explanation:
      "removeIf は条件に合う要素をまとめて削除するメソッドで、内部でイテレータを使って安全に走査するため ConcurrentModificationException になりません。引数は Predicate なのでラムダ式を渡せます。拡張 for 文の中でリストを変更すると例外になるのに対し、意図を宣言的に伝えるこの形なら安全に書けます。Collection の default メソッドとして追加されたため、既存の実装クラスを変更せずに利用できるようになっています。",
  },
  {
    id: 621,
    topic: "api",
    variantOf: "api-comparator-contract",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Natural",
    code: [
      "import java.util.ArrayList;",
      "import java.util.Collections;",
      "import java.util.List;",
      "",
      "public class Natural {",
      "    public static void main(String[] args) {",
      "        List<Integer> numbers = new ArrayList<>();",
      "        numbers.add(3);",
      "        numbers.add(1);",
      "        numbers.add(2);",
      "        Collections.sort(numbers);",
      "        System.out.println(numbers);",
      "    }",
      "}",
    ],
    choices: ["[1, 2, 3]", "[3, 2, 1]", "[3, 1, 2]", "実行時に ClassCastException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 2, 3]" },
    explanation:
      "Comparator を渡さない sort は、要素の自然順序（Comparable の compareTo）で並べ替えます。Integer は数値の昇順として compareTo を実装しているため [1, 2, 3] になります。要素が Comparable を実装していない型だと、コンパイルは通っても実行時に ClassCastException になります。並び順をその場で決めたい場合や、自然順序とは違う基準で並べたい場合に Comparator を渡す、という使い分けになります。",
  },

  // ========================================================== モジュール (modules)
  {
    id: 622,
    topic: "modules",
    variantOf: "modules-exports",
    question:
      "モジュール com.example.lib が次の module-info.java を持つ。このモジュールの説明として正しいものはどれか。1つ選びなさい。",
    code: [
      "module com.example.lib {",
      "    requires java.logging;",
      "    exports com.example.lib.api;",
      "    exports com.example.lib.spi;",
      "}",
    ],
    choices: [
      "com.example.lib.api と com.example.lib.spi の public 型が、すべてのモジュールから参照できる",
      "exports は 1 つのモジュールに 1 つしか書けないためコンパイルできない",
      "java.logging を requires したモジュールからのみ参照できる",
      "2 つのパッケージは同じモジュール内からしか参照できない",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "both" },
    // exports を 2 つ書いた両方のパッケージが利用側から使えることを確認する
    moduleSetup: {
      main: "com.example.client/com.example.client.Main",
      sources: [
        { module: "com.example.lib", path: "module-info.java", content: ["module com.example.lib {", "    requires java.logging;", "    exports com.example.lib.api;", "    exports com.example.lib.spi;", "}"] },
        { module: "com.example.lib", path: "com/example/lib/api/Api.java", content: ["package com.example.lib.api;", "", "public class Api {", "}"] },
        { module: "com.example.lib", path: "com/example/lib/spi/Spi.java", content: ["package com.example.lib.spi;", "", "public class Spi {", "}"] },
        { module: "com.example.client", path: "module-info.java", content: ["module com.example.client {", "    requires com.example.lib;", "}"] },
        { module: "com.example.client", path: "com/example/client/Main.java", content: ["package com.example.client;", "", "import com.example.lib.api.Api;", "import com.example.lib.spi.Spi;", "", "public class Main {", "    public static void main(String[] args) {", "        new Api();", "        new Spi();", "        System.out.println(\"both\");", "    }", "}"] },
      ],
    },
    explanation:
      "exports は必要な数だけ記述でき、指定した各パッケージの public 型が他モジュールへ公開されます。requires は自分が他を使うための宣言で、公開範囲とは無関係です。公開したいパッケージを 1 つずつ列挙させる方式なのは、「明示したものだけを見せる」という原則を徹底するためで、書き忘れたパッケージが意図せず公開されることはありません。特定のモジュールにだけ見せたい場合は exports ... to を使います。",
  },
  {
    id: 623,
    topic: "modules",
    variantOf: "modules-requires-transitive",
    question:
      "モジュール A が「requires transitive B」と宣言し、モジュール C が「requires A」と宣言している。この関係の説明として正しいものはどれか。1つ選びなさい。",
    choices: [
      "C は B を requires しなくても B の公開型を利用できる",
      "C は B を利用するために requires B を追加しなければならない",
      "A は B の公開型を利用できない",
      "C は A の公開型を利用できない",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "ok" },
    // requires transitive により、C が mod.b を requires せずに b.api を使えることを確認する
    moduleSetup: {
      main: "mod.c/c.Main",
      sources: [
        { module: "mod.b", path: "module-info.java", content: ["module mod.b {", "    exports b.api;", "}"] },
        { module: "mod.b", path: "b/api/Service.java", content: ["package b.api;", "", "public class Service {", "}"] },
        { module: "mod.a", path: "module-info.java", content: ["module mod.a {", "    requires transitive mod.b;", "    exports a.api;", "}"] },
        { module: "mod.a", path: "a/api/Facade.java", content: ["package a.api;", "", "public class Facade {", "}"] },
        { module: "mod.c", path: "module-info.java", content: ["module mod.c {", "    requires mod.a;", "}"] },
        { module: "mod.c", path: "c/Main.java", content: ["package c;", "", "import a.api.Facade;", "import b.api.Service;", "", "public class Main {", "    public static void main(String[] args) {", "        new Facade();", "        new Service();", "        System.out.println(\"ok\");", "    }", "}"] },
      ],
    },
    explanation:
      "requires transitive は依存を利用側へ引き継ぐ宣言なので、C は B を明示的に requires しなくても使えます。これが必要になるのは、A の公開 API の戻り値や引数に B の型が現れる場合です。利用者がその型を受け取れなければコンパイルできないため、A 自身が「私を使うなら B も必要だ」と宣言する責任を負います。逆に内部実装でしか使わない依存を transitive にすると、不要な依存が利用側へ広がってしまいます。",
  },
  {
    id: 624,
    topic: "modules",
    variantOf: "modules-java-base",
    question: "モジュールシステムにおける暗黙の依存関係について、正しい説明はどれか。1つ選びなさい。",
    choices: [
      "すべてのモジュールは java.base を暗黙的に requires する",
      "すべてのモジュールは java.se を暗黙的に requires する",
      "暗黙の依存は存在せず、必要なモジュールはすべて明示しなければならない",
      "同じ名前空間のモジュールは互いを暗黙的に requires する",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "implicit" },
    // java.base を書かなくても List や String が使えることを確認する
    moduleSetup: {
      main: "com.example.implicit/com.example.implicit.Main",
      sources: [
        { module: "com.example.implicit", path: "module-info.java", content: ["module com.example.implicit {", "}"] },
        { module: "com.example.implicit", path: "com/example/implicit/Main.java", content: ["package com.example.implicit;", "", "import java.util.List;", "", "public class Main {", "    public static void main(String[] args) {", "        List<String> list = List.of(\"implicit\");", "        System.out.println(list.get(0));", "    }", "}"] },
      ],
    },
    explanation:
      "java.base には Object や String、コレクションなど言語の土台となる型が含まれ、すべてのモジュールが暗黙的に依存します。java.se は Java SE 全体を束ねる集約モジュールで、暗黙にはなりません。例外なく全員が必要とするものだけを暗黙にする、という判断は、java.lang が import なしで使えるのと同じ考え方です。裏を返せば、java.sql や java.logging のようにすべてのアプリが使うとは限らないモジュールは、必ず明示する必要があります。",
  },
  {
    id: 625,
    topic: "modules",
    variantOf: "modules-declaration-rules",
    question: "モジュールを実行するコマンドとして正しいものはどれか。1つ選びなさい。",
    choices: [
      "java --module-path mods -m com.example.app/com.example.app.Main",
      "java -cp mods com.example.app/com.example.app.Main",
      "java --module-path mods com.example.app.Main",
      "java -m mods com.example.app.Main",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "launched" },
    // --module-path と -m モジュール名/クラス名 の形式で実際に起動できることを確認する（他の選択肢の誤りまでは機械検証できない）
    moduleSetup: {
      main: "com.example.app/com.example.app.Main",
      sources: [
        { module: "com.example.app", path: "module-info.java", content: ["module com.example.app {", "}"] },
        { module: "com.example.app", path: "com/example/app/Main.java", content: ["package com.example.app;", "", "public class Main {", "    public static void main(String[] args) {", "        System.out.println(\"launched\");", "    }", "}"] },
      ],
    },
    explanation:
      "モジュールを実行するには、--module-path でモジュールの置き場所を指定し、-m（--module）で「モジュール名/メインクラスの完全修飾名」を渡します。従来のクラスパス（-cp）はモジュールを解決しないため、モジュールとして動かす場合は使いません。モジュール名とクラス名をスラッシュで区切るのは、どのモジュールに属するクラスかを一意に示すためで、同名のクラスが別モジュールに存在しても区別できます。",
  },
  {
    id: 626,
    topic: "modules",
    variantOf: "modules-encapsulation",
    question:
      "モジュール化されたライブラリにおける public の扱いについて、正しい説明はどれか。1つ選びなさい。",
    choices: [
      "exports されていないパッケージの public 型は、同じモジュール内からしか参照できない",
      "public を付けた型は、モジュールの設定に関わらずどこからでも参照できる",
      "exports すると、そのパッケージの private メンバーも他モジュールから参照できる",
      "モジュール化すると public は使えなくなり、代わりに exports を型ごとに書く",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    // public でも exports されていなければ他モジュールから参照できないことを確認する
    moduleSetup: {
      sources: [
        { module: "com.example.lib", path: "module-info.java", content: ["module com.example.lib {", "    exports com.example.lib.api;", "}"] },
        { module: "com.example.lib", path: "com/example/lib/api/Api.java", content: ["package com.example.lib.api;", "", "public class Api {", "}"] },
        { module: "com.example.lib", path: "com/example/lib/hidden/Secret.java", content: ["package com.example.lib.hidden;", "", "public class Secret {", "}"] },
        { module: "com.example.client", path: "module-info.java", content: ["module com.example.client {", "    requires com.example.lib;", "}"] },
        { module: "com.example.client", path: "com/example/client/Main.java", content: ["package com.example.client;", "", "import com.example.lib.hidden.Secret;", "", "public class Main {", "    public static void main(String[] args) {", "        System.out.println(new Secret());", "    }", "}"] },
      ],
    },
    explanation:
      "モジュールシステムの導入により、public の意味が「どこからでも見える」から「exports されたパッケージにあれば見える」へと実質的に変わりました。exports が公開するのはパッケージ単位で、しかも公開されるのはその中の public 型だけです。private や package-private のメンバーが見えるようになるわけではなく、従来のアクセス修飾子による制御はそのまま働きます。つまりモジュールは既存の仕組みを置き換えるのではなく、その外側にもう一段の境界を足したものだと理解すると整理できます。",
  },
];
