import type { SilverQuestion } from "../quizTypes";

/** 亜種の追加・その2（データ型後半 / 演算子、id 521 以降） */
export const variantQuestions4: SilverQuestion[] = [
  // ==================================================== データ型 (datatypes)
  {
    id: 521,
    topic: "datatypes",
    variantOf: "datatypes-wrapper-conversion",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Parsing",
    code: [
      "public class Parsing {",
      "    public static void main(String[] args) {",
      '        String text = "7";',
      "        int number = Integer.parseInt(text);",
      "        String back = Integer.toString(number * 2);",
      '        System.out.println(back + " " + back.length());',
      "    }",
      "}",
    ],
    choices: ["14 2", "7 1", "14 1", "72 2", "実行時に NumberFormatException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "14 2" },
    explanation:
      'parseInt で数値に変換して計算し、toString で文字列に戻すと "14" になり、長さは 2 です。文字列と数値は互いに自動変換されないため、この明示的な往復が必要になります。もし text をそのまま * 2 しようとしてもコンパイルエラーです。なお String.valueOf でも同じ結果が得られますが、valueOf は null を渡しても "null" を返すのに対し、Integer.toString は引数が int なのでその心配がありません。入力の変換は失敗しうる処理であり、数字以外が来れば NumberFormatException になる点も押さえておきましょう。',
  },
  {
    id: 522,
    topic: "datatypes",
    variantOf: "datatypes-implicit-widening",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Narrowing",
    code: [
      "public class Narrowing {",
      "    public static void main(String[] args) {",
      "        double d = 3.5;",
      "        int i = d;",
      '        System.out.println(i);',
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、3 が出力される",
      "コンパイルは成功し、4 が出力される",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "double から int へは情報が失われる方向（縮小変換）なので、キャストなしでは代入できません。拡大変換が暗黙に行われるのと対照的です。コンパイラが自動で切り捨ててしまうと、値が壊れたことに誰も気づけないため、明示的なキャストで「承知のうえ」と書かせる設計になっています。int i = (int) d; と書けば 3 になります。どちらの方向かを判断する基準は「変換先がもとの値をすべて表現できるか」で、できないなら必ずキャストが要ります。",
  },
  {
    id: 523,
    topic: "datatypes",
    variantOf: "datatypes-int-literal-narrowing",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Range",
    code: [
      "public class Range {",
      "    public static void main(String[] args) {",
      "        byte small = 127;",
      "        byte over = 128;",
      '        System.out.println(small + " " + over);',
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、127 -128 が出力される",
      "コンパイルは成功し、127 128 が出力される",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "byte の範囲は -128〜127 です。127 はリテラルの値が範囲に収まるためキャストなしで代入できますが、128 は超えているためコンパイルエラーになります。コンパイル時に値が分かる場合は範囲を検査する、という仕組みのおかげで、この誤りは実行前に判明します。もし (byte) 128 と明示的にキャストすれば、コンパイルは通り -128 になります。範囲外を承知で切り詰めるのか、単なる書き間違いなのかをプログラマに選ばせる形になっています。",
  },
  {
    id: 524,
    topic: "datatypes",
    variantOf: "datatypes-null-primitive",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Unboxing",
    code: [
      "public class Unboxing {",
      "    public static void main(String[] args) {",
      "        Integer boxed = null;",
      "        int value = boxed;",
      "        System.out.println(value);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に NullPointerException がスローされる",
      "0 と出力される",
      "null と出力される",
      "4行目でコンパイルエラーになる",
      "何も出力されずに正常終了する",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException" },
    explanation:
      "Integer を int に代入するとアンボクシング（内部的に intValue() の呼び出し）が行われます。参照が null だとメソッドを呼べないため NullPointerException になります。コンパイルは通るので、型の上では安全に見えるのが厄介な点です。オートボクシングは記述を簡潔にする一方、null が絡むと例外が「代入しただけの行」で発生するため原因が分かりにくくなります。Map の get やデータベースから取得した値など、null を返しうる API の戻り値をプリミティブへ代入する箇所は特に注意が必要です。",
  },
  {
    id: 525,
    topic: "datatypes",
    variantOf: "datatypes-null-concat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Concatenation",
    code: [
      "public class Concatenation {",
      "    public static void main(String[] args) {",
      "        String value = null;",
      "        value += \"x\";",
      "        System.out.println(value);",
      "    }",
      "}",
    ],
    choices: [
      "nullx",
      "x",
      "実行時に NullPointerException がスローされる",
      "null",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "nullx" },
    explanation:
      'value += "x" は value = value + "x" と同じなので、連結の規則に従って null が文字列 "null" に変換され "nullx" になります。null のまま何かを足したつもりが、文字列としての "null" が紛れ込むわけです。この挙動のせいで、未設定の値がログやメッセージに "null" として現れ、バグの発見が遅れることがあります。文字列を組み立てる前に値の有無を確認するか、Objects.toString(value, "") のように既定値を明示するのが安全です。',
  },
  {
    id: 526,
    topic: "datatypes",
    variantOf: "datatypes-literal-suffix",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "FloatLiteral",
    code: [
      "public class FloatLiteral {",
      "    public static void main(String[] args) {",
      "        double d = 1.5;",
      "        float f = 1.5;",
      '        System.out.println(d + " " + f);',
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、1.5 1.5 が出力される",
      "3行目でコンパイルエラーになる",
      "コンパイルは成功し、1.5 1.50 が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "小数リテラルは既定で double 型です。double から float への代入は縮小変換にあたるため、キャストなしではエラーになります。1.5f と書くか (float) 1.5 とキャストすれば通ります。整数リテラルが既定で int なのと同じ考え方で、「リテラルの型は書き方で決まり、代入先には合わせてくれない」という一貫した規則です。float を使う場面では F を付け忘れやすいので、そもそも精度に不安のある float ではなく double を既定で使うのが実務上の推奨です。",
  },
  {
    id: 527,
    topic: "datatypes",
    variantOf: "datatypes-stringbuilder-capacity",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Builder2",
    code: [
      "public class Builder2 {",
      "    public static void main(String[] args) {",
      '        StringBuilder sb = new StringBuilder("abc");',
      "        sb.setLength(2);",
      '        sb.append("Z");',
      '        System.out.println(sb + " " + sb.length());',
      "    }",
      "}",
    ],
    choices: ["abZ 3", "abcZ 4", "ab 2", "abZ 4", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "abZ 3" },
    explanation:
      'setLength は保持する文字数そのものを変更します。2 に縮めると "ab" になり、そこへ append して "abZ"（長さ 3）です。capacity（容量）は内部配列の大きさなので、setLength で縮めても容量は減りません。長さと容量が独立していることが、この 2 つのメソッドの違いに表れています。なお setLength で現在より大きい値を指定すると、増えた分は文字コード 0 の文字（ヌル文字）で埋められるため、意図せず見えない文字が混ざる点にも注意が必要です。',
  },

  // ====================================================== 演算子 (operators)
  {
    id: 528,
    topic: "operators",
    variantOf: "operators-ternary",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Choice",
    code: [
      "public class Choice {",
      "    public static void main(String[] args) {",
      "        int score = 70;",
      '        String grade = score >= 80 ? "A" : score >= 60 ? "B" : "C";',
      "        System.out.println(grade);",
      "    }",
      "}",
    ],
    choices: ["B", "A", "C", "AB", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "B" },
    explanation:
      '条件演算子は右結合なので、score >= 80 ? "A" : (score >= 60 ? "B" : "C") と解釈されます。70 は最初の条件を満たさず、次の条件で "B" になります。この形は else if の連鎖と同じ構造で、上から順に条件を試して最初に一致したものを返します。条件演算子は式なので、変数の宣言と初期化を 1 文で書けるのが利点です。ただし分岐ごとに副作用のある処理をしたい場合は if 文を使うべきで、値を選ぶ用途に限定すると読みやすさを保てます。',
  },
  {
    id: 529,
    topic: "operators",
    variantOf: "operators-precedence",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Mixed",
    code: [
      "public class Mixed {",
      "    public static void main(String[] args) {",
      "        boolean result = 2 + 3 > 4 && 10 / 2 == 5;",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: ["true", "false", "コンパイルエラーになる", "5", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "true" },
    explanation:
      "優先順位は算術演算子（+ / ）が最も高く、次に比較演算子（> ==）、最後に論理演算子（&&）です。そのため (2 + 3) > 4 と (10 / 2) == 5 がそれぞれ評価され、true && true で true になります。この並び順は「値を計算してから比べ、最後にまとめて判断する」という自然な流れに沿っています。とはいえ一目で読み取るのは難しいため、実務では括弧で意図を示すのが親切です。特に && と || が混在すると、&& の方が優先される点を忘れて誤読しやすくなります。",
  },
  {
    id: 530,
    topic: "operators",
    variantOf: "operators-object-equality",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Identity",
    code: [
      "public class Identity {",
      "    public static void main(String[] args) {",
      '        String a = new String("x");',
      '        String b = new String("x");',
      '        System.out.println((a == b) + " " + a.equals(b) + " " + (a.length() == b.length()));',
      "    }",
      "}",
    ],
    choices: ["false true true", "true true true", "false false true", "false true false"],
    correct: [0],
    expected: { kind: "output", stdout: "false true true" },
    explanation:
      "new で生成した以上、内容が同じでも別インスタンスなので == は false です。String は equals を内容比較として実装しているため true になり、length() どうしの比較はプリミティブの int の比較なので true です。同じ == でも、参照型に使えば「同じインスタンスか」、プリミティブに使えば「同じ値か」を意味します。この二重性が == の混乱の元で、参照型を比較するときは常に equals を使う、と決めておくと事故を防げます。",
  },
  {
    id: 531,
    topic: "operators",
    variantOf: "operators-assignment-chain",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Counter2",
    code: [
      "public class Counter2 {",
      "    public static void main(String[] args) {",
      "        int a = 1;",
      "        int b = 2;",
      "        a += b -= 1;",
      '        System.out.println(a + " " + b);',
      "    }",
      "}",
    ],
    choices: ["2 1", "3 1", "2 2", "3 2", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 1" },
    explanation:
      "複合代入も右結合なので、まず b -= 1 が評価されて b が 1 になり、その式の値である 1 が a に足されて a は 2 になります。代入式が「代入後の値」を返すという性質がここでも効いています。一見すると a に b の元の値 2 が足されそうに見えますが、実際には減算後の 1 が使われる点が引っかけどころです。副作用のある式を別の式に埋め込むと評価順の理解が必須になるため、実務では行を分けて書くのが賢明です。",
  },
  {
    id: 532,
    topic: "operators",
    variantOf: "operators-bitwise",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Shifting",
    code: [
      "public class Shifting {",
      "    public static void main(String[] args) {",
      "        int value = -8;",
      '        System.out.println((value >> 1) + " " + (value >>> 28));',
      "    }",
      "}",
    ],
    choices: ["-4 15", "-4 -1", "4 15", "-4 0", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "-4 15" },
    explanation:
      ">> は符号を保ったまま右へずらす算術シフトなので、-8 は -4 になります（2 で割るのと同じ効果）。>>> は空いた上位ビットを常に 0 で埋める論理シフトで、-8 のビット列（上位が 1 で埋まった 32 ビット）を 28 ビット右へずらすと上位 4 ビットの 1111 が残り 15 になります。符号付き整数を 2 の補数で表しているため、符号を維持したい場合と純粋なビット列として扱いたい場合の両方が必要になり、2 種類の右シフトが用意されています。なお左シフトは符号の考慮が不要なので << だけです。",
  },
  {
    id: 533,
    topic: "operators",
    variantOf: "operators-instanceof-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TypeCheck",
    code: [
      "public class TypeCheck {",
      "    public static void main(String[] args) {",
      '        Object value = "text";',
      '        System.out.println((value instanceof String) + " " + (value instanceof Object));',
      "    }",
      "}",
    ],
    choices: ["true true", "true false", "false true", "false false", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true true" },
    explanation:
      "instanceof は「その型、またはその派生型のインスタンスか」を判定します。String のインスタンスは String でもあり Object でもあるため、どちらも true です。継承関係にある型すべてに対して true になるこの性質は、ポリモーフィズムの考え方と一貫しています。注意点として、まったく継承関係のない型どうしで instanceof を書くと、常に false になることが明らかなためコンパイルエラーになります。判定が意味を持つ組み合わせでしか使えない、というのもコンパイラによる支援のひとつです。",
  },
  {
    id: 534,
    topic: "operators",
    variantOf: "operators-compound-concat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Mixing",
    code: [
      "public class Mixing {",
      "    public static void main(String[] args) {",
      '        String s = "n=";',
      "        int n = 2;",
      "        s += n * 3;",
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["n=6", "n=23", "n=2*3", "6", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "n=6" },
    explanation:
      '複合代入は右辺全体を先に評価するため、n * 3 が 6 になってから連結され "n=6" になります。もし s = s + n * 3 と書いても、* の優先順位が + より高いので同じ結果です。一方 s = s + n + 3 と書くと左から順に連結され "n=23" になります。+ が算術加算と文字列連結を兼ねているため、優先順位と評価順の両方を意識する必要があるということです。意図を明確にしたいなら括弧を付けるか、String.format を使うと誤解が生じません。',
  },
  {
    id: 535,
    topic: "operators",
    variantOf: "operators-unary",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "NotNumber",
    code: [
      "public class NotNumber {",
      "    public static void main(String[] args) {",
      "        int value = 1;",
      "        boolean result = !value;",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、false が出力される",
      "コンパイルは成功し、true が出力される",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "! は boolean 専用の演算子で、数値には適用できません。C 言語のように 0 を偽、それ以外を真として扱う仕組みが Java には無いためです。数値を真偽値として扱いたいなら value != 0 のように明示的な比較を書きます。一見遠回りですが、「何を条件としているのか」がコードに残るため読み手に意図が伝わります。同様に ~ は整数専用で boolean には使えず、型ごとに使える演算子がはっきり分かれているのが Java の特徴です。",
  },
];
