import type { SilverQuestion } from "../quizTypes";

/**
 * 後半分野（メソッド / 継承 / ラムダ / API / 例外 / モジュール）の亜種問題（id 119 以降）。
 * 既存問題とは別の切り口で同じ論点を問う。
 */
export const variantQuestions2: SilverQuestion[] = [
  // ========================================================== メソッド (methods)
  {
    id: 119,
    topic: "methods",
    variantOf: "methods-overload-resolution",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Dispatcher",
    code: [
      "public class Dispatcher {",
      '    static void handle(Object value) { System.out.print("Object"); }',
      "",
      '    static void handle(String value) { System.out.print("String"); }',
      "",
      "    public static void main(String[] args) {",
      "        handle(null);",
      "    }",
      "}",
    ],
    choices: ["String", "Object", "あいまいなためコンパイルエラーになる", "実行時に NullPointerException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "String" },
    explanation:
      "null はすべての参照型に代入できるため両方のメソッドが候補になりますが、オーバーロードの解決では「最も具体的な型」が選ばれます。String は Object の派生型なので String 版が勝ちます。この規則があるおかげで、派生型を追加しても既存の呼び出しが急に基底型版へ切り替わることがありません。ただし handle(Integer) と handle(String) のように優劣が付けられない組み合わせだと、どちらも選べずコンパイルエラーになります。null を渡す必要がある場面では (String) null のように明示的にキャストするのが確実です。",
  },
  {
    id: 120,
    topic: "methods",
    variantOf: "methods-varargs",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Joiner",
    code: [
      "public class Joiner {",
      "    static String join(String first, String... rest) {",
      '        return first + ":" + rest.length;',
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(join("a") + " " + join("a", "b", "c"));',
      "    }",
      "}",
    ],
    choices: ["a:0 a:2", "a:1 a:3", "a:0 a:3", "実行時に NullPointerException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "a:0 a:2" },
    explanation:
      "可変長引数は必ず引数リストの末尾に 1 つだけ置け、余った実引数がまとめて配列になります。join(\"a\") では余りがないので長さ 0 の配列、join(\"a\", \"b\", \"c\") では b と c が入った長さ 2 の配列になります。呼び出し側で配列を組み立てなくてよいのは、コンパイラが暗黙に配列生成を挿入してくれるためです。引数を渡さなくても null ではなく空配列が渡される点は、args と同じ「不在を空で表す」設計です。可変長引数が末尾に限られるのは、どこまでが固定引数でどこからが可変かを一意に決めるためです。",
  },
  {
    id: 121,
    topic: "methods",
    variantOf: "methods-static-context",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Visits",
    code: [
      "public class Visits {",
      "    private static int count = 0;",
      "",
      "    void increment() {",
      "        count++;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Visits().increment();",
      "        new Visits().increment();",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: ["2", "1", "0", "5行目でコンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2" },
    explanation:
      "インスタンスメソッドから static フィールドを参照するのは問題ありません。逆（static メソッドからインスタンスフィールド）が禁止なのは、static 側には「どのインスタンスか」という情報が無いからです。static フィールドはクラスに 1 つだけ存在する記憶領域なので、インスタンスを 2 つ作っても count は共有され 2 になります。この共有こそが static の本質で、便利な一方でインスタンスごとに独立していてほしい状態をうっかり static にすると、全体に影響が漏れるバグになります。",
  },
  {
    id: 122,
    topic: "methods",
    variantOf: "methods-constructor-chaining",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Item",
    code: [
      "public class Item {",
      "    private final String name;",
      "",
      "    Item() {",
      '        this.name = "default";',
      "    }",
      "",
      "    Item(String label) {",
      "        this();",
      '        System.out.print("set ");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(new Item("custom").name);',
      "    }",
      "}",
    ],
    choices: ["set default", "set custom", "default", "custom", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "set default" },
    explanation:
      'Item(String) は this() で引数なしコンストラクタに処理を委譲しており、そこで name が "default" に確定します。戻ってきたあとに set を出力しますが、name は final なので二度と代入できず、引数の label は使われないままです。this(...) を必ず先頭に書く決まりがあるのは、フィールドの初期化を一度だけ、決まった順序で完了させるためです。final フィールドが「必ず 1 回だけ初期化される」ことをコンパイラが保証できるのも、この制約があってこそです。',
  },

  // ==================================================== 継承 (inheritance)
  {
    id: 123,
    topic: "inheritance",
    variantOf: "inheritance-field-hiding",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Vehicle",
    code: [
      "public class Vehicle {",
      '    static String type = "Vehicle";',
      "",
      "    static String describe() {",
      '        return "Vehicle";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Vehicle v = new Car();",
      '        System.out.println(v.type + " " + v.describe());',
      "    }",
      "}",
      "",
      "class Car extends Vehicle {",
      '    static String type = "Car";',
      "",
      "    static String describe() {",
      '        return "Car";',
      "    }",
      "}",
    ],
    choices: ["Vehicle Vehicle", "Car Car", "Vehicle Car", "Car Vehicle", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "Vehicle Vehicle" },
    explanation:
      "static メソッドはオーバーライドされず「隠蔽（hiding）」されるだけです。オーバーライドによる動的な切り替えはインスタンスに対して行われるものですが、static はクラスに属するため実行時のインスタンスの型では選ばれません。結果として、フィールドもメソッドも変数の宣言型である Vehicle 側が使われます。インスタンス変数経由で static メンバーを呼べてしまうのが誤解の元なので、static メンバーは Vehicle.describe() のようにクラス名で呼ぶべきです。多くの静的解析ツールがこの書き方を警告するのはこのためです。",
  },
  {
    id: 124,
    topic: "inheritance",
    variantOf: "inheritance-abstract-anonymous",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Canvas",
    code: [
      "abstract class Shape {",
      "    abstract double area();",
      "",
      "    abstract String label();",
      "}",
      "",
      "public class Canvas {",
      "    public static void main(String[] args) {",
      "        Shape shape = new Shape() {",
      "            @Override",
      "            double area() {",
      "                return 4.0;",
      "            }",
      "        };",
      "        System.out.println(shape.area());",
      "    }",
      "}",
    ],
    choices: [
      "label() が実装されていないためコンパイルエラーになる",
      "コンパイルは成功し、4.0 が出力される",
      "抽象クラスはインスタンス化できないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "匿名クラスも具象クラスの一種なので、継承元の抽象メソッドをすべて実装しなければインスタンス化できません。ここでは label() が未実装なのでコンパイルエラーになります。抽象メソッドは「派生型が必ず用意する」という契約であり、その契約を守っていない型のインスタンスを作れないよう、コンパイル時点で検出されます。もし実装漏れのまま実行できてしまうと、呼び出した瞬間に初めて壊れることになります。抽象クラスやインタフェースは、この種のエラーを実行時から翻訳時へ前倒しする仕組みだと捉えると分かりやすいです。",
  },
  {
    id: 125,
    topic: "inheritance",
    variantOf: "inheritance-class-wins",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Impl",
    code: [
      "interface Alpha {",
      "    default String name() {",
      '        return "Alpha";',
      "    }",
      "}",
      "",
      "interface Beta {",
      "    default String name() {",
      '        return "Beta";',
      "    }",
      "}",
      "",
      "public class Impl implements Alpha, Beta {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Impl().name());",
      "    }",
      "}",
    ],
    choices: [
      "どちらの default メソッドを継承するか決められないためコンパイルエラーになる",
      "Alpha と出力される",
      "Beta と出力される",
      "コンパイルは成功し、実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "複数のインタフェースから同じシグネチャの default メソッドを継承すると、どちらを使うか決定できずコンパイルエラーになります（菱形継承の曖昧さ）。クラスとインタフェースの競合では「クラスが勝つ」と決められていますが、インタフェース同士には優劣がないため、実装クラスが自分で name() をオーバーライドして解決する必要があります。その際 Alpha.super.name() のように、どちらを使うか明示して呼び出せます。多重継承を認めつつ曖昧さだけは必ず人間に決めさせる、という安全側に倒した設計です。",
  },
  {
    id: 126,
    topic: "inheritance",
    variantOf: "inheritance-cast",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Checker",
    code: [
      "public class Checker {",
      "    public static void main(String[] args) {",
      '        Object value = "text";',
      "        if (value instanceof Integer) {",
      '            System.out.print("int ");',
      "        }",
      "        String s = (String) value;",
      "        System.out.println(s.length());",
      "    }",
      "}",
    ],
    choices: ["4", "int 4", "実行時に ClassCastException がスローされる", "4行目でコンパイルエラーになる", "0"],
    correct: [0],
    expected: { kind: "output", stdout: "4" },
    explanation:
      "instanceof は実行時の型を調べる演算子で、value の実体は String なので Integer との判定は false になり、if の中は実行されません。その後のキャストは実体と一致しているため成功し、長さ 4 が出力されます。instanceof が null に対しても常に false を返すので、null チェックとキャスト可能判定を同時に行える点も重要です。キャストは「コンパイラに型を教える」だけで実体は変わらないため、事前に instanceof で確認してからキャストするのが安全な作法です。",
  },

  // ============================================================ ラムダ (lambda)
  {
    id: 127,
    topic: "lambda",
    variantOf: "lambda-functional-interface",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Calc",
    code: [
      "@FunctionalInterface",
      "interface Calculator {",
      "    int apply(int a, int b);",
      "",
      "    String toString();",
      "}",
      "",
      "public class Calc {",
      "    public static void main(String[] args) {",
      "        Calculator add = (a, b) -> a + b;",
      "        System.out.println(add.apply(2, 3));",
      "    }",
      "}",
    ],
    choices: [
      "5",
      "抽象メソッドが 2 つあるためコンパイルエラーになる",
      "23",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "5" },
    explanation:
      "関数型インタフェースの条件は「抽象メソッドがちょうど 1 つ」ですが、Object の public メソッドと同じシグネチャ（toString、equals、hashCode）は数に含まれません。どんなインタフェースの実装も必ず Object を継承していて、これらは必ず実装済みだからです。したがって抽象メソッドは apply の 1 つだけとみなされ、ラムダ式を代入できます。@FunctionalInterface は条件を満たすかコンパイラに検査させるための任意の注釈で、付けなくてもラムダは使えますが、付けておくと後からメソッドを追加した際に即座に気づけます。",
  },
  {
    id: 128,
    topic: "lambda",
    variantOf: "lambda-effectively-final",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Runner",
    code: [
      "interface Task {",
      "    void execute();",
      "}",
      "",
      "public class Runner {",
      "    public static void main(String[] args) {",
      "        int base = 10;",
      "        Task task = () -> System.out.println(base * 2);",
      "        task.execute();",
      "    }",
      "}",
    ],
    choices: ["20", "10", "final が付いていないためコンパイルエラーになる", "0", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "20" },
    explanation:
      "base は宣言後に再代入されていないため「実質的に final」とみなされ、ラムダ式から参照できます。final キーワードを明示する必要はありません。この制約があるのは、ラムダがローカル変数を参照する際に値をコピーして保持するためで、後から変数が変わっても両者が食い違わないようにしています。ローカル変数はメソッドの終了とともに消えるのに、ラムダはそれより長く生き延びることがある、という寿命の違いを埋める仕組みです。どうしても変化する値を扱いたい場合は、配列やフィールドなどヒープ上のオブジェクトに置く必要があります。",
  },
  {
    id: 129,
    topic: "lambda",
    variantOf: "lambda-builtin-interfaces",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Pipeline",
    code: [
      "import java.util.function.Consumer;",
      "import java.util.function.Function;",
      "",
      "public class Pipeline {",
      "    public static void main(String[] args) {",
      "        Function<String, Integer> length = s -> s.length();",
      '        Consumer<String> printer = s -> System.out.print("[" + s + "]");',
      '        printer.accept("ab");',
      '        System.out.println(length.apply("abcd"));',
      "    }",
      "}",
    ],
    choices: ["[ab]4", "[ab]2", "ab4", "[abcd]4", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[ab]4" },
    explanation:
      "Function<T, R> は「T を受け取って R を返す」関数で apply で呼び出し、Consumer<T> は「T を受け取って何も返さない」処理で accept で呼び出します。ここでは印字してから長さ 4 を出力するので [ab]4 になります。標準の関数型インタフェースが引数と戻り値の有無で細かく分かれているのは、ジェネリクスではプリミティブや void を型引数にできず、ひとつの型で表現しきれないためです。名前（Supplier は供給する、Consumer は消費する、Predicate は判定する）と役割を結び付けて覚えると迷いません。",
  },

  // ================================================================= API (api)
  {
    id: 130,
    topic: "api",
    variantOf: "api-list-remove",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Catalog",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Catalog {",
      "    public static void main(String[] args) {",
      "        List<String> items = new ArrayList<>();",
      '        items.add("x");',
      '        items.add("y");',
      '        items.remove("x");',
      "        System.out.println(items);",
      "    }",
      "}",
    ],
    choices: ["[y]", "[x]", "[x, y]", "実行時に IndexOutOfBoundsException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[y]" },
    explanation:
      'remove には remove(int index) と remove(Object o) があり、引数が String なので後者が選ばれ、"x" と等しい要素が削除されます。要素型が String のときは直感どおりに動きますが、List<Integer> で remove(1) と書くと int 版が優先されて「インデックス 1 の要素」が消えます。remove(int) と remove(Object) は Java 1.2 のコレクション API から両方あり、remove(1) が値削除に見えてしまうのは Java 5 以降オートボクシングで int リテラルが両方に適合し、より具体的な int 版が選ばれるためです。要素を値で消したいときは remove(Integer.valueOf(1)) のように型を明示するのが安全です。',
  },
  {
    id: 131,
    topic: "api",
    variantOf: "api-immutable-list",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Fixed",
    code: [
      "import java.util.Arrays;",
      "import java.util.List;",
      "",
      "public class Fixed {",
      "    public static void main(String[] args) {",
      '        List<String> names = Arrays.asList("a", "b");',
      '        names.set(0, "z");',
      "        System.out.println(names);",
      "    }",
      "}",
    ],
    choices: [
      "[z, b]",
      "[a, b]",
      "実行時に UnsupportedOperationException がスローされる",
      "実行時に ArrayStoreException がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[z, b]" },
    explanation:
      "Arrays.asList が返すのは「固定長だが要素の入れ替えは可能なリスト」で、内部の配列をリストとして見せているだけです。そのため set は成功しますが、サイズが変わる add や remove は UnsupportedOperationException になります。一方 List.of は完全に変更不可で set も拒否します。同じ List 型でも、どのファクトリで作ったかによって許される操作が違う点が要注意です。List インタフェースが「できるはずの操作」を型では表現しきれておらず、実行時例外で表現しているのは、コレクション API 設計上の既知の妥協点です。",
  },
  {
    id: 132,
    topic: "api",
    variantOf: "api-localdate-immutable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Planner",
    code: [
      "import java.time.LocalDate;",
      "",
      "public class Planner {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2026, 3, 15);",
      "        LocalDate next = date.plusDays(20);",
      '        System.out.println(date + " " + next);',
      "    }",
      "}",
    ],
    choices: [
      "2026-03-15 2026-04-04",
      "2026-04-04 2026-04-04",
      "2026-03-15 2026-03-35",
      "2026-03-15 2026-04-05",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "2026-03-15 2026-04-04" },
    explanation:
      "LocalDate は不変クラスなので plusDays は元の値を変えず、新しいインスタンスを返します。3 月は 31 日までなので 15 日の 20 日後は 4 月 4 日に繰り上がり、date 自体は元のままです。日付を不変にしたのは、旧 java.util.Date や Calendar が可変であったために、他の場所へ渡した日付が知らないうちに書き換えられるバグを多発させた反省によるものです。不変であれば共有しても安全で、スレッド間で受け渡してもロックが要りません。戻り値を必ず受け取る、という使い方が身に付けば取り違えません。",
  },

  // ======================================================= 例外 (exceptions)
  {
    id: 133,
    topic: "exceptions",
    variantOf: "exceptions-finally-return",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Value",
    code: [
      "public class Value {",
      "    static int get() {",
      "        int v = 1;",
      "        try {",
      "            return v;",
      "        } finally {",
      "            v = 2;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(get());",
      "    }",
      "}",
    ],
    choices: ["1", "2", "0", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1" },
    explanation:
      "return は「戻り値を評価して確保してから」メソッドを抜けます。そのため finally で v を書き換えても、既に確保済みの戻り値 1 には影響しません。これが finally で return 文そのものを書いた場合と決定的に違う点で、そちらは戻り値の差し替えになり、例外すら握りつぶしてしまいます。finally の役割はあくまで後始末であり、制御フローや戻り値を変える場所ではない、と割り切るのが安全です。実際、finally 内の return は多くの静的解析ツールが警告します。",
  },
  {
    id: 134,
    topic: "exceptions",
    variantOf: "exceptions-checked",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Thrower",
    code: [
      "public class Thrower {",
      "    static void risky() {",
      '        throw new IllegalStateException("boom");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        risky();",
      "    }",
      "}",
    ],
    choices: [
      "実行時に IllegalStateException がスローされて異常終了する",
      "throws 宣言が無いためコンパイルエラーになる",
      "何も起こらず正常終了する",
      "boom と出力されて正常終了する",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalStateException" },
    explanation:
      "IllegalStateException は RuntimeException を継承する非検査例外なので、throws 宣言も try-catch も要求されません。検査例外との違いは「呼び出し側が回復できる見込みがあるか」で、ファイルが無いといった外的要因は検査例外、プログラムの誤りに起因するものは非検査例外、という住み分けです。非検査例外は捕捉を強制されない代わりに、放置すればスレッドを終了させます。すべてを検査例外にすると呼び出し側が意味のない catch を書き続けることになるため、この二分類が用意されています。",
  },
  {
    id: 135,
    topic: "exceptions",
    variantOf: "exceptions-twr-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Flow",
    code: [
      "class Res implements AutoCloseable {",
      "    @Override",
      "    public void close() {",
      '        System.out.print("closed ");',
      "    }",
      "}",
      "",
      "public class Flow {",
      "    public static void main(String[] args) {",
      "        try (Res r = new Res()) {",
      '            System.out.print("try ");',
      '            throw new RuntimeException("x");',
      "        } catch (RuntimeException e) {",
      '            System.out.print("catch ");',
      "        } finally {",
      '            System.out.print("finally");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "try closed catch finally",
      "try catch closed finally",
      "try catch finally closed",
      "try closed finally catch",
      "try finally closed catch",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "try closed catch finally" },
    explanation:
      "try-with-resources のリソースは、catch 節や finally 節に入るより前にクローズされます。例外が投げられた時点でまず close() が呼ばれ、その後で catch、最後に finally という順序です。この順序でなければ、catch の中でリソースの後始末状況が不定になり、finally で手動クローズしていた従来の書き方と同じ問題が残ってしまいます。リソースの寿命を try 文の括弧内に閉じ込め、例外経路でも確実に閉じることを言語側が保証する、というのが try-with-resources の目的です。",
  },
  {
    id: 136,
    topic: "exceptions",
    variantOf: "exceptions-multicatch",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Parser",
    code: [
      "public class Parser {",
      "    public static void main(String[] args) {",
      "        try {",
      '            Object o = "text";',
      "            Integer n = (Integer) o;",
      "            System.out.print(n);",
      "        } catch (ClassCastException e) {",
      '            System.out.print("cast ");',
      "        } catch (RuntimeException e) {",
      '            System.out.print("runtime ");',
      "        }",
      '        System.out.print("end");',
      "    }",
      "}",
    ],
    choices: ["cast end", "runtime end", "cast runtime end", "end", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "cast end" },
    explanation:
      "catch 節は上から順に照合され、最初に適合した 1 つだけが実行されます。ClassCastException は RuntimeException の派生型ですが、先に書かれた具体的な型の方が選ばれます。だからこそ catch は「具体的な型から順に」書く必要があり、逆順にすると後ろの catch には決して到達できず、コンパイラが到達不能としてエラーにします。捕捉後は try ブロックの残りには戻らず後続処理へ進むため、例外発生後の n は出力されません。例外処理は「どこで失敗しても、決められた合流点に集まる」構造だと捉えると流れを追いやすくなります。",
  },

  // ========================================================== モジュール (modules)
  {
    id: 137,
    topic: "modules",
    variantOf: "modules-exports",
    question:
      "次の module-info.java を持つモジュール com.example.service がある。この宣言の説明として正しいものはどれか。1つ選びなさい。",
    code: [
      "module com.example.service {",
      "    requires transitive java.sql;",
      "    exports com.example.service.api;",
      "    exports com.example.service.internal to com.example.admin;",
      "}",
    ],
    choices: [
      "com.example.service.internal は com.example.admin モジュールからのみ参照できる",
      "com.example.service.internal はすべてのモジュールから参照できる",
      "com.example.service を requires したモジュールは java.sql を別途 requires しなければ使えない",
      "com.example.service.api は同一モジュール内からしか参照できない",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    // 限定公開したパッケージを対象外のモジュールから参照するとコンパイルできないことを確認する
    moduleSetup: {
      sources: [
        { module: "com.example.service", path: "module-info.java", content: ["module com.example.service {", "    requires transitive java.sql;", "    exports com.example.service.api;", "    exports com.example.service.internal to com.example.admin;", "}"] },
        { module: "com.example.service", path: "com/example/service/api/Api.java", content: ["package com.example.service.api;", "", "public class Api {", "}"] },
        { module: "com.example.service", path: "com/example/service/internal/Internal.java", content: ["package com.example.service.internal;", "", "public class Internal {", "}"] },
        { module: "com.example.other", path: "module-info.java", content: ["module com.example.other {", "    requires com.example.service;", "}"] },
        { module: "com.example.other", path: "com/example/other/Main.java", content: ["package com.example.other;", "", "import com.example.service.internal.Internal;", "", "public class Main {", "    public static void main(String[] args) {", "        System.out.println(new Internal());", "    }", "}"] },
      ],
    },
    explanation:
      "exports ... to は「限定的公開」で、指定したモジュールにだけパッケージを見せます。実装の詳細を特定の相手（管理ツールなど）にだけ渡したいときに使います。requires transitive は依存を推移的に再公開する宣言で、このモジュールを requires した側は java.sql も自動的に使えます。自分の API の戻り値や引数に他モジュールの型が現れる場合、これが無いと利用側がコンパイルできません。モジュールシステムの狙いは、これまで public しか無く事実上すべて公開されていた境界に、「誰に見せるか」という軸を持ち込むことにあります。",
  },
];
