import type { SilverQuestion } from "../quizTypes";

/**
 * 既存の各論点に対する亜種問題（id 101 以降）。
 *
 * `variantOf` が同じ問題は「同じ論点を別の切り口・別の値で問うたもの」で、
 * 出題時はその中から 1 問だけが選ばれる（繰り返し解いても同じ問題が続かない）。
 */
export const variantQuestions: SilverQuestion[] = [
  // ============================================================ 基本 (basics)
  {
    id: 101,
    topic: "basics",
    variantOf: "basics-main-signature",
    question: "次のコードをコンパイルし、java Launcher として実行した場合の結果はどれか。1つ選びなさい。",
    className: "Launcher",
    code: [
      "public class Launcher {",
      "    static public void main(String... args) {",
      '        System.out.println("started");',
      "    }",
      "}",
    ],
    choices: [
      "started",
      "コンパイルエラーになる",
      "main メソッドとして認識されず、実行時にエラーになる",
      "何も出力されずに正常終了する",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "started" },
    explanation:
      "修飾子の並び順に決まりはないため static public でも public static でも同じ意味です。また可変長引数 String... は内部的に String[] と同一のシグネチャにコンパイルされるため、JVM はこれをエントリーポイントとして認識します。JVM が探しているのは「名前が main、戻り値が void、引数が String 配列、public かつ static」という条件であって、ソース上の書き方ではありません。逆に言えば戻り値を int にしたり static を外したりすると、コンパイルは通るのに実行時にエントリーポイントが見つからず失敗します。",
  },
  {
    id: 102,
    topic: "basics",
    variantOf: "basics-declaration-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Registry",
    code: [
      "package com.example;",
      "",
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Registry {",
      "    public static void main(String[] args) {",
      "        List<String> items = new ArrayList<>();",
      '        items.add("ok");',
      "        System.out.println(items.size());",
      "    }",
      "}",
    ],
    choices: ["1", "0", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1" },
    explanation:
      "package 宣言 → import 宣言 → 型宣言という順序が守られているため、正しくコンパイル・実行できます。import が複数ある場合の順序は自由です。この順序が決まっているのは、コンパイラがソースを読む際に「このファイルがどの名前空間に属するか」を最初に確定させる必要があるからです。パッケージが決まって初めて、import による名前の解決や同一パッケージ内の型の参照が意味を持ちます。なお実行時は java com.example.Registry のように完全修飾名で指定する必要があります。",
  },
  {
    id: 103,
    topic: "basics",
    variantOf: "basics-args",
    question: "次のコードをコンパイルし、java Entry とだけ入力して実行した場合の結果はどれか。1つ選びなさい。",
    className: "Entry",
    code: [
      "public class Entry {",
      "    public static void main(String[] args) {",
      "        System.out.println(args[0]);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ArrayIndexOutOfBoundsException がスローされる",
      "実行時に NullPointerException がスローされる",
      "null と出力される",
      "何も出力されずに正常終了する",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ArrayIndexOutOfBoundsException" },
    explanation:
      "引数を渡さなかった場合、args は null ではなく長さ 0 の配列です。そのため args[0] は存在しない要素へのアクセスとなり ArrayIndexOutOfBoundsException になります。JVM が空配列を渡すのは、利用者側で毎回 null チェックを書かなくて済むようにするためです。「値が無い」ことを null ではなく空のコレクションで表すのは Java の API 全体に一貫した設計方針で、実務でもメソッドの戻り値として空リストを返すべきか null を返すべきか迷ったときの指針になります。",
  },

  // ==================================================== データ型 (datatypes)
  {
    id: 104,
    topic: "datatypes",
    variantOf: "datatypes-compound-assign",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Meter",
    code: [
      "public class Meter {",
      "    public static void main(String[] args) {",
      "        byte b = 100;",
      "        b *= 2;",
      "        System.out.println(b);",
      "    }",
      "}",
    ],
    choices: ["-56", "200", "127", "0", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "-56" },
    explanation:
      "複合代入演算子には暗黙の縮小変換が含まれるため b *= 2 はコンパイルできますが、計算結果の 200 は byte の範囲（-128〜127）を超えます。超えた分は上位ビットが捨てられ、200 のビット列がそのまま符号付き 8 ビットとして解釈されて -56 になります。ここが複合代入の怖いところで、b = b * 2 と書けばコンパイルエラーで気づけるのに、b *= 2 では警告もなく静かに値が壊れます。コンパイラが通したことと、値が正しいことは別物だという典型例です。",
  },
  {
    id: 105,
    topic: "datatypes",
    variantOf: "datatypes-string-identity",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Pool",
    code: [
      "public class Pool {",
      "    public static void main(String[] args) {",
      '        String a = "ja" + "va";',
      '        String b = "java";',
      '        String c = new String("java").intern();',
      '        System.out.println((a == b) + " " + (b == c));',
      "    }",
      "}",
    ],
    choices: ["true true", "false true", "true false", "false false"],
    correct: [0],
    expected: { kind: "output", stdout: "true true" },
    explanation:
      'リテラル同士の "ja" + "va" は実行時ではなくコンパイル時に "java" へ畳み込まれるため、a は定数プールの "java" そのものを指します。intern() は「同じ内容の文字列がプールにあればその参照を返す」メソッドなので c も同一インスタンスになり、どちらの比較も true です。文字列が不変（immutable）だからこそ、こうしたインスタンスの共有が安全に行えます。ただし変数が絡む連結は実行時に新しいインスタンスを作るため == は false になります。この違いを踏む前提で、文字列の比較には常に equals を使うのが唯一の安全策です。',
  },
  {
    id: 106,
    topic: "datatypes",
    variantOf: "datatypes-stringbuilder",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Editor",
    code: [
      "public class Editor {",
      "    public static void main(String[] args) {",
      '        StringBuilder sb = new StringBuilder("abcdef");',
      '        sb.delete(1, 3).append("X");',
      '        System.out.println(sb + " " + sb.length());',
      "    }",
      "}",
    ],
    choices: ["adefX 5", "acdefX 6", "adefX 4", "abcX 4", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "adefX 5" },
    explanation:
      'delete(1, 3) は「開始位置 1 以上、終了位置 3 未満」を削除するため bc が消えて "adef" になり、append で "adefX"（長さ 5）になります。Java の範囲指定 API はほぼ一貫して「開始は含み、終了は含まない」という半開区間です。この統一があるおかげで、end - start がそのまま長さになり、区間を連結しても境界が重複しません。substring や List.subList も同じ規則なので、片方だけ違うと誤解すると境界ずれのバグに直結します。',
  },
  {
    id: 107,
    topic: "datatypes",
    variantOf: "datatypes-char-arithmetic",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Code",
    code: [
      "public class Code {",
      "    public static void main(String[] args) {",
      "        char a = 'a';",
      "        char b = (char) (a + 1);",
      "        System.out.println(a + b);",
      "    }",
      "}",
    ],
    choices: ["195", "ab", "9798", "b", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "195" },
    explanation:
      "char に + を適用すると数値演算として扱われ、両辺が int に昇格します（数値昇格）。'a' は 97、b は 98 なので結果は 195 という int になり、文字ではなく数値として出力されます。char が文字であると同時に 16 ビットの整数でもあるのは、文字コードを直接扱えるようにするための設計です。文字として連結したいなら \"\" + a + b のように文字列を先頭に置くか、String.valueOf を使う必要があります。println に渡すものが char なのか int なのかで出力が変わる点が落とし穴です。",
  },
  {
    id: 108,
    topic: "datatypes",
    variantOf: "datatypes-var",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Holder",
    code: [
      "public class Holder {",
      "    var message = \"hello\";",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Holder().message);",
      "    }",
      "}",
    ],
    choices: [
      "2行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、hello が出力される",
      "コンパイルは成功し、null が出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 2 },
    explanation:
      "var が使えるのはローカル変数（およびループ変数など、メソッド内の変数）に限られ、フィールドには使えません。これは型推論の影響範囲を 1 つのメソッド内に閉じ込めるための制限です。フィールドはクラスの外部に公開される API の一部であり、その型が初期化子の書き方で決まってしまうと、実装をちょっと変えただけで外部に見える型が変わりかねません。var はあくまで「読めば分かる局所的な型の省略」であって、型を書かなくてよくする仕組みではない、という位置づけです。",
  },

  // ====================================================== 演算子 (operators)
  {
    id: 109,
    topic: "operators",
    variantOf: "operators-increment",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Tally",
    code: [
      "public class Tally {",
      "    public static void main(String[] args) {",
      "        int x = 3;",
      "        x = x++ + x--;",
      "        System.out.println(x);",
      "    }",
      "}",
    ],
    choices: ["7", "6", "3", "8", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "7" },
    explanation:
      "式は左から順に評価されます。x++ は 3 を返して x を 4 にし、続く x-- は 4 を返して x を 3 にするため、右辺は 3 + 4 で 7 です。最後にその 7 が x へ代入されるので、途中の増減はすべて上書きされます。ポイントは「代入の左辺への書き込みが最後に起きる」ことで、同じ変数を式の中で複数回書き換えても最終的な代入が勝ちます。こうした式は評価順を知らないと読めないため、実務では一文に複数の副作用を詰め込まないのが鉄則です。",
  },
  {
    id: 110,
    topic: "operators",
    variantOf: "operators-short-circuit",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Access",
    code: [
      "public class Access {",
      "    public static void main(String[] args) {",
      "        String value = null;",
      "        if (value != null && value.length() > 0) {",
      '            System.out.print("has ");',
      "        }",
      '        System.out.print("done");',
      "    }",
      "}",
    ],
    choices: [
      "done",
      "has done",
      "実行時に NullPointerException がスローされる",
      "何も出力されない",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "done" },
    explanation:
      "&& は左辺が false の時点で結果が確定するため右辺を評価しません。value != null が false なので value.length() は実行されず、NullPointerException は起きません。この「ガード付き評価」は短絡評価の最も重要な使い道で、null チェックと参照の使用を 1 つの条件式にまとめて書けるのはこの仕様のおかげです。ここを & に変えると両辺が必ず評価され、同じコードが NullPointerException で落ちます。& と && は「結果が同じで速いかどうか」の違いではなく、安全性に関わる違いだと理解してください。",
  },
  {
    id: 111,
    topic: "operators",
    variantOf: "operators-string-concat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Mix",
    code: [
      "public class Mix {",
      "    public static void main(String[] args) {",
      '        String a = "total: " + 1 + 2;',
      '        String b = "total: " + (1 + 2);',
      '        System.out.println(a + " / " + b);',
      "    }",
      "}",
    ],
    choices: [
      "total: 12 / total: 3",
      "total: 3 / total: 3",
      "total: 12 / total: 12",
      "total: 3 / total: 12",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "total: 12 / total: 3" },
    explanation:
      '+ は左結合なので、a では先に "total: " + 1 が文字列連結として確定し、その結果にさらに 2 が連結されて "total: 12" になります。b では括弧によって 1 + 2 が先に算術加算され "total: 3" です。+ が算術加算と文字列連結を兼ねているため、どちらとして解釈されるかは「その時点の左辺が文字列かどうか」で決まります。ログ出力で "件数: " + count + 1 のような式を書いて意図しない結果になるのは、この評価順が原因です。迷ったら括弧を付けるのが確実です。',
  },

  // ======================================================== 制御構造 (control)
  {
    id: 112,
    topic: "control",
    variantOf: "control-switch-fallthrough",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Grade",
    code: [
      "public class Grade {",
      "    public static void main(String[] args) {",
      '        String level = "B";',
      "        switch (level) {",
      '            case "A":',
      '            case "B":',
      '                System.out.print("high ");',
      '            case "C":',
      '                System.out.print("mid ");',
      "                break;",
      "            default:",
      '                System.out.print("low");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["high mid", "high", "high mid low", "mid", "low"],
    correct: [0],
    expected: { kind: "output", stdout: "high mid" },
    explanation:
      'case "A" のように処理を書かず次の case に続ける書き方は、複数の値をまとめて扱う常套手段です。ここでは "B" に一致して high を出力し、break が無いため case "C" の処理にも流れ込んで mid を出力し、break で switch を抜けます。switch が「一致した位置へジャンプし、そこから下へ実行し続ける」という構造なのは、元をたどれば C 言語のジャンプテーブルの発想を受け継いでいるためです。意図しないフォールスルーはバグの温床なので、Java 14 以降では矢印構文の switch が導入され、フォールスルーしないのが既定になっています。',
  },
  {
    id: 113,
    topic: "control",
    variantOf: "control-labeled-break",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Grid",
    code: [
      "public class Grid {",
      "    public static void main(String[] args) {",
      "        int count = 0;",
      "        outer:",
      "        for (int i = 0; i < 3; i++) {",
      "            for (int j = 0; j < 3; j++) {",
      "                if (j == 1) {",
      "                    continue outer;",
      "                }",
      "                count++;",
      "            }",
      "        }",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: ["3", "9", "6", "0", "無限ループになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3" },
    explanation:
      "ラベル付き continue は、指定したラベルのループの「次の繰り返し」へ進みます。内側のループは j が 0 のときだけ count を増やし、j が 1 になった時点で外側のループの次の i へ移るため、i ごとに 1 回ずつ、合計 3 回だけ加算されます。ラベルなしの continue なら内側のループの次の j へ進むため結果は 6 になります。Java には goto がありませんが、多重ループから抜けたい・飛ばしたいという正当な要求は残るため、行き先をループに限定した安全な形としてラベルが用意されています。",
  },
  {
    id: 114,
    topic: "control",
    variantOf: "control-enhanced-for",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Names",
    code: [
      "import java.util.ArrayList;",
      "import java.util.List;",
      "",
      "public class Names {",
      "    public static void main(String[] args) {",
      "        List<StringBuilder> items = new ArrayList<>();",
      '        items.add(new StringBuilder("a"));',
      "        for (StringBuilder sb : items) {",
      '            sb.append("!");',
      "        }",
      "        System.out.println(items.get(0));",
      "    }",
      "}",
    ],
    choices: ["a!", "a", "!", "実行時に例外がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "a!" },
    explanation:
      "拡張 for 文のループ変数にコピーされるのは「参照の値」であり、参照先のオブジェクトそのものではありません。そのため sb への再代入は元のリストに影響しませんが、sb.append(...) のように参照先の状態を変えるメソッドを呼べば、リストが保持しているインスタンスが変化します。int の要素を書き換えても元に戻らないのと結果が違って見えるのは、この「参照のコピー」と「オブジェクトの共有」の区別が理由です。Java の引数渡しが常に値渡しでありながら、オブジェクトの中身は呼び出し先で変えられるのも同じ仕組みです。",
  },
  {
    id: 115,
    topic: "control",
    variantOf: "control-do-while",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Countdown",
    code: [
      "public class Countdown {",
      "    public static void main(String[] args) {",
      "        int i = 3;",
      "        while (i-- > 0) {",
      "            System.out.print(i);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["210", "321", "3210", "210-1", "無限ループになる"],
    correct: [0],
    expected: { kind: "output", stdout: "210" },
    explanation:
      "i-- > 0 は「判定には減算前の値を使い、判定後に i を 1 減らす」という意味です。判定に使われるのは 3・2・1・0 で、本体が実行されるのは最初の 3 回。ただし本体に入った時点では既に減算が済んでいるため、出力されるのは 2・1・0 になります。後置演算子が「古い値を返してから更新する」という性質を持つおかげで、条件判定とカウンタ更新を 1 行にまとめられますが、条件の中で見た値と本体で見える値がずれます。ループ条件に副作用を混ぜると読み手が必ず一度立ち止まるため、実務では分けて書くのが無難です。",
  },

  // ============================================================ 配列 (arrays)
  {
    id: 116,
    topic: "arrays",
    variantOf: "arrays-jagged-default",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Table",
    code: [
      "public class Table {",
      "    public static void main(String[] args) {",
      "        String[][] table = new String[2][3];",
      '        System.out.println(table.length + " " + table[0].length + " " + table[1][2]);',
      "    }",
      "}",
    ],
    choices: ["2 3 null", "2 3 ", "3 2 null", "2 3 0", "実行時に NullPointerException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 3 null" },
    explanation:
      "new String[2][3] は両方の次元をまとめて確保するため、table[0] や table[1] には長さ 3 の配列が入っています。要素そのものは参照型の既定値である null で初期化されます。配列生成時に必ず既定値で埋められるのは、未初期化のメモリが読めてしまう事態を防ぐための仕様で、数値型なら 0、boolean なら false、参照型なら null になります。ここで null が出力されても例外にならないのは、null を出力しているだけで参照をたどっていないからです。table[1][2].length() のように操作した瞬間に NullPointerException になります。",
  },
  {
    id: 117,
    topic: "arrays",
    variantOf: "arrays-initializer",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Setup",
    code: [
      "public class Setup {",
      "    public static void main(String[] args) {",
      "        int[] a = new int[] {1, 2, 3};",
      "        int[] b = {4, 5};",
      "        int[][] c = {{1}, {2, 3}};",
      "        System.out.println(a.length + b.length + c[1].length);",
      "    }",
      "}",
    ],
    choices: ["7", "322", "6", "8", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "7" },
    explanation:
      "3 つとも正しい初期化です。{...} だけの短い形は「宣言と同時に初期化する場合」に限って使え、new int[] {...} は式なのでどこでも使えます。length はすべて int なので 3 + 2 + 2 が算術加算されて 7 になります（もし 1 つでも文字列が混じれば連結に変わる点に注意）。短い形が宣言時にしか使えないのは、{1, 2} という記述だけでは要素の型が決まらず、代入先の宣言があって初めて int[] と確定できるからです。型情報が文脈から得られる場所でのみ省略を許す、という Java の一貫した方針の表れです。",
  },
  {
    id: 118,
    topic: "arrays",
    variantOf: "arrays-covariance",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Bag",
    code: [
      "public class Bag {",
      "    public static void main(String[] args) {",
      "        Object[] values = new Integer[2];",
      "        values[0] = 1;",
      '        values[1] = "two";',
      "        System.out.println(values[0]);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ArrayStoreException がスローされる",
      "1 と出力される",
      "5行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "実行時に ClassCastException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ArrayStoreException" },
    explanation:
      "Integer[] を Object[] として扱えるのは、配列が共変（Integer が Object の派生型なら Integer[] も Object[] の派生型）だからです。しかし実体は Integer[] なので、String を入れようとした時点で ArrayStoreException になります。コンパイラは変数の型 Object[] しか見ないため、この矛盾を実行時まで検出できません。ジェネリクスが非変（List<Integer> は List<Object> ではない）に設計されたのは、まさにこの穴を繰り返さないためです。配列とジェネリクスで型の扱いが違う理由はここにあります。",
  },
];
