import type { SilverQuestion } from "../quizTypes";

/**
 * 亜種の追加・その1（基本 / データ型前半、id 501 以降）。
 * 既存論点と同じ観点を、別の切り口・別の値で問う。
 */
export const variantQuestions3: SilverQuestion[] = [
  // ============================================================ 基本 (basics)
  {
    id: 501,
    topic: "basics",
    variantOf: "basics-comments",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Quoted",
    code: [
      "public class Quoted {",
      "    public static void main(String[] args) {",
      '        String s = "/* not a comment */";',
      '        // System.out.print("skip");',
      "        System.out.print(s.length());",
      "    }",
      "}",
    ],
    choices: ["19", "0", "コンパイルエラーになる", "skip19", "5"],
    correct: [0],
    expected: { kind: "output", stdout: "19" },
    explanation:
      "コメントの判定は字句解析の段階で行われますが、文字列リテラルの内側は対象外です。そのため 3 行目の /* はコメントの開始とはみなされず、ただの文字として 19 文字の文字列になります。逆に 4 行目は行コメントなので実行されません。「文字列の中か外か」を先に判断してからコメントを探す、という順序になっているおかげで、コメント記号を含む文字列を安心して書けます。もしこの区別が無ければ、正規表現やパスを扱う文字列がコードを壊してしまいます。",
  },
  {
    id: 502,
    topic: "basics",
    variantOf: "basics-source-structure",
    question: "次のコードを 1 つのファイル First.java に記述してコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "First",
    code: [
      "public class First {",
      "    public static void main(String[] args) {",
      '        System.out.println("x");',
      "    }",
      "}",
      "",
      "public class Second {",
      "}",
    ],
    choices: [
      "public なクラスは 1 ファイルに 1 つまでのためコンパイルエラーになる",
      "コンパイルは成功し、x が出力される",
      "Second に main が無いためコンパイルエラーになる",
      "コンパイルは成功するが実行時にエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "1 つのソースファイルに public なクラスを 2 つ以上置くことはできません。public クラスの名前はファイル名と一致させる規則があるため、2 つあるとどちらの名前を採用するか決められないからです。この規則によって、コンパイラは「型 Second を探すなら Second.java を読めばよい」と機械的に判断できます。public でないクラスなら同じファイルに何個でも置けます。ファイル名とクラス名を結び付けているのは Java の探索コストを下げるための設計です。",
  },
  {
    id: 503,
    topic: "basics",
    variantOf: "basics-initialization-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Sequence",
    code: [
      "public class Sequence {",
      '    static int value = init("field");',
      "",
      "    static {",
      '        System.out.print("block ");',
      "    }",
      "",
      "    static int init(String tag) {",
      '        System.out.print(tag + " ");',
      "        return 1;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.print("main");',
      "    }",
      "}",
    ],
    choices: ["field block main", "block field main", "main field block", "field main block", "block main field"],
    correct: [0],
    expected: { kind: "output", stdout: "field block main" },
    explanation:
      "static フィールドの初期化子と static 初期化ブロックは、どちらもクラスの初期化時に「ソースに書かれた順」で実行されます。ここではフィールドが先に書かれているので field、次に block、最後にクラスの準備が終わってから main が動きます。記述順で決まるため、ブロックを上に移せば順序も入れ替わります。この順序が保証されているおかげで、後続の初期化処理が前の結果に依存できます。裏を返せば、宣言より前に書いたブロックからそのフィールドを読むと初期値のままになるため、順序に依存する初期化は避けるのが無難です。",
  },
  {
    id: 504,
    topic: "basics",
    variantOf: "basics-println-chararray",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Valued",
    code: [
      "public class Valued {",
      "    public static void main(String[] args) {",
      "        char[] chars = {'a', 'b'};",
      '        System.out.println(String.valueOf(chars) + " " + new String(chars));',
      "    }",
      "}",
    ],
    choices: ["ab ab", "[C@... のような文字列が 2 つ", "ab [C@...", "a b", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ab ab" },
    explanation:
      "String.valueOf には char[] 専用のオーバーロードがあり、配列の中身を文字列に変換します。new String(char[]) も同じく中身から文字列を作ります。一方 \"x\" + chars のように連結演算子を使うと、char[] は Object として扱われ、既定の toString()（型名とハッシュ値）が出てしまいます。同じ char[] でも、どのメソッドを通すかで結果が大きく変わるということです。文字の配列から文字列を作る場面では valueOf か new String を使うと覚えておくと確実です。",
  },
  {
    id: 505,
    topic: "basics",
    variantOf: "basics-wildcard-import",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Ambiguity",
    code: [
      "import java.util.*;",
      "import java.sql.*;",
      "",
      "public class Ambiguity {",
      "    public static void main(String[] args) {",
      "        Date date = null;",
      "        System.out.println(date);",
      "    }",
      "}",
    ],
    choices: [
      "Date がどちらのパッケージのものか決められないためコンパイルエラーになる",
      "コンパイルは成功し、null が出力される",
      "後に書いた java.sql.Date が優先されコンパイルは成功する",
      "先に書いた java.util.Date が優先されコンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "java.util と java.sql の両方に Date があるため、アスタリスクのインポートを 2 つ書くと型名が一意に決まらずコンパイルエラーになります。インポートの記述順で優先されることはありません。曖昧さを黙って解決せずエラーにするのは、どちらが選ばれたか読み手に分からない状態を避けるためです。解決するには import java.util.Date; のように単一型インポートを併記する（こちらが優先されます）か、使う箇所で完全修飾名を書きます。",
  },
  {
    id: 506,
    topic: "basics",
    variantOf: "basics-class-access-modifier",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Contradiction",
    code: [
      "public class Contradiction {",
      "    public static void main(String[] args) {",
      '        System.out.println("x");',
      "    }",
      "}",
      "",
      "abstract final class Impossible {",
      "}",
    ],
    choices: [
      "abstract と final は同時に指定できないためコンパイルエラーになる",
      "コンパイルは成功し、x が出力される",
      "final class に abstract を付けると警告だけが出る",
      "Impossible をインスタンス化していないためコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "abstract は「継承して完成させる前提」、final は「継承を禁止する」という意味なので、同時に指定すると矛盾します。abstract クラスは自身をインスタンス化できないため、final で継承も禁じると誰も使えない型になってしまいます。コンパイラは意味の通らない修飾子の組み合わせを検出してエラーにします。同様に、メソッドでも abstract と final、abstract と private、abstract と static は併用できません。修飾子は単なる飾りではなく、互いに矛盾しないかが検査されるということです。",
  },
  {
    id: 507,
    topic: "basics",
    variantOf: "basics-source-file-mode",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Deploy",
    code: [
      "package com.example.app;",
      "",
      "public class Deploy {",
      "    public static void main(String[] args) {",
      "        System.out.println(Deploy.class.getName());",
      "    }",
      "}",
    ],
    choices: [
      "com.example.app.Deploy",
      "Deploy",
      "com/example/app/Deploy",
      "com.example.app",
      "実行時に ClassNotFoundException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "com.example.app.Deploy" },
    explanation:
      "クラスの正式な名前はパッケージ名を含む完全修飾名です。getName() はそれを返すため com.example.app.Deploy になります。実行時も java com.example.app.Deploy と完全修飾名で指定する必要があり、ファイルパスのようにスラッシュで区切ったり .class を付けたりはしません。一方 javac にはソースファイルのパスを渡すため、そちらはスラッシュ区切りになります。「javac にはファイル、java にはクラス」と対象が違うことを押さえると混同しません。",
  },

  // ==================================================== データ型 (datatypes)
  {
    id: 508,
    topic: "datatypes",
    variantOf: "datatypes-integer-cache",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Boxed",
    code: [
      "public class Boxed {",
      "    public static void main(String[] args) {",
      "        Integer a = 1000;",
      "        Integer b = 1000;",
      '        System.out.println((a == b) + " " + a.equals(b));',
      "    }",
      "}",
    ],
    choices: ["false true", "true true", "false false", "true false", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false true" },
    explanation:
      "1000 はキャッシュ対象（-128〜127）の外なので、オートボクシングのたびに別のインスタンスが作られ == は false になります。一方 equals は Integer が値の比較としてオーバーライドしているため true です。同じコードでも値が 100 なら == が true になってしまうため、テストでたまたま通って本番で壊れる、という厄介な不具合を生みます。ラッパー型を比較するときは必ず equals を使うか、プリミティブに戻してから比較するのが鉄則です。",
  },
  {
    id: 509,
    topic: "datatypes",
    variantOf: "datatypes-literals",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Radix",
    code: [
      "public class Radix {",
      "    public static void main(String[] args) {",
      "        int a = 0xff;",
      "        int b = 0XFF;",
      "        int c = 0b1111_1111;",
      '        System.out.println((a == b) + " " + (b == c) + " " + a);',
      "    }",
      "}",
    ],
    choices: ["true true 255", "true false 255", "false false 255", "true true 0xff", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true true 255" },
    explanation:
      "接頭辞の x も基数を表す英字も大文字小文字を区別しないため、0xff と 0XFF は同じ値です。2 進表記の 1111_1111 も同じ 255 を表します。基数はあくまで「ソース上での書き方」であり、コンパイル後はどれも同じ int の値になります。出力すると常に 10 進で表示されるのもそのためで、16 進で表示したければ Integer.toHexString を使います。表記はビット単位の値を読みやすくするためのもの、と理解しておくと混乱しません。",
  },
  {
    id: 510,
    topic: "datatypes",
    variantOf: "datatypes-float-precision",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Precision",
    code: [
      "public class Precision {",
      "    public static void main(String[] args) {",
      "        float f = 0.1f;",
      "        double d = 0.1;",
      '        System.out.println(f == d ? "same" : "diff");',
      "    }",
      "}",
    ],
    choices: ["diff", "same", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "diff" },
    explanation:
      "float と double を比較すると float 側が double に拡大変換されますが、float は 0.1 を double より粗い精度でしか保持していないため、変換しても double の 0.1 とは一致しません。精度の低い値を精度の高い型に広げても、失われた情報は戻らないということです。これは丸め誤差が型ごとに異なる位置で生じることの典型例で、異なる精度の浮動小数点を混ぜて比較するのは避けるべきです。そもそも浮動小数点は == で比較せず、許容誤差を決めて差の大きさで判定します。",
  },
  {
    id: 511,
    topic: "datatypes",
    variantOf: "datatypes-integer-division",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Mod",
    code: [
      "public class Mod {",
      "    public static void main(String[] args) {",
      '        System.out.println(10 % 3 + " " + (-10) % 3 + " " + 10 % (-3));',
      "    }",
      "}",
    ],
    choices: ["1 -1 1", "1 1 1", "1 2 -1", "1 -1 -1", "実行時に ArithmeticException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 -1 1" },
    explanation:
      "剰余の符号は「割られる数（左辺）」に従い、割る数の符号は結果の符号に影響しません。これは a == (a / b) * b + (a % b) という関係を成り立たせるための定義です。数学的な剰余（常に 0 以上）とは異なる点に注意が必要で、負数に対して n % 2 == 1 で奇数判定を書くと -3 のときに成立せず破綻します。奇数判定は n % 2 != 0 と書くか、Math.floorMod を使うと安全です。",
  },
  {
    id: 512,
    topic: "datatypes",
    variantOf: "datatypes-string-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Transform",
    code: [
      "public class Transform {",
      "    public static void main(String[] args) {",
      '        String s = "a-b-c";',
      '        System.out.println(s.replace("-", "") + " " + s.substring(2).length() + " " + s.indexOf("z"));',
      "    }",
      "}",
    ],
    choices: ["abc 3 -1", "abc 3 0", "a-b-c 3 -1", "abc 5 -1", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "abc 3 -1" },
    explanation:
      'replace は該当箇所をすべて置き換えた新しい文字列を返し、元の s は変わりません。substring(2) は添字 2 以降なので "b-c" で長さ 3 です。indexOf は見つからない場合に -1 を返します。「見つからない」を例外ではなく -1 で表すのは、探索の失敗が異常事態ではなく通常の結果だからです。そのため戻り値の判定を忘れると、-1 をそのまま添字に使って例外になります。0 は「先頭で見つかった」を意味するので、if (s.indexOf(x) > 0) のような条件は先頭一致を取りこぼす典型的な誤りです。',
  },
  {
    id: 513,
    topic: "datatypes",
    variantOf: "datatypes-string-immutable-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Reassigned",
    code: [
      "public class Reassigned {",
      "    public static void main(String[] args) {",
      '        String s = "java";',
      "        s = s.toUpperCase();",
      '        s = s.concat("!");',
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["JAVA!", "java", "JAVA", "java!", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "JAVA!" },
    explanation:
      "String のメソッドは元の文字列を変えず新しい文字列を返しますが、その戻り値を変数へ代入し直せば結果は反映されます。変わったのは変数が指す先であって、もとの文字列オブジェクト自体ではありません。不変オブジェクトを扱うときは「操作した結果を受け取る」のが基本形で、LocalDate や BigDecimal も同じ使い方になります。なお連結を繰り返すと毎回新しいインスタンスが生まれるため、ループ内で大量に連結する場合は StringBuilder を使うのが定石です。",
  },
  {
    id: 514,
    topic: "datatypes",
    variantOf: "datatypes-se11-string-api",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Blank",
    code: [
      "public class Blank {",
      "    public static void main(String[] args) {",
      '        String empty = "";',
      '        String spaces = "   ";',
      '        System.out.println(empty.isEmpty() + " " + spaces.isEmpty() + " " + spaces.isBlank());',
      "    }",
      "}",
    ],
    choices: ["true false true", "true true true", "true false false", "false false true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true false true" },
    explanation:
      "isEmpty は長さが 0 かどうかだけを見るため、空白だけの文字列は false です。Java 11 で追加された isBlank は空白だけの場合も true を返します。両者が別メソッドとして用意されたのは、既存の isEmpty の意味を変えると互換性が壊れるからで、入力の未入力判定には isBlank の方が実用的です。ユーザー入力や設定値の検証では「空文字」と「空白のみ」を同一視したい場面が多く、この違いを知らないと空白だけの入力を通してしまいます。",
  },
  {
    id: 515,
    topic: "datatypes",
    variantOf: "datatypes-explicit-cast",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ToChar",
    code: [
      "public class ToChar {",
      "    public static void main(String[] args) {",
      "        int code = 65;",
      "        char c = (char) code;",
      "        double d = 66.9;",
      "        char e = (char) d;",
      '        System.out.println(c + " " + e);',
      "    }",
      "}",
    ],
    choices: ["A B", "65 66", "A C", "65 66.9", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "A B" },
    explanation:
      "int から char へのキャストは、その数値を文字コードとして解釈します。65 は 'A' です。double から char へは、まず小数部が切り捨てられて 66 になり、それが 'B' として扱われます。切り捨てであって四捨五入ではないため 66.9 でも 'C' にはなりません。char が 16 ビットの数値型でもあるからこそ、こうした数値との相互変換が成立します。文字コードを直接扱う処理では便利ですが、範囲外の値をキャストすると意図しない文字になるため注意が必要です。",
  },
  {
    id: 516,
    topic: "datatypes",
    variantOf: "datatypes-boolean-cast",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Compare",
    code: [
      "public class Compare {",
      "    public static void main(String[] args) {",
      "        boolean flag = true;",
      "        if (flag == 1) {",
      '            System.out.println("yes");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "コンパイルは成功し、yes が出力される",
      "コンパイルは成功し、何も出力されない",
      "3行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "boolean と数値型は互換性がないため、== で比較することもできません。C 言語のように真を 1、偽を 0 として扱う仕組みを Java は持たないからです。この分離によって、条件式に数値が紛れ込む誤りや、代入と比較の取り違えがコンパイル時に検出されます。boolean の判定は if (flag) と書けば済み、== true のような比較は冗長なだけでなく、== を = と打ち間違える危険も増やします。",
  },
];
