import type { SilverQuestion } from "../quizTypes";

/** 亜種の追加・その3（制御構造 / 配列、id 541 以降） */
export const variantQuestions5: SilverQuestion[] = [
  // ======================================================== 制御構造 (control)
  {
    id: 541,
    topic: "control",
    variantOf: "control-for-multiple",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Paired",
    code: [
      "public class Paired {",
      "    public static void main(String[] args) {",
      '        String result = "";',
      "        for (int i = 0, j = 3; i < j; i++, j--) {",
      "            result += i;",
      "        }",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: ["01", "012", "0", "0123", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "01" },
    explanation:
      "(i, j) は (0, 3) → (1, 2) → (2, 1) と変化し、条件 i < j を満たすのは最初の 2 回だけです。そのため 0 と 1 が連結されます。初期化部と更新部はカンマで複数の式を並べられますが、条件部は 1 つの boolean 式だけで、カンマで並べることはできません（&& で結合します）。3 つの部分でカンマの扱いが違うのは、初期化と更新が「複数の副作用を順に実行する」場所であるのに対し、条件は「1 つの真偽値」を求める場所だからです。",
  },
  {
    id: 542,
    topic: "control",
    variantOf: "control-infinite-for",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Loop2",
    code: [
      "public class Loop2 {",
      "    public static void main(String[] args) {",
      "        int count = 0;",
      "        while (true) {",
      "            count++;",
      "            if (count == 3) {",
      "                break;",
      "            }",
      "        }",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: ["3", "2", "4", "無限ループになる", "条件が常に真のためコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3" },
    explanation:
      "while (true) は無限ループで、break で抜けます。count が 3 になった時点で脱出するため 3 が出力されます。for (;;) と機能は同じですが、while (true) の方が「条件は本体の中で判断する」という意図が読み取りやすいと好まれます。注意点として、while (true) の後ろに到達不能なコードを書くとコンパイルエラーになります。コンパイラは定数条件のループを解析しており、break が無ければその後の文へ到達できないと判断するためです。",
  },
  {
    id: 543,
    topic: "control",
    variantOf: "control-switch-types",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CharSwitch",
    code: [
      "public class CharSwitch {",
      "    public static void main(String[] args) {",
      "        char grade = 'B';",
      "        switch (grade) {",
      "            case 'A':",
      '                System.out.print("excellent");',
      "                break;",
      "            case 'B':",
      '                System.out.print("good");',
      "                break;",
      "            default:",
      '                System.out.print("other");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["good", "excellent", "other", "goodother", "char は switch に使えないためコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "good" },
    explanation:
      "char は switch に使える型です（byte・short・char・int とそのラッパー、String、enum が対象）。'B' が一致して good を出力し、break で抜けます。char が使えるのは、内部的に整数として扱われ、飛び先の表を作れるからです。逆に long が使えないのは値の幅が int を超えるためで、同じ整数系でも区別されています。boolean や浮動小数点数も使えないため、それらで分岐したい場合は if 文を選びます。",
  },
  {
    id: 544,
    topic: "control",
    variantOf: "control-switch-default-position",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NoMatch",
    code: [
      "public class NoMatch {",
      "    public static void main(String[] args) {",
      "        int code = 5;",
      "        switch (code) {",
      "            case 1:",
      '                System.out.print("one");',
      "                break;",
      "            case 2:",
      '                System.out.print("two");',
      "                break;",
      "        }",
      '        System.out.print("end");',
      "    }",
      "}",
    ],
    choices: ["end", "oneend", "twoend", "何も出力されない", "default が無いためコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "end" },
    explanation:
      "どの case にも一致せず default も無い場合、switch 全体が何もせずに終わります。エラーにはならず、後続の処理が続きます。default は任意であり、書かなければ「該当なしのときは何もしない」という意味になります。ただし想定外の値が来たことに気づけなくなるため、実務では default を用意して記録したり例外を投げたりするのが安全です。enum を対象にした switch では、すべての定数を網羅していれば default 不要ですが、後から定数が追加されたときに漏れが出る点は同じです。",
  },
  {
    id: 545,
    topic: "control",
    variantOf: "control-continue-basic",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SkipWhile",
    code: [
      "public class SkipWhile {",
      "    public static void main(String[] args) {",
      '        String result = "";',
      "        for (int i = 0; i < 5; i++) {",
      "            if (i == 2) {",
      "                continue;",
      "            }",
      "            result += i;",
      "        }",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: ["0134", "01234", "01", "234", "無限ループになる"],
    correct: [0],
    expected: { kind: "output", stdout: "0134" },
    explanation:
      "continue は残りの本体を飛ばして次の繰り返しへ進みます。i が 2 のときだけ連結を飛ばすため 0134 になります。for 文では continue しても更新部（i++）が必ず実行されるため、ループは正しく進みます。同じことを while 文で書く場合、continue の前にカウンタを進めておかないと無限ループになります。break がループ自体を終えるのに対し、continue は「この回だけ中断する」という違いを押さえておくと使い分けを誤りません。",
  },
  {
    id: 546,
    topic: "control",
    variantOf: "control-loop-scope",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OuterVar",
    code: [
      "public class OuterVar {",
      "    public static void main(String[] args) {",
      "        int i;",
      "        for (i = 0; i < 3; i++) {",
      '            System.out.print("*");',
      "        }",
      "        System.out.println(i);",
      "    }",
      "}",
    ],
    choices: ["***3", "***2", "***0", "3行目でコンパイルエラーになる", "7行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "***3" },
    explanation:
      "for 文の外で宣言した変数を初期化部で代入すれば、ループ終了後もその値を参照できます。条件が偽になった時点の値、つまり 3 が残ります。ループ内で宣言した場合はスコープがループ内に限られ、外から参照できません。どちらを選ぶかは「ループ後に値が必要か」で決まります。必要ないのに外で宣言すると、メソッドの最後まで変数が生き続けて意図しない再利用を招くため、必要な範囲に絞るのが原則です。",
  },
  {
    id: 547,
    topic: "control",
    variantOf: "control-concurrent-modification",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SafeRemove",
    code: [
      "import java.util.ArrayList;",
      "import java.util.Iterator;",
      "import java.util.List;",
      "",
      "public class SafeRemove {",
      "    public static void main(String[] args) {",
      "        List<String> items = new ArrayList<>();",
      '        items.add("a");',
      '        items.add("b");',
      "        Iterator<String> it = items.iterator();",
      "        while (it.hasNext()) {",
      '            if (it.next().equals("a")) {',
      "                it.remove();",
      "            }",
      "        }",
      "        System.out.println(items);",
      "    }",
      "}",
    ],
    choices: [
      "[b]",
      "実行時に ConcurrentModificationException がスローされる",
      "[a, b]",
      "[]",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[b]" },
    explanation:
      "イテレータ自身の remove を使えば、走査中でも安全に要素を削除できます。イテレータが自分で削除した場合は内部の変更回数の記録も同時に更新されるため、整合性が崩れないからです。一方リスト側の remove を呼ぶとイテレータの記録とずれ、ConcurrentModificationException になります。同じ「削除」でも、誰が行ったかによって結果が変わるということです。なお Java 8 以降は removeIf を使えば条件を渡すだけで済み、より簡潔かつ安全です。",
  },
  {
    id: 548,
    topic: "control",
    variantOf: "control-if-without-braces",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "DanglingElse",
    code: [
      "public class DanglingElse {",
      "    public static void main(String[] args) {",
      "        int value = 5;",
      "        if (value > 0)",
      "            int doubled = value * 2;",
      "        System.out.println(value);",
      "    }",
      "}",
    ],
    choices: [
      "5行目でコンパイルエラーになる",
      "コンパイルは成功し、5 が出力される",
      "コンパイルは成功し、10 が出力される",
      "4行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 5 },
    explanation:
      "波括弧を省略した if の本体には「文」を 1 つ書けますが、ローカル変数の宣言はそこに置けません。宣言した変数のスコープがその場で消えてしまい、宣言する意味が無いためです。ブロックで囲めば宣言できます。この制約は、意味の無いコードを早い段階で弾くための仕様です。そもそも波括弧を常に書いていればこの問題は起きず、条件分岐に文を足したときの取り違えも防げるため、省略しないことが推奨されます。",
  },
  {
    id: 549,
    topic: "control",
    variantOf: "control-switch-case-constant",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Duplicate",
    code: [
      "public class Duplicate {",
      "    public static void main(String[] args) {",
      "        int value = 1;",
      "        switch (value) {",
      "            case 1:",
      '                System.out.print("a");',
      "                break;",
      "            case 1:",
      '                System.out.print("b");',
      "                break;",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "case の値が重複しているためコンパイルエラーになる",
      "コンパイルは成功し、a が出力される",
      "コンパイルは成功し、ab が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "case のラベルは重複できません。同じ値に対する飛び先が 2 つあると、どちらへ飛ぶか決められないからです。switch が値から飛び先を引く表に変換される仕組み上、キーの重複は許されません。case の値がコンパイル時に確定する定数に限られているのも同じ理由で、だからこそ重複をコンパイル時に検出できます。複数の値で同じ処理をしたい場合は、case を連続して並べてフォールスルーさせます。",
  },
  {
    id: 550,
    topic: "control",
    variantOf: "control-switch-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Guarded",
    code: [
      "public class Guarded {",
      "    public static void main(String[] args) {",
      "        String command = null;",
      '        if (command == null) {',
      '            System.out.print("none");',
      "        } else {",
      "            switch (command) {",
      '                case "run":',
      '                    System.out.print("r");',
      "                    break;",
      "                default:",
      '                    System.out.print("d");',
      "            }",
      "        }",
      "    }",
      "}",
    ],
    choices: ["none", "d", "実行時に NullPointerException がスローされる", "r", "何も出力されない"],
    correct: [0],
    expected: { kind: "output", stdout: "none" },
    explanation:
      "switch に渡す前に null を判定しているため、例外は発生せず none が出力されます。String の switch は内部で対象のハッシュ値を求めるため null だと NullPointerException になりますが、このように事前に弾けば安全です。default があっても null は救えないので、null を取りうる値で分岐するときは必ず手前で確認します。逆に言えば、switch に到達した時点で値が非 null であることが保証される書き方にしておくと、分岐の意図が明確になります。",
  },
  {
    id: 551,
    topic: "control",
    variantOf: "control-for-type-mixing",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SameType",
    code: [
      "public class SameType {",
      "    public static void main(String[] args) {",
      "        int total = 0;",
      "        for (int i = 0, step = 2; i < 6; i += step) {",
      "            total += i;",
      "        }",
      "        System.out.println(total);",
      "    }",
      "}",
    ],
    choices: ["6", "12", "15", "0", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "6" },
    explanation:
      "初期化部で複数の変数を宣言する場合、型が同じであれば問題ありません。i は 0, 2, 4 と進み、合計は 6 になります。step のようにループ内で変化しない値も初期化部で宣言できますが、スコープが for 文の中に限定されるため、外から参照できない点は同じです。異なる型を混ぜられないのは通常の変数宣言と同じ規則によるもので、for 文だけの特別扱いではありません。",
  },

  // ============================================================ 配列 (arrays)
  {
    id: 552,
    topic: "arrays",
    variantOf: "arrays-length-member",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "LengthCall",
    code: [
      "public class LengthCall {",
      "    public static void main(String[] args) {",
      "        int[] numbers = {1, 2, 3};",
      "        System.out.println(numbers.length());",
      "    }",
      "}",
    ],
    choices: [
      "配列の length はメソッドではないためコンパイルエラーになる",
      "コンパイルは成功し、3 が出力される",
      "コンパイルは成功し、0 が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "配列の length はフィールドなので、括弧を付けて呼び出すことはできません。String の length() はメソッドなので括弧が必要で、両者は書き方が逆になります。配列の長さがフィールドなのは、配列が言語組み込みの構造で、長さが生成時に確定する固定値として JVM に直接保持されているためです。クラスである String は内部表現を隠すためにメソッドを介します。混同しやすいので「配列は括弧なし、オブジェクトは括弧あり」と対で覚えるのが確実です。",
  },
  {
    id: 553,
    topic: "arrays",
    variantOf: "arrays-index-bounds",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NegativeSize",
    code: [
      "public class NegativeSize {",
      "    public static void main(String[] args) {",
      "        int size = -1;",
      "        int[] values = new int[size];",
      "        System.out.println(values.length);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に NegativeArraySizeException がスローされる",
      "実行時に ArrayIndexOutOfBoundsException がスローされる",
      "4行目でコンパイルエラーになる",
      "0 と出力される",
      "-1 と出力される",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NegativeArraySizeException" },
    explanation:
      "負の長さで配列を作ろうとすると NegativeArraySizeException になります。長さ 0 は有効ですが、負の長さは意味を持たないためです。変数の値は実行時にしか分からないので、コンパイルではなく実行時の検査になります（定数で new int[-1] と書いてもコンパイルは通ります）。範囲外アクセスの ArrayIndexOutOfBoundsException とは発生する場面が異なり、こちらは「生成時」、あちらは「アクセス時」の失敗です。どちらも実行時例外で、事前の入力検証が防御策になります。",
  },
  {
    id: 554,
    topic: "arrays",
    variantOf: "arrays-copyof",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Truncate",
    code: [
      "import java.util.Arrays;",
      "",
      "public class Truncate {",
      "    public static void main(String[] args) {",
      "        int[] source = {1, 2, 3, 4};",
      "        int[] shorter = Arrays.copyOf(source, 2);",
      "        int[] ranged = Arrays.copyOfRange(source, 1, 3);",
      '        System.out.println(Arrays.toString(shorter) + " " + Arrays.toString(ranged));',
      "    }",
      "}",
    ],
    choices: ["[1, 2] [2, 3]", "[1, 2] [2, 3, 4]", "[3, 4] [2, 3]", "[1, 2] [1, 2]", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 2] [2, 3]" },
    explanation:
      "copyOf に元より短い長さを渡すと、先頭から指定数だけを取り出した新しい配列になります。copyOfRange は開始位置以上・終了位置未満の範囲を切り出すため、添字 1 と 2 の要素が入ります。ここでも「開始は含み終了は含まない」という半開区間の規則が使われています。どちらも新しい配列を返すので元の配列は変化しません。配列の長さを変えられない以上、伸縮はすべて新しい配列の生成として表現される、という点が共通しています。",
  },
  {
    id: 555,
    topic: "arrays",
    variantOf: "arrays-reference-sharing",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Detached",
    code: [
      "public class Detached {",
      "    public static void main(String[] args) {",
      "        int[] a = {1, 2};",
      "        int[] b = a.clone();",
      "        b[0] = 9;",
      '        System.out.println(a[0] + " " + (a == b));',
      "    }",
      "}",
    ],
    choices: ["1 false", "9 true", "9 false", "1 true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 false" },
    explanation:
      "clone() は新しい配列を作って要素をコピーするため、b への変更は a に影響せず、参照も別物なので == は false です。単純な代入（b = a）が参照のコピーだったのと対照的で、実体を複製したいときは明示的に clone や copyOf を呼ぶ必要があります。ただし要素が参照型の場合、コピーされるのは要素の参照だけなので、指す先のオブジェクトは共有されます（浅いコピー）。int のようなプリミティブ配列でのみ、clone は完全に独立した複製になります。",
  },
  {
    id: 556,
    topic: "arrays",
    variantOf: "arrays-declaration-syntax",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TwoVars",
    code: [
      "public class TwoVars {",
      "    public static void main(String[] args) {",
      "        int[] a, b;",
      "        a = new int[2];",
      "        b = new int[3];",
      '        System.out.println(a.length + " " + b.length);',
      "    }",
      "}",
    ],
    choices: ["2 3", "3 2", "2 2", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 3" },
    explanation:
      "int[] a, b; と型側に角括弧を書くと、a も b も配列型になります。一方 int a[], b; と変数側に書いた場合は a だけが配列で b は int になってしまい、意図と食い違います。この差が、角括弧を型側に書く記法が推奨される理由です。宣言の左側だけを見れば型が分かる、という読みやすさは、複数の変数をまとめて宣言するときに特に効いてきます。そもそも 1 行に複数の変数を宣言しないのも、誤解を避ける有効な習慣です。",
  },
  {
    id: 557,
    topic: "arrays",
    variantOf: "arrays-sort-tostring",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SortText",
    code: [
      "import java.util.Arrays;",
      "",
      "public class SortText {",
      "    public static void main(String[] args) {",
      '        String[] names = {"banana", "Apple", "cherry"};',
      "        Arrays.sort(names);",
      "        System.out.println(Arrays.toString(names));",
      "    }",
      "}",
    ],
    choices: [
      "[Apple, banana, cherry]",
      "[apple, banana, cherry]",
      "[banana, Apple, cherry]",
      "[Apple, cherry, banana]",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[Apple, banana, cherry]" },
    explanation:
      "String の自然順序は辞書順ではなく文字コード順です。大文字は小文字より小さいコードなので、Apple が先頭に来ます。この並びは人間の感覚とずれることがあり、大文字小文字を無視して並べたい場合は String.CASE_INSENSITIVE_ORDER を Comparator として渡します。Arrays.sort が要素の自然順序を使うのは、要素が Comparable を実装していることを前提にしているためで、実装していない型の配列を並べ替えようとすると実行時に ClassCastException になります。",
  },
  {
    id: 558,
    topic: "arrays",
    variantOf: "arrays-size-required",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "BothSpecified",
    code: [
      "public class BothSpecified {",
      "    public static void main(String[] args) {",
      "        int[] values = new int[2] {1, 2};",
      "        System.out.println(values.length);",
      "    }",
      "}",
    ],
    choices: [
      "要素数と初期化子を同時に書けないためコンパイルエラーになる",
      "コンパイルは成功し、2 が出力される",
      "コンパイルは成功し、0 が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 3 },
    explanation:
      "配列の長さは「要素数を書く」か「初期化子の個数で決まる」かのどちらか一方で決めます。両方を同時に指定することはできません。もし両方書けてしまうと、食い違ったときにどちらを優先するか決める必要が生じ、無意味な曖昧さが生まれるからです。new int[2] と new int[] {1, 2} はどちらも有効で、前者は既定値で埋められ、後者は書いた値で初期化されます。長さの決め方は常にひとつ、という単純な規則になっています。",
  },
  {
    id: 559,
    topic: "arrays",
    variantOf: "arrays-clone-shallow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DeepEnough",
    code: [
      "public class DeepEnough {",
      "    public static void main(String[] args) {",
      "        int[][] original = {{1, 2}, {3, 4}};",
      "        int[][] copy = original.clone();",
      "        copy[0] = new int[] {9, 9};",
      '        System.out.println(original[0][0] + " " + copy[0][0]);',
      "    }",
      "}",
    ],
    choices: ["1 9", "9 9", "1 1", "9 1", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 9" },
    explanation:
      "clone は外側の配列を複製するので、copy[0] に別の配列を代入し直しても original には影響しません。影響が出るのは copy[0][0] = 9 のように内側の配列の中身を書き換えた場合で、そちらは参照が共有されているため original からも見えます。「要素そのものを差し替える」のと「要素が指す先を変更する」のは別の操作だ、という違いがここに表れています。浅いコピーの意味を正しく理解するには、この 2 つを区別することが鍵になります。",
  },
];
