import type { SilverQuestion } from "../quizTypes";

/** 亜種の追加・その5（継承・インタフェース、id 581 以降） */
export const variantQuestions7: SilverQuestion[] = [
  {
    id: 581,
    topic: "inheritance",
    variantOf: "inheritance-field-hiding",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Depot",
    code: [
      "class Storage {",
      '    String kind = "base";',
      "",
      "    String kind() {",
      "        return kind;",
      "    }",
      "}",
      "",
      "class Cabinet extends Storage {",
      '    String kind = "derived";',
      "",
      "    @Override",
      "    String kind() {",
      "        return kind;",
      "    }",
      "}",
      "",
      "public class Depot {",
      "    public static void main(String[] args) {",
      "        Storage s = new Cabinet();",
      '        System.out.println(s.kind + " " + s.kind());',
      "    }",
      "}",
    ],
    choices: ["base derived", "derived derived", "base base", "derived base", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "base derived" },
    explanation:
      "フィールドは変数の宣言型で解決されるため s.kind は base です。一方 kind() はオーバーライドされているので実行時の型 Cabinet の実装が呼ばれ、その中の kind は Cabinet 自身のフィールドを指すので derived になります。同じ名前でも、フィールドは静的に、メソッドは動的に決まるという違いが 1 行に同居しています。フィールドを隠蔽すると読み手が混乱するだけで利点がないため、実務では親子で同名フィールドを定義しないのが原則です。",
  },
  {
    id: 582,
    topic: "inheritance",
    variantOf: "inheritance-super-implicit",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Grandchild",
    code: [
      "class Root {",
      "    Root() {",
      '        System.out.print("R");',
      "    }",
      "}",
      "",
      "class Middle2 extends Root {",
      "    Middle2() {",
      '        System.out.print("M");',
      "    }",
      "}",
      "",
      "public class Grandchild extends Middle2 {",
      "    Grandchild() {",
      '        System.out.print("G");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Grandchild();",
      "    }",
      "}",
    ],
    choices: ["RMG", "GMR", "G", "RG", "MRG"],
    correct: [0],
    expected: { kind: "output", stdout: "RMG" },
    explanation:
      "コンストラクタは継承の最上位から順に実行されます。Grandchild の暗黙の super() が Middle2 を呼び、さらにその super() が Root を呼ぶため、実際の出力は Root から始まります。この順序でなければ、子の初期化処理が未初期化の親のフィールドを参照しかねません。Object から順に土台を固めてから各層を積み上げる、という流れを押さえておくと、初期化にまつわる不具合を追いやすくなります。",
  },
  {
    id: 583,
    topic: "inheritance",
    variantOf: "inheritance-missing-super",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Explicit",
    code: [
      "class Vehicle2 {",
      "    private final int wheels;",
      "",
      "    Vehicle2(int wheels) {",
      "        this.wheels = wheels;",
      "    }",
      "",
      "    int wheels() {",
      "        return wheels;",
      "    }",
      "}",
      "",
      "public class Explicit extends Vehicle2 {",
      "    Explicit() {",
      "        super(4);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Explicit().wheels());",
      "    }",
      "}",
    ],
    choices: ["4", "0", "コンパイルエラーになる", "実行時に例外がスローされる", "1"],
    correct: [0],
    expected: { kind: "output", stdout: "4" },
    explanation:
      "親に引数なしのコンストラクタが無い場合でも、子から super(4) と明示的に呼べば正しくコンパイルできます。super(...) はコンストラクタ本体の最初の文でなければならず、それより前に処理を書くことはできません。親の初期化が終わる前に子が動き出すのを防ぐためです。final フィールドである wheels が確実に一度だけ初期化されるのも、この順序と「必ずいずれかのコンストラクタを通る」という保証があってこそ成り立ちます。",
  },
  {
    id: 584,
    topic: "inheritance",
    variantOf: "inheritance-covariant-return",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Broader",
    code: [
      "class Producer {",
      "    String create() {",
      '        return "s";',
      "    }",
      "}",
      "",
      "public class Broader extends Producer {",
      "    @Override",
      "    Object create() {",
      "        return new Object();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Broader().create());",
      "    }",
      "}",
    ],
    choices: [
      "戻り値の型を広げることはできないためコンパイルエラーになる",
      "コンパイルは成功し、Object のハッシュ値が出力される",
      "コンパイルは成功し、s が出力される",
      "実行時に ClassCastException がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "オーバーライドで戻り値の型を狭める（派生型にする）ことは許されますが、広げることはできません。Producer 型として使う側は String が返ると想定しているため、Object が返ってくると受け取れなくなるからです。アクセス修飾子は広げてよく、戻り値は狭めてよい、という一見逆の規則も、どちらも「基底型の利用者が困らない方向だけ許す」という同じ原則から導かれます。置換可能性を壊す変更は、すべてコンパイル時に弾かれます。",
  },
  {
    id: 585,
    topic: "inheritance",
    variantOf: "inheritance-override-access",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Widening2",
    code: [
      "class Guarded2 {",
      "    protected String tag() {",
      '        return "protected";',
      "    }",
      "}",
      "",
      "public class Widening2 extends Guarded2 {",
      "    @Override",
      "    public String tag() {",
      '        return "public";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Widening2().tag());",
      "    }",
      "}",
    ],
    choices: ["public", "protected", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "public" },
    explanation:
      "オーバーライド時にアクセス範囲を広げるのは許可されています。protected を public にしても、基底型を通じて使う人が困ることはないからです。呼び出しは実行時の型で解決されるので public が出力されます。逆に public を protected に狭めるとコンパイルエラーになります。この非対称な規則は、派生型が基底型の代わりとして常に通用しなければならない、という置換可能性の原則から来ています。",
  },
  {
    id: 586,
    topic: "inheritance",
    variantOf: "inheritance-final-method",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Extending",
    code: [
      "class Template {",
      "    final String run() {",
      '        return "step:" + hook();',
      "    }",
      "",
      "    String hook() {",
      '        return "base";',
      "    }",
      "}",
      "",
      "public class Extending extends Template {",
      "    @Override",
      "    String hook() {",
      '        return "custom";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Extending().run());",
      "    }",
      "}",
    ],
    choices: ["step:custom", "step:base", "コンパイルエラーになる", "custom", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "step:custom" },
    explanation:
      "final なのは run だけなので、run 自体は差し替えられませんが、その中から呼ばれる hook はオーバーライドできます。結果として全体の手順は固定したまま一部だけを変えられます。これがテンプレートメソッドパターンの骨格で、「変えてよい箇所」と「変えさせない箇所」を final で明示することで、派生クラスによる意図しない改変を防ぎつつ拡張性を確保しています。final はすべてを縛るのではなく、設計の意図を伝える道具だと捉えると使いどころが見えてきます。",
  },
  {
    id: 587,
    topic: "inheritance",
    variantOf: "inheritance-interface-constant",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Reassigning",
    code: [
      "interface Limits {",
      "    int MAX = 10;",
      "}",
      "",
      "public class Reassigning implements Limits {",
      "    public static void main(String[] args) {",
      "        MAX = 20;",
      "        System.out.println(MAX);",
      "    }",
      "}",
    ],
    choices: [
      "インタフェースのフィールドは final のためコンパイルエラーになる",
      "コンパイルは成功し、20 が出力される",
      "コンパイルは成功し、10 が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "インタフェースのフィールドは暗黙に public static final なので、再代入できません。インタフェースはインスタンスごとの状態を持たない「契約」であるため、書き換え可能な変数を置く余地がなく、必然的に定数になります。実装クラスから見ると継承された定数として参照できますが、値を変えることはできません。なお定数の公開手段としてインタフェースを使う手法は現在では推奨されず、enum か final クラスの static フィールドを使うのが定石です。",
  },
  {
    id: 588,
    topic: "inheritance",
    variantOf: "inheritance-interface-static",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Inheriting",
    code: [
      "interface Factory2 {",
      "    static String create() {",
      '        return "made";',
      "    }",
      "}",
      "",
      "public class Inheriting implements Factory2 {",
      "    public static void main(String[] args) {",
      "        System.out.println(Inheriting.create());",
      "    }",
      "}",
    ],
    choices: [
      "static メソッドは継承されないためコンパイルエラーになる",
      "コンパイルは成功し、made が出力される",
      "コンパイルは成功し、null が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "インタフェースの static メソッドは実装クラスに継承されないため、Inheriting.create() とは書けません。呼ぶときは必ず Factory2.create() のようにインタフェース名で修飾します。継承しない仕様なのは、複数のインタフェースを実装したときに同名の static メソッドが衝突し、どちらを指すか決められなくなるのを避けるためです。クラスの static メソッドがサブクラス経由で呼べる（隠蔽される）のとは扱いが異なる点が引っかけどころになります。",
  },
  {
    id: 589,
    topic: "inheritance",
    variantOf: "inheritance-abstract-without-abstract-method",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Instantiate",
    code: [
      "abstract class Blueprint {",
      "    void describe() {",
      '        System.out.print("blueprint");',
      "    }",
      "}",
      "",
      "public class Instantiate {",
      "    public static void main(String[] args) {",
      "        Blueprint b = new Blueprint();",
      "        b.describe();",
      "    }",
      "}",
    ],
    choices: [
      "抽象クラスはインスタンス化できないためコンパイルエラーになる",
      "コンパイルは成功し、blueprint が出力される",
      "抽象メソッドが無いのでインスタンス化できる",
      "実行時に InstantiationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "抽象メソッドが 1 つも無くても、abstract を付けたクラスは直接インスタンス化できません。abstract の本質は「このクラス単独では使わせない」という宣言であり、抽象メソッドの有無とは独立しています。使いたい場合はサブクラスを作るか、匿名クラスとして new Blueprint() { } と書きます。逆に、抽象メソッドを 1 つでも持つクラスは必ず abstract を付けなければなりません。両者は片方向の関係にある、と整理すると覚えやすくなります。",
  },
  {
    id: 590,
    topic: "inheritance",
    variantOf: "inheritance-reference-type-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Downcast",
    code: [
      "class Creature {",
      "    void move() {",
      '        System.out.print("move");',
      "    }",
      "}",
      "",
      "class Bird extends Creature {",
      "    void fly() {",
      '        System.out.print("fly");',
      "    }",
      "}",
      "",
      "public class Downcast {",
      "    public static void main(String[] args) {",
      "        Creature c = new Bird();",
      "        if (c instanceof Bird) {",
      "            ((Bird) c).fly();",
      "        }",
      "    }",
      "}",
    ],
    choices: ["fly", "move", "何も出力されない", "実行時に ClassCastException がスローされる", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "fly" },
    explanation:
      "変数の宣言型からは fly() を呼べませんが、instanceof で実体を確認したうえでキャストすれば呼び出せます。キャストは実体を変換するのではなく「コンパイラにこの型として扱ってよいと伝える」操作で、実際の型と食い違えば実行時に ClassCastException になります。だからこそ instanceof による事前確認が対で使われます。とはいえ型で分岐する箇所が増えるなら、共通の操作を基底型のメソッドとして定義し、ポリモーフィズムで解決できないかを先に検討すべきです。",
  },
  {
    id: 591,
    topic: "inheritance",
    variantOf: "inheritance-super-call",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Recursive",
    code: [
      "class Layer {",
      "    String render() {",
      '        return "base";',
      "    }",
      "}",
      "",
      "public class Recursive extends Layer {",
      "    @Override",
      "    String render() {",
      '        return "[" + super.render() + "]";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Layer layer = new Recursive();",
      "        System.out.println(layer.render());",
      "    }",
      "}",
    ],
    choices: ["[base]", "base", "[[base]]", "実行時に StackOverflowError が発生する", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[base]" },
    explanation:
      "super.render() は動的束縛を経由せず親の実装を直接呼ぶため、無限再帰にはならず [base] になります。もし this.render() と書けば自分自身を呼び続けて StackOverflowError です。super による呼び出しだけが静的に解決されるのは、オーバーライドした側から元の実装を利用する道を残すためで、これが無いと「親の処理に前後を足す」という拡張が書けなくなります。呼び出し元の変数が Layer 型でも、実行されるのは Recursive の実装である点も押さえておきましょう。",
  },
  {
    id: 592,
    topic: "inheritance",
    variantOf: "inheritance-interface-multiple-impl",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Combined",
    code: [
      "interface Countable {",
      "    int count();",
      "}",
      "",
      "interface Named {",
      "    default String name() {",
      '        return "unnamed";',
      "    }",
      "}",
      "",
      "public class Combined implements Countable, Named {",
      "    @Override",
      "    public int count() {",
      "        return 2;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Combined c = new Combined();",
      '        System.out.println(c.count() + " " + c.name());',
      "    }",
      "}",
    ],
    choices: ["2 unnamed", "2 null", "コンパイルエラーになる", "0 unnamed", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 unnamed" },
    explanation:
      "複数のインタフェースを実装する場合、抽象メソッドはすべて実装する必要がありますが、default メソッドはそのまま継承されるので実装しなくても使えます。count は自分で実装し、name は Named の既定実装が使われます。default メソッドが導入されたのは、既存のインタフェースにメソッドを追加しても既存の実装クラスが壊れないようにするためで、Collection に forEach を追加できたのもこの仕組みのおかげです。",
  },
  {
    id: 593,
    topic: "inheritance",
    variantOf: "inheritance-object-equals-default",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Valued2",
    code: [
      "public class Valued2 {",
      "    private final int id;",
      "",
      "    Valued2(int id) {",
      "        this.id = id;",
      "    }",
      "",
      "    @Override",
      "    public boolean equals(Object other) {",
      "        if (!(other instanceof Valued2)) {",
      "            return false;",
      "        }",
      "        return this.id == ((Valued2) other).id;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Valued2 a = new Valued2(1);",
      "        Valued2 b = new Valued2(1);",
      '        System.out.println(a.equals(b) + " " + (a == b) + " " + a.equals(null));',
      "    }",
      "}",
    ],
    choices: ["true false false", "true true false", "false false false", "true false true"],
    correct: [0],
    expected: { kind: "output", stdout: "true false false" },
    explanation:
      "equals をオーバーライドして id の比較にしているため内容が同じなら true、ただし別インスタンスなので == は false です。null に対しては instanceof が false を返すため、null チェックを別途書かなくても false になります。equals の契約には「null と等しくない」ことが含まれており、instanceof を使う実装はこれを自然に満たします。なお equals をオーバーライドしたら hashCode も揃えて実装しないと、HashMap や HashSet で期待どおりに動かなくなる点に注意してください。",
  },
  {
    id: 594,
    topic: "inheritance",
    variantOf: "inheritance-constructor-not-inherited",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Redeclared",
    code: [
      "class Device {",
      "    private final String name;",
      "",
      "    Device(String name) {",
      "        this.name = name;",
      "    }",
      "",
      "    String name() {",
      "        return name;",
      "    }",
      "}",
      "",
      "public class Redeclared extends Device {",
      "    Redeclared(String name) {",
      "        super(name);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(new Redeclared("printer").name());',
      "    }",
      "}",
    ],
    choices: ["printer", "null", "コンパイルエラーになる", "実行時に例外がスローされる", "Redeclared"],
    correct: [0],
    expected: { kind: "output", stdout: "printer" },
    explanation:
      "コンストラクタは継承されないため、親と同じ形で使いたい場合は子でも定義して super へ委譲します。引数をそのまま渡すだけの記述が必要になるのは冗長に見えますが、子が独自のフィールドを追加したときに初期化を忘れないようにするための仕組みでもあります。どのコンストラクタを公開するかを子が自分で決められる、という設計上の自由度も確保されています。フィールド name は private なので子からは直接触れず、name() を通じて読みます。",
  },
  {
    id: 595,
    topic: "inheritance",
    variantOf: "inheritance-interface-super",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Unresolved",
    code: [
      "interface First2 {",
      "    default String label() {",
      '        return "first";',
      "    }",
      "}",
      "",
      "interface Second2 {",
      "    default String label() {",
      '        return "second";',
      "    }",
      "}",
      "",
      "public class Unresolved implements First2, Second2 {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Unresolved().label());",
      "    }",
      "}",
    ],
    choices: [
      "オーバーライドして解決していないためコンパイルエラーになる",
      "コンパイルは成功し、first が出力される",
      "コンパイルは成功し、second が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "同じシグネチャの default メソッドを複数のインタフェースから継承すると、どちらを使うか決められないためコンパイルエラーになります。実装クラスで label() をオーバーライドし、必要なら First2.super.label() のように呼び分けて解決します。先に書いた方が優先されるといった暗黙の規則を設けなかったのは、宣言順という見落としやすい情報で挙動が変わるのを避けるためです。曖昧さは必ず人間に解消させる、という安全側の設計になっています。",
  },
  {
    id: 596,
    topic: "inheritance",
    variantOf: "inheritance-abstract-chain",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Incomplete",
    code: [
      "abstract class Shape2 {",
      "    abstract double area();",
      "",
      "    abstract String label();",
      "}",
      "",
      "public class Incomplete extends Shape2 {",
      "    @Override",
      "    double area() {",
      "        return 1.0;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Incomplete().area());",
      "    }",
      "}",
    ],
    choices: [
      "label が未実装のためコンパイルエラーになる",
      "コンパイルは成功し、1.0 が出力される",
      "コンパイルは成功し、0.0 が出力される",
      "実行時に AbstractMethodError が発生する",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "具象クラスは、継承したすべての抽象メソッドを実装しなければなりません。label が残っているためエラーです。実装を完了できないなら、このクラス自身も abstract として宣言する必要があります。抽象メソッドは「派生型が必ず用意する」という契約であり、未履行のままインスタンス化できてしまうと、呼び出した瞬間に初めて破綻することになります。コンパイル時点で検出できる誤りは翻訳時に潰す、という方針の表れです。",
  },
  {
    id: 597,
    topic: "inheritance",
    variantOf: "inheritance-interface-private",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Caller",
    code: [
      "interface Support {",
      "    private String helper() {",
      '        return "help";',
      "    }",
      "",
      "    default String use() {",
      "        return helper();",
      "    }",
      "}",
      "",
      "public class Caller implements Support {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Caller().helper());",
      "    }",
      "}",
    ],
    choices: [
      "private メソッドは実装クラスから呼べないためコンパイルエラーになる",
      "コンパイルは成功し、help が出力される",
      "インタフェースに private メソッドは定義できないためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 13 },
    explanation:
      "インタフェースの private メソッドは、そのインタフェース内の default メソッドから使うための仕組みで、実装クラスからは見えません。use() 経由でなら間接的に呼べます。公開しないメソッドを置けるようにしたのは、default メソッドどうしで共通する処理をまとめたいが、それをインタフェースの契約（public API）に含めたくないからです。private はインタフェースにおいても「外に見せない実装の詳細」を表す、という一貫した意味を持っています。",
  },
];
