import type { SilverQuestion } from "../quizTypes";

/** 亜種の追加・その4（メソッド / ラムダ、id 561 以降） */
export const variantQuestions6: SilverQuestion[] = [
  // ========================================================== メソッド (methods)
  {
    id: 561,
    topic: "methods",
    variantOf: "methods-pass-by-value",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Reference",
    code: [
      "class Holder2 {",
      "    int value = 1;",
      "}",
      "",
      "public class Reference {",
      "    static void replace(Holder2 holder) {",
      "        holder = new Holder2();",
      "        holder.value = 99;",
      "    }",
      "",
      "    static void modify(Holder2 holder) {",
      "        holder.value = 50;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Holder2 h = new Holder2();",
      "        replace(h);",
      "        int afterReplace = h.value;",
      "        modify(h);",
      '        System.out.println(afterReplace + " " + h.value);',
      "    }",
      "}",
    ],
    choices: ["1 50", "99 50", "1 1", "99 99", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 50" },
    explanation:
      "replace では引数の変数に新しいインスタンスを代入していますが、変わったのは呼び出し先のローカル変数だけで、呼び出し元の h が指す先は変わりません。一方 modify は受け取った参照をたどって中身を書き換えるため、呼び出し元にも反映されます。この 2 つの違いが「参照の値渡し」の意味そのものです。引数を差し替えても呼び出し元には伝わらないので、結果を返したいならメソッドの戻り値を使うのが正しい設計になります。",
  },
  {
    id: 562,
    topic: "methods",
    variantOf: "methods-return-type-overload",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "SameParams",
    code: [
      "public class SameParams {",
      "    static void show(int value) {",
      '        System.out.print("a");',
      "    }",
      "",
      "    static void show(int number) {",
      '        System.out.print("b");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        show(1);",
      "    }",
      "}",
    ],
    choices: [
      "引数名が違うだけでは多重定義にならないためコンパイルエラーになる",
      "コンパイルは成功し、a が出力される",
      "コンパイルは成功し、b が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "オーバーロードを区別する要素は、メソッド名と引数の型・個数・並び順だけです。引数名は呼び出し側から見えないため区別に使えず、同じシグネチャの重複としてエラーになります。呼び出し側は show(1) と書くだけで引数名を指定しないのだから、名前で区別できないのは当然の帰結です。戻り値の型が区別に使えないのも同じ理由で、「呼び出し時に書かれる情報だけが区別の材料になる」と整理して覚えると迷いません。",
  },
  {
    id: 563,
    topic: "methods",
    variantOf: "methods-private-access",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SameClass",
    code: [
      "public class SameClass {",
      "    private int secret = 42;",
      "",
      "    private int reveal() {",
      "        return secret;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        SameClass a = new SameClass();",
      "        SameClass b = new SameClass();",
      "        b.secret = 7;",
      '        System.out.println(a.reveal() + " " + b.reveal());',
      "    }",
      "}",
    ],
    choices: ["42 7", "42 42", "コンパイルエラーになる", "7 7", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "42 7" },
    explanation:
      "private の有効範囲は「同じクラス」であって「同じインスタンス」ではありません。そのため main の中から別インスタンス b の private フィールドにも直接アクセスできます。アクセス制御がクラス単位なのは、equals や compareTo のように同じ型の別インスタンスを内部まで見て比較する実装を書けるようにするためです。もしインスタンス単位だったら、これらのメソッドは公開アクセサを経由せざるを得ず、カプセル化の意味が薄れてしまいます。",
  },
  {
    id: 564,
    topic: "methods",
    variantOf: "methods-static-via-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Shared",
    code: [
      "public class Shared {",
      "    static int counter = 0;",
      "",
      "    public static void main(String[] args) {",
      "        Shared a = new Shared();",
      "        Shared b = new Shared();",
      "        a.counter = 5;",
      "        b.counter++;",
      '        System.out.println(a.counter + " " + Shared.counter);',
      "    }",
      "}",
    ],
    choices: ["6 6", "5 6", "6 5", "1 1", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "6 6" },
    explanation:
      "static フィールドはクラスに 1 つしか存在しないため、どのインスタンス経由で触っても同じ領域を指します。a.counter = 5 のあと b.counter++ で 6 になり、どちらから読んでも 6 です。インスタンス変数経由で static メンバーにアクセスできる構文が許されているせいで、インスタンスごとに値を持つように見えてしまうのがこの誤解の元です。実体は 1 つしかないので、Shared.counter とクラス名で書くのが正しい表現であり、多くの静的解析ツールもそう警告します。",
  },
  {
    id: 565,
    topic: "methods",
    variantOf: "methods-this-shadowing",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Assigned",
    code: [
      "public class Assigned {",
      "    private int x;",
      "",
      "    Assigned(int x) {",
      "        this.x = x;",
      "    }",
      "",
      "    int doubled() {",
      "        int x = this.x * 2;",
      "        return x;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Assigned(5).doubled());",
      "    }",
      "}",
    ],
    choices: ["10", "5", "0", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "10" },
    explanation:
      "this.x はフィールド、単なる x はその時点で有効なローカル変数を指します。コンストラクタでは this.x = x でフィールドへ代入し、doubled ではフィールドを 2 倍した値をローカル変数 x に入れて返しています。名前が重なっても this を付ければ確実にフィールドを指せる、というのが this の役割です。ローカル変数がフィールドを覆い隠す（シャドーイング）規則は「より内側の宣言が優先される」という一般則に従っており、意図的に使えば引数名をフィールド名と揃えられます。",
  },
  {
    id: 566,
    topic: "methods",
    variantOf: "methods-varargs-priority",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Widened",
    code: [
      "public class Widened {",
      '    static void accept(long value) { System.out.print("long"); }',
      "",
      '    static void accept(Integer value) { System.out.print("Integer"); }',
      "",
      "    public static void main(String[] args) {",
      "        int number = 1;",
      "        accept(number);",
      "    }",
      "}",
    ],
    choices: ["long", "Integer", "あいまいなためコンパイルエラーになる", "何も出力されない"],
    correct: [0],
    expected: { kind: "output", stdout: "long" },
    explanation:
      "オーバーロードの解決は「拡大変換 → オートボクシング → 可変長引数」の順で候補を探します。int から long への拡大変換で呼べる accept(long) が先に見つかるため、ボクシングを伴う Integer 版より優先されます。この順序は、オートボクシングが後から言語に追加された際、既存のコードの呼び出し先が変わらないようにするための配慮です。互換性を守るという判断が優先順位として残っている例で、直感的な「より近い型」とは限らない点に注意が必要です。",
  },
  {
    id: 567,
    topic: "methods",
    variantOf: "methods-void-return",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "MissingReturn",
    code: [
      "public class MissingReturn {",
      "    static int classify(int n) {",
      "        if (n > 0) {",
      "            return 1;",
      "        } else if (n < 0) {",
      "            return -1;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(classify(0));",
      "    }",
      "}",
    ],
    choices: [
      "すべての経路で値を返していないためコンパイルエラーになる",
      "コンパイルは成功し、0 が出力される",
      "コンパイルは成功し、1 が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "戻り値のあるメソッドは、すべての実行経路で値を返さなければなりません。n が 0 のときはどちらの条件にも当てはまらず、return に到達しないためコンパイルエラーになります。コンパイラが経路を静的に解析して検出してくれるため、返し忘れが実行時まで残りません。else を付けるか、最後に return 0; を書けば解決します。void のメソッドでは値を伴わない return でいつでも抜けられるのと対照的で、「戻り値の契約は必ず守らせる」という方針が現れています。",
  },
  {
    id: 568,
    topic: "methods",
    variantOf: "methods-final-parameter",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Immutable2",
    code: [
      "public class Immutable2 {",
      "    static int increase(final int value) {",
      "        value = value + 1;",
      "        return value;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(increase(1));",
      "    }",
      "}",
    ],
    choices: [
      "final 引数に再代入しているためコンパイルエラーになる",
      "コンパイルは成功し、2 が出力される",
      "コンパイルは成功し、1 が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 3 },
    explanation:
      "final を付けた引数には再代入できません。引数への代入は呼び出し元に影響しないため実害は無いのですが、読み手が「呼び出し元の値も変わるのでは」と誤解する余地を無くし、メソッド内で意味が変わらないことを保証できます。値を変えたい場合は新しいローカル変数を用意します。なお final は再代入を禁じるだけで、参照型なら指す先のオブジェクトの中身は変更できる点に注意してください。禁止されるのは「参照の差し替え」です。",
  },
  {
    id: 569,
    topic: "methods",
    variantOf: "methods-field-defaults",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "LocalDefault",
    code: [
      "public class LocalDefault {",
      "    public static void main(String[] args) {",
      "        int count;",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: [
      "初期化されていないローカル変数を参照しているためコンパイルエラーになる",
      "コンパイルは成功し、0 が出力される",
      "コンパイルは成功し、null が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "ローカル変数には既定値が与えられず、代入前に読むとコンパイルエラーになります。フィールドが自動的に 0 や null で初期化されるのとは対照的です。この違いは、ローカル変数はメソッド内で使われ方を静的に追跡できるため「初期化漏れ」を確実に検出できるのに対し、フィールドはどの順序でアクセスされるか分からないので安全な既定値を与えるしかない、という事情によります。厳しく検査できる場所では検査し、できない場所では安全側に倒す、という使い分けです。",
  },
  {
    id: 570,
    topic: "methods",
    variantOf: "methods-recursion",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Countdown2",
    code: [
      "public class Countdown2 {",
      "    static String down(int n) {",
      "        if (n == 0) {",
      '            return "go";',
      "        }",
      '        return n + down(n - 1);',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(down(3));",
      "    }",
      "}",
    ],
    choices: ["321go", "123go", "go321", "3go", "実行時に StackOverflowError が発生する"],
    correct: [0],
    expected: { kind: "output", stdout: "321go" },
    explanation:
      "down(3) は 3 + down(2)、down(2) は 2 + down(1) と展開され、基底条件 n == 0 で \"go\" が返ってから順に連結されていきます。結果は 321go です。再帰の展開は「行きに引数を減らし、帰りに結果を組み立てる」という構造で、帰り道での処理順が出力順を決めます。基底条件が無い、あるいは引数が基底へ向かわない場合は StackOverflowError になります。ここでは n が必ず 1 ずつ減るため、有限回で停止することが保証されています。",
  },
  {
    id: 571,
    topic: "methods",
    variantOf: "methods-encapsulation",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Balance",
    code: [
      "public class Balance {",
      "    private int amount = 100;",
      "",
      "    boolean withdraw(int value) {",
      "        if (value > amount) {",
      "            return false;",
      "        }",
      "        amount -= value;",
      "        return true;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Balance b = new Balance();",
      '        System.out.println(b.withdraw(150) + " " + b.withdraw(40) + " " + b.amount);',
      "    }",
      "}",
    ],
    choices: ["false true 60", "true true 60", "false false 100", "true false 60", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false true 60" },
    explanation:
      "残高を超える引き出しは false を返して状態を変えず、範囲内の引き出しだけが反映されるため 100 から 40 を引いて 60 になります。フィールドを private にして操作をメソッドに限定することで、「残高は負にならない」という不変条件をクラス自身が守れます。処理の成否を戻り値で返すか例外にするかは設計判断ですが、いずれにせよ呼び出し側が結果を確認できることが重要です。なお main は同じクラス内なので b.amount を直接読めますが、外部のクラスからは読めません。",
  },
  {
    id: 572,
    topic: "methods",
    variantOf: "methods-protected-access",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Inherited",
    code: [
      "class Ancestor {",
      "    protected String describe() {",
      '        return "ancestor";',
      "    }",
      "}",
      "",
      "public class Inherited extends Ancestor {",
      "    @Override",
      "    public String describe() {",
      '        return "inherited";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Ancestor a = new Inherited();",
      "        System.out.println(a.describe());",
      "    }",
      "}",
    ],
    choices: [
      "inherited",
      "ancestor",
      "アクセス修飾子が異なるためコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "inherited" },
    explanation:
      "オーバーライドではアクセス範囲を広げる方向（protected から public）は許されます。狭めることだけが禁止されており、これは基底型として扱う利用者が呼べなくなるのを防ぐためです。呼び出しは実行時の型で解決されるので inherited が出力されます。可視性を広げてよいのは、基底型を通じて使う人にとって「呼べるものが呼べるまま」だからで、契約は破られません。戻り値を派生型に狭めてよいのと合わせて、「利用者が困らない方向の変更だけ許す」という一貫した基準になっています。",
  },

  // ============================================================ ラムダ (lambda)
  {
    id: 573,
    topic: "lambda",
    variantOf: "lambda-syntax-forms",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "Braced",
    code: [
      "interface Transformer {",
      "    int apply(int value);",
      "}",
      "",
      "public class Braced {",
      "    public static void main(String[] args) {",
      "        Transformer t = value -> { value * 2; };",
      "        System.out.println(t.apply(3));",
      "    }",
      "}",
    ],
    choices: [
      "波括弧を使う場合は return が必要なためコンパイルエラーになる",
      "コンパイルは成功し、6 が出力される",
      "コンパイルは成功し、3 が出力される",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error" },
    explanation:
      "本体を波括弧で囲んだ場合はブロックとして扱われるため、値を返すには return が必要です。また value * 2; のように計算結果を捨てるだけの式は文として成立しないため、その点でもエラーになります。波括弧を省略して value -> value * 2 と書けば、式の値がそのまま戻り値になります。「式なら暗黙に返す、ブロックなら明示的に返す」という区別は、通常のメソッド本体との一貫性を保つための設計です。",
  },
  {
    id: 574,
    topic: "lambda",
    variantOf: "lambda-method-reference",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "StaticRef",
    code: [
      "import java.util.function.Function;",
      "",
      "public class StaticRef {",
      "    public static void main(String[] args) {",
      "        Function<String, Integer> parse = Integer::parseInt;",
      '        System.out.println(parse.apply("12") + 1);',
      "    }",
      "}",
    ],
    choices: ["13", "121", "12", "コンパイルエラーになる", "実行時に NumberFormatException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "13" },
    explanation:
      'Integer::parseInt は static メソッドへの参照で、s -> Integer.parseInt(s) と等価です。戻り値は int ですが、Function の型引数が Integer なのでオートボクシングされます。取り出した 12 に 1 を足すため 13 です（どちらも数値なので連結ではありません）。メソッド参照には static メソッド、特定インスタンスのメソッド、型に属するインスタンスメソッド、コンストラクタの 4 形式があり、いずれも「呼び出す対象を指し示すだけ」という点で共通しています。',
  },
  {
    id: 575,
    topic: "lambda",
    variantOf: "lambda-two-abstract-methods",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "WithDefault",
    code: [
      "interface Calculator2 {",
      "    int apply(int value);",
      "",
      "    default int twice(int value) {",
      "        return apply(apply(value));",
      "    }",
      "}",
      "",
      "public class WithDefault {",
      "    public static void main(String[] args) {",
      "        Calculator2 addOne = value -> value + 1;",
      "        System.out.println(addOne.twice(1));",
      "    }",
      "}",
    ],
    choices: [
      "3",
      "抽象メソッドが 2 つあるためコンパイルエラーになる",
      "2",
      "4",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "3" },
    explanation:
      "default メソッドは実装を持つため抽象メソッドとして数えられません。抽象メソッドは apply の 1 つだけなので関数型インタフェースとして成立し、ラムダ式を代入できます。twice は apply を 2 回適用するので 1 + 1 + 1 で 3 です。default メソッドをいくつ追加しても関数型インタフェースであり続ける、という性質のおかげで、Predicate の negate や Function の andThen のような便利な派生操作を、ラムダで書ける性質を損なわずに提供できています。",
  },
  {
    id: 576,
    topic: "lambda",
    variantOf: "lambda-target-type",
    question: "次のコードをコンパイルした場合の結果はどれか。1つ選びなさい。",
    className: "VarLambda",
    code: [
      "public class VarLambda {",
      "    public static void main(String[] args) {",
      "        var action = () -> System.out.print(\"x\");",
      '        System.out.println("done");',
      "    }",
      "}",
    ],
    choices: [
      "3行目でコンパイルエラーになる",
      "コンパイルは成功し、done が出力される",
      "コンパイルは成功し、xdone が出力される",
      "4行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 3 },
    explanation:
      "var は初期化子から型を推論しますが、ラムダ式自身は型を持たず、代入先の関数型インタフェースによって初めて型が決まります。推論の材料が無いため var との組み合わせはエラーです。同じ理由でメソッド参照や配列初期化子も var では使えません。var が使えるのは「初期化子だけを見れば型が決まる」場合に限られる、という原則で整理できます。ラムダを変数に入れたい場合は Runnable r = () -> ...; のように受け取る型を明示します。",
  },
  {
    id: 577,
    topic: "lambda",
    variantOf: "lambda-name-conflict",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Captured",
    code: [
      "import java.util.function.Supplier;",
      "",
      "public class Captured {",
      "    public static void main(String[] args) {",
      '        String prefix = "value=";',
      "        int number = 5;",
      "        Supplier<String> supplier = () -> prefix + number;",
      "        System.out.println(supplier.get());",
      "    }",
      "}",
    ],
    choices: ["value=5", "value=", "5", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "value=5" },
    explanation:
      "prefix も number も宣言後に再代入されていないため実質的に final とみなされ、ラムダ式から参照できます。引数名と重ならなければ外側の変数をそのまま使えるということです。ラムダは外側のスコープを共有するため、名前が衝突する場合だけがエラーになります。キャプチャされるのは変数そのものではなく宣言時点の値のコピーなので、ラムダを作ったあとで元の変数を変えても（そもそも変えられませんが）結果は変わらない、という一貫性が保たれています。",
  },
];
