import type { Silver17Question } from "../quizTypes";

/**
 * Silver SE 17（1Z0-825-JPN）で新たに出題範囲に入った言語機能の問題（id 21001-）。
 * テキスト・ブロック、switch 式、レコード、instanceof のパターン・マッチング、シール・クラス。
 */
export const java17Questions: Silver17Question[] = [
  // ======================================================= テキスト・ブロック
  {
    id: 21001,
    topic: "datatypes",
    variantOf: "s17-datatypes-textblock-indent",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TextBlock",
    code: [
      "public class TextBlock {",
      "    public static void main(String[] args) {",
      '        String s = """',
      "            Hello",
      "              World",
      '            """;',
      '        System.out.println(s.replace("\\n", "|"));',
      "    }",
      "}",
    ],
    choices: ["Hello|  World|", "Hello|  World", "Hello|World|", "            Hello|              World|", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "Hello|  World|" },
    explanation:
      "テキスト・ブロックでは、各行に共通する先頭の空白（付随的な空白）が取り除かれます。共通の字下げは、内容の行と閉じ側の \"\"\" の行のうち最も字下げが少ないものに合わせて決まるので、Hello の前の空白はすべて消え、World は Hello より深い 2 文字分だけ字下げが残ります。閉じ側の \"\"\" を次の行に置いたため、World の後ろにも改行が入り、末尾に | が付きます。ソースコードの字下げに合わせて書いても文字列に余計な空白が入らないようにするための仕組みで、残したい字下げは相対的な深さで表します。",
  },
  {
    id: 21002,
    topic: "datatypes",
    variantOf: "s17-datatypes-textblock-indent",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TextBlockIndent",
    code: [
      "public class TextBlockIndent {",
      "    public static void main(String[] args) {",
      '        String s = """',
      "                A",
      "                 B",
      '            """;',
      "        System.out.println(s.replace(' ', '.').replace(\"\\n\", \"|\"));",
      "    }",
      "}",
    ],
    choices: ["....A|.....B|", "A|.B|", "A|.B", "....A|.....B", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "....A|.....B|" },
    explanation:
      "取り除かれる共通の字下げは、閉じ側の \"\"\" の行も含めて最も浅い行に合わせて決まります。この例では閉じ側の \"\"\" が内容の行より 4 文字浅い位置にあるため、そこまでの空白だけが取り除かれ、A の前に 4 文字、B の前に 5 文字の空白が残ります。つまり閉じ側の \"\"\" の位置を左に動かすことで、文字列全体に字下げを付けられます。逆に最後の行の末尾に \"\"\" を続けて書くと、末尾に改行が入らず、字下げの基準にも閉じ側の行が使われなくなります。",
  },
  {
    id: 21003,
    topic: "datatypes",
    variantOf: "s17-datatypes-textblock-escape",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TextBlockEscape",
    code: [
      "public class TextBlockEscape {",
      "    public static void main(String[] args) {",
      '        String s = """',
      "            one \\",
      "            two\\s",
      '            three""";',
      '        System.out.println("[" + s.replace("\\n", "|") + "]");',
      "    }",
      "}",
    ],
    choices: ["[one two |three]", "[one two|three]", "[one |two |three]", "[one two\\s|three]", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[one two |three]" },
    explanation:
      "テキスト・ブロックの行末の \\（バックスラッシュ）は改行を打ち消し、次の行とつなげるエスケープです。そのため one の行と two の行が 1 行になり、one の後ろの空白はそのまま残ります。\\s は空白 1 文字を表すエスケープで、行末の空白は通常取り除かれますが、\\s で書いた空白は取り除き処理の後に変換されるので残ります。最後の行の末尾に \"\"\" を続けて書いたため、three の後ろには改行が入りません。長い文字列を読みやすく折り返したい場合や、意図的に行末の空白を残したい場合に使うエスケープです。",
  },
  {
    id: 21004,
    topic: "datatypes",
    variantOf: "s17-datatypes-textblock-literal",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OneLine",
    code: [
      "public class OneLine {",
      "    public static void main(String[] args) {",
      '        String s = """Hello""";',
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["3行目でコンパイルエラーになる", "4行目でコンパイルエラーになる", "Hello", "\"Hello\"", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "compile-error", line: 3 },
    explanation:
      "テキスト・ブロックは、開始の \"\"\" の直後に改行が必要です。開始の \"\"\" と同じ行に内容を書くことはできないため、3行目はコンパイルエラーになります。開始の区切りの後で必ず改行させることで、内容の 1 行目も他の行と同じ字下げの規則で扱えるようにしているのです。1 行で済む文字列は、通常の \"Hello\" という文字列リテラルで書きます。",
  },
  {
    id: 21005,
    topic: "datatypes",
    variantOf: "s17-datatypes-textblock-literal",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TextBlockEquals",
    code: [
      "public class TextBlockEquals {",
      "    public static void main(String[] args) {",
      '        String a = """',
      '            abc""";',
      '        String b = "abc";',
      '        System.out.println((a == b) + " " + a.equals(b));',
      "    }",
      "}",
    ],
    choices: ["true true", "false true", "false false", "true false", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true true" },
    explanation:
      "テキスト・ブロックは新しい型ではなく、String のリテラルを書くための別の構文です。字下げの除去やエスケープの処理はコンパイル時に行われ、結果は通常の文字列リテラルと同じ定数になります。文字列リテラルは同じ内容なら同じインスタンスが共有される（インターンされる）ため、\"abc\" と書いた b と同じオブジェクトを指し、== も true になります。ただし文字列の比較に == を使うのは、このように定数どうしのときに限って偶然成り立つだけなので、内容の比較には equals を使います。",
  },

  // ============================================================== switch 式
  {
    id: 21011,
    topic: "control",
    variantOf: "s17-control-switch-yield",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "YieldTest",
    code: [
      "public class YieldTest {",
      "    public static void main(String[] args) {",
      "        int n = 2;",
      "        int r = switch (n) {",
      "            case 1 -> 10;",
      "            case 2 -> {",
      "                int t = n * 100;",
      "                yield t + 1;",
      "            }",
      "            default -> 0;",
      "        };",
      "        System.out.println(r);",
      "    }",
      "}",
    ],
    choices: ["201", "200", "10", "0", "8行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "201" },
    explanation:
      "switch 式は値を返す switch で、矢印（->）の右側に書いた式の値がそのまま switch 式の値になります。右側に波括弧のブロックを書いた場合は、yield 文で値を返します（ブロックの中の return はメソッドからの復帰になってしまうため、switch 式の値を返すには別のキーワードが必要なのです）。n が 2 なので、ブロック内で t = 200 を計算して yield t + 1 により 201 が r に代入されます。switch 式を使うと、分岐ごとに変数へ代入する書き方と違って代入漏れが起きず、変数を final にもできます。",
  },
  {
    id: 21012,
    topic: "control",
    variantOf: "s17-control-switch-yield",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ColonYield",
    code: [
      "public class ColonYield {",
      "    public static void main(String[] args) {",
      "        int k = 3;",
      "        String s = switch (k) {",
      "            case 1:",
      "            case 2:",
      '                yield "low";',
      "            case 3:",
      '                System.out.print("three ");',
      "            default:",
      '                yield "high";',
      "        };",
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["three high", "three", "high", "three low", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "three high" },
    explanation:
      "switch 式でも、コロン（:）を使う従来の書き方ができます。その場合は switch 文と同じくフォールスルーが起こり、値は yield で返します。k が 3 なので case 3 から実行が始まり、three を出力したあと break も yield も無いまま default に流れ込み、yield \"high\" が switch 式の値になります。矢印の書き方ではフォールスルーが起こらないため、分岐をまたいで処理を共有する必要がない限り、矢印の書き方を使う方が誤りにくくなります。",
  },
  {
    id: 21013,
    topic: "control",
    variantOf: "s17-control-switch-exhaustive",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Exhaustive",
    code: [
      "public class Exhaustive {",
      "    public static void main(String[] args) {",
      "        int n = 3;",
      "        String s = switch (n) {",
      '            case 1 -> "one";',
      '            case 2 -> "two";',
      "        };",
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["4行目でコンパイルエラーになる", "7行目でコンパイルエラーになる", "null", "実行時に例外がスローされる", "何も出力されない"],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "switch 式は必ず値を返さなければならないため、あり得るすべての値を case で網羅している必要があります（網羅性）。int の値は 1 と 2 だけではないので、default が無いこの switch 式は 4行目でコンパイルエラーになります。値を返さない分岐があると、変数に何を代入すべきか決まらないからです。switch 文の場合は網羅していなくても構いませんが、switch 式では default を書くか、enum のようにすべての値を列挙できる型ですべてを case に並べる必要があります。",
  },
  {
    id: 21014,
    topic: "control",
    variantOf: "s17-control-switch-exhaustive",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Seasons",
    code: [
      "public class Seasons {",
      "    enum Season { SPRING, SUMMER, AUTUMN, WINTER }",
      "",
      "    static String feel(Season s) {",
      "        return switch (s) {",
      '            case SPRING, AUTUMN -> "mild";',
      '            case SUMMER -> "hot";',
      '            case WINTER -> "cold";',
      "        };",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(feel(Season.AUTUMN) + " " + feel(Season.WINTER));',
      "    }",
      "}",
    ],
    choices: ["mild cold", "mild mild", "hot cold", "5行目でコンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "mild cold" },
    explanation:
      "enum を対象にした switch 式では、すべての定数を case に並べれば default が無くても網羅しているとみなされ、コンパイルできます。case SPRING, AUTUMN のようにカンマで区切ると、1 つの case に複数の値をまとめられます。default をあえて書かないでおくと、後から enum に定数を追加したときに、網羅していない switch 式をコンパイラがエラーとして教えてくれます。なお、コンパイル後に enum へ定数が追加された場合に備えて、コンパイラは実行時に想定外の値を検出する処理を自動で組み込みます。",
  },
  {
    id: 21015,
    topic: "control",
    variantOf: "s17-control-switch-arrow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ArrowStatement",
    code: [
      "public class ArrowStatement {",
      "    public static void main(String[] args) {",
      "        int x = 1;",
      "        switch (x) {",
      '            case 1 -> System.out.print("A");',
      '            case 2 -> System.out.print("B");',
      '            default -> System.out.print("C");',
      "        }",
      "        System.out.println();",
      "    }",
      "}",
    ],
    choices: ["A", "AB", "ABC", "AC", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "A" },
    explanation:
      "矢印（->）の書き方は switch 式だけでなく、値を返さない switch 文でも使えます。矢印の書き方では、一致した case の右側だけが実行され、次の case に流れ込む（フォールスルーする）ことはありません。そのため x が 1 のとき出力は A だけです。従来のコロンの書き方で break を書き忘れると、後続の case まで実行されてしまう不具合が起きやすかったため、その原因をなくすために導入された構文です。",
  },
  {
    id: 21016,
    topic: "control",
    variantOf: "s17-control-switch-arrow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MixedCase",
    code: [
      "public class MixedCase {",
      "    public static void main(String[] args) {",
      "        int k = 2;",
      "        String s = switch (k) {",
      '            case 1 -> "one";',
      '            case 2: yield "two";',
      '            default -> "other";',
      "        };",
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["6行目でコンパイルエラーになる", "5行目でコンパイルエラーになる", "7行目でコンパイルエラーになる", "two", "other"],
    correct: [0],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "1 つの switch の中で、矢印（->）の case とコロン（:）の case を混在させることはできません。5行目で矢印の書き方を使っているのに、6行目でコロンの書き方を使っているため、6行目でコンパイルエラーになります。矢印はフォールスルーしない、コロンはフォールスルーするという、まったく異なる実行の規則を持つためで、混在を許すとどの case から流れ込むのかが分かりにくくなります。switch ごとに、どちらか一方の書き方にそろえます。",
  },

  // ================================================================== レコード
  {
    id: 21021,
    topic: "classes",
    variantOf: "s17-classes-record-basics",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RecordBasics",
    code: [
      "public class RecordBasics {",
      "    record Point(int x, int y) {}",
      "",
      "    public static void main(String[] args) {",
      "        Point p = new Point(1, 2);",
      "        Point q = new Point(1, 2);",
      '        System.out.println(p.x() + " " + p + " " + p.equals(q) + " " + (p == q));',
      "    }",
      "}",
    ],
    choices: [
      "1 Point[x=1, y=2] true false",
      "1 Point[x=1, y=2] false false",
      "1 Point(1, 2) true false",
      "1 Point[x=1, y=2] true true",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1 Point[x=1, y=2] true false" },
    explanation:
      "レコードは、宣言したコンポーネント（x と y）から、private final のフィールド、全コンポーネントを受け取るコンストラクタ、コンポーネントと同じ名前のアクセサメソッド（getX ではなく x()）、equals・hashCode・toString を自動で生成します。toString は Point[x=1, y=2] の形式で、equals はすべてのコンポーネントが等しければ true を返すので、別々に生成した p と q でも true です。== は参照の比較なので false になります。データを運ぶだけのクラスで、これらを手書きする手間と書き間違いをなくすための機能です。",
  },
  {
    id: 21022,
    topic: "classes",
    variantOf: "s17-classes-record-basics",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RecordAccessor",
    code: [
      "public class RecordAccessor {",
      "    record User(String name) {",
      "        public String name() {",
      "            return name.toUpperCase();",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        User u = new User("ann");',
      '        System.out.println(u.name() + " " + u);',
      "    }",
      "}",
    ],
    choices: ["ANN User[name=ann]", "ANN User[name=ANN]", "ann User[name=ann]", "3行目でコンパイルエラーになる", "4行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ANN User[name=ann]" },
    explanation:
      "レコードのアクセサメソッドは、自分で定義して自動生成のものを置き換えられます（public で、戻り値の型がコンポーネントと同じである必要があります）。ここでは name() が大文字に変換して返すので ANN になります。一方、自動生成される toString はアクセサを呼ばず、フィールドの値を直接使うため、User[name=ann] のままです。アクセサで値を加工すると toString や equals と食い違うことがあるので、値そのものを正規化したい場合はアクセサではなくコンストラクタで行うのが適切です。",
  },
  {
    id: 21023,
    topic: "classes",
    variantOf: "s17-classes-record-members",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RecordFields",
    code: [
      "public class RecordFields {",
      "    record Item(String name, int price) {",
      "        static int count = 0;",
      "        int stock;",
      "",
      "        Item {",
      "            count++;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        new Item("pen", 100);',
      "        System.out.println(Item.count);",
      "    }",
      "}",
    ],
    choices: ["4行目でコンパイルエラーになる", "3行目でコンパイルエラーになる", "6行目でコンパイルエラーになる", "7行目でコンパイルエラーになる", "1"],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "レコードには、コンポーネントから生成されるもの以外のインスタンスフィールドを宣言できません。そのため int stock を宣言した 4行目がコンパイルエラーになります。static フィールドや static メソッド、インスタンスメソッドは自由に追加できるので、3行目の static int count や、コンストラクタで count を増やす処理は問題ありません。レコードの状態はコンポーネントだけで完全に表される、という前提があるからこそ、equals や toString を自動生成できるのです。",
  },
  {
    id: 21024,
    topic: "classes",
    variantOf: "s17-classes-record-members",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RecordFinal",
    code: [
      "public class RecordFinal {",
      "    record Counter(int value) {",
      "        Counter increment() {",
      "            return new Counter(value + 1);",
      "        }",
      "        void reset() {",
      "            value = 0;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Counter(1).increment().value());",
      "    }",
      "}",
    ],
    choices: ["7行目でコンパイルエラーになる", "4行目でコンパイルエラーになる", "12行目でコンパイルエラーになる", "2", "1"],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "レコードのコンポーネントから生成されるフィールドは private final なので、生成後に値を変更することはできず、value = 0 と代入する 7行目がコンパイルエラーになります。値を変えたいときは、4行目の increment() のように新しい値を持つ別のインスタンスを作って返します。レコードは不変（イミュータブル）なデータを表すための型で、不変だからこそ複数の箇所やスレッドで共有しても安全で、HashMap のキーにしても hashCode が変わる心配がありません。",
  },
  {
    id: 21025,
    topic: "classes",
    variantOf: "s17-classes-record-compact",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CompactCtor",
    code: [
      "public class CompactCtor {",
      "    record Range(int lo, int hi) {",
      "        Range {",
      "            if (lo > hi) {",
      "                int t = lo;",
      "                lo = hi;",
      "                hi = t;",
      "            }",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(new Range(5, 2) + " " + new Range(1, 3).hi());',
      "    }",
      "}",
    ],
    choices: [
      "Range[lo=2, hi=5] 3",
      "Range[lo=5, hi=2] 3",
      "6行目でコンパイルエラーになる",
      "3行目でコンパイルエラーになる",
      "実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Range[lo=2, hi=5] 3" },
    explanation:
      "Range { ... } のように引数リストを省略したコンストラクタはコンパクト・コンストラクタと呼ばれ、コンポーネントと同じ名前の引数（lo と hi）を暗黙に受け取ります。本体の中で行うのは引数の検証や正規化で、本体が終わった後に、その時点の引数の値が自動でフィールドに代入されます。そのため引数の lo と hi を入れ替えると、入れ替えた値がフィールドに入り Range[lo=2, hi=5] になります。すべてのフィールドへの代入を書かなくても、値の検証や補正だけを簡潔に書けるようにした仕組みです。",
  },
  {
    id: 21026,
    topic: "classes",
    variantOf: "s17-classes-record-compact",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CompactAssign",
    code: [
      "public class CompactAssign {",
      "    record Range(int lo, int hi) {",
      "        Range {",
      "            if (lo > hi) {",
      "                this.lo = hi;",
      "            }",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Range(5, 2));",
      "    }",
      "}",
    ],
    choices: ["5行目でコンパイルエラーになる", "3行目でコンパイルエラーになる", "Range[lo=2, hi=2]", "Range[lo=5, hi=2]", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "compile-error", line: 5 },
    explanation:
      "コンパクト・コンストラクタの中では、フィールドへの代入（this.lo = ...）は書けません。フィールドへの代入は本体の終了後にコンパイラが自動で行うため、本体の中で代入すると final フィールドへの二重の代入になってしまうからです。そのため 5行目がコンパイルエラーになります。値を補正したい場合は、this を付けずに引数の lo へ代入すれば、その値が最終的にフィールドへ入ります。",
  },
  {
    id: 21027,
    topic: "classes",
    variantOf: "s17-classes-record-restrictions",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FinalRecord",
    code: [
      "public class FinalRecord {",
      "    interface Shape {",
      "        double area();",
      "    }",
      "",
      "    record Square(double side) implements Shape {",
      "        public double area() {",
      "            return side * side;",
      "        }",
      "    }",
      "",
      "    static class BigSquare extends Square {",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Square(3).area());",
      "    }",
      "}",
    ],
    choices: ["12行目でコンパイルエラーになる", "6行目でコンパイルエラーになる", "7行目でコンパイルエラーになる", "9.0", "9"],
    correct: [0],
    expected: { kind: "compile-error", line: 12 },
    explanation:
      "レコードは暗黙に final であり、他のクラスから継承することはできないため、Square を extends した 12行目がコンパイルエラーになります。一方、インタフェースを implements することはできるので、6行目の Square implements Shape は問題ありません。レコードは java.lang.Record を暗黙に継承しているので、extends で別のクラスを継承することもできません。サブクラスで状態を追加されると、コンポーネントだけで等しさを判定する equals の前提が崩れてしまうため、継承を禁じているのです。",
  },
  {
    id: 21028,
    topic: "classes",
    variantOf: "s17-classes-record-restrictions",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AccessorModifier",
    code: [
      "public class AccessorModifier {",
      "    record User(String name) {",
      "        String name() {",
      "            return name;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(new User("ann").name());',
      "    }",
      "}",
    ],
    choices: ["3行目でコンパイルエラーになる", "2行目でコンパイルエラーになる", "9行目でコンパイルエラーになる", "ann", "null"],
    correct: [0],
    expected: { kind: "compile-error", line: 3 },
    explanation:
      "レコードのアクセサメソッドを自分で定義する場合は、public にしなければなりません。3行目の name() はアクセス修飾子が無い（パッケージ・アクセスの）ためコンパイルエラーになります。アクセサはレコードの公開された状態を読み出すためのもので、自動生成されるアクセサも public なので、明示的に定義したものだけ公開範囲を狭めることはできないのです。戻り値の型もコンポーネントと同じでなければならず、throws 節も付けられません。",
  },

  // ============================================= instanceof のパターン・マッチング
  {
    id: 21031,
    topic: "classes",
    variantOf: "s17-classes-pattern-scope",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PatternAnd",
    code: [
      "public class PatternAnd {",
      "    public static void main(String[] args) {",
      '        Object o = "hello";',
      "        if (o instanceof String s && s.length() > 3) {",
      "            System.out.println(s.toUpperCase());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["HELLO", "hello", "何も出力されない", "4行目でコンパイルエラーになる", "5行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "HELLO" },
    explanation:
      "instanceof のパターン・マッチングでは、o instanceof String s のように型の後に変数名を書くと、判定が true のときにキャスト済みの値がパターン変数 s に入ります。&& の右側は左側が true のときにだけ評価されるので、s を安全に使えます。if の本体も判定が true のときにだけ実行されるため、s を String として使えます。「instanceof で確認してからキャストする」という定型の 2 段階を 1 つにまとめ、キャストの書き忘れや型の取り違えを防ぐための機能です。",
  },
  {
    id: 21032,
    topic: "classes",
    variantOf: "s17-classes-pattern-scope",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PatternOr",
    code: [
      "public class PatternOr {",
      "    public static void main(String[] args) {",
      '        Object o = "hello";',
      "        if (o instanceof String s || s.isEmpty()) {",
      '            System.out.println("match");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["4行目でコンパイルエラーになる", "5行目でコンパイルエラーになる", "match", "何も出力されない", "実行時に NullPointerException がスローされる"],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "パターン変数は、判定が確実に true である箇所でしか使えません（フロー・スコープ）。|| の右側は、左側が false のとき、つまり o が String ではなかったときに評価されるので、そこでは s に値が入っていません。そのため || の右側で s を使った 4行目はコンパイルエラーになります。&& なら右側は左側が true のときだけ評価されるので使えます。パターン変数がどこで使えるかは、コンパイラが条件の真偽の流れから判断しています。",
  },
  {
    id: 21033,
    topic: "classes",
    variantOf: "s17-classes-pattern-scope",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlowScope",
    code: [
      "public class FlowScope {",
      "    static int len(Object o) {",
      "        if (!(o instanceof String s)) {",
      "            return -1;",
      "        }",
      "        return s.length();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(len(42) + " " + len("abc"));',
      "    }",
      "}",
    ],
    choices: ["-1 3", "-1 -1", "3 3", "6行目でコンパイルエラーになる", "実行時に ClassCastException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "-1 3" },
    explanation:
      "パターン変数のスコープは、if の本体だけでなく、条件の真偽の流れによって広がることがあります。ここでは「String でなければ return する」ので、if 文の後ろに到達したときには o が必ず String だと分かり、6行目でも s を使えます。len(42) は String ではないので -1、len(\"abc\") は 3 を返します。条件を満たさない場合を先に return で抜ける書き方（早期リターン）と組み合わせると、正常系の処理を入れ子にせずに書けます。",
  },
  {
    id: 21034,
    topic: "classes",
    variantOf: "s17-classes-pattern-subtype",
    question: "次のコードを Java SE 17 でコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SameType",
    code: [
      "public class SameType {",
      "    public static void main(String[] args) {",
      '        String text = "java";',
      "        if (text instanceof String s) {",
      "            System.out.println(s.length());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["4行目でコンパイルエラーになる", "5行目でコンパイルエラーになる", "4", "何も出力されない", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "Java SE 17 の instanceof のパターン・マッチングでは、判定する式の型がパターンの型と同じ（またはそのサブタイプ）だとコンパイルエラーになります。text は宣言時点で String と分かっているので、text instanceof String s は null でない限り必ず true となり、判定する意味が無いからです。パターン・マッチングは「実行時に型が分からない値を、型ごとに振り分ける」ための機能であり、必ず成り立つ判定は書き間違いとみなされます（この制限は Java SE 21 で緩和されました）。",
  },

  // ================================================================ シール・クラス
  {
    id: 21041,
    topic: "inheritance",
    variantOf: "s17-inheritance-sealed-permits",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SealedShapes",
    code: [
      "public class SealedShapes {",
      "    sealed interface Shape permits Circle, Square {}",
      "    static final class Circle implements Shape {}",
      "    static non-sealed class Square implements Shape {}",
      "    static class Cube extends Square {}",
      "    static final class Triangle implements Shape {}",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println("ok");',
      "    }",
      "}",
    ],
    choices: ["6行目でコンパイルエラーになる", "5行目でコンパイルエラーになる", "4行目でコンパイルエラーになる", "2行目でコンパイルエラーになる", "ok"],
    correct: [0],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "sealed を付けたクラスやインタフェースは、permits に列挙した型だけが継承・実装できます。Triangle は permits に含まれていないため、Shape を実装した 6行目がコンパイルエラーになります。Square は non-sealed と宣言しているので、その先は制限が解除され、Cube のように自由に継承できます。継承できる型をあらかじめ限定することで、「Shape は Circle か Square のどちらか」と型の種類を閉じた集合として扱え、分岐の漏れをコンパイラが確かめられるようになります。",
  },
  {
    id: 21042,
    topic: "inheritance",
    variantOf: "s17-inheritance-sealed-permits",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SealedModifier",
    code: [
      "public class SealedModifier {",
      "    abstract static sealed class Vehicle permits Car, Bike {}",
      "    static final class Car extends Vehicle {}",
      "    static class Bike extends Vehicle {}",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println("ok");',
      "    }",
      "}",
    ],
    choices: ["4行目でコンパイルエラーになる", "2行目でコンパイルエラーになる", "3行目でコンパイルエラーになる", "ok", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "シール・クラスを直接継承するクラスは、final・sealed・non-sealed のいずれかを必ず宣言しなければなりません。Bike にはどれも付いていないため、4行目がコンパイルエラーになります。final ならそこで継承が止まり、sealed ならさらに permits で継承先を限定し、non-sealed なら制限を解除して誰でも継承できるようにします。どれかを明示させることで、継承の制限がどこまで続くのかを、宣言を見るだけで判断できるようにしているのです。",
  },
  {
    id: 21043,
    topic: "inheritance",
    variantOf: "s17-inheritance-sealed-record",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SealedRecords",
    code: [
      "public class SealedRecords {",
      "    sealed interface Shape {}",
      "    record Circle(double r) implements Shape {}",
      "    record Rect(double w, double h) implements Shape {}",
      "",
      "    static double area(Shape s) {",
      "        if (s instanceof Circle c) {",
      "            return 3 * c.r() * c.r();",
      "        } else if (s instanceof Rect r) {",
      "            return r.w() * r.h();",
      "        }",
      "        return 0;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(area(new Circle(2)) + " " + area(new Rect(2, 3)));',
      "    }",
      "}",
    ],
    choices: ["12.0 6.0", "12 6", "0.0 0.0", "2行目でコンパイルエラーになる", "3行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "12.0 6.0" },
    explanation:
      "シール・クラス（インタフェース）とそのサブクラスが同じソースファイルにある場合は、permits を省略でき、そのファイル内で継承・実装している型が許可されたものとみなされます。レコードは暗黙に final なので、final・sealed・non-sealed を書かなくても許可されたサブクラスの条件を満たします。area は instanceof のパターン・マッチングで型ごとに処理を分け、Circle(2) は 3 × 2 × 2 = 12.0、Rect(2, 3) は 6.0 を返します（戻り値は double なので小数で表示されます）。シール・インタフェースとレコードを組み合わせると、取りうる形の種類が限られたデータを簡潔に表せます。",
  },
];
