import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: コレクションとジェネリクスの追加問題（id 10125-10199）。
 * ナビゲーション可能なコレクション、equals / hashCode、Map の更新メソッド、境界付き型パラメータなど。
 */
export const goldCollectionsQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ 変更不可コレクションと null
  {
    id: 10125,
    topic: "collections",
    variantOf: "gold-collections-null-element",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NullElement",
    code: [
      "import java.util.*;",
      "",
      "public class NullElement {",
      "    public static void main(String[] args) {",
      "        List<String> a = new ArrayList<>();",
      "        a.add(null);",
      "        a.add(\"x\");",
      "        System.out.print(a + \" \");",
      "        List<String> b = List.copyOf(a);",
      "        System.out.println(b);",
      "    }",
      "}",
    ],
    choices: [
      "[null, x] と出力された後、NullPointerException がスローされる",
      "[null, x] [null, x]",
      "[null, x] [x]",
      "6行目で NullPointerException がスローされる",
      "9行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "[null, x]" },
    explanation:
      "ArrayList は null を要素として持てるので、a は [null, x] と出力されます。一方 List.of / List.copyOf / Set.of / Map.of などが作る変更不可コレクションは null の要素を一切受け付けず、List.copyOf に null を含むリストを渡すと NullPointerException がスローされます。null を「値が無い」の意味で紛れ込ませると、contains や indexOf の結果があいまいになり不具合の温床になるため、新しい変更不可コレクションは最初から null を締め出す設計になっています。既存のリストをコピーする箇所で突然例外になることがあるので、null が入りうるデータでは Collections.unmodifiableList などを使うか、先に null を取り除きます。",
  },
  {
    id: 10126,
    topic: "collections",
    variantOf: "gold-collections-null-element",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ContainsNull",
    code: [
      "import java.util.*;",
      "",
      "public class ContainsNull {",
      "    public static void main(String[] args) {",
      "        List<String> a = new ArrayList<>(List.of(\"x\", \"y\"));",
      "        List<String> b = List.of(\"x\", \"y\");",
      "        System.out.print(a.contains(null) + \" \");",
      "        System.out.println(b.contains(null));",
      "    }",
      "}",
    ],
    choices: [
      "false と出力された後、NullPointerException がスローされる",
      "false false",
      "7行目で NullPointerException がスローされる",
      "false true",
      "8行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "false" },
    explanation:
      "ArrayList.contains(null) は要素に null が無いので false を返します。List.of で作った変更不可のリストは、null を要素に持てないだけでなく、contains や indexOf に null を渡した時点で NullPointerException をスローします（Collection の仕様は、要素として受け付けない値を問い合わせたときに例外をスローすることを実装に認めています）。null が入り得ないコレクションに null を問い合わせるのは呼び出し側の誤りである可能性が高いので、黙って false を返すより早く失敗させる方針が取られています。ArrayList から List.of に書き換えただけで例外が出るようになることがあるので注意が必要です。",
  },

  // ------------------------------------------------------------ Arrays.asList
  {
    id: 10127,
    topic: "collections",
    variantOf: "gold-collections-arrays-aslist",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AsListView",
    code: [
      "import java.util.*;",
      "",
      "public class AsListView {",
      "    public static void main(String[] args) {",
      "        String[] array = {\"a\", \"b\", \"c\"};",
      "        List<String> list = Arrays.asList(array);",
      "        array[0] = \"x\";",
      "        list.set(2, \"z\");",
      "        System.out.println(list + \" \" + array[2]);",
      "    }",
      "}",
    ],
    choices: ["[x, b, z] z", "[a, b, z] c", "[x, b, z] c", "[a, b, z] z", "実行時に UnsupportedOperationException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[x, b, z] z" },
    explanation:
      "Arrays.asList は配列をコピーせず、元の配列をそのまま裏側の記憶領域として使う固定長のリストを返します。そのため配列への書き込み（array[0] = \"x\"）はリストから見え、リストへの set は配列に反映されます。要素数を変える add / remove は配列の長さを変えられないので UnsupportedOperationException になりますが、置き換えの set は許されます。配列をリストとして扱うための「窓」であってコピーではない、と理解しておくと、思わぬところで元の配列が書き換わるバグを避けられます。",
  },
  {
    id: 10128,
    topic: "collections",
    variantOf: "gold-collections-arrays-aslist",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AsListPrimitive",
    code: [
      "import java.util.*;",
      "",
      "public class AsListPrimitive {",
      "    public static void main(String[] args) {",
      "        int[] nums = {1, 2, 3};",
      "        Integer[] boxed = {1, 2, 3};",
      "        System.out.println(Arrays.asList(nums).size() + \" \" + Arrays.asList(boxed).size());",
      "    }",
      "}",
    ],
    choices: ["1 3", "3 3", "3 1", "7行目でコンパイルエラーになる", "実行時に ClassCastException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 3" },
    explanation:
      "Arrays.asList(T... a) は可変長引数で、型パラメータ T には参照型しか入りません。int[] を渡すと、int は T になれないため「int[] という 1 つのオブジェクト」が T として扱われ、要素が 1 つの List<int[]> になります。Integer[] ならその配列がそのまま可変長引数の配列として使われ、要素 3 つの List<Integer> になります。ジェネリクスがプリミティブ型を扱えない制約がここに表れており、int 配列をリストにしたいときは IntStream.of(nums).boxed().toList() のように明示的にボクシングします。",
  },

  // ------------------------------------------------------------ NavigableSet / NavigableMap
  {
    id: 10129,
    topic: "collections",
    variantOf: "gold-collections-navigable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NavigateTest",
    code: [
      "import java.util.*;",
      "",
      "public class NavigateTest {",
      "    public static void main(String[] args) {",
      "        TreeSet<Integer> set = new TreeSet<>(List.of(10, 20, 30, 40));",
      "        System.out.println(set.floor(20) + \" \" + set.lower(20) + \" \"",
      "                + set.ceiling(25) + \" \" + set.higher(40));",
      "    }",
      "}",
    ],
    choices: [
      "20 10 30 null",
      "10 10 30 null",
      "20 10 20 40",
      "20 20 30 null",
      "実行時に NoSuchElementException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "20 10 30 null" },
    explanation:
      "NavigableSet の 4 つのメソッドは、指定した値に最も近い要素を返します。floor は「以下」で最大（20 自身を含むので 20）、lower は「より小さい」で最大（10）、ceiling は「以上」で最小（25 以上なので 30）、higher は「より大きい」で最小です。40 より大きい要素は無いので higher(40) は例外ではなく null を返します。等しい値を含むかどうか（floor/ceiling は含む、lower/higher は含まない）が区別の要点で、範囲検索やしきい値の判定を自前のループで書かずに済みます。",
  },
  {
    id: 10130,
    topic: "collections",
    variantOf: "gold-collections-navigable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SubMapTest",
    code: [
      "import java.util.*;",
      "",
      "public class SubMapTest {",
      "    public static void main(String[] args) {",
      "        TreeMap<Integer, String> map = new TreeMap<>();",
      "        map.put(1, \"a\");",
      "        map.put(3, \"c\");",
      "        map.put(5, \"e\");",
      "        map.put(7, \"g\");",
      "        SortedMap<Integer, String> head = map.headMap(5);",
      "        map.put(2, \"b\");",
      "        System.out.println(head + \" \" + map.tailMap(5).size());",
      "    }",
      "}",
    ],
    choices: [
      "{1=a, 2=b, 3=c} 2",
      "{1=a, 3=c} 2",
      "{1=a, 3=c, 5=e} 2",
      "{1=a, 2=b, 3=c} 1",
      "実行時に ConcurrentModificationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{1=a, 2=b, 3=c} 2" },
    explanation:
      "headMap(5) は 5 より小さいキー（5 自身は含まない）、tailMap(5) は 5 以上のキー（5 を含む）の部分を返します。これらはコピーではなく元のマップのビューなので、後から元のマップに追加した 2=b も範囲内であれば head に現れます。tailMap(5) は 5=e と 7=g の 2 件です。ビューを反復している最中でなければ元のマップを変更しても例外にはなりません。「下限は含み、上限は含まない」半開区間の規則は subList や subMap とも共通なので、境界を誤ると 1 件ずれるバグになります。",
  },

  // ------------------------------------------------------------ equals / hashCode
  {
    id: 10131,
    topic: "collections",
    variantOf: "gold-collections-hashcode",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PointSet",
    code: [
      "import java.util.*;",
      "",
      "public class PointSet {",
      "    static class Point {",
      "        final int x, y;",
      "        Point(int x, int y) { this.x = x; this.y = y; }",
      "        @Override",
      "        public boolean equals(Object o) {",
      "            return o instanceof Point p && p.x == x && p.y == y;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Set<Point> set = new HashSet<>();",
      "        set.add(new Point(1, 2));",
      "        set.add(new Point(1, 2));",
      "        List<Point> list = new ArrayList<>(set);",
      "        System.out.println(set.size() + \" \" + list.contains(new Point(1, 2)));",
      "    }",
      "}",
    ],
    choices: ["2 true", "1 true", "2 false", "1 false", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 true" },
    explanation:
      "HashSet はまず hashCode で格納先のバケットを決め、同じバケットの中でだけ equals で重複を判定します。Point は equals だけをオーバーライドし hashCode は Object のまま（通常はインスタンスごとに異なる値）なので、等しいはずの 2 つの Point が別のバケットに入り、重複と判定されずに 2 件になります。一方 ArrayList.contains は hashCode を使わず equals だけで先頭から比べるので true になります。「equals が true なら hashCode も等しい」という規約を破ると、ハッシュを使うコレクションだけが壊れるため、equals をオーバーライドしたら hashCode も必ずオーバーライドします（record ならこの両方が自動生成されます）。",
  },
  {
    id: 10132,
    topic: "collections",
    variantOf: "gold-collections-hashcode",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MutableKey",
    code: [
      "import java.util.*;",
      "",
      "public class MutableKey {",
      "    public static void main(String[] args) {",
      "        List<String> key = new ArrayList<>(List.of(\"a\"));",
      "        Map<List<String>, Integer> map = new HashMap<>();",
      "        map.put(key, 1);",
      "        key.add(\"b\");",
      "        System.out.println(map.get(key) + \" \" + map.size());",
      "    }",
      "}",
    ],
    choices: ["null 1", "1 1", "null 0", "1 2", "実行時に ConcurrentModificationException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "null 1" },
    explanation:
      "List の hashCode は要素から計算されるので、キーとして登録した後に要素を追加すると hashCode が変わります。HashMap は登録時の hashCode に基づくバケットにエントリを置いたままなので、get(key) では新しい hashCode のバケットを探しに行き、見つからずに null を返します。エントリ自体は残っているので size は 1 です。ハッシュを使うコレクションは「キーの equals / hashCode が格納中に変わらない」ことを前提にしているため、キーには String や record のような不変のオブジェクトを使うのが原則です。",
  },

  // ------------------------------------------------------------ Map の更新メソッド
  {
    id: 10133,
    topic: "collections",
    variantOf: "gold-collections-map-compute",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ComputeTest",
    code: [
      "import java.util.*;",
      "",
      "public class ComputeTest {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> count = new TreeMap<>();",
      "        for (String w : List.of(\"a\", \"b\", \"a\", \"c\", \"a\")) {",
      "            count.compute(w, (k, v) -> v == null ? 1 : v + 1);",
      "        }",
      "        count.compute(\"b\", (k, v) -> null);",
      "        count.replaceAll((k, v) -> v * 10);",
      "        System.out.println(count);",
      "    }",
      "}",
    ],
    choices: [
      "{a=30, c=10}",
      "{a=30, b=0, c=10}",
      "{a=3, c=1}",
      "{a=30, b=null, c=10}",
      "実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{a=30, c=10}" },
    explanation:
      "compute は、キーがあってもなくても関数を呼び、現在の値（無ければ null）から新しい値を計算して登録します。v == null ? 1 : v + 1 と書くと「初出なら 1、既出なら 1 増やす」という出現回数の集計になり、a=3, b=1, c=1 になります。関数が null を返すとエントリは削除されるので、b は消えます（null が値として格納されるわけではありません）。replaceAll はすべてのエントリの値を関数で置き換えるので、a=30, c=10 です。get と put を組み合わせる集計を 1 つのメソッドで書けるうえ、ConcurrentHashMap では compute が原子的に実行されるので並行処理でも更新が失われません。",
  },
  {
    id: 10134,
    topic: "collections",
    variantOf: "gold-collections-map-compute",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "GroupWords",
    code: [
      "import java.util.*;",
      "",
      "public class GroupWords {",
      "    public static void main(String[] args) {",
      "        Map<Integer, List<String>> byLength = new TreeMap<>();",
      "        for (String w : List.of(\"cat\", \"ox\", \"dog\", \"hen\", \"yak\")) {",
      "            byLength.computeIfAbsent(w.length(), k -> new ArrayList<>()).add(w);",
      "        }",
      "        int r = byLength.putIfAbsent(2, List.of(\"ant\")) == null ? 0 : 1;",
      "        System.out.println(byLength + \" \" + r);",
      "    }",
      "}",
    ],
    choices: [
      "{2=[ox], 3=[cat, dog, hen, yak]} 1",
      "{2=[ant], 3=[cat, dog, hen, yak]} 1",
      "{2=[ox], 3=[cat, dog, hen, yak]} 0",
      "{2=[ox, ant], 3=[cat, dog, hen, yak]} 1",
      "{2=[ox], 3=[yak]} 1",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{2=[ox], 3=[cat, dog, hen, yak]} 1" },
    explanation:
      "computeIfAbsent はキーが無いときに関数で値を作って登録し、登録済みの値（既にあればその値）を返します。そのため戻り値のリストに add すると、「無ければ空のリストを作ってから追加する」というグループ化を 1 行で書けます。長さ 3 の単語はすべて同じリストに追加されます。putIfAbsent はキーが既にあれば何もせず既存の値を返すので、キー 2 の値は [ox] のままで戻り値は null ではなく r は 1 です。get → null チェック → put の 3 手順を 1 つのメソッドにまとめられるうえ、ConcurrentHashMap ではこれが原子的に行われる利点もあります。",
  },

  // ------------------------------------------------------------ 境界付き型パラメータ
  {
    id: 10135,
    topic: "collections",
    variantOf: "gold-collections-bounded-type",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "MaxFinder",
    code: [
      "import java.util.*;",
      "",
      "public class MaxFinder {",
      "    static <T extends Comparable<T>> T max(List<T> list) {",
      "        T best = list.get(0);",
      "        for (T t : list) {",
      "            if (t.compareTo(best) > 0) best = t;",
      "        }",
      "        return best;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(max(List.of(3, 9, 4)));",
      "        System.out.println(max(List.of(\"b\", \"a\")));",
      "        System.out.println(max(List.of(new Object())));",
      "    }",
      "}",
    ],
    choices: [
      "15行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
      "14行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 15 },
    explanation:
      "<T extends Comparable<T>> は「T は自分自身と比較できる型でなければならない」という境界です。境界があるので、メソッドの中では T の値に対して compareTo を呼べます（7行目）。Integer と String は Comparable を実装しているので 13・14行目は問題ありませんが、Object は Comparable ではないため、15行目では T を推論できずコンパイルエラーになります。型パラメータに境界を付けると「メソッドの中で使える操作」と「呼び出し側が渡せる型」がセットで決まり、比較できない型を渡す誤りを実行前に検出できます。",
  },
  {
    id: 10136,
    topic: "collections",
    variantOf: "gold-collections-bounded-type",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SumNumbers",
    code: [
      "import java.util.*;",
      "",
      "public class SumNumbers {",
      "    static <T extends Number> double sum(List<T> list) {",
      "        double total = 0;",
      "        for (T n : list) total += n.doubleValue();",
      "        return total;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Integer> ints = List.of(1, 2);",
      "        List<Double> doubles = List.of(0.5, 1.5);",
      "        System.out.println(sum(ints) + sum(doubles));",
      "    }",
      "}",
    ],
    choices: ["5.0", "5", "32.0", "13行目でコンパイルエラーになる", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "5.0" },
    explanation:
      "<T extends Number> と境界を付けているので、T 型の変数に対して Number のメソッド doubleValue() を呼べます。List<Integer> でも List<Double> でも T がそれぞれ Integer・Double と推論されて呼び出せ、3.0 + 2.0 = 5.0 になります。sum は double を返すので、+ は文字列連結ではなく数値の加算です。境界の無い <T> だと T は Object として扱われ doubleValue() を呼べないため、境界は「型を制限する」だけでなく「その型の機能を使えるようにする」ためのものでもあります。",
  },

  // ------------------------------------------------------------ ワイルドカードの読み書き
  {
    id: 10137,
    topic: "collections",
    variantOf: "gold-collections-unbounded-wildcard",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "UnknownList",
    code: [
      "import java.util.*;",
      "",
      "public class UnknownList {",
      "    static int grow(List<?> list) {",
      "        Object first = list.get(0);",
      "        list.add(null);",
      "        list.add(\"x\");",
      "        return list.size();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(grow(new ArrayList<>(List.of(1, 2))));",
      "    }",
      "}",
    ],
    choices: [
      "7行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "List<?>（非境界ワイルドカード）は「何かの型の要素を持つリスト」で、実体は List<Integer> かもしれないし List<String> かもしれません。取り出した要素は必ず Object として扱えるので5行目は問題なく、null はどんな参照型の要素にもなれるので6行目の add(null) も許されます。しかし実体の要素型が分からない以上、String を入れても安全とは言えないため、7行目がコンパイルエラーになります（実体の List<Integer> に String が紛れ込むのを防いでいます）。要素の型に依存しない処理（件数を数える、要素を読むだけ）を書くときに、List<?> は List<Object> より多くのリストを受け付けられます。List<Object> の引数には List<Integer> を渡せない点との違いが要点です。",
  },
  {
    id: 10138,
    topic: "collections",
    variantOf: "gold-collections-super-wildcard",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CopyTest",
    code: [
      "import java.util.*;",
      "",
      "public class CopyTest {",
      "    static <T> void copy(List<? extends T> src, List<? super T> dest) {",
      "        for (T t : src) dest.add(t);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Integer> ints = List.of(1, 2);",
      "        List<Number> nums = new ArrayList<>(List.of(0.5));",
      "        List<Object> objs = new ArrayList<>();",
      "        copy(ints, nums);",
      "        copy(nums, objs);",
      "        System.out.println(objs);",
      "    }",
      "}",
    ],
    choices: ["[0.5, 1, 2]", "[1, 2]", "[0.5]", "13行目でコンパイルエラーになる", "12行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[0.5, 1, 2]" },
    explanation:
      "copy は「T かそのサブタイプを読み出せるリスト」から「T かそのスーパータイプを書き込めるリスト」へ要素を移します。12行目は T = Integer（または Number）として List<Integer> から List<Number> へコピーでき、nums は [0.5, 1, 2] になります。13行目は T = Number（または Object）として List<Number> から List<Object> へコピーできます。引数を List<T> 同士にすると両方の型が完全に一致しなければ呼べませんが、ワイルドカードで読み出し側・書き込み側に幅を持たせると、互換性のある型の組み合わせを広く受け付けられます。Collections.copy もこの形で宣言されています。",
  },

  // ------------------------------------------------------------ Comparable
  {
    id: 10139,
    topic: "collections",
    variantOf: "gold-collections-comparable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ReversedOrder",
    code: [
      "import java.util.*;",
      "",
      "public class ReversedOrder {",
      "    record Score(int v) implements Comparable<Score> {",
      "        public int compareTo(Score o) { return Integer.compare(o.v, v); }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Score> list = new ArrayList<>(List.of(new Score(2), new Score(5), new Score(3)));",
      "        list.sort(null);",
      "        System.out.println(list.get(0).v() + \" \" + list.get(2).v() + \" \" + Collections.max(list).v());",
      "    }",
      "}",
    ],
    choices: ["5 2 2", "2 5 5", "5 2 5", "2 5 2", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "5 2 2" },
    explanation:
      "List.sort に null を渡すと、Comparator の代わりに要素の自然順序（Comparable の compareTo）で並べ替えます。この Score の compareTo は引数と自分を逆にして比べているので、値の大きいものほど「小さい」とみなされ、並びは 5, 3, 2 になります。Collections.max も自然順序で「最大」の要素を返すので、数値としては最小の 2 が返ります。自然順序は「数値の大小」ではなく compareTo が定める順序そのものであり、max / min / TreeSet / sort のすべてがそれに従います。自然順序を逆向きに定義すると利用者が混乱するので、降順が必要なら Comparator.reverseOrder() などで呼び出し側が指定するのが一般的です。",
  },
  {
    id: 10140,
    topic: "collections",
    variantOf: "gold-collections-treeset-comparator",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Version",
    code: [
      "import java.util.*;",
      "",
      "public class Version implements Comparable<Version> {",
      "    final int major, minor;",
      "    Version(int major, int minor) { this.major = major; this.minor = minor; }",
      "",
      "    public int compareTo(Version o) {",
      "        return Integer.compare(major, o.major);",
      "    }",
      "",
      "    public String toString() { return major + \".\" + minor; }",
      "",
      "    public static void main(String[] args) {",
      "        Set<Version> set = new TreeSet<>();",
      "        set.add(new Version(2, 0));",
      "        set.add(new Version(1, 5));",
      "        set.add(new Version(2, 1));",
      "        System.out.println(set);",
      "    }",
      "}",
    ],
    choices: ["[1.5, 2.0]", "[1.5, 2.0, 2.1]", "[1.5, 2.1]", "[2.0, 1.5, 2.1]", "実行時に ClassCastException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[1.5, 2.0]" },
    explanation:
      "TreeSet は equals ではなく compareTo（または Comparator）の結果が 0 かどうかで重複を判定します。この compareTo は major だけを比べるので、2.0 と 2.1 は「等しい」とみなされ、後から追加した 2.1 は追加されません。compareTo が 0 を返す組み合わせと equals が true になる組み合わせが一致しない（equals と整合しない）順序を使うと、HashSet と TreeSet で同じ要素を入れても件数が変わるという不整合が起きます。比較に使うフィールドは、同一性を決めるフィールドをすべて含めるのが安全です。",
  },

  // ------------------------------------------------------------ Queue と PriorityQueue
  {
    id: 10141,
    topic: "collections",
    variantOf: "gold-collections-priority-queue",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PriorityTest",
    code: [
      "import java.util.*;",
      "",
      "public class PriorityTest {",
      "    public static void main(String[] args) {",
      "        Queue<String> q = new PriorityQueue<>(Comparator.comparing(String::length).reversed());",
      "        q.offer(\"bb\");",
      "        q.offer(\"a\");",
      "        q.offer(\"cccc\");",
      "        q.offer(\"ddd\");",
      "        StringBuilder sb = new StringBuilder();",
      "        while (!q.isEmpty()) sb.append(q.poll()).append(\" \");",
      "        System.out.println(sb.toString().trim());",
      "    }",
      "}",
    ],
    choices: ["cccc ddd bb a", "bb a cccc ddd", "a bb ddd cccc", "a bb cccc ddd", "5行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "cccc ddd bb a" },
    explanation:
      "PriorityQueue は追加順ではなく、比較順で「先頭（最小）」の要素から取り出すキューです。ここでは文字列長の比較を reversed() で逆にしているので、長い文字列ほど「小さい」とみなされ、poll は長い順に cccc、ddd、bb、a を返します。なお PriorityQueue の toString や拡張 for 文での反復は内部のヒープ配列の順になり、並んだ順序は保証されません。優先度順に処理したいときは、必ず poll で 1 つずつ取り出します。",
  },
  {
    id: 10142,
    topic: "collections",
    variantOf: "gold-collections-priority-queue",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "EmptyQueue",
    code: [
      "import java.util.*;",
      "",
      "public class EmptyQueue {",
      "    public static void main(String[] args) {",
      "        Queue<Integer> q = new PriorityQueue<>();",
      "        System.out.print(q.poll() + \" \");",
      "        System.out.print(q.peek() + \" \");",
      "        System.out.println(q.remove());",
      "    }",
      "}",
    ],
    choices: [
      "null null と出力された後、NoSuchElementException がスローされる",
      "null null null",
      "6行目で NoSuchElementException がスローされる",
      "0 0 0",
      "null と出力された後、NoSuchElementException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NoSuchElementException", stdout: "null null" },
    explanation:
      "Queue の操作は、失敗したときに特別な値を返すものと例外をスローするものが対になっています。取り出しの poll と参照の peek は、キューが空なら null を返します。一方 remove（取り出し）と element（参照）は空なら NoSuchElementException をスローします。追加も同様で、容量制限のあるキューでは offer が false を返し、add が IllegalStateException をスローします。「空であることが通常の状態」なら poll / peek、「空なら呼び出し側のバグ」なら remove / element、と使い分けます。",
  },

  // ------------------------------------------------------------ 反復中の削除
  {
    id: 10143,
    topic: "collections",
    variantOf: "gold-collections-iterator-remove",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "IteratorRemove",
    code: [
      "import java.util.*;",
      "",
      "public class IteratorRemove {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = new ArrayList<>(List.of(1, 2, 3, 4, 5, 6));",
      "        Iterator<Integer> it = list.iterator();",
      "        while (it.hasNext()) {",
      "            if (it.next() % 2 == 0) it.remove();",
      "        }",
      "        list.removeIf(n -> n > 3);",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: ["[1, 3]", "[1, 3, 5]", "[1, 2, 3]", "[]", "実行時に ConcurrentModificationException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 3]" },
    explanation:
      "反復中に List.remove を直接呼ぶと、イテレータが把握している変更回数とリストの変更回数が食い違い ConcurrentModificationException になります。しかし Iterator.remove は「直前に next で返した要素」をイテレータ自身が削除し、変更回数も同期させるので安全です。偶数が消えて [1, 3, 5] になり、続く removeIf で 3 より大きい 5 が消えて [1, 3] が残ります。条件で要素を消すだけなら removeIf がもっとも簡潔で、内部でイテレータの削除と同じく安全に処理されます。",
  },
  {
    id: 10144,
    topic: "collections",
    variantOf: "gold-collections-iterator-remove",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SubListTest",
    code: [
      "import java.util.*;",
      "",
      "public class SubListTest {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>(List.of(\"a\", \"b\", \"c\", \"d\"));",
      "        List<String> sub = list.subList(1, 3);",
      "        sub.set(0, \"B\");",
      "        System.out.print(list + \" \");",
      "        list.add(\"e\");",
      "        System.out.println(sub);",
      "    }",
      "}",
    ],
    choices: [
      "[a, B, c, d] と出力された後、ConcurrentModificationException がスローされる",
      "[a, B, c, d] [B, c]",
      "[a, b, c, d] [B, c]",
      "[a, B, c, d] [B, c, e]",
      "7行目で UnsupportedOperationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ConcurrentModificationException", stdout: "[a, B, c, d]" },
    explanation:
      "subList(1, 3) は元のリストのインデックス 1 以上 3 未満の範囲を示すビューで、sub への set は元のリストに反映されて [a, B, c, d] になります。ところがビューを作った後に元のリストの要素数を（ビューを経由せずに）変えると、ビューが指している範囲の意味が失われます。List の仕様ではこの後のビューの振る舞いは「未定義」とされており、ArrayList の subList は変更回数の食い違いを検出して、ビューを使った時点で ConcurrentModificationException をスローします。サブリストは短命な作業用のビューとして使い、長く保持したいなら new ArrayList<>(list.subList(...)) でコピーします。",
  },

  // ------------------------------------------------------------ LinkedHashMap
  {
    id: 10145,
    topic: "collections",
    variantOf: "gold-collections-map-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AccessOrder",
    code: [
      "import java.util.*;",
      "",
      "public class AccessOrder {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> insertion = new LinkedHashMap<>();",
      "        Map<String, Integer> access = new LinkedHashMap<>(16, 0.75f, true);",
      "        for (String k : List.of(\"x\", \"y\", \"z\")) {",
      "            insertion.put(k, 0);",
      "            access.put(k, 0);",
      "        }",
      "        insertion.get(\"x\");",
      "        access.get(\"x\");",
      "        insertion.put(\"y\", 1);",
      "        System.out.println(insertion.keySet() + \" \" + access.keySet());",
      "    }",
      "}",
    ],
    choices: [
      "[x, y, z] [y, z, x]",
      "[x, y, z] [x, y, z]",
      "[x, z, y] [y, z, x]",
      "[y, z, x] [y, z, x]",
      "[x, z, y] [x, y, z]",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[x, y, z] [y, z, x]" },
    explanation:
      "LinkedHashMap は既定では挿入順を保ち、既存のキーに put し直しても順序は変わりません（y の値を更新しても位置はそのまま）。コンストラクタの第 3 引数 accessOrder に true を渡すとアクセス順になり、get や put でアクセスされたエントリが末尾へ移動します。x を get したので access は [y, z, x] になります。アクセス順の LinkedHashMap は先頭が「最も長く使われていないエントリ」になるため、removeEldestEntry をオーバーライドして LRU キャッシュを作る定番の部品として使われます。",
  },

  // ------------------------------------------------------------ Arrays のユーティリティ
  {
    id: 10146,
    topic: "collections",
    variantOf: "gold-collections-arrays-util",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "BinarySearch",
    code: [
      "import java.util.*;",
      "",
      "public class BinarySearch {",
      "    public static void main(String[] args) {",
      "        int[] nums = {5, 1, 4, 2};",
      "        Arrays.sort(nums);",
      "        System.out.println(Arrays.toString(nums) + \" \"",
      "                + Arrays.binarySearch(nums, 4) + \" \"",
      "                + Arrays.binarySearch(nums, 3) + \" \"",
      "                + Arrays.binarySearch(nums, 9));",
      "    }",
      "}",
    ],
    choices: ["[1, 2, 4, 5] 2 -3 -5", "[1, 2, 4, 5] 2 -1 -1", "[1, 2, 4, 5] 3 -3 -5", "[1, 2, 4, 5] 2 -2 -4", "[5, 1, 4, 2] 2 -3 -5"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 2, 4, 5] 2 -3 -5" },
    explanation:
      "Arrays.sort は配列そのものを昇順に並べ替えます（新しい配列は返しません）。binarySearch は並べ替え済みの配列から二分探索で値を探し、見つかればそのインデックス（4 は 2）を返します。見つからない場合は -1 ではなく「-(挿入位置) - 1」を返します。3 を挿入すべき位置は 2 なので -3、9 は末尾の 4 なので -5 です。負の値にしたうえで 1 を引くのは、挿入位置 0 の場合でも「見つかった位置 0」と区別するためで、戻り値から挿入位置を復元して、並びを保ったまま要素を追加できます。並べ替えていない配列に対する結果は定義されないので、必ず先に sort します。",
  },
  {
    id: 10147,
    topic: "collections",
    variantOf: "gold-collections-arrays-util",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ArrayCompare",
    code: [
      "import java.util.*;",
      "",
      "public class ArrayCompare {",
      "    public static void main(String[] args) {",
      "        int[] a = {1, 2, 3};",
      "        int[] b = {1, 2, 3};",
      "        int[] c = {1, 2, 4};",
      "        System.out.println((a == b) + \" \" + a.equals(b) + \" \" + Arrays.equals(a, b) + \" \"",
      "                + Arrays.compare(a, c) + \" \" + Arrays.mismatch(a, c) + \" \" + Arrays.mismatch(a, b));",
      "    }",
      "}",
    ],
    choices: [
      "false false true -1 2 -1",
      "false true true -1 2 -1",
      "true true true -1 2 -1",
      "false false true 1 2 0",
      "false false true -1 3 -1",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "false false true -1 2 -1" },
    explanation:
      "配列は equals をオーバーライドしていないので、a.equals(b) は == と同じく同一インスタンスかどうかを比べ、中身が同じでも false です。中身を比べるには Arrays.equals を使います。Arrays.compare は先頭から要素を比べて最初に異なる位置の大小で辞書順の比較をし、3 < 4 なので負の値（-1）を返します。Arrays.mismatch は最初に異なる要素のインデックス（2）を返し、完全に一致すれば -1 です。配列をマップのキーやセットの要素に使うと、この equals の性質のせいで同じ中身でも別物として扱われるので、List に変換するか record で包みます。",
  },
  {
    id: 10148,
    topic: "collections",
    variantOf: "gold-collections-comparator-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NullsFirst",
    code: [
      "import java.util.*;",
      "",
      "public class NullsFirst {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>(Arrays.asList(\"pear\", null, \"fig\", null, \"apple\"));",
      "        list.sort(Comparator.nullsLast(Comparator.comparing(String::length)));",
      "        System.out.print(list + \" \");",
      "        list.sort(Comparator.naturalOrder());",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[fig, pear, apple, null, null] と出力された後、NullPointerException がスローされる",
      "[fig, pear, apple, null, null] [apple, fig, pear, null, null]",
      "[null, null, fig, pear, apple] と出力された後、NullPointerException がスローされる",
      "6行目で NullPointerException がスローされる",
      "[fig, pear, apple, null, null] [null, null, apple, fig, pear]",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "[fig, pear, apple, null, null]" },
    explanation:
      "Comparator.nullsLast(比較器) は、null を「どの値よりも大きい」とみなして末尾に置き、null でない値同士は渡した比較器で比べる Comparator を返します。そのため長さ順に並んだ後に null が 2 つ続きます。一方 Comparator.naturalOrder() は compareTo を呼ぶだけなので、null の要素に対して NullPointerException がスローされます。ArrayList は null を要素に持てるため、データベースの値など null が紛れ込むデータを並べ替えるときは nullsFirst / nullsLast で null の位置を明示しておくのが安全です。",
  },
  {
    id: 10149,
    topic: "collections",
    variantOf: "gold-collections-list-iterator",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ListIter",
    code: [
      "import java.util.*;",
      "",
      "public class ListIter {",
      "    public static void main(String[] args) {",
      "        List<String> list = new ArrayList<>(List.of(\"a\", \"b\", \"c\"));",
      "        ListIterator<String> it = list.listIterator();",
      "        while (it.hasNext()) {",
      "            String s = it.next();",
      "            if (s.equals(\"a\")) it.set(\"A\");",
      "            if (s.equals(\"b\")) it.add(\"x\");",
      "        }",
      "        System.out.print(list + \" \");",
      "        while (it.hasPrevious()) System.out.print(it.previous());",
      "        System.out.println();",
      "    }",
      "}",
    ],
    choices: ["[A, b, x, c] cxbA", "[A, b, x, c] Abxc", "[A, x, b, c] cbxA", "[A, b, c] cbA", "実行時に ConcurrentModificationException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[A, b, x, c] cxbA" },
    explanation:
      "ListIterator は List 専用のイテレータで、双方向の移動（previous）と、反復中の置き換え（set）・挿入（add）ができます。set は直前に next で返した要素を置き換えるので a が A になり、add は現在のカーソル位置（直前に返した b の後ろ）に挿入するので x は b と c の間に入ります。どちらもイテレータ自身の操作なので ConcurrentModificationException にはなりません。最後まで進んだ後は previous で末尾から逆順にたどれるので cxbA になります。反復しながら要素を差し込みたい場面では、インデックスを自分で調整するより ListIterator を使うのが安全です。",
  },
  {
    id: 10150,
    topic: "collections",
    variantOf: "gold-collections-immutable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "EntryTest",
    code: [
      "import java.util.*;",
      "",
      "public class EntryTest {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> m = Map.ofEntries(Map.entry(\"b\", 2), Map.entry(\"a\", 1));",
      "        System.out.print(new TreeMap<>(m) + \" \");",
      "        Map<String, Integer> copy = new HashMap<>(m);",
      "        for (Map.Entry<String, Integer> e : copy.entrySet()) e.setValue(e.getValue() * 10);",
      "        System.out.print(new TreeMap<>(copy) + \" \");",
      "        Map.entry(\"c\", 3).setValue(30);",
      "    }",
      "}",
    ],
    choices: [
      "{a=1, b=2} {a=10, b=20} と出力された後、UnsupportedOperationException がスローされる",
      "{a=1, b=2} {a=1, b=2} と出力された後、UnsupportedOperationException がスローされる",
      "{a=1, b=2} と出力された後、UnsupportedOperationException がスローされる",
      "{a=1, b=2} {a=10, b=20}",
      "{b=2, a=1} {b=20, a=10} と出力された後、UnsupportedOperationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedOperationException", stdout: "{a=1, b=2} {a=10, b=20}" },
    explanation:
      "Map.ofEntries は Map.entry で作ったエントリから変更不可のマップを作ります（Map.of の引数が 10 組までなのに対し、個数の制限がありません）。HashMap にコピーした後の entrySet の各エントリは元のマップにつながったビューで、setValue で値を書き換えるとマップに反映されます。反復中でも要素数は変わらないので ConcurrentModificationException にはなりません。一方 Map.entry が返すのは変更不可のエントリなので、setValue は UnsupportedOperationException をスローします。キーと値の組を一時的に扱いたいだけなら Map.entry、書き換えが必要なら HashMap などを使います。",
  },
];
