import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: コレクションとジェネリクス（id 10101-10199）。
 * オートボクシング、List / Set / Map / Deque、総称型、Comparator、Collections のユーティリティ。
 */
export const goldCollectionsQuestions: GoldQuestion[] = [
  // ------------------------------------------------ オートボクシングとオーバーロード
  {
    id: 10101,
    topic: "collections",
    variantOf: "gold-collections-remove-overload",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RemoveTest",
    code: [
      "import java.util.*;",
      "",
      "public class RemoveTest {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = new ArrayList<>(List.of(1, 2, 3));",
      "        list.remove(1);",
      "        list.remove(Integer.valueOf(1));",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: ["[3]", "[2, 3]", "[1, 3]", "[1]", "コンパイルエラーになる", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[3]" },
    explanation:
      "List には remove(int index) と remove(Object o) の 2 つがオーバーロードされています。list.remove(1) は引数が int なので、ボクシングが不要な remove(int) が優先され、インデックス 1 の要素 2 が削除されて [1, 3] になります。続く remove(Integer.valueOf(1)) は Integer を渡しているので remove(Object) が選ばれ、値 1 が削除されて [3] が残ります。オーバーロード解決ではボクシングなしで適用できるメソッドが先に探されるため、List<Integer> で値を消したいときは Integer.valueOf で明示するのが安全です。",
  },
  {
    id: 10102,
    topic: "collections",
    variantOf: "gold-collections-remove-overload",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ShortSet",
    code: [
      "import java.util.*;",
      "",
      "public class ShortSet {",
      "    public static void main(String[] args) {",
      "        Set<Short> set = new HashSet<>();",
      "        for (short i = 0; i < 5; i++) {",
      "            set.add(i);",
      "            set.remove(i - 1);",
      "        }",
      "        System.out.println(set.size());",
      "    }",
      "}",
    ],
    choices: ["5", "1", "0", "4", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "5" },
    explanation:
      "set.add(i) では short の i が Short にボクシングされて追加されます。一方 i - 1 は算術演算で int に昇格するため、remove には Integer がボクシングされて渡されます。Set.remove の引数は Object 型なのでコンパイルは通りますが、Short と Integer は equals で等しくならず、1 つも削除されません。remove や contains が Object を受け取るのは総称型導入前との互換性のためで、型の違いがコンパイル時に検出されない落とし穴になっています。",
  },
  {
    id: 10103,
    topic: "collections",
    variantOf: "gold-collections-unboxing-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "StockCount",
    code: [
      "import java.util.*;",
      "",
      "public class StockCount {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> stock = new HashMap<>();",
      '        stock.put("apple", 3);',
      '        int apple = stock.get("apple");',
      '        int melon = stock.get("melon");',
      '        System.out.println(apple + " " + melon);',
      "    }",
      "}",
    ],
    choices: [
      "実行時に NullPointerException がスローされる",
      "3 0",
      "3 null",
      "8行目でコンパイルエラーになる",
      "実行時に NoSuchElementException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException" },
    explanation:
      "Map.get は該当するキーが無いと null を返します。8行目では戻り値の Integer を int 変数に代入するためにアンボクシング（intValue() の呼び出し）が行われ、null に対して実行されるので NullPointerException になります。プリミティブ型には「値が無い」を表す手段が無いため、null をプリミティブに変換する方法が存在しないのです。キーが無い可能性がある場合は getOrDefault(\"melon\", 0) を使うか、Integer のまま受けて null を確認します。",
  },
  {
    id: 10104,
    topic: "collections",
    variantOf: "gold-collections-unboxing-null",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CacheCheck",
    code: [
      "public class CacheCheck {",
      "    public static void main(String[] args) {",
      "        Integer a = 127, b = 127;",
      "        Integer c = 128, d = 128;",
      "        Integer e = null;",
      '        System.out.print((a == b) + " " + (c == d) + " ");',
      "        System.out.println(e == 0);",
      "    }",
      "}",
    ],
    choices: [
      "true false と出力された後、NullPointerException がスローされる",
      "true true false",
      "true false false",
      "false false false",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "true false" },
    explanation:
      "オートボクシングは Integer.valueOf を使い、-128〜127 の値はキャッシュ済みの同じインスタンスを返すため a == b は true になります。128 はキャッシュ範囲外なので別々のインスタンスとなり、参照の比較である c == d は false です。7行目の e == 0 は片方が int なので e がアンボクシングされ、null に対して intValue() が呼ばれて NullPointerException になります。ラッパー型どうしの == は値ではなく参照を比べるため、値の比較には equals を使うのが原則です。",
  },

  // ------------------------------------------------------------ Set と Comparator
  {
    id: 10105,
    topic: "collections",
    variantOf: "gold-collections-treeset-comparator",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LengthSet",
    code: [
      "import java.util.*;",
      "",
      "public class LengthSet {",
      "    public static void main(String[] args) {",
      "        Set<String> set = new TreeSet<>(Comparator.comparing(String::length));",
      '        set.addAll(List.of("bb", "a", "ccc", "dd"));',
      "        System.out.println(set);",
      "    }",
      "}",
    ],
    choices: ["[a, bb, ccc]", "[a, bb, dd, ccc]", "[a, dd, ccc]", "[bb, a, ccc, dd]", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[a, bb, ccc]" },
    explanation:
      "TreeSet は要素の重複を equals ではなく、比較器の compare が 0 を返すかどうかで判定します。この比較器は文字列の長さだけを比べるため、\"dd\" は先に追加された \"bb\" と長さが同じ＝重複とみなされ、追加されません。TreeSet / TreeMap は並べ替えのための比較結果を同一性の判定にも使う設計で、比較器が equals と矛盾すると要素が黙って消えます。同じ長さの文字列も区別したいなら thenComparing(Comparator.naturalOrder()) で順序を決めきる必要があります。",
  },
  {
    id: 10106,
    topic: "collections",
    variantOf: "gold-collections-treeset-comparator",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TicketBox",
    code: [
      "import java.util.*;",
      "",
      "public class TicketBox {",
      "    static class Ticket {",
      "        int no;",
      "        Ticket(int no) { this.no = no; }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Set<Ticket> set = new TreeSet<>();",
      "        set.add(new Ticket(1));",
      "        System.out.println(set.size());",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ClassCastException がスローされる",
      "1",
      "0",
      "10行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ClassCastException" },
    explanation:
      "比較器を指定しない TreeSet は、要素を Comparable にキャストして compareTo で並べます。Ticket は Comparable を実装していないため、最初の 1 件を追加した時点でキャストに失敗し ClassCastException になります。TreeSet<Ticket> という型だけでは Comparable であることを要求できない（型パラメータに境界が無い）ため、この誤りはコンパイル時には検出されません。自作クラスを TreeSet / TreeMap のキーにするときは、Comparable を実装するか、コンストラクタに Comparator を渡します。",
  },

  // -------------------------------------------------------------------- Deque
  {
    id: 10107,
    topic: "collections",
    variantOf: "gold-collections-deque-ops",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DequeOps",
    code: [
      "import java.util.*;",
      "",
      "public class DequeOps {",
      "    public static void main(String[] args) {",
      "        Deque<Integer> d = new ArrayDeque<>();",
      "        d.push(1);",
      "        d.offer(2);",
      "        d.push(3);",
      "        d.offerFirst(4);",
      '        System.out.println(d.pollLast() + " " + d.pop() + " " + d);',
      "    }",
      "}",
    ],
    choices: ["2 4 [3, 1]", "1 4 [3, 2]", "4 2 [3, 1]", "2 3 [4, 1]", "1 3 [4, 2]"],
    correct: [0],
    expected: { kind: "output", stdout: "2 4 [3, 1]" },
    explanation:
      "Deque はスタック用のメソッド（push / pop は先頭側）とキュー用のメソッド（offer は末尾に追加、poll は先頭から取り出し）を併せ持ちます。push(1) で [1]、offer(2) で末尾に追加して [1, 2]、push(3) で [3, 1, 2]、offerFirst(4) で [4, 3, 1, 2] になります。pollLast() は末尾の 2、pop() は先頭の 4 を取り出すので、残りは [3, 1] です。push = addFirst、offer = offerLast と対応づけて覚えると、スタックとキューを 1 つの型で扱う Deque の設計が見通しやすくなります。",
  },
  {
    id: 10108,
    topic: "collections",
    variantOf: "gold-collections-deque-ops",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DequeEmpty",
    code: [
      "import java.util.*;",
      "",
      "public class DequeEmpty {",
      "    public static void main(String[] args) {",
      "        Deque<String> d = new ArrayDeque<>();",
      '        d.offerLast("x");',
      "        System.out.print(d.poll() + \" \");",
      "        System.out.print(d.peek() + \" \");",
      "        System.out.print(d.pop());",
      "    }",
      "}",
    ],
    choices: [
      "x null と出力された後、NoSuchElementException がスローされる",
      "x null null",
      "x x x",
      "x と出力された後、NullPointerException がスローされる",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NoSuchElementException", stdout: "x null" },
    explanation:
      "Deque の取り出し・参照メソッドは、空のときの振る舞いで 2 系統に分かれます。poll / peek / offer 系は失敗を戻り値（null や false）で知らせ、pop / remove / element / add 系は例外で知らせます。1 件だけの \"x\" を poll で取り出したあと、peek は null を返し、pop は空の Deque に対して NoSuchElementException をスローします。null を失敗の合図に使う設計のため、ArrayDeque には null 要素そのものを追加できない（NullPointerException になる）点も合わせて押さえておきます。",
  },

  // ---------------------------------------------------------------- Map の操作
  {
    id: 10109,
    topic: "collections",
    variantOf: "gold-collections-map-merge",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MergeTest",
    code: [
      "import java.util.*;",
      "",
      "public class MergeTest {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> m = new TreeMap<>();",
      '        m.put("a", 1);',
      '        m.merge("a", 5, Integer::sum);',
      '        m.merge("b", 7, Integer::sum);',
      '        m.putIfAbsent("a", 100);',
      '        m.computeIfPresent("b", (k, v) -> null);',
      '        m.computeIfAbsent("c", k -> 3);',
      "        System.out.println(m);",
      "    }",
      "}",
    ],
    choices: ["{a=6, c=3}", "{a=6, b=7, c=3}", "{a=100, c=3}", "{a=6, b=null, c=3}", "実行時に NullPointerException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "{a=6, c=3}" },
    explanation:
      "merge はキーが無ければ値をそのまま入れ、あれば既存値と新しい値を関数で合成します。\"a\" は 1 + 5 で 6、\"b\" は存在しないので 7 がそのまま入ります。putIfAbsent は既に値がある \"a\" を上書きしません。computeIfPresent / merge / compute は関数が null を返すとそのエントリを削除する約束になっているため、\"b\" は消えます。「null を返す＝削除」という規約のおかげで、集計値が 0 になったら消すといった処理を 1 回の呼び出しで書けます。",
  },
  {
    id: 10110,
    topic: "collections",
    variantOf: "gold-collections-map-merge",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NullValueMap",
    code: [
      "import java.util.*;",
      "",
      "public class NullValueMap {",
      "    public static void main(String[] args) {",
      "        Map<String, String> m = new HashMap<>();",
      '        m.put("a", null);',
      '        m.putIfAbsent("a", "x");',
      '        m.computeIfAbsent("b", k -> null);',
      '        String c = m.getOrDefault("c", "none");',
      '        System.out.println(m + " " + c + " " + m.containsKey("b"));',
      "    }",
      "}",
    ],
    choices: [
      "{a=x} none false",
      "{a=null} none false",
      "{a=x, b=null} none true",
      "{a=null, b=null} null true",
      "実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{a=x} none false" },
    explanation:
      "putIfAbsent や computeIfAbsent は「キーが無い」だけでなく「値が null」の場合も不在とみなします。そのため値が null の \"a\" には \"x\" が入ります。computeIfAbsent は関数が null を返すと何も登録しないので、\"b\" は追加されません。getOrDefault は \"c\" が無いので既定値 \"none\" を返します。HashMap は null 値を許しますが、これらのメソッドでは null が「値が無い」と区別できないため、実務では null を値として格納しない設計にしておくと混乱を避けられます。",
  },

  // ---------------------------------------------------------- 変更不可コレクション
  {
    id: 10111,
    topic: "collections",
    variantOf: "gold-collections-immutable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CopyOfTest",
    code: [
      "import java.util.*;",
      "",
      "public class CopyOfTest {",
      "    public static void main(String[] args) {",
      '        List<String> a = Arrays.asList("x", "y");',
      '        a.set(0, "z");',
      "        List<String> b = List.copyOf(a);",
      '        a.set(1, "w");',
      '        System.out.println(a + " " + b);',
      '        b.add("q");',
      "    }",
      "}",
    ],
    choices: [
      "[z, w] [z, y] と出力された後、UnsupportedOperationException がスローされる",
      "[z, w] [z, w] と出力された後、UnsupportedOperationException がスローされる",
      "6行目で UnsupportedOperationException がスローされる",
      "[z, w] [z, y, q]",
      "[z, w] [z, w, q]",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedOperationException", stdout: "[z, w] [z, y]" },
    explanation:
      "Arrays.asList は元の配列を包む固定長のリストを返すため、要素数を変える add / remove はできませんが set による置き換えはできます。List.copyOf はその時点の要素をコピーした変更不可のリストを作るので、後から a を書き換えても b は [z, y] のままです。変更不可のリストに add すると UnsupportedOperationException になります。「サイズ固定」「変更不可のコピー」「変更不可のビュー」は似て非なるもので、他者に渡すリストを守りたいなら copyOf でコピーするのが確実です。",
  },
  {
    id: 10112,
    topic: "collections",
    variantOf: "gold-collections-immutable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MapOfTest",
    code: [
      "import java.util.*;",
      "",
      "public class MapOfTest {",
      "    public static void main(String[] args) {",
      '        Map<String, Integer> m = Map.of("a", 1, "b", 2, "a", 3);',
      "        System.out.println(m.size());",
      "    }",
      "}",
    ],
    choices: [
      "実行時に IllegalArgumentException がスローされる",
      "2",
      "3",
      "5行目でコンパイルエラーになる",
      "実行時に UnsupportedOperationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalArgumentException" },
    explanation:
      "Map.of で作る変更不可のマップは、キーの重複を許さず、重複があると IllegalArgumentException をスローします。HashMap の put のように後勝ちで上書きしないのは、リテラル的に書いた定義に重複があるのはほぼ確実に記述ミスであり、黙って片方を捨てると発見しにくいバグになるからです。同様に Map.of / List.of / Set.of は null の要素・キー・値も拒否します（NullPointerException）。変更不可コレクションのファクトリは「作った瞬間に不正を検出する」方針で設計されています。",
  },
  {
    id: 10113,
    topic: "collections",
    variantOf: "gold-collections-unmodifiable-view",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ViewTest",
    code: [
      "import java.util.*;",
      "",
      "public class ViewTest {",
      "    public static void main(String[] args) {",
      '        List<String> base = new ArrayList<>(List.of("a"));',
      "        List<String> view = Collections.unmodifiableList(base);",
      "        List<String> copy = List.copyOf(base);",
      '        base.add("b");',
      '        System.out.println(view + " " + copy);',
      "    }",
      "}",
    ],
    choices: ["[a, b] [a]", "[a] [a]", "[a, b] [a, b]", "[a] [a, b]", "実行時に UnsupportedOperationException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[a, b] [a]" },
    explanation:
      "Collections.unmodifiableList は元のリストを包んだ「読み取り専用のビュー」を返します。ビュー経由の変更は禁止されますが、元のリスト base を変更すればその内容はビューにもそのまま見えるため、view は [a, b] になります。一方 List.copyOf は呼び出した時点の要素を複製するので、後からの変更の影響を受けません。内部のリストをビューで公開すると、呼び出し側からは変更できなくても中身は変わりうる点に注意が必要です。",
  },

  // ------------------------------------------------------------------ 総称型
  {
    id: 10114,
    topic: "collections",
    variantOf: "gold-collections-wildcard",
    question: "次のコードのうち、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Wildcards",
    code: [
      "import java.util.*;",
      "",
      "public class Wildcards {",
      "    static void copy(List<? extends Number> src, List<? super Number> dst) {",
      "        Number n = src.get(0);",
      "        dst.add(n);",
      "        dst.add(3.14);",
      "        Object o = dst.get(0);",
      "        src.add(n);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        copy(List.of(1), new ArrayList<Object>());",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "List<? extends Number> は「Number の何らかのサブタイプのリスト」で、実体は List<Integer> かもしれないし List<Double> かもしれません。取り出した要素は必ず Number として扱えますが、どの型のリストか分からないため要素を追加することはできず（null を除く）、9行目がコンパイルエラーになります。逆に List<? super Number> は Number を入れても安全なので add でき、取り出すと型は Object としか分かりません。「取り出すなら extends、入れるなら super」（PECS）と覚えると、API の引数設計にもそのまま使えます。",
  },
  {
    id: 10115,
    topic: "collections",
    variantOf: "gold-collections-wildcard",
    question: "次のコードのうち、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "SuperBox",
    code: [
      "import java.util.*;",
      "",
      "public class SuperBox {",
      "    static void fill(List<? super Integer> list) {",
      "        list.add(1);",
      "        list.add(null);",
      "        Object first = list.get(0);",
      "        Integer second = list.get(1);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        fill(new ArrayList<Number>());",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "List<? super Integer> の実体は List<Integer>、List<Number>、List<Object> のいずれかです。どれであっても Integer（と null）は安全に追加できるので 5・6行目は正しく、12行目のように List<Number> を渡すこともできます。しかし取り出した要素は Number かもしれないし Object かもしれないため、確実に言えるのは Object 型であることだけで、Integer 変数に代入する 8行目はコンパイルエラーになります。super 境界のワイルドカードは「値を受け取る側（消費者）」として使うためのものです。",
  },
  {
    id: 10116,
    topic: "collections",
    variantOf: "gold-collections-erasure",
    question: "次のコードをコンパイルした場合の結果として正しいものはどれか。1つ選びなさい。",
    className: "Printer",
    code: [
      "import java.util.*;",
      "",
      "public class Printer {",
      "    void print(List<String> list) {",
      '        System.out.println("String");',
      "    }",
      "",
      "    void print(List<Integer> list) {",
      '        System.out.println("Integer");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Printer().print(List.of(1));",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "コンパイルに成功し、実行すると Integer と出力される",
      "コンパイルに成功し、実行すると String と出力される",
      "13行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "総称型の型引数はコンパイル時の検査にだけ使われ、クラスファイルには残りません（型消去）。そのため print(List<String>) と print(List<Integer>) はどちらも print(List) という同じシグネチャになり、オーバーロードとして共存できず 8行目で name clash のコンパイルエラーになります。型消去は総称型導入以前のバイトコードとの互換性を保つための設計です。型引数だけが違うメソッドを並べたいときは、printStrings / printIntegers のようにメソッド名を分けます。",
  },
  {
    id: 10117,
    topic: "collections",
    variantOf: "gold-collections-erasure",
    question: "次のコードのうち、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Holder",
    code: [
      "public class Holder<T> {",
      "    private T value;",
      "    private static int count;",
      "    private static T shared;",
      "",
      "    Holder(T value) {",
      "        this.value = value;",
      "        count++;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println(new Holder<>("a").value);',
      "    }",
      "}",
    ],
    choices: [
      "4行目でコンパイルエラーになる",
      "2行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 4 },
    explanation:
      "型パラメータ T はインスタンスごとに決まるもので（Holder<String> と Holder<Integer> は別の T を持つ）、クラスに 1 つしかない static メンバーからは参照できません。そのため static T shared を宣言した 4行目がコンパイルエラーになります。型消去により Holder<String> も Holder<Integer> も実行時には同じ 1 つのクラスであり、static フィールドはその全員で共有されるので、どの T か決めようがないのです。static メソッドで型パラメータが必要なら、<T> を付けた総称メソッドとして独自に宣言します。",
  },
  {
    id: 10118,
    topic: "collections",
    variantOf: "gold-collections-raw-type",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RawList",
    code: [
      "import java.util.*;",
      "",
      "public class RawList {",
      "    public static void main(String[] args) {",
      "        List raw = new ArrayList<String>();",
      "        raw.add(10);",
      "        List<String> names = raw;",
      '        System.out.print(names.size() + " ");',
      "        String first = names.get(0);",
      "        System.out.println(first);",
      "    }",
      "}",
    ],
    choices: [
      "1 と出力された後、ClassCastException がスローされる",
      "1 10",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "6行目で ClassCastException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ClassCastException", stdout: "1" },
    explanation:
      "原型（raw type）の List を使うと型検査が無効になり、警告は出るもののコンパイルは通ります。型消去により実行時の ArrayList は要素の型を知らないため、6行目で Integer を追加しても例外は起きません。問題が表面化するのは 9行目で、コンパイラが挿入した String へのキャストが Integer に対して行われ ClassCastException になります。このように原型は、不正な値が入った場所から離れた箇所で例外を起こす（ヒープ汚染）ので、未検査警告を無視しないことが重要です。",
  },

  // ---------------------------------------------------------------- Comparator
  {
    id: 10119,
    topic: "collections",
    variantOf: "gold-collections-comparator-chain",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Ranking",
    code: [
      "import java.util.*;",
      "",
      "public class Ranking {",
      "    record Player(String name, int score) {}",
      "",
      "    public static void main(String[] args) {",
      "        List<Player> list = new ArrayList<>(List.of(",
      '            new Player("Ken", 80), new Player("Ai", 95),',
      '            new Player("Bob", 80), new Player("Cy", 70)));',
      "        list.sort(Comparator.comparingInt(Player::score).reversed()",
      "                .thenComparing(Player::name));",
      "        for (Player p : list) {",
      '            System.out.print(p.name() + " ");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["Ai Bob Ken Cy", "Ai Ken Bob Cy", "Cy Bob Ken Ai", "Cy Ken Bob Ai", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "Ai Bob Ken Cy" },
    explanation:
      "comparingInt(Player::score).reversed() で点数の降順になり、thenComparing(Player::name) は点数が同じ要素どうしを名前の昇順で並べます。reversed() はそれを呼んだ時点までの比較器全体を逆にするもので、後から付けた thenComparing には影響しません。そのため 95 点の Ai、80 点の Bob と Ken（名前順）、70 点の Cy の順になります。Comparator のメソッドチェーンは「左から順に組み立てた比較器に次の操作を適用する」と読むと、reversed の効く範囲を取り違えずに済みます。",
  },
  {
    id: 10120,
    topic: "collections",
    variantOf: "gold-collections-comparator-chain",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Ranking2",
    code: [
      "import java.util.*;",
      "",
      "public class Ranking2 {",
      "    record Player(String name, int score) {}",
      "",
      "    public static void main(String[] args) {",
      "        List<Player> list = new ArrayList<>(List.of(",
      '            new Player("Ken", 80), new Player("Ai", 95),',
      '            new Player("Bob", 80), new Player("Cy", 70)));',
      "        list.sort(Comparator.comparingInt(Player::score)",
      "                .thenComparing(Player::name).reversed());",
      "        for (Player p : list) {",
      '            System.out.print(p.name() + " ");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["Ai Ken Bob Cy", "Ai Bob Ken Cy", "Cy Bob Ken Ai", "Cy Ken Bob Ai", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "Ai Ken Bob Cy" },
    explanation:
      "comparingInt(Player::score).thenComparing(Player::name) で「点数の昇順、同点なら名前の昇順」という比較器ができ、最後の reversed() はその全体を逆にします。したがって点数は降順、同点の 80 点どうしは名前の降順（Ken、Bob の順）になります。reversed() はチェーンの末尾に置くと、それまでに積み上げたすべての条件を反転させる点に注意してください。点数だけを降順にしたい場合は、reversed() を comparingInt の直後に置くか、Comparator.comparing(Player::score, Comparator.reverseOrder()) のようにキーごとに順序を指定します。",
  },
  {
    id: 10121,
    topic: "collections",
    variantOf: "gold-collections-comparator-inference",
    question: "次のコードのうち、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "SortWords",
    code: [
      "import java.util.*;",
      "",
      "public class SortWords {",
      "    public static void main(String[] args) {",
      '        List<String> words = new ArrayList<>(List.of("pear", "fig", "kiwi"));',
      "        words.sort(Comparator.comparing(String::length));",
      "        words.sort(Comparator.comparing(s -> s.length()));",
      "        words.sort(Comparator.comparing(String::length).reversed());",
      "        words.sort(Comparator.comparing(s -> s.length()).reversed());",
      "        System.out.println(words);",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "7行目のラムダ s -> s.length() は、sort の引数という文脈から s が String と推論されます。ところが 9行目では comparing(...) の結果に対して .reversed() を呼んでおり、comparing の呼び出しは sort の引数ではなくメソッド呼び出しのレシーバーになるため、ターゲット型が伝わりません。その結果 s は Object と推論され、Object に length() は無いのでコンパイルエラーになります。8行目のようにメソッド参照 String::length なら型が明示されているので問題ありません。チェーンする場合は (String s) -> s.length() と引数の型を書くか、メソッド参照を使います。",
  },

  // ---------------------------------------------------- 反復中の変更と Collections
  {
    id: 10122,
    topic: "collections",
    variantOf: "gold-collections-cme",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RemoveLoop",
    code: [
      "import java.util.*;",
      "",
      "public class RemoveLoop {",
      "    public static void main(String[] args) {",
      '        List<String> list = new ArrayList<>(List.of("a", "b", "c"));',
      "        for (String s : list) {",
      '            if (s.equals("a")) {',
      "                list.remove(s);",
      "            }",
      "        }",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に ConcurrentModificationException がスローされる",
      "[b, c]",
      "[a, b, c]",
      "[c]",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ConcurrentModificationException" },
    explanation:
      "拡張 for 文は内部で Iterator を使います。ArrayList の Iterator は生成時のリストの変更回数（modCount）を覚えておき、next() のたびに一致を確認します。ループ中に list.remove で直接要素を削除すると変更回数がずれ、次の next() で ConcurrentModificationException がスローされます。反復中に構造が変わると、次にどの要素を返すべきかが不確かになるため、早期に失敗させる（fail-fast）設計です。反復しながら削除するには Iterator.remove() か、list.removeIf(s -> s.equals(\"a\")) を使います。",
  },
  {
    id: 10123,
    topic: "collections",
    variantOf: "gold-collections-cme",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RemoveLoop2",
    code: [
      "import java.util.*;",
      "",
      "public class RemoveLoop2 {",
      "    public static void main(String[] args) {",
      '        List<String> list = new ArrayList<>(List.of("a", "b", "c"));',
      "        for (String s : list) {",
      '            if (s.equals("b")) {',
      "                list.remove(s);",
      "            }",
      "        }",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[a, c]",
      "実行時に ConcurrentModificationException がスローされる",
      "[a, b, c]",
      "[a]",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[a, c]" },
    explanation:
      "ArrayList の Iterator の hasNext() は「次に返す位置 cursor がサイズと異なるか」だけを見ています。\"b\"（2 番目）を返した時点で cursor は 2 で、そこで要素を削除するとサイズも 2 になるため hasNext() が false を返し、変更回数を確認する next() が呼ばれないままループが終わります。そのため例外は起きず、\"c\" は判定されないまま [a, c] が出力されます。例外が出ないのは偶然の結果で、正しく動いているわけではありません。反復中の削除は removeIf や Iterator.remove() で行うべきです。",
  },
  {
    id: 10124,
    topic: "collections",
    variantOf: "gold-collections-utilities",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "UtilTest",
    code: [
      "import java.util.*;",
      "",
      "public class UtilTest {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = new ArrayList<>(List.of(3, 1, 2, 2));",
      "        Collections.sort(list, Collections.reverseOrder());",
      "        Collections.swap(list, 0, 3);",
      "        System.out.println(list + \" \" + Collections.max(list)",
      "                + \" \" + Collections.frequency(list, 2));",
      "    }",
      "}",
    ],
    choices: ["[1, 2, 2, 3] 3 2", "[3, 2, 2, 1] 3 2", "[1, 2, 2, 3] 1 2", "[2, 2, 1, 3] 3 2", "[3, 2, 2, 1] 1 1"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 2, 2, 3] 3 2" },
    explanation:
      "Collections.sort に Collections.reverseOrder() を渡すと自然順序の逆、つまり降順の [3, 2, 2, 1] になります。swap(list, 0, 3) は先頭と末尾を入れ替えるので [1, 2, 2, 3] です。Collections.max は並び順に関係なく自然順序で最大の 3 を返し、frequency は equals で一致する要素を数えるので 2 は 2 個です。Collections クラスのメソッドはリストの現在の並びに依存するもの（binarySearch など）とそうでないもの（max / min / frequency）があり、その区別を意識すると誤用を避けられます。",
  },
];
