import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: 並列処理（id 10501-10599）。
 * Thread / Runnable、ExecutorService、synchronized、java.util.concurrent のコレクション、Flow。
 *
 * 実機検証の結果が実行のたびに変わらないよう、スレッドの完了は join / Future.get などで必ず待ち、
 * 出力が実行順序に依存するコードは出題しない。
 */
export const goldConcurrencyQuestions: GoldQuestion[] = [
  // ------------------------------------------------------ Thread と Runnable
  {
    id: 10501,
    topic: "concurrency",
    variantOf: "gold-concurrency-start-run",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "StartRun",
    code: [
      "public class StartRun {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Runnable task = () -> System.out.print(Thread.currentThread().getName() + \" \");",
      '        Thread t = new Thread(task, "worker");',
      "        t.run();",
      "        t.start();",
      "        t.join();",
      "    }",
      "}",
    ],
    choices: ["main worker", "worker worker", "worker main", "main main", "実行時に IllegalThreadStateException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "main worker" },
    explanation:
      "run() を直接呼ぶと、それは普通のメソッド呼び出しとして呼び出し元の main スレッドで実行されるため、main と出力されます。新しいスレッドを起動するのは start() で、JVM が別スレッドを作り、そのスレッドの中で run() を呼び出すので worker と出力されます。join() はそのスレッドの終了を待つので、出力の順序は main → worker に確定します。run() を呼んでもエラーにはならず、単に並行処理にならないだけなので、見落としやすい誤りです。",
  },
  {
    id: 10502,
    topic: "concurrency",
    variantOf: "gold-concurrency-start-run",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "StartTwice",
    code: [
      "public class StartTwice {",
      "    public static void main(String[] args) throws InterruptedException {",
      '        Thread t = new Thread(() -> System.out.print("run "));',
      "        t.start();",
      "        t.join();",
      "        t.start();",
      "    }",
      "}",
    ],
    choices: [
      "run と出力された後、IllegalThreadStateException がスローされる",
      "run run",
      "run",
      "6行目でコンパイルエラーになる",
      "何も出力されずに IllegalThreadStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalThreadStateException", stdout: "run" },
    explanation:
      "Thread オブジェクトは一度しか start() できません。1 回目の start() で run と出力され、join() でその終了を待ったあと、終了済みのスレッドに再度 start() を呼ぶと IllegalThreadStateException がスローされます。start() を呼べるのはスレッドが NEW（新規）状態のときだけで、スレッドの状態は NEW から TERMINATED（終了）へ一方向に進み、終了したスレッドを NEW に戻す手段はありません。同じ処理をもう一度別スレッドで動かしたい場合は、新しい Thread を作るか、ExecutorService にタスクとして繰り返し渡します。",
  },

  // ---------------------------------------------------------- ExecutorService
  {
    id: 10503,
    topic: "concurrency",
    variantOf: "gold-concurrency-future",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FutureError",
    code: [
      "import java.io.*;",
      "import java.util.concurrent.*;",
      "",
      "public class FutureError {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      "        Future<Integer> f = ex.submit(() -> {",
      '            throw new IOException("disk");',
      "        });",
      "        try {",
      "            System.out.println(f.get());",
      "        } catch (ExecutionException e) {",
      "            System.out.println(e.getCause().getClass().getSimpleName());",
      "        } finally {",
      "            ex.shutdown();",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "IOException",
      "ExecutionException",
      "null",
      "7行目でコンパイルエラーになる",
      "実行時に IOException がスローされてプログラムが終了する",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "IOException" },
    explanation:
      "本体が例外をスローするだけで正常に終わらないラムダ式は、戻り値の無い Runnable にも、戻り値のある Callable にも適合します。submit(Runnable) と submit(Callable) の両方が候補になる場合は、戻り値を持つ Callable 版の方がより具体的とみなされて選ばれます。Callable の call() は throws Exception と宣言されているので、検査例外の IOException をスローしてもコンパイルエラーになりません（Runnable が選ばれていたら run() は検査例外をスローできないため、コンパイルエラーになるところです）。タスク内で発生した例外はその場では伝わらず、Future.get() を呼んだときに ExecutionException に包まれてスローされ、getCause() で元の IOException を取り出せます。別スレッドで起きた例外を呼び出し元に確実に届けるための仕組みで、get() を呼ばないと例外に気付けない点に注意が必要です。",
  },
  {
    id: 10504,
    topic: "concurrency",
    variantOf: "gold-concurrency-future",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SubmitRunnable",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class SubmitRunnable {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      '        Future<?> a = ex.submit(() -> System.out.print("A "));',
      '        Future<String> b = ex.submit(() -> System.out.print("B "), "done");',
      "        Object ra = a.get();",
      "        String rb = b.get();",
      "        System.out.println(ra + \" \" + rb);",
      "        ex.shutdown();",
      "    }",
      "}",
    ],
    choices: ["A B null done", "A B A done", "A B null null", "7行目でコンパイルエラーになる", "8行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "A B null done" },
    explanation:
      "System.out.print は戻り値が void なので、6・7行目のラムダ式は値を返せず、Callable ではなく Runnable として submit されます。Runnable には戻り値が無いため、submit(Runnable) が返す Future の get() は正常終了を待って null を返します。submit(Runnable, result) の形では、タスク完了後に get() が第 2 引数の \"done\" を返します。単一スレッドのエグゼキュータなので A → B の順に実行され、両方の get() が完了を待ってから最後の行を出力するため、結果は確定します。戻り値の無い処理でも Future で完了を待ったり例外を受け取ったりできる、というのが submit(Runnable) の用途です。",
  },
  {
    id: 10505,
    topic: "concurrency",
    variantOf: "gold-concurrency-invokeall",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "InvokeAllTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class InvokeAllTest {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newFixedThreadPool(3);",
      "        List<Callable<Integer>> tasks = List.of(",
      "                () -> { Thread.sleep(300); return 1; },",
      "                () -> 2,",
      "                () -> { Thread.sleep(100); return 3; });",
      "        int result = 0;",
      "        for (Future<Integer> f : ex.invokeAll(tasks)) {",
      "            result = result * 10 + f.get();",
      "        }",
      "        ex.shutdown();",
      "        System.out.println(result);",
      "    }",
      "}",
    ],
    choices: ["123", "231", "321", "6", "実行するたびに結果が変わりうる"],
    correct: [0],
    expected: { kind: "output", stdout: "123" },
    explanation:
      "invokeAll はすべてのタスクが完了するまで待機し、渡したタスクのリストと同じ順序で Future のリストを返します。タスクの完了順は 2 → 3 → 1 ですが、結果の並びは完了順ではなくタスクの並びに対応するため、1, 2, 3 の順に取り出されて 123 になります。invokeAll から戻った時点ですべての Future は完了しているので、get() で待たされることもありません。これに対して invokeAny は、正常に完了したいずれか 1 つのタスクの結果だけを返し、残りのタスクは取り消します。",
  },
  {
    id: 10506,
    topic: "concurrency",
    variantOf: "gold-concurrency-shutdown",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ShutdownTest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class ShutdownTest {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      '        ex.submit(() -> System.out.print("A "));',
      "        ex.shutdown();",
      "        System.out.print(ex.awaitTermination(5, TimeUnit.SECONDS) + \" \");",
      '        ex.submit(() -> System.out.print("B "));',
      "    }",
      "}",
    ],
    choices: [
      "A true と出力された後、RejectedExecutionException がスローされる",
      "A true B",
      "A false B",
      "true と出力された後、RejectedExecutionException がスローされる",
      "A true と出力された後、IllegalStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "RejectedExecutionException", stdout: "A true" },
    explanation:
      "shutdown() は新しいタスクの受け付けを停止しますが、既に投入されたタスクは最後まで実行させます。awaitTermination は全タスクの完了（またはタイムアウト）まで待ち、完了していれば true を返すので、A が出力されたあとに true が出力されます。停止後の ExecutorService に submit すると、タスクは実行されず RejectedExecutionException がスローされます。ExecutorService のスレッドは明示的に止めない限り残り続けるため、使い終わったら shutdown し、必要に応じて awaitTermination で完了を待つのが基本の流れです。",
  },
  {
    id: 10507,
    topic: "concurrency",
    variantOf: "gold-concurrency-shutdown",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SingleOrder",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class SingleOrder {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      "        for (String s : new String[] {\"x\", \"y\", \"z\"}) {",
      "            ex.execute(() -> System.out.print(s));",
      "        }",
      "        ex.shutdown();",
      "        ex.awaitTermination(5, TimeUnit.SECONDS);",
      "        System.out.println(\" \" + ex.isShutdown() + \" \" + ex.isTerminated());",
      "    }",
      "}",
    ],
    choices: [
      "xyz true true",
      "xyz true false",
      "xyz false true",
      "x、y、z の出力順序は保証されない",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "xyz true true" },
    explanation:
      "newSingleThreadExecutor はスレッドを 1 つだけ持ち、投入されたタスクを投入順に 1 つずつ実行するため、出力は必ず xyz になります。拡張 for 文の変数 s は反復ごとに新しい変数なので実質的に final で、ラムダ式から参照できます。isShutdown() は shutdown() が呼ばれていれば true、isTerminated() は shutdown 後にすべてのタスクが完了していれば true で、awaitTermination で完了を待ったのでどちらも true です。順序が重要な処理を非同期に逃がしたい場合、単一スレッドのエグゼキュータは同期処理なしで順序を保証できる手軽な選択肢です。",
  },

  // ------------------------------------------------------------ 同期と排他制御
  {
    id: 10508,
    topic: "concurrency",
    variantOf: "gold-concurrency-synchronized",
    question: "次のコードを実行した場合に、必ず出力される値はどれか。1つ選びなさい。",
    className: "SyncCounter",
    code: [
      "public class SyncCounter {",
      "    private int count;",
      "",
      "    synchronized void increment() {",
      "        count++;",
      "    }",
      "",
      "    public static void main(String[] args) throws InterruptedException {",
      "        SyncCounter c = new SyncCounter();",
      "        Runnable task = () -> {",
      "            for (int i = 0; i < 10000; i++) c.increment();",
      "        };",
      "        Thread t1 = new Thread(task);",
      "        Thread t2 = new Thread(task);",
      "        t1.start();",
      "        t2.start();",
      "        t1.join();",
      "        t2.join();",
      "        System.out.println(c.count);",
      "    }",
      "}",
    ],
    choices: ["20000", "10000", "20000 以下のいずれかの値（実行するたびに変わりうる）", "0", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "20000" },
    explanation:
      "count++ は「読み出し・加算・書き込み」の 3 段階からなり、複数のスレッドが同時に実行すると更新が失われることがあります。increment() は synchronized なので、同じ SyncCounter インスタンスのロックを取得したスレッドだけが実行でき、2 つのスレッドの count++ が重なることはありません。さらに join() で両スレッドの終了を待ってから読むため、synchronized によるメモリの可視性の保証と合わせて、必ず 20000 が出力されます。synchronized を外すと結果は 20000 以下の不定な値になり、この種の不具合はテストで再現しにくいのが厄介な点です。",
  },
  {
    id: 10509,
    topic: "concurrency",
    variantOf: "gold-concurrency-atomic",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AtomicTest",
    code: [
      "import java.util.concurrent.atomic.*;",
      "",
      "public class AtomicTest {",
      "    public static void main(String[] args) {",
      "        AtomicInteger a = new AtomicInteger(5);",
      "        System.out.println(a.getAndIncrement() + \" \" + a.incrementAndGet() + \" \"",
      "                + a.addAndGet(10) + \" \" + a.updateAndGet(n -> n * 2));",
      "    }",
      "}",
    ],
    choices: ["5 7 17 34", "6 7 17 34", "5 6 16 32", "5 7 15 30", "6 8 18 36"],
    correct: [0],
    expected: { kind: "output", stdout: "5 7 17 34" },
    explanation:
      "getAndIncrement() は後置の i++ に相当し、増やす前の値 5 を返して内部の値を 6 にします。incrementAndGet() は前置の ++i に相当し、7 にしてから 7 を返します。addAndGet(10) は 17 を返し、updateAndGet は関数を適用した後の値 34 を返します。AtomicInteger のこれらの操作は、ロックを使わずに CPU の不可分な命令（比較交換＝CAS など）で「読み出しから書き込みまで」を 1 つの操作として行うため、複数スレッドから同時に呼んでも更新が失われません。",
  },
  {
    id: 10510,
    topic: "concurrency",
    variantOf: "gold-concurrency-monitor",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "WaitTest",
    code: [
      "public class WaitTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Object lock = new Object();",
      "        lock.wait(100);",
      '        System.out.println("done");',
      "    }",
      "}",
    ],
    choices: [
      "実行時に IllegalMonitorStateException がスローされる",
      "約 100 ミリ秒後に done と出力される",
      "done と出力され、プログラムは終了しない",
      "4行目でコンパイルエラーになる",
      "実行時に InterruptedException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalMonitorStateException" },
    explanation:
      "wait() / notify() / notifyAll() は、そのオブジェクトのモニター（ロック）を保持しているスレッド、つまり synchronized (lock) ブロックの中からしか呼び出せません。ロックを持たずに lock.wait(100) を呼んだため、IllegalMonitorStateException がスローされます。wait は「ロックを手放して待ち、通知されたら再びロックを取得して戻る」という操作なので、手放すべきロックを持っていないと意味を成さないのです。この制約はコンパイル時には検査されないため、wait は必ず synchronized ブロック内で、条件を while で確認しながら呼ぶのが定型です。",
  },
  {
    id: 10511,
    topic: "concurrency",
    variantOf: "gold-concurrency-monitor",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LockTest",
    code: [
      "import java.util.concurrent.locks.*;",
      "",
      "public class LockTest {",
      "    public static void main(String[] args) {",
      "        ReentrantLock lock = new ReentrantLock();",
      "        lock.lock();",
      "        lock.lock();",
      "        System.out.print(lock.getHoldCount() + \" \");",
      "        lock.unlock();",
      "        lock.unlock();",
      "        System.out.print(lock.isLocked() + \" \");",
      "        lock.unlock();",
      "    }",
      "}",
    ],
    choices: [
      "2 false と出力された後、IllegalMonitorStateException がスローされる",
      "2 false",
      "1 false と出力された後、IllegalMonitorStateException がスローされる",
      "7行目でデッドロックになり、プログラムは終了しない",
      "2 true と出力された後、IllegalMonitorStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalMonitorStateException", stdout: "2 false" },
    explanation:
      "ReentrantLock は名前のとおり再入可能で、ロックを保持しているスレッドが再度 lock() してもブロックされず、保持回数が増えるだけです（getHoldCount() は 2）。ロックが解放されるのは lock() と同じ回数だけ unlock() したときで、2 回の unlock() で isLocked() は false になります。保持していないロックをさらに unlock() すると IllegalMonitorStateException がスローされます。synchronized と違いロックの解放は自動ではないため、lock() の直後から try を始め、finally で unlock() するのが定型です。",
  },

  // ------------------------------------------------------------ 並行コレクション
  {
    id: 10512,
    topic: "concurrency",
    variantOf: "gold-concurrency-cow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CowTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class CowTest {",
      "    public static void main(String[] args) {",
      '        List<String> list = new CopyOnWriteArrayList<>(List.of("a", "b"));',
      "        for (String s : list) {",
      '            list.add(s + "!");',
      "        }",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[a, b, a!, b!]",
      "実行時に ConcurrentModificationException がスローされる",
      "[a, b, a!, b!, a!!, b!!]",
      "[a, b]",
      "プログラムが終了しない",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[a, b, a!, b!]" },
    explanation:
      "CopyOnWriteArrayList は、変更のたびに内部の配列をまるごとコピーして新しい配列に差し替えます。Iterator は作成された時点の配列（スナップショット）を参照し続けるため、ループ中に add しても ConcurrentModificationException は起きず、反復されるのは元の a と b の 2 回だけです。追加した要素はループ後のリストには反映されているので [a, b, a!, b!] になります。読み取りが圧倒的に多く変更がまれな場面（イベントリスナーの一覧など）で、ロックなしに安全に反復できるよう設計されたコレクションです。",
  },
  {
    id: 10513,
    topic: "concurrency",
    variantOf: "gold-concurrency-cow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CowRemove",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class CowRemove {",
      "    public static void main(String[] args) {",
      '        List<String> list = new CopyOnWriteArrayList<>(List.of("a", "b", "c"));',
      "        Iterator<String> it = list.iterator();",
      '        list.remove("a");',
      "        System.out.print(it.next() + \" \" + list + \" \");",
      "        it.remove();",
      "    }",
      "}",
    ],
    choices: [
      "a [b, c] と出力された後、UnsupportedOperationException がスローされる",
      "b [b, c] と出力された後、UnsupportedOperationException がスローされる",
      "a [b, c]",
      "実行時に ConcurrentModificationException がスローされる",
      "a [a, b, c] と出力された後、UnsupportedOperationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedOperationException", stdout: "a [b, c]" },
    explanation:
      "CopyOnWriteArrayList の Iterator は作成時点の配列のスナップショットを反復するため、その後にリストから \"a\" を削除しても、it.next() は削除前の配列の先頭である a を返します。リスト自体は [b, c] になっています。スナップショットはリストの現在の内容とつながっていないので、Iterator 経由で要素を削除する remove() はサポートされず、UnsupportedOperationException がスローされます。反復中の安全性と引き換えに「反復中に見える内容は古いかもしれない」という性質を持つことを理解して使う必要があります。",
  },
  {
    id: 10514,
    topic: "concurrency",
    variantOf: "gold-concurrency-chm",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ChmNull",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class ChmNull {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> hash = new HashMap<>();",
      "        Map<String, Integer> chm = new ConcurrentHashMap<>();",
      '        hash.put("k", null);',
      '        System.out.print(hash.containsKey("k") + " ");',
      '        chm.put("k", null);',
      '        System.out.println(chm.containsKey("k"));',
      "    }",
      "}",
    ],
    choices: [
      "true と出力された後、NullPointerException がスローされる",
      "true true",
      "true false",
      "false false",
      "10行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "true" },
    explanation:
      "HashMap は null のキーや値を格納できますが、ConcurrentHashMap は null のキーも値も受け付けず、put で NullPointerException をスローします。複数スレッドから同時に使うマップでは、get が null を返したときに「キーが無い」のか「値が null」なのかを containsKey で確かめる間に、別スレッドが内容を変えてしまうかもしれません。null を禁止することで「get の結果が null ならキーは無い」と 1 回の操作で判断できるようにしているのです。",
  },
  {
    id: 10515,
    topic: "concurrency",
    variantOf: "gold-concurrency-chm",
    question: "次のコードを実行した場合に、必ず出力される値はどれか。1つ選びなさい。",
    className: "ChmMerge",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "import java.util.stream.*;",
      "",
      "public class ChmMerge {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> map = new ConcurrentHashMap<>();",
      "        IntStream.range(0, 1000).parallel()",
      '                .forEach(i -> map.merge(i % 2 == 0 ? "even" : "odd", 1, Integer::sum));',
      "        System.out.println(new TreeMap<>(map));",
      "    }",
      "}",
    ],
    choices: [
      "{even=500, odd=500}",
      "{even=1, odd=1}",
      "合計が 1000 以下の不定な値（実行するたびに変わりうる）",
      "実行時に ConcurrentModificationException がスローされる",
      "{even=1000, odd=1000}",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{even=500, odd=500}" },
    explanation:
      "ConcurrentHashMap の merge は、キーに対する「読み出し・合成・書き込み」を不可分な 1 つの操作として実行します。そのため並列ストリームの複数スレッドから同じキーに対して同時に merge しても更新は失われず、偶数・奇数それぞれ 500 回ずつ正確に数えられます。get で値を取り出して 1 を足し put し直す書き方では、個々のメソッドがスレッドセーフでも操作の間に他スレッドが割り込み、結果が不定になります。並行コレクションでは、merge / compute / putIfAbsent のような複合操作用のメソッドを使うことが重要です。",
  },

  // ---------------------------------------------------------------------- Flow
  {
    id: 10516,
    topic: "concurrency",
    variantOf: "gold-concurrency-flow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlowConsume",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class FlowConsume {",
      "    public static void main(String[] args) {",
      "        SubmissionPublisher<Integer> pub = new SubmissionPublisher<>();",
      "        CompletableFuture<Void> done = pub.consume(n -> System.out.print(n * 2 + \" \"));",
      "        pub.submit(1);",
      "        pub.submit(2);",
      "        pub.submit(3);",
      "        pub.close();",
      "        done.join();",
      '        System.out.println("end");',
      "    }",
      "}",
    ],
    choices: [
      "2 4 6 end",
      "end",
      "end 2 4 6",
      "2、4、6 の出力順序は保証されない",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "2 4 6 end" },
    explanation:
      "SubmissionPublisher は java.util.concurrent.Flow の Publisher の標準実装で、submit した要素を購読者に非同期で配信します。consume はすべての要素を受け取る購読者を登録し、配信が完了すると完了する CompletableFuture を返します。1 つの購読者への配信は submit した順に行われ、close() で完了が通知されるので、done.join() で待てば 2 4 6 のあとに end が出力されます。発行側と購読側を別スレッドで動かしつつ、完了や順序を型で扱えるのが Flow の利点です。",
  },
  {
    id: 10517,
    topic: "concurrency",
    variantOf: "gold-concurrency-flow",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlowRequest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class FlowRequest {",
      "    static class Printer implements Flow.Subscriber<String> {",
      "        final CountDownLatch received = new CountDownLatch(1);",
      "",
      "        public void onSubscribe(Flow.Subscription s) {",
      "            s.request(1);",
      "        }",
      "        public void onNext(String item) {",
      "            System.out.print(item + \" \");",
      "            received.countDown();",
      "        }",
      "        public void onError(Throwable t) {",
      '            System.out.print("error ");',
      "        }",
      "        public void onComplete() {",
      '            System.out.print("complete ");',
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws InterruptedException {",
      "        SubmissionPublisher<String> pub = new SubmissionPublisher<>();",
      "        Printer p = new Printer();",
      "        pub.subscribe(p);",
      '        pub.submit("a");',
      '        pub.submit("b");',
      '        pub.submit("c");',
      "        pub.close();",
      "        p.received.await();",
      "        Thread.sleep(500);",
      '        System.out.println("end");',
      "    }",
      "}",
    ],
    choices: [
      "a end",
      "a b c complete end",
      "a complete end",
      "end",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "a end" },
    explanation:
      "Flow の購読者は、Subscription.request(n) で「あと n 件まで受け取れる」と要求した分だけ onNext で要素を受け取ります（背圧制御）。この購読者は onSubscribe で request(1) を 1 回呼ぶだけで、onNext で追加の要求をしていないため、a だけが配信されて b と c は発行側のバッファに残ります。SubmissionPublisher は未配信の要素がすべて届いてから onComplete を通知するため、complete も出力されません。処理の遅い購読者が要求量で流量を調整できるのが Flow の目的であり、全件を受け取るには onNext の中で次の request を呼ぶ必要があります。",
  },
];
