import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: 並列処理の追加問題（id 10518-10599）。
 * 同期化ユーティリティ（CountDownLatch / CyclicBarrier）、CompletableFuture、BlockingQueue、割り込みなど。
 * 実行のたびに結果が変わらないよう、スレッドの完了は join / get / await で必ず待つ。
 */
export const goldConcurrencyQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ Future.get の検査例外
  {
    id: 10518,
    topic: "concurrency",
    variantOf: "gold-concurrency-future",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "FutureGet",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class FutureGet {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      "        Future<Integer> f = ex.submit(() -> 1 + 2);",
      "        ex.shutdown();",
      "        ex.awaitTermination(1, TimeUnit.SECONDS);",
      "        System.out.println(f.isDone());",
      "        System.out.println(f.get());",
      "    }",
      "}",
    ],
    choices: [
      "10行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 10 },
    explanation:
      "Future.get() は InterruptedException と ExecutionException の 2 つの検査例外をスローすると宣言されています。main は InterruptedException だけを throws に宣言しているので、ExecutionException が処理されずに10行目がコンパイルエラーになります。awaitTermination（8行目）は InterruptedException だけなので問題ありません。ExecutionException は「タスクの中で例外が起きた」ことを表し、元の例外は getCause() で取り出せます。タスクが別スレッドで失敗しても、結果を受け取る側でその失敗に対処するよう、get の呼び出し時に検査例外として強制されているのです。",
  },

  // ------------------------------------------------------------ ScheduledExecutorService
  {
    id: 10519,
    topic: "concurrency",
    variantOf: "gold-concurrency-scheduled",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ScheduleTest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class ScheduleTest {",
      "    public static void main(String[] args) throws Exception {",
      "        ScheduledExecutorService ses = Executors.newSingleThreadScheduledExecutor();",
      "        ScheduledFuture<String> late = ses.schedule(() -> \"late\", 300, TimeUnit.MILLISECONDS);",
      "        ScheduledFuture<String> soon = ses.schedule(() -> \"soon\", 50, TimeUnit.MILLISECONDS);",
      "        System.out.print(late.isDone() + \" \");",
      "        System.out.print(soon.get() + \" \");",
      "        System.out.println(late.get());",
      "        ses.shutdown();",
      "    }",
      "}",
    ],
    choices: ["false soon late", "false late soon", "true soon late", "false soon と出力された後、例外がスローされる", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false soon late" },
    explanation:
      "ScheduledExecutorService.schedule は、指定した遅延の後にタスクを 1 回実行し、結果を ScheduledFuture で返します。タスクは登録した順ではなく実行予定時刻の順に実行されますが、ここでは各 Future から個別に結果を get しているので、出力は get を呼んだ順（soon → late）になります。直後の isDone は 300 ミリ秒経っていないので false です。定期実行には scheduleAtFixedRate（開始時刻の間隔を一定に保つ）や scheduleWithFixedDelay（前回の終了から一定の間隔をあける）を使います。",
  },

  // ------------------------------------------------------------ CountDownLatch
  {
    id: 10520,
    topic: "concurrency",
    variantOf: "gold-concurrency-sync-utility",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LatchTest",
    code: [
      "import java.util.concurrent.*;",
      "import java.util.concurrent.atomic.*;",
      "",
      "public class LatchTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        CountDownLatch latch = new CountDownLatch(3);",
      "        AtomicInteger sum = new AtomicInteger();",
      "        ExecutorService ex = Executors.newFixedThreadPool(3);",
      "        for (int i = 1; i <= 3; i++) {",
      "            int n = i;",
      "            ex.execute(() -> {",
      "                sum.addAndGet(n * 10);",
      "                latch.countDown();",
      "            });",
      "        }",
      "        latch.await();",
      "        System.out.println(sum.get() + \" \" + latch.getCount());",
      "        ex.shutdown();",
      "    }",
      "}",
    ],
    choices: ["60 0", "60 3", "0 3", "実行のたびに 0〜60 のいずれかが出力される", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "60 0" },
    explanation:
      "CountDownLatch はカウンタが 0 になるまで await を呼んだスレッドを待たせる同期化ユーティリティです。3 つのタスクがそれぞれ加算した後に countDown するので、await から戻った時点では 3 回の加算がすべて終わっており、合計 60、カウントは 0 です。10行目の int n = i は、ラムダ式が変化するループ変数 i を捕捉できないため、実質的 final なコピーを作っています。CountDownLatch は一度 0 になると元に戻らない使い捨てのゲートなので、「複数の準備が完了するまで待つ」場面に向いています。",
  },
  {
    id: 10521,
    topic: "concurrency",
    variantOf: "gold-concurrency-sync-utility",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "BarrierTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class BarrierTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        List<String> log = Collections.synchronizedList(new ArrayList<>());",
      "        CyclicBarrier barrier = new CyclicBarrier(3, () -> log.add(\"go\"));",
      "        List<Thread> threads = new ArrayList<>();",
      "        for (int i = 0; i < 3; i++) {",
      "            Thread t = new Thread(() -> {",
      "                try {",
      "                    barrier.await();",
      "                } catch (InterruptedException | BrokenBarrierException e) {",
      "                    log.add(\"error\");",
      "                }",
      "            });",
      "            threads.add(t);",
      "            t.start();",
      "        }",
      "        for (Thread t : threads) t.join();",
      "        System.out.println(log + \" \" + barrier.getNumberWaiting());",
      "    }",
      "}",
    ],
    choices: ["[go] 0", "[go, go, go] 0", "[go] 3", "[] 0", "12行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[go] 0" },
    explanation:
      "CyclicBarrier は、指定した数（3）のスレッドが await に到達するまで全員を待たせ、そろった時点で全員を同時に先へ進めます。コンストラクタに渡したバリア・アクションは、そろったときに 1 回だけ（最後に到達したスレッドで）実行されるので、go は 1 つだけ記録されます。全員が解放された後は待機中のスレッドは 0 で、バリアは次の周回に使えるようにリセットされます。CountDownLatch が使い捨てなのに対し、CyclicBarrier は「全員がそろってから次の段階へ」を繰り返す処理に使えるのが違いです。",
  },

  // ------------------------------------------------------------ CompletableFuture
  {
    id: 10522,
    topic: "concurrency",
    variantOf: "gold-concurrency-completable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CombineTest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class CombineTest {",
      "    public static void main(String[] args) {",
      "        CompletableFuture<Integer> price = CompletableFuture.supplyAsync(() -> 100);",
      "        CompletableFuture<Integer> qty = CompletableFuture.supplyAsync(() -> 3);",
      "        CompletableFuture<String> total = price",
      "                .thenCombine(qty, (p, q) -> p * q)",
      "                .thenApply(n -> \"total=\" + n);",
      "        total.thenAccept(s -> System.out.print(s + \" \")).join();",
      "        System.out.println(total.isDone());",
      "    }",
      "}",
    ],
    choices: ["total=300 true", "total=300 false", "total=103 true", "true total=300", "8行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "total=300 true" },
    explanation:
      "supplyAsync は値を返すタスクを非同期に実行し、CompletableFuture を返します。thenCombine は 2 つの Future が両方完了したら結果を関数で結合し、thenApply は結果を変換します。どちらもブロックせずに「完了したら行う処理」を登録するだけです。thenAccept が返す Future を join で待つので、total=300 が出力された後に total.isDone() が評価され、既に完了しているので true です。Future.get で結果を待ってから次の処理を書く代わりに、処理の依存関係を宣言的につなげられるのが CompletableFuture の利点です。",
  },
  {
    id: 10523,
    topic: "concurrency",
    variantOf: "gold-concurrency-completable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RecoverTest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class RecoverTest {",
      "    static int parse(String s) {",
      "        return Integer.parseInt(s);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        String r = CompletableFuture.supplyAsync(() -> parse(\"x\"))",
      "                .thenApply(n -> n * 2)",
      "                .exceptionally(e -> -1)",
      "                .thenApply(n -> \"result=\" + n)",
      "                .join();",
      "        System.out.println(r);",
      "    }",
      "}",
    ],
    choices: [
      "result=-1",
      "result=-2",
      "実行時に CompletionException がスローされる",
      "実行時に NumberFormatException がスローされる",
      "11行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "result=-1" },
    explanation:
      "supplyAsync のタスクで NumberFormatException が起きると、その CompletableFuture は「例外で完了」した状態になります。例外で完了した段の後続の thenApply(n -> n * 2) は実行されずに飛ばされ、exceptionally に到達して、例外の代わりの値 -1 で正常に完了し直します。その後の thenApply は通常どおり実行され result=-1 になります。exceptionally が無ければ join は CompletionException（原因は NumberFormatException）をスローします。try-catch と同じく、回復処理を置いた位置より後ろでは正常な流れに戻るという構造です。",
  },
  {
    id: 10524,
    topic: "concurrency",
    variantOf: "gold-concurrency-completable",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AllOfTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class AllOfTest {",
      "    public static void main(String[] args) {",
      "        List<CompletableFuture<String>> list = List.of(",
      "                CompletableFuture.supplyAsync(() -> \"a\"),",
      "                CompletableFuture.supplyAsync(() -> \"b\"),",
      "                CompletableFuture.supplyAsync(() -> \"c\"));",
      "        CompletableFuture<Void> all = CompletableFuture.allOf(list.toArray(new CompletableFuture[0]));",
      "        String joined = all.thenApply(v -> {",
      "            StringBuilder sb = new StringBuilder();",
      "            for (CompletableFuture<String> f : list) sb.append(f.join());",
      "            return sb.toString();",
      "        }).join();",
      "        System.out.println(joined + \" \" + all.join());",
      "    }",
      "}",
    ],
    choices: ["abc null", "abc abc", "実行のたびに a、b、c の並び順が変わる", "abc と出力された後、例外がスローされる", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "abc null" },
    explanation:
      "CompletableFuture.allOf は、渡したすべての Future が完了したときに完了する CompletableFuture<Void> を返します。型が Void であることからわかるように、個々の結果は含まれず、join すると null が返ります。そのため thenApply の中で元の Future を順に join して結果を集めています。この時点で全員完了済みなのでブロックせず、リストの順序どおり abc になります（タスクの実行順とは無関係です）。複数の非同期処理の完了をまとめて待つときの定番の書き方です。",
  },

  // ------------------------------------------------------------ スレッドの状態と割り込み
  {
    id: 10525,
    topic: "concurrency",
    variantOf: "gold-concurrency-thread-lifecycle",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ThreadState",
    code: [
      "public class ThreadState {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Thread t = new Thread(() -> { });",
      "        System.out.print(t.getState() + \" \");",
      "        t.start();",
      "        t.join();",
      "        System.out.println(t.getState() + \" \" + t.isAlive());",
      "    }",
      "}",
    ],
    choices: ["NEW TERMINATED false", "RUNNABLE TERMINATED false", "NEW RUNNABLE true", "NEW TERMINATED true", "NEW WAITING false"],
    correct: [0],
    expected: { kind: "output", stdout: "NEW TERMINATED false" },
    explanation:
      "Thread オブジェクトを作っただけで start していない状態は NEW です。start すると RUNNABLE になり、run メソッドが終わると TERMINATED になります。join はそのスレッドが終了するまで待つので、その後は必ず TERMINATED で、isAlive も false です。途中の状態には、ロックを待つ BLOCKED、wait や join で待つ WAITING、時間指定で待つ TIMED_WAITING があります。終了したスレッドは再び start できないので、同じ処理を繰り返すにはスレッド・プールにタスクとして投入します。",
  },
  {
    id: 10526,
    topic: "concurrency",
    variantOf: "gold-concurrency-thread-lifecycle",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "InterruptTest",
    code: [
      "public class InterruptTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Thread t = new Thread(() -> {",
      "            try {",
      "                Thread.sleep(10_000);",
      "                System.out.print(\"woke \");",
      "            } catch (InterruptedException e) {",
      "                System.out.print(\"interrupted \" + Thread.currentThread().isInterrupted() + \" \");",
      "            }",
      "        });",
      "        t.start();",
      "        t.interrupt();",
      "        t.join();",
      "        System.out.println(\"end\");",
      "    }",
      "}",
    ],
    choices: [
      "interrupted false end",
      "interrupted true end",
      "woke end",
      "end",
      "5行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "interrupted false end" },
    explanation:
      "interrupt() はスレッドを強制停止するのではなく、「割り込み状態」のフラグを立てて中断を依頼するだけです。sleep や wait などで待機中のスレッド（または待機に入ろうとするスレッド）は、フラグが立っていると InterruptedException をスローして待機を抜けます。このとき割り込み状態はクリアされるので、catch の中で isInterrupted() を調べると false です。InterruptedException を捕捉して握りつぶすと、呼び出し元は中断が依頼されたことを知る手段を失うので、処理を終了するか Thread.currentThread().interrupt() でフラグを立て直すのが作法です。",
  },
  {
    id: 10527,
    topic: "concurrency",
    variantOf: "gold-concurrency-thread-lifecycle",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DaemonTest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class DaemonTest {",
      "    public static void main(String[] args) {",
      "        CountDownLatch gate = new CountDownLatch(1);",
      "        Thread t = new Thread(() -> {",
      "            try {",
      "                gate.await();",
      "            } catch (InterruptedException e) {",
      "                Thread.currentThread().interrupt();",
      "            }",
      "        });",
      "        System.out.print(t.isDaemon() + \" \");",
      "        t.start();",
      "        try {",
      "            t.setDaemon(true);",
      "            System.out.println(t.isDaemon());",
      "        } finally {",
      "            gate.countDown();",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "false と出力された後、IllegalThreadStateException がスローされる",
      "false true",
      "true true",
      "false false",
      "16行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalThreadStateException", stdout: "false" },
    explanation:
      "新しいスレッドはデーモンかどうかを作成元のスレッドから引き継ぎ、main スレッドは非デーモンなので false です。デーモン・スレッドは「非デーモン・スレッドがすべて終われば JVM が終了してよい」補助的なスレッドを表し、setDaemon は start する前に呼ばなければなりません。t は latch で待機しているので確実に生存中であり、そのスレッドに対して setDaemon を呼ぶと IllegalThreadStateException がスローされます（finally で latch を開けるので t も終了し、プログラムは例外で終わります）。デーモン・スレッドは JVM の終了時に finally も実行されずに打ち切られるので、ファイルの書き込みなど完了を保証したい処理には使いません。",
  },

  // ------------------------------------------------------------ BlockingQueue
  {
    id: 10528,
    topic: "concurrency",
    variantOf: "gold-concurrency-blocking-queue",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "BoundedQueue",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class BoundedQueue {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        BlockingQueue<String> q = new ArrayBlockingQueue<>(2);",
      "        System.out.print(q.offer(\"a\") + \" \" + q.offer(\"b\") + \" \" + q.offer(\"c\") + \" \");",
      "        System.out.print(q.offer(\"d\", 100, TimeUnit.MILLISECONDS) + \" \");",
      "        System.out.print(q.poll() + \" \");",
      "        q.add(\"e\");",
      "        q.add(\"f\");",
      "    }",
      "}",
    ],
    choices: [
      "true true false false a と出力された後、IllegalStateException がスローされる",
      "true true false false a と出力され、正常終了する",
      "true true true true a と出力された後、IllegalStateException がスローされる",
      "true true と出力された後、プログラムが停止したまま終了しない",
      "true true false false a と出力された後、プログラムが停止したまま終了しない",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalStateException", stdout: "true true false false a" },
    explanation:
      "ArrayBlockingQueue は容量が固定のキューで、満杯のときの振る舞いがメソッドごとに異なります。offer はすぐに false を返し、時間指定の offer は指定時間だけ空きを待ってから false を返します。add は例外（IllegalStateException）をスローし、put は空きができるまでいつまでも待ちます。poll で a を取り出して空きが 1 つできるので e は追加できますが、f で再び満杯になり add が例外をスローします。生産者と消費者の速度差を吸収するキューでは、満杯時に「待つ」「諦める」「失敗させる」のどれにするかをメソッドの選択で決めます。",
  },
  {
    id: 10529,
    topic: "concurrency",
    variantOf: "gold-concurrency-blocking-queue",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ProducerConsumer",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class ProducerConsumer {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        BlockingQueue<Integer> q = new LinkedBlockingQueue<>(1);",
      "        int[] total = {0};",
      "        Thread consumer = new Thread(() -> {",
      "            try {",
      "                for (int n = q.take(); n >= 0; n = q.take()) total[0] += n;",
      "            } catch (InterruptedException e) {",
      "                Thread.currentThread().interrupt();",
      "            }",
      "        });",
      "        consumer.start();",
      "        for (int i = 1; i <= 4; i++) q.put(i);",
      "        q.put(-1);",
      "        consumer.join();",
      "        System.out.println(total[0] + \" \" + q.size());",
      "    }",
      "}",
    ],
    choices: ["10 0", "9 1", "10 1", "実行のたびに 0〜10 のいずれかが出力される", "プログラムが停止したまま終了しない"],
    correct: [0],
    expected: { kind: "output", stdout: "10 0" },
    explanation:
      "put はキューに空きができるまで、take は要素が届くまで待機します。容量 1 のキューでも、生産者（main）は消費者が取り出すたびに次の値を入れられるので、1〜4 と終了の合図 -1 がすべて順に渡されます。消費者は -1 を受け取るとループを抜けて終了し、join から戻った main は合計 10 と、空になったキューの要素数 0 を出力します。このように「これ以上データが無い」ことを特別な値で伝える方法をポイズン・ピルと呼びます。total[0] は消費者スレッドだけが書き込み、join によってその書き込みが main から見えることが保証されます。",
  },

  // ------------------------------------------------------------ 並行コレクション
  {
    id: 10530,
    topic: "concurrency",
    variantOf: "gold-concurrency-skiplist",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SkipListTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class SkipListTest {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> map = new ConcurrentSkipListMap<>();",
      "        map.put(\"pear\", 3);",
      "        map.put(\"apple\", 1);",
      "        map.put(\"fig\", 2);",
      "        for (String key : map.keySet()) {",
      "            if (key.startsWith(\"a\")) map.remove(key);",
      "        }",
      "        System.out.println(map);",
      "    }",
      "}",
    ],
    choices: [
      "{fig=2, pear=3}",
      "{pear=3, fig=2}",
      "{pear=3, fig=2, apple=1}",
      "実行時に ConcurrentModificationException がスローされる",
      "6行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{fig=2, pear=3}" },
    explanation:
      "ConcurrentSkipListMap は TreeMap の並行版で、キーを自然順序（または Comparator の順）に保ちます。並行コレクションのイテレータは「弱い整合性」を持ち、反復中に別の操作（同じスレッドからの remove を含む）でコレクションが変更されても ConcurrentModificationException をスローしません。そのため apple を削除でき、{fig=2, pear=3} が残ります。TreeMap で同じことをすると例外になります。複数スレッドから読み書きされ、かつ順序付きで扱いたいデータには ConcurrentSkipListMap / ConcurrentSkipListSet を使います。",
  },

  // ------------------------------------------------------------ Lock の tryLock
  {
    id: 10531,
    topic: "concurrency",
    variantOf: "gold-concurrency-trylock",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TryLockTest",
    code: [
      "import java.util.concurrent.locks.*;",
      "",
      "public class TryLockTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Lock lock = new ReentrantLock();",
      "        boolean[] got = new boolean[2];",
      "        lock.lock();",
      "        try {",
      "            Thread t = new Thread(() -> got[0] = lock.tryLock());",
      "            t.start();",
      "            t.join();",
      "            got[1] = lock.tryLock();",
      "            if (got[1]) lock.unlock();",
      "        } finally {",
      "            lock.unlock();",
      "        }",
      "        System.out.println(got[0] + \" \" + got[1]);",
      "    }",
      "}",
    ],
    choices: ["false true", "true true", "false false", "true false", "プログラムが停止したまま終了しない"],
    correct: [0],
    expected: { kind: "output", stdout: "false true" },
    explanation:
      "tryLock() はロックを取得できればすぐに true を返し、他のスレッドが保持していれば待たずに false を返します。main がロックを保持している間に別スレッドが tryLock を呼ぶので false です。一方 ReentrantLock は再入可能なので、保持しているスレッド自身が tryLock を呼ぶと成功して true になり、保持回数が 2 に増えます（そのため unlock も 2 回必要です）。synchronized ブロックはロックを待ち始めたら取得するまで抜けられませんが、Lock の tryLock を使えば「取れなければ別の処理をする」ことでデッドロックを避ける設計ができます。",
  },

  // ------------------------------------------------------------ Runnable と Callable
  {
    id: 10532,
    topic: "concurrency",
    variantOf: "gold-concurrency-callable-checked",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "SubmitSleep",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class SubmitSleep {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      "        Future<String> a = ex.submit(() -> {",
      "            Thread.sleep(10);",
      "            return \"a\";",
      "        });",
      "        Future<?> b = ex.submit(() -> {",
      "            Thread.sleep(10);",
      "        });",
      "        System.out.println(a.get());",
      "        ex.shutdown();",
      "    }",
      "}",
    ],
    choices: [
      "11行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 11 },
    explanation:
      "submit は Callable と Runnable の両方でオーバーロードされており、ラムダ式が値を返すかどうかでどちらになるかが決まります。6〜9行目は値を返すので Callable<String> になり、Callable.call() は throws Exception を宣言しているので、sleep の InterruptedException をそのままスローできます。10〜12行目は値を返さないので Runnable になりますが、Runnable.run() は検査例外を宣言していないため、sleep の InterruptedException を処理していない11行目がコンパイルエラーになります。値を返さないタスクで検査例外を扱いたい場合は、return null; を書いて Callable にする方法もあります。",
  },

  // ------------------------------------------------------------ invokeAny
  {
    id: 10533,
    topic: "concurrency",
    variantOf: "gold-concurrency-invokeall",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "InvokeAnyTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class InvokeAnyTest {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newFixedThreadPool(3);",
      "        List<Callable<String>> tasks = List.of(",
      "                () -> { throw new IllegalStateException(\"a\"); },",
      "                () -> \"b\",",
      "                () -> { throw new IllegalStateException(\"c\"); });",
      "        String r = ex.invokeAny(tasks);",
      "        ex.shutdown();",
      "        System.out.println(r);",
      "    }",
      "}",
    ],
    choices: [
      "b",
      "実行時に ExecutionException がスローされる",
      "実行時に IllegalStateException がスローされる",
      "実行のたびに a、b、c のいずれかが出力される",
      "8行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "b" },
    explanation:
      "invokeAny は複数のタスクを実行し、例外を出さずに正常に完了したいずれか 1 つの結果を返します（残りのタスクは取り消されます）。例外で終わったタスクの結果は採用されないので、正常に完了するのが \"b\" のタスクだけであるこのコードでは、必ず b が返ります。すべてのタスクが例外で終わった場合に限り ExecutionException がスローされます。すべての結果を順序どおりに受け取る invokeAll に対し、invokeAny は「複数の手段のうち最初に成功したものを使う」冗長化の用途に向いています。",
  },

  // ------------------------------------------------------------ shutdownNow
  {
    id: 10534,
    topic: "concurrency",
    variantOf: "gold-concurrency-shutdown",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ShutdownNowTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class ShutdownNowTest {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newSingleThreadExecutor();",
      "        CountDownLatch started = new CountDownLatch(1);",
      "        ex.execute(() -> {",
      "            started.countDown();",
      "            try {",
      "                Thread.sleep(10_000);",
      "            } catch (InterruptedException e) {",
      "                System.out.print(\"stopped \");",
      "            }",
      "        });",
      "        ex.execute(() -> System.out.print(\"second \"));",
      "        ex.execute(() -> System.out.print(\"third \"));",
      "        started.await();",
      "        List<Runnable> pending = ex.shutdownNow();",
      "        ex.awaitTermination(5, TimeUnit.SECONDS);",
      "        System.out.println(pending.size());",
      "    }",
      "}",
    ],
    choices: ["stopped 2", "stopped second third 0", "2", "second third stopped 0", "stopped 3"],
    correct: [0],
    expected: { kind: "output", stdout: "stopped 2" },
    explanation:
      "shutdownNow は新しいタスクの受け付けを止めるだけでなく、キューで待っているタスクを実行せずに取り除いてリストで返し、実行中のタスクには interrupt で中断を依頼します。1 つ目のタスクは開始済み（latch で確認済み）で sleep 中なので、割り込まれて stopped を出力します。second と third はまだ開始していないので実行されず、返されたリストの 2 件になります。shutdown が「受け付けを止めて、投入済みのタスクは最後までやる」穏やかな停止なのに対し、shutdownNow は即時停止を試みます。ただし割り込みに応答しないタスクは止められません。",
  },

  // ------------------------------------------------------------ LongAdder
  {
    id: 10535,
    topic: "concurrency",
    variantOf: "gold-concurrency-atomic",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AdderTest",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "import java.util.concurrent.atomic.*;",
      "",
      "public class AdderTest {",
      "    public static void main(String[] args) throws Exception {",
      "        LongAdder adder = new LongAdder();",
      "        AtomicInteger atomic = new AtomicInteger();",
      "        ExecutorService ex = Executors.newFixedThreadPool(4);",
      "        List<Future<?>> futures = new ArrayList<>();",
      "        for (int i = 0; i < 4; i++) {",
      "            futures.add(ex.submit(() -> {",
      "                for (int j = 0; j < 1000; j++) {",
      "                    adder.increment();",
      "                    atomic.compareAndSet(0, 100);",
      "                }",
      "            }));",
      "        }",
      "        for (Future<?> f : futures) f.get();",
      "        ex.shutdown();",
      "        System.out.println(adder.sum() + \" \" + atomic.get());",
      "    }",
      "}",
    ],
    choices: ["4000 100", "4000 400000", "4000 0", "実行のたびに 4000 以下のいずれかと 100 が出力される", "14行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "4000 100" },
    explanation:
      "LongAdder はスレッドごとに分散したセルへ加算し、sum() で合計を求める加算専用のカウンタです。increment は原子的なので、4 スレッドが 1000 回ずつ加算した結果は必ず 4000 になり、競合が多い場面では AtomicLong より高速です。compareAndSet(0, 100) は「現在値が 0 なら 100 にする」を原子的に行うので、最初の 1 回だけ成功し、それ以降は現在値が 100 なので何も変わりません。f.get() ですべてのタスクの完了を待ってから読むので、結果は実行のたびに変わりません。",
  },

  // ------------------------------------------------------------ ReadWriteLock / Semaphore / Condition
  {
    id: 10536,
    topic: "concurrency",
    variantOf: "gold-concurrency-readwrite-lock",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ReadWriteTest",
    code: [
      "import java.util.concurrent.locks.*;",
      "",
      "public class ReadWriteTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        ReentrantReadWriteLock rw = new ReentrantReadWriteLock();",
      "        boolean[] r = new boolean[2];",
      "        rw.readLock().lock();",
      "        try {",
      "            Thread t = new Thread(() -> {",
      "                r[0] = rw.readLock().tryLock();",
      "                if (r[0]) rw.readLock().unlock();",
      "                r[1] = rw.writeLock().tryLock();",
      "            });",
      "            t.start();",
      "            t.join();",
      "        } finally {",
      "            rw.readLock().unlock();",
      "        }",
      "        System.out.println(r[0] + \" \" + r[1] + \" \" + rw.getReadLockCount());",
      "    }",
      "}",
    ],
    choices: ["true false 0", "false false 0", "true true 0", "true false 1", "プログラムが停止したまま終了しない"],
    correct: [0],
    expected: { kind: "output", stdout: "true false 0" },
    explanation:
      "ReadWriteLock は読み取り用と書き込み用の 2 つのロックを組にしたものです。読み取りロックは、書き込みロックが保持されていなければ複数のスレッドが同時に取得できるので、main が読み取りロックを持っていても別スレッドの tryLock は成功します。書き込みロックは排他的で、誰かが読み取りロックか書き込みロックを保持している間は取得できないため false です。最後に main が解放するので保持数は 0 になります。読み取りが多く書き込みが少ないデータ（設定のキャッシュなど）で、読み取り同士を並行させて性能を上げるための仕組みです。",
  },
  {
    id: 10537,
    topic: "concurrency",
    variantOf: "gold-concurrency-semaphore",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SemaphoreTest",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class SemaphoreTest {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Semaphore sem = new Semaphore(2);",
      "        sem.acquire();",
      "        System.out.print(sem.availablePermits() + \" \");",
      "        System.out.print(sem.tryAcquire() + \" \" + sem.tryAcquire() + \" \");",
      "        sem.release(3);",
      "        System.out.println(sem.availablePermits());",
      "    }",
      "}",
    ],
    choices: ["1 true false 3", "1 true false 2", "1 true true 3", "2 true false 3", "1 true と出力された後、プログラムが停止したまま終了しない"],
    correct: [0],
    expected: { kind: "output", stdout: "1 true false 3" },
    explanation:
      "Semaphore は「許可」の数を管理し、同時にリソースを使えるスレッドの数を制限します。許可 2 から acquire で 1 つ取ると残り 1、tryAcquire は許可があれば取って true、無ければ待たずに false を返します（acquire なら許可が返されるまで待ち続けます）。release は許可を返しますが、Semaphore は誰が許可を取ったかを記録していないので、取得した数を超えて返すこともでき、残りは 0 + 3 = 3 になります。ロックと違い所有者の概念が無いため、取得と返却の数を合わせるのはプログラムの責任です。接続プールの同時接続数の制限などに使われます。",
  },
  {
    id: 10538,
    topic: "concurrency",
    variantOf: "gold-concurrency-condition",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ConditionTest",
    code: [
      "import java.util.concurrent.locks.*;",
      "",
      "public class ConditionTest {",
      "    private final Lock lock = new ReentrantLock();",
      "    private final Condition ready = lock.newCondition();",
      "    private String message;",
      "",
      "    String take() throws InterruptedException {",
      "        lock.lock();",
      "        try {",
      "            while (message == null) ready.await();",
      "            return message;",
      "        } finally {",
      "            lock.unlock();",
      "        }",
      "    }",
      "",
      "    void put(String m) {",
      "        lock.lock();",
      "        try {",
      "            message = m;",
      "            ready.signalAll();",
      "        } finally {",
      "            lock.unlock();",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws InterruptedException {",
      "        ConditionTest box = new ConditionTest();",
      "        String[] got = new String[1];",
      "        Thread t = new Thread(() -> {",
      "            try {",
      "                got[0] = box.take();",
      "            } catch (InterruptedException e) {",
      "                got[0] = \"interrupted\";",
      "            }",
      "        });",
      "        t.start();",
      "        box.put(\"hello\");",
      "        t.join();",
      "        System.out.println(got[0]);",
      "    }",
      "}",
    ],
    choices: ["hello", "null", "interrupted", "実行のたびに hello か null のどちらかが出力される", "プログラムが停止したまま終了しない"],
    correct: [0],
    expected: { kind: "output", stdout: "hello" },
    explanation:
      "Condition は Lock と組み合わせて使う待機・通知の仕組みで、synchronized における wait / notifyAll に相当します。await はロックを一時的に手放して通知を待ち、signalAll で起こされるとロックを取り直してから戻ります。take は message が null の間だけ待つので、put が先に実行されても（待たずに）、後に実行されても（通知で起きて）、必ず hello を受け取ります。条件を if ではなく while で確認するのは、通知以外の理由で起きる「見せかけの起床」や、起きた時点で条件が変わっている場合に備えるためです。1 つの Lock から複数の Condition を作り、「空でない」「満杯でない」などの条件ごとに待たせ分けられるのが wait / notify に対する利点です。",
  },
  {
    id: 10539,
    topic: "concurrency",
    variantOf: "gold-concurrency-condition",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AwaitWithoutLock",
    code: [
      "import java.util.concurrent.*;",
      "import java.util.concurrent.locks.*;",
      "",
      "public class AwaitWithoutLock {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        Lock lock = new ReentrantLock();",
      "        Condition c = lock.newCondition();",
      "        lock.lock();",
      "        try {",
      "            System.out.print(c.await(10, TimeUnit.MILLISECONDS) + \" \");",
      "        } finally {",
      "            lock.unlock();",
      "        }",
      "        c.signal();",
      "        System.out.println(\"end\");",
      "    }",
      "}",
    ],
    choices: [
      "false と出力された後、IllegalMonitorStateException がスローされる",
      "false end",
      "true end",
      "true と出力された後、IllegalMonitorStateException がスローされる",
      "プログラムが停止したまま終了しない",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalMonitorStateException", stdout: "false" },
    explanation:
      "時間指定の await は、通知を受けずに時間切れになると false を返します（通知で起きた場合は true）。ここでは誰も signal しないので false です。Condition の await / signal は、その Condition を作った Lock を保持しているスレッドからしか呼べず、ロックを解放した後の14行目で signal を呼ぶと IllegalMonitorStateException がスローされます。synchronized ブロックの外で wait / notify を呼べないのと同じ規則で、条件の確認と待機・通知を同じロックの中で行わせることで、通知の取りこぼしを防いでいます。",
  },
];
