import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: 関数型インタフェースとラムダ式の追加問題（id 10217-10299）。
 * static ネスト・クラス、ローカル・クラス、実質的 final、java.util.function の合成メソッドなど。
 */
export const goldFunctionalQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ static ネスト・クラス
  {
    id: 10217,
    topic: "functional",
    variantOf: "gold-functional-static-nested",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Counter",
    code: [
      "public class Counter {",
      "    private int count = 1;",
      "    private static int total = 2;",
      "",
      "    static class Helper {",
      "        int read(Counter c) { return c.count; }",
      "        int total() { return total; }",
      "        int current() { return count; }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Helper().total());",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "static ネスト・クラスは外側クラスのインスタンスに結び付かないので、外側のインスタンス・フィールド count を単独の名前で参照する8行目はコンパイルエラーになります（どのインスタンスの count か決まらないため）。一方、外側クラスの static フィールドは参照でき（7行目）、引数で受け取ったインスタンスを通してなら private の count にもアクセスできます（6行目）。ネストしたクラスは外側クラスの一部なので private メンバーも見えますが、「暗黙の外側インスタンス」を持つのは static でない内部クラスだけ、というのが両者の本質的な違いです。外側のインスタンスを必要としないなら static ネスト・クラスにすると、不要な参照を保持せずに済みます。",
  },
  {
    id: 10218,
    topic: "functional",
    variantOf: "gold-functional-static-nested",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Builder",
    code: [
      "public class Builder {",
      "    private final String name;",
      "    private final int size;",
      "",
      "    private Builder(Inner b) {",
      "        this.name = b.name;",
      "        this.size = b.size;",
      "    }",
      "",
      "    static class Inner {",
      "        private String name = \"none\";",
      "        private int size;",
      "        Inner name(String n) { name = n; return this; }",
      "        Inner size(int s) { size = s; return this; }",
      "        Builder build() { return new Builder(this); }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Builder b = new Builder.Inner().size(3).build();",
      "        System.out.println(b.name + \":\" + b.size);",
      "    }",
      "}",
    ],
    choices: ["none:3", "null:3", ":3", "15行目でコンパイルエラーになる", "19行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "none:3" },
    explanation:
      "static ネスト・クラス Inner は外側のインスタンス無しに new Builder.Inner() で生成できます。ネストしたクラスと外側クラスは互いの private メンバーにアクセスできるので、Inner から Builder の private コンストラクタを呼ぶこと（15行目）も、Builder から Inner の private フィールドを読むこと（6・7行目）も許されます。name は初期値 \"none\" のまま、size は 3 に設定されて none:3 と出力されます。これはビルダー・パターンの典型的な形で、コンストラクタを private にして生成手段をネスト・クラスに限定できるのは、ネスト・クラスが外側クラスのカプセル化の内側にいるからです。",
  },

  // ------------------------------------------------------------ ローカル・クラスとローカル・レコード
  {
    id: 10219,
    topic: "functional",
    variantOf: "gold-functional-local-class",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "LocalClass",
    code: [
      "public class LocalClass {",
      "    private int base = 100;",
      "",
      "    void run() {",
      "        int step = 5;",
      "        int limit = 10;",
      "        class Adder {",
      "            int add(int n) { return base + n + step; }",
      "            int max() { return limit; }",
      "        }",
      "        limit = 20;",
      "        System.out.println(new Adder().add(1));",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new LocalClass().run();",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "ローカル・クラスはメソッドのローカル変数を参照できますが、その変数は final か実質的に final（初期化後に一度も代入されない）でなければなりません。limit は11行目で再代入されているので実質的 final ではなく、それを参照している9行目がコンパイルエラーになります（エラーは代入側ではなく参照側で報告されます）。step は再代入されていないので8行目は問題なく、外側クラスのフィールド base もこの制約を受けません。ローカル・クラスのインスタンスはメソッドの終了後も生き残りうるため、参照したローカル変数は値としてコピーされます。後から値が変わるとコピーと食い違ってしまうので、変わらない変数だけを捕捉できる規則になっています。",
  },
  {
    id: 10220,
    topic: "functional",
    variantOf: "gold-functional-local-class",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "LocalRecord",
    code: [
      "public class LocalRecord {",
      "    static int scale = 10;",
      "",
      "    public static void main(String[] args) {",
      "        int offset = 1;",
      "        record Point(int x, int y) {",
      "            int scaled() { return x * scale; }",
      "            int shifted() { return x + offset; }",
      "        }",
      "        Point p = new Point(2, 3);",
      "        System.out.println(p.scaled() + \" \" + p);",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "メソッドの中で宣言したレコード（ローカル・レコード）は暗黙に static で、ローカル・クラスと違って外側のメソッドのローカル変数を捕捉できません。offset は実質的 final ですが、それでも8行目の参照はコンパイルエラーになります。一方、static フィールドの scale は外側のインスタンスもローカル変数も必要としないので7行目は問題ありません。レコードは「宣言したコンポーネントだけがデータのすべて」という透明なデータの入れ物なので、隠れた状態（捕捉した変数や外側のインスタンスへの参照）を持たせない設計になっているのです。ローカルのインタフェースや列挙型も同じく暗黙に static です。",
  },

  // ------------------------------------------------------------ 実質的 final とラムダ式
  {
    id: 10221,
    topic: "functional",
    variantOf: "gold-functional-effectively-final",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "LambdaCapture",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class LambdaCapture {",
      "    public static void main(String[] args) {",
      "        List<String> names = new ArrayList<>();",
      "        int[] total = {0};",
      "        String prefix = \"id-\";",
      "        String last = \"\";",
      "        Consumer<String> add = s -> names.add(prefix + s);",
      "        Consumer<String> count = s -> total[0]++;",
      "        Consumer<String> keep = s -> last = s;",
      "        add.accept(\"a\");",
      "        System.out.println(names);",
      "    }",
      "}",
    ],
    choices: [
      "12行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 12 },
    explanation:
      "ラムダ式の本体から参照するローカル変数は final か実質的 final でなければならず、ラムダ式の中から代入することもできません。12行目はラムダ式の中で last に代入しているのでコンパイルエラーです。10行目は names の参照先（リスト）の中身を変えているだけで変数 names 自体は再代入していないので問題なく、11行目も配列の要素を変えているだけで変数 total は実質的 final のままです。ラムダ式は値をコピーして捕捉するため変数の再代入は禁じられますが、参照先オブジェクトの変更は止められません。配列の要素で「カウンタ」を作る書き方は動きますが、並列実行では競合するので、集計はストリームのリダクションなどで行うのが安全です。",
  },
  {
    id: 10222,
    topic: "functional",
    variantOf: "gold-functional-effectively-final",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "LambdaScope",
    code: [
      "import java.util.function.*;",
      "",
      "public class LambdaScope {",
      "    static int x = 1;",
      "",
      "    public static void main(String[] args) {",
      "        int y = 2;",
      "        IntUnaryOperator f = x -> x + y;",
      "        IntUnaryOperator g = y -> y * 2;",
      "        IntUnaryOperator h = n -> { int x = n; return x; };",
      "        System.out.println(f.applyAsInt(3));",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "ラムダ式は新しいスコープを作らず、その引数や本体のローカル変数は、ラムダ式を囲むメソッドのローカル変数と同じスコープに属します。そのため、既にあるローカル変数 y と同じ名前の引数を宣言した9行目はコンパイルエラーになります。一方、static フィールドの x は「ローカル変数」ではないので、8行目の引数 x や10行目の本体内の変数 x がフィールドを隠すのは許されます（匿名クラスのメソッドなら別スコープなので y も使えます）。ラムダ式が囲むメソッドの一部として扱われるのは、this がラムダ式の外側のインスタンスを指すのと同じ理由で、見た目どおりの字句的なスコープにするための設計です。",
  },

  // ------------------------------------------------------------ Consumer / Predicate の合成
  {
    id: 10223,
    topic: "functional",
    variantOf: "gold-functional-consumer-chain",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ConsumerChain",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class ConsumerChain {",
      "    public static void main(String[] args) {",
      "        StringBuilder sb = new StringBuilder();",
      "        Consumer<String> first = s -> sb.append(s.toUpperCase());",
      "        Consumer<String> second = s -> sb.append(s.length());",
      "        Consumer<String> both = second.andThen(first);",
      "        List.of(\"ab\", \"c\").forEach(both);",
      "        System.out.println(sb);",
      "    }",
      "}",
    ],
    choices: ["2AB1C", "AB2C1", "2AB", "AB2", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2AB1C" },
    explanation:
      "Consumer.andThen は「自分を実行した後に引数の Consumer を実行する」Consumer を返します。both は second → first の順に同じ引数で実行するので、\"ab\" では長さ 2 の後に AB、\"c\" では 1 の後に C が追加され 2AB1C になります。Consumer は値を返さないので、andThen に渡した Consumer にも元の引数がそのまま渡される点が、前の結果を次に渡す Function.andThen との違いです。副作用だけを順に並べたい処理（ログ出力と保存など）を部品として組み合わせるのに使います。",
  },
  {
    id: 10224,
    topic: "functional",
    variantOf: "gold-functional-predicate",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PredicateTest",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class PredicateTest {",
      "    public static void main(String[] args) {",
      "        Predicate<String> empty = String::isEmpty;",
      "        Predicate<String> longWord = s -> s.length() > 3;",
      "        Predicate<String> p = Predicate.not(empty).and(longWord.negate());",
      "        List<String> words = new ArrayList<>(List.of(\"\", \"ab\", \"java\", \"xyz\"));",
      "        words.removeIf(p);",
      "        System.out.println(words);",
      "    }",
      "}",
    ],
    choices: ["[, java]", "[ab, xyz]", "[java]", "[]", "8行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[, java]" },
    explanation:
      "Predicate.not(empty) は「空でない」、longWord.negate() は「長さが 3 以下」なので、p は「空でなく、かつ長さ 3 以下」の文字列で true になります。該当するのは \"ab\" と \"xyz\" で、removeIf によって削除され [, java] が残ります（空文字列は空として出力されます）。Predicate.not は Java 11 で追加された static メソッドで、メソッド参照を否定したいときに s -> !s.isEmpty() と書き直さずに済みます。条件を部品として組み合わせると、個々の条件に名前が付いて読みやすくなります。",
  },
  {
    id: 10225,
    topic: "functional",
    variantOf: "gold-functional-predicate",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ShortCircuit",
    code: [
      "import java.util.function.*;",
      "",
      "public class ShortCircuit {",
      "    static Predicate<Integer> log(String name, Predicate<Integer> p) {",
      "        return n -> {",
      "            System.out.print(name);",
      "            return p.test(n);",
      "        };",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Predicate<Integer> a = log(\"A\", n -> n > 0);",
      "        Predicate<Integer> b = log(\"B\", n -> n % 2 == 0);",
      "        Predicate<Integer> c = log(\"C\", n -> n < 100);",
      "        boolean r = a.and(b).or(c).test(-3);",
      "        System.out.println(\" \" + r);",
      "    }",
      "}",
    ],
    choices: ["AC true", "ABC true", "A false", "ABC false", "AB true"],
    correct: [0],
    expected: { kind: "output", stdout: "AC true" },
    explanation:
      "Predicate の and と or は、&& と || と同じく短絡評価します。a.and(b).or(c) は (a && b) || c の意味で、-3 に対して a が false を返すので b は評価されず、a.and(b) 全体が false になります。|| の左辺が false なので c が評価され、-3 < 100 で true になります。出力は A と C だけで、結果は true です。条件に副作用（ログや重い処理）がある場合、合成の順序によって実行される条件が変わるので、安くて外れやすい条件を先に置くと無駄な評価を減らせます。",
  },

  // ------------------------------------------------------------ UnaryOperator / BinaryOperator
  {
    id: 10226,
    topic: "functional",
    variantOf: "gold-functional-operator",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OperatorTest",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class OperatorTest {",
      "    public static void main(String[] args) {",
      "        BinaryOperator<String> shorter = BinaryOperator.minBy(Comparator.comparing(String::length));",
      "        UnaryOperator<String> same = UnaryOperator.identity();",
      "        List<String> list = new ArrayList<>(List.of(\"kiwi\", \"fig\"));",
      "        list.replaceAll(s -> same.apply(s) + \"!\");",
      "        System.out.println(shorter.apply(\"pear\", \"plum\") + \" \" + list);",
      "    }",
      "}",
    ],
    choices: ["pear [kiwi!, fig!]", "plum [kiwi!, fig!]", "pear [kiwi, fig]", "fig [kiwi!, fig!]", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "pear [kiwi!, fig!]" },
    explanation:
      "BinaryOperator.minBy は、Comparator で比べて小さいほうを返す BinaryOperator を作ります。\"pear\" と \"plum\" は長さが同じで比較結果が 0 になり、その場合は第 1 引数が返されるので pear です。UnaryOperator は引数と戻り値が同じ型の Function で、identity() は受け取った値をそのまま返します。List.replaceAll は UnaryOperator を受け取って各要素を置き換えるので、要素の型を変えずに変換する操作であることが型で表現されています。",
  },
  {
    id: 10227,
    topic: "functional",
    variantOf: "gold-functional-operator",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "OperatorTypes",
    code: [
      "import java.util.function.*;",
      "",
      "public class OperatorTypes {",
      "    public static void main(String[] args) {",
      "        UnaryOperator<String> trim = String::trim;",
      "        BinaryOperator<Integer> add = Integer::sum;",
      "        Function<String, String> f = trim;",
      "        UnaryOperator<String> g = f;",
      "        System.out.println(add.apply(1, 2));",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "UnaryOperator<T> は Function<T, T> を継承したインタフェースなので、UnaryOperator<String> の値を Function<String, String> の変数に代入する7行目は、サブタイプからスーパータイプへの代入として許されます。逆に8行目は Function 型の変数を UnaryOperator 型へ代入しようとしており、キャストなしのダウンキャストになるのでコンパイルエラーです。ラムダ式やメソッド参照は代入先の型に合わせて生成されますが、一度生成された値は普通のオブジェクトとして型の規則に従います。関数型インタフェース同士は、シグネチャが同じでも継承関係が無ければ互換になりません。",
  },

  // ------------------------------------------------------------ Function の合成
  {
    id: 10228,
    topic: "functional",
    variantOf: "gold-functional-bifunction",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "BiFunctionTest",
    code: [
      "import java.util.function.*;",
      "",
      "public class BiFunctionTest {",
      "    public static void main(String[] args) {",
      "        BiFunction<String, Integer, String> repeat = String::repeat;",
      "        Function<String, Integer> len = String::length;",
      "        BiFunction<String, Integer, Integer> total = repeat.andThen(len);",
      "        ToIntBiFunction<String, String> cmp = String::compareTo;",
      "        System.out.println(total.apply(\"ab\", 3) + \" \" + cmp.applyAsInt(\"b\", \"a\"));",
      "    }",
      "}",
    ],
    choices: ["6 1", "ababab 1", "6 -1", "5 1", "7行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "6 1" },
    explanation:
      "BiFunction には andThen だけがあり、compose はありません（2 つの引数を返す関数は存在しないので、前段に関数をつなげられないため）。repeat.andThen(len) は「repeat の結果を len に渡す」BiFunction で、\"ab\" を 3 回繰り返した \"ababab\" の長さ 6 を返します。String::repeat は「第 1 引数をレシーバ、第 2 引数をメソッドの引数」とする非 static メソッドの参照です。ToIntBiFunction は結果を int で返す特殊化で、\"b\".compareTo(\"a\") は文字コードの差の 1 を返します。",
  },

  // ------------------------------------------------------------ コンストラクタ参照
  {
    id: 10229,
    topic: "functional",
    variantOf: "gold-functional-constructor-ref",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ConstructorRef",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class ConstructorRef {",
      "    record Tag(String name) {",
      "        Tag() { this(\"default\"); }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Supplier<Tag> s = Tag::new;",
      "        Function<String, Tag> f = Tag::new;",
      "        IntFunction<String[]> arr = String[]::new;",
      "        System.out.println(s.get().name() + \" \" + f.apply(\"x\").name() + \" \" + arr.apply(3).length);",
      "    }",
      "}",
    ],
    choices: ["default x 3", "null x 3", "default x 0", "10行目でコンパイルエラーになる", "12行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "default x 3" },
    explanation:
      "コンストラクタ参照 Tag::new は、代入先の関数型インタフェースの引数に合わせてコンストラクタが選ばれます。Supplier<Tag>（引数なし）なら引数なしのコンストラクタ、Function<String, Tag> なら String を 1 つ取る正準コンストラクタです。String[]::new は配列の生成を表す参照で、IntFunction の int 引数が配列の長さになります。メソッド参照と同じく、どのオーバーロードが呼ばれるかは参照の書き方ではなく代入先の型で決まる点が要点です。",
  },
  {
    id: 10230,
    topic: "functional",
    variantOf: "gold-functional-constructor-ref",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "RefTargets",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class RefTargets {",
      "    public static void main(String[] args) {",
      "        Supplier<List<String>> a = ArrayList::new;",
      "        Function<Integer, List<String>> b = ArrayList::new;",
      "        BiFunction<Integer, Integer, List<String>> c = ArrayList::new;",
      "        Comparator<String> d = String::compareToIgnoreCase;",
      "        System.out.println(a.get().size());",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "ArrayList には引数なし・int（初期容量）・Collection の 3 つのコンストラクタがあります。Supplier には引数なし、Function<Integer, ...> には int を取るコンストラクタ（アンボクシングして適用）が対応しますが、int を 2 つ取るコンストラクタは存在しないので8行目はコンパイルエラーになります。9行目の String::compareToIgnoreCase は「第 1 引数をレシーバにして第 2 引数と比べる」非 static メソッドの参照で、Comparator<String> の compare(String, String) に合致します。メソッド参照が成り立つかは、関数型インタフェースの引数の並びに合うメソッド（コンストラクタ）があるかで決まります。",
  },

  // ------------------------------------------------------------ ラムダ式とオーバーロード
  {
    id: 10231,
    topic: "functional",
    variantOf: "gold-functional-lambda-overload",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SubmitOverload",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class SubmitOverload {",
      "    static void run(Runnable r) { System.out.print(\"Runnable \"); }",
      "    static void run(Callable<String> c) { System.out.print(\"Callable \"); }",
      "",
      "    public static void main(String[] args) {",
      "        run(() -> \"done\");",
      "        run(() -> System.out.print(\"\"));",
      "        run(() -> { });",
      "        System.out.println();",
      "    }",
      "}",
    ],
    choices: [
      "Callable Runnable Runnable",
      "Callable Callable Runnable",
      "Runnable Runnable Runnable",
      "8行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Callable Runnable Runnable" },
    explanation:
      "ラムダ式がどの関数型インタフェースに適合するかは、本体が値を返すかどうかで決まります。() -> \"done\" は String を返すので、戻り値が void の Runnable.run には適合せず、Callable<String> が選ばれます。() -> System.out.print(\"\") は本体が void のメソッド呼び出しなので値を返せず Runnable だけに適合し、() -> { } も値を返さないので Runnable です。ExecutorService.submit もこの 2 つでオーバーロードされており、同じ仕組みで「結果のあるタスク」か「結果のないタスク」かが決まります。",
  },
  {
    id: 10232,
    topic: "functional",
    variantOf: "gold-functional-lambda-overload",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "CheckedLambda",
    code: [
      "import java.util.concurrent.*;",
      "import java.util.function.*;",
      "",
      "public class CheckedLambda {",
      "    static String load() throws Exception {",
      "        return \"data\";",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        Callable<String> c = () -> load();",
      "        Supplier<String> s = () -> load();",
      "        System.out.println(c.call());",
      "    }",
      "}",
    ],
    choices: [
      "11行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 11 },
    explanation:
      "ラムダ式の本体からスローできる検査例外は、実装する関数型インタフェースのメソッドの throws 節で宣言されたものに限られます。Callable.call() は throws Exception を宣言しているので10行目は問題ありませんが、Supplier.get() は検査例外を宣言していないため、load() の Exception を処理していない11行目はコンパイルエラーになります。main が throws Exception を宣言していても、ラムダ式の本体は main の中で実行されるわけではない（get が呼ばれたときに実行される）ので助けになりません。java.util.function のインタフェースで検査例外を扱うには、ラムダ式の中で catch して非検査例外に包むのが一般的です。",
  },

  // ------------------------------------------------------------ 匿名クラス
  {
    id: 10233,
    topic: "functional",
    variantOf: "gold-functional-anonymous-class",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AnonymousShape",
    code: [
      "abstract class Shape {",
      "    final String name;",
      "    Shape(String name) {",
      "        this.name = name;",
      "        System.out.print(\"init \");",
      "    }",
      "    abstract double area();",
      "}",
      "",
      "public class AnonymousShape {",
      "    public static void main(String[] args) {",
      "        Shape s = new Shape(\"square\") {",
      "            double side = 2;",
      "            double area() { return side * side; }",
      "        };",
      "        System.out.println(s.name + \" \" + s.area());",
      "    }",
      "}",
    ],
    choices: [
      "init square 4.0",
      "square 4.0",
      "init square 0.0",
      "12行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "init square 4.0" },
    explanation:
      "匿名クラスは抽象クラスを継承して、その場で 1 つだけインスタンスを作れます。匿名クラスは名前が無いのでコンストラクタを宣言できませんが、new Shape(\"square\") の引数はスーパークラスのコンストラクタにそのまま渡され、init が出力されます。匿名クラスには独自のフィールド side を宣言でき、スーパークラスのコンストラクタの実行後に初期化されてから area() が呼ばれるので 4.0 になります。ただし変数 s の型は Shape なので、外から s.side と書くことはできません。インタフェースの実装だけならラムダ式で足りますが、状態を持つ場合や抽象クラスを実装する場合は匿名クラスが必要です。",
  },
  {
    id: 10234,
    topic: "functional",
    variantOf: "gold-functional-anonymous-class",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AnonymousState",
    code: [
      "import java.util.function.*;",
      "",
      "public class AnonymousState {",
      "    public static void main(String[] args) {",
      "        IntSupplier counter = new IntSupplier() {",
      "            private int n;",
      "            public int getAsInt() { return ++n; }",
      "        };",
      "        IntSupplier lambda = () -> 0;",
      "        counter.getAsInt();",
      "        counter.getAsInt();",
      "        System.out.println(counter.getAsInt() + lambda.getAsInt());",
      "    }",
      "}",
    ],
    choices: ["3", "1", "30", "2", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3" },
    explanation:
      "匿名クラスは通常のクラスと同じくフィールドを持てるので、呼び出しのたびに n を増やすカウンタを作れます。3 回目の呼び出しで 3 が返り、lambda の 0 と数値として加算されて 3 になります。ラムダ式は関数型インタフェースの実装を簡潔に書くためのもので、自分自身のフィールドを宣言できません（ラムダ式の中の変数は毎回の呼び出しで作り直されます）。呼び出しをまたいで状態を保持する実装が必要なら匿名クラスか名前付きのクラスを使い、ラムダ式は状態を持たない処理に使い分けます。",
  },

  // ------------------------------------------------------------ 内部クラスと外側クラス
  {
    id: 10235,
    topic: "functional",
    variantOf: "gold-functional-inner-access",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Account",
    code: [
      "public class Account {",
      "    private int balance = 100;",
      "",
      "    class Transaction {",
      "        private final int amount;",
      "        Transaction(int amount) { this.amount = amount; }",
      "        void apply() { balance += amount; }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Account a = new Account();",
      "        Account b = new Account();",
      "        Account.Transaction t1 = a.new Transaction(50);",
      "        Account.Transaction t2 = b.new Transaction(-30);",
      "        t1.apply();",
      "        t1.apply();",
      "        t2.apply();",
      "        System.out.println(a.balance + \" \" + b.balance + \" \" + t2.amount);",
      "    }",
      "}",
    ],
    choices: ["200 70 -30", "120 120 -30", "150 70 -30", "200 70 30", "18行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "200 70 -30" },
    explanation:
      "内部クラスのインスタンスは、生成時に使った外側のインスタンスへの参照を暗黙に保持します。t1 は a.new で作ったので apply は a の balance を変更し（100 + 50 + 50 = 200）、t2 は b の balance を変更します（100 - 30 = 70）。7行目の balance は Account.this.balance の省略形です。また外側クラスと内部クラスは互いの private メンバーにアクセスできるので、main から t2.amount を読むこともできます。内部クラスは「特定の外側インスタンスに付属する部品」を表すのに向いていますが、外側インスタンスへの参照を持ち続けるので、長生きするオブジェクトに渡すとメモリが解放されない原因にもなります。",
  },

  // ------------------------------------------------------------ 関数型インタフェースの条件
  {
    id: 10236,
    topic: "functional",
    variantOf: "gold-functional-generic-method-target",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "GenericTarget",
    code: [
      "interface Converter<T> {",
      "    String convert(T value);",
      "}",
      "",
      "interface AnyConverter {",
      "    <T> String convert(T value);",
      "}",
      "",
      "public class GenericTarget {",
      "    public static void main(String[] args) {",
      "        Converter<Integer> c1 = v -> \"#\" + v;",
      "        AnyConverter c2 = v -> \"#\" + v;",
      "        System.out.println(c1.convert(1));",
      "    }",
      "}",
    ],
    choices: [
      "12行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 12 },
    explanation:
      "ラムダ式は型パラメータを宣言する構文を持たないので、抽象メソッド自体がジェネリック・メソッド（<T> String convert(T)）である関数型インタフェースは、ラムダ式の代入先になれません。そのため12行目がコンパイルエラーになります。インタフェースの宣言（6行目）は問題なく、匿名クラスやメソッド参照なら実装できます。一方 Converter<T> のように型パラメータをインタフェースに持たせれば、Converter<Integer> と型を確定させた時点で抽象メソッドは普通のメソッドになり、ラムダ式で実装できます。java.util.function のインタフェースがすべてインタフェース側に型パラメータを持つのはこのためです。",
  },

  // ------------------------------------------------------------ インタフェースの private / static メソッド
  {
    id: 10237,
    topic: "functional",
    variantOf: "gold-functional-interface-methods",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "PrivateMethods",
    code: [
      "interface Formatter {",
      "    String format(String s);",
      "",
      "    default String bracket(String s) {",
      "        return wrap(\"[\", s, \"]\");",
      "    }",
      "    static String quote(String s) {",
      "        return wrap(\"\\\"\", s, \"\\\"\");",
      "    }",
      "    static String upper(String s) {",
      "        return trimmed(s).toUpperCase();",
      "    }",
      "    private static String wrap(String l, String s, String r) {",
      "        return l + s + r;",
      "    }",
      "    private String trimmed(String s) {",
      "        return s.trim();",
      "    }",
      "}",
      "",
      "public class PrivateMethods {",
      "    public static void main(String[] args) {",
      "        Formatter f = s -> s;",
      "        System.out.println(f.bracket(\"a\") + Formatter.quote(\"b\"));",
      "    }",
      "}",
    ],
    choices: [
      "11行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 11 },
    explanation:
      "Java 9 以降、インタフェースに private メソッドを定義でき、default メソッドや static メソッドの共通処理をまとめられます（実装クラスからは見えません）。private static メソッドは static メソッドからも default メソッドからも呼べるので、5行目と8行目は問題ありません。一方 private の非 static メソッド trimmed はインスタンス（this）を前提にしたメソッドなので、インスタンスを持たない static メソッド upper から呼ぶ11行目はコンパイルエラーになります。クラスの static メソッドからインスタンス・メソッドを呼べないのと同じ規則です。",
  },
  {
    id: 10238,
    topic: "functional",
    variantOf: "gold-functional-interface-methods",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "StaticInherit",
    code: [
      "interface Shape {",
      "    double area();",
      "    static Shape unit() {",
      "        return () -> 1.0;",
      "    }",
      "}",
      "",
      "class Square implements Shape {",
      "    public double area() { return 4.0; }",
      "}",
      "",
      "public class StaticInherit {",
      "    public static void main(String[] args) {",
      "        Shape a = Shape.unit();",
      "        Square b = new Square();",
      "        Shape c = Square.unit();",
      "        System.out.println(a.area() + b.area());",
      "    }",
      "}",
    ],
    choices: [
      "16行目でコンパイルエラーになる",
      "4行目でコンパイルエラーになる",
      "14行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 16 },
    explanation:
      "インタフェースの static メソッドは、実装クラスやサブインタフェースに継承されません。そのため Shape.unit() のようにインタフェース名で呼ぶ必要があり、実装クラス名で Square.unit() と呼ぶ16行目はコンパイルエラーになります。クラスの static メソッドはサブクラス名でも呼べるので、ここが両者の違いです。クラスは複数のインタフェースを実装できるので、同じシグネチャの static メソッドを持つインタフェースを 2 つ実装したときにどちらを呼ぶか曖昧にならないよう、継承しない設計になっています。",
  },
  {
    id: 10239,
    topic: "functional",
    variantOf: "gold-functional-builtin-types",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PrimitiveFunctions",
    code: [
      "import java.util.function.*;",
      "",
      "public class PrimitiveFunctions {",
      "    public static void main(String[] args) {",
      "        ToDoubleFunction<String> half = s -> s.length() / 2;",
      "        DoubleUnaryOperator twice = d -> d * 2;",
      "        ObjIntConsumer<StringBuilder> repeat = (sb, n) -> sb.append(\"*\".repeat(n));",
      "        BooleanSupplier yes = () -> true;",
      "        StringBuilder sb = new StringBuilder();",
      "        repeat.accept(sb, 3);",
      "        System.out.println(twice.applyAsDouble(half.applyAsDouble(\"abcde\")) + \" \" + sb + \" \" + yes.getAsBoolean());",
      "    }",
      "}",
    ],
    choices: ["4.0 *** true", "5.0 *** true", "4 *** true", "4.0 3 true", "11行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "4.0 *** true" },
    explanation:
      "java.util.function には、ボクシングを避けるための基本型向けの特殊化があります。ToDoubleFunction<T> は T を受け取って double を返し（applyAsDouble）、DoubleUnaryOperator は double から double、ObjIntConsumer<T> はオブジェクトと int を受け取り、BooleanSupplier は boolean を返します（getAsBoolean）。s.length() / 2 は int 同士の割り算なので 5 / 2 = 2 になってから double の 2.0 に拡張され、twice で 4.0 になります。戻り値が double であっても、計算自体が小数で行われるわけではない点に注意します。",
  },
];
