import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: 関数型インタフェースとラムダ式（id 10201-10299）。
 * 内部クラス（内部クラス、static なネストクラス、無名クラス）、関数型インタフェースの定義、
 * ラムダ式とメソッド参照、java.util.function の主要インタフェース。
 */
export const goldFunctionalQuestions: GoldQuestion[] = [
  // ---------------------------------------------------------------- 内部クラス
  {
    id: 10201,
    topic: "functional",
    variantOf: "gold-functional-inner-instantiation",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Outer",
    code: [
      "public class Outer {",
      "    class Inner {",
      '        String hello() { return "inner"; }',
      "    }",
      "    static class Nested {",
      '        String hello() { return "nested"; }',
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Outer outer = new Outer();",
      "        Outer.Inner a = outer.new Inner();",
      "        Outer.Nested b = new Outer.Nested();",
      "        Outer.Inner c = new Outer.Inner();",
      "        System.out.println(a.hello() + b.hello() + c.hello());",
      "    }",
      "}",
    ],
    choices: [
      "13行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "12行目でコンパイルエラーになる",
      "14行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 13 },
    explanation:
      "static でない内部クラス（Inner）のインスタンスは、必ずいずれかの外側クラスのインスタンスに結び付いて生成されます。そのため outer.new Inner() のように外側のインスタンスを指定する必要があり、static な main から new Outer.Inner() と書いた 13行目は「外側のインスタンスが無い」ためコンパイルエラーになります。static なネストクラス（Nested）は外側のインスタンスに依存しないので、new Outer.Nested() で生成できます。内部クラスは外側のフィールドに暗黙にアクセスできる代わりに外側への参照を保持するため、外側の状態が不要なら static にしておくのが定石です。",
  },
  {
    id: 10202,
    topic: "functional",
    variantOf: "gold-functional-inner-instantiation",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Library",
    code: [
      "public class Library {",
      "    private String name = \"central\";",
      "    private static int count = 3;",
      "",
      "    static class Catalog {",
      "        int size() {",
      "            return count;",
      "        }",
      "        String owner() {",
      "            return name;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(new Catalog().size());",
      "    }",
      "}",
    ],
    choices: [
      "10行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "15行目でコンパイルエラーになる",
      "2行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 10 },
    explanation:
      "static なネストクラスは外側クラスのインスタンスを持たないため、外側の static メンバー（count）には private であってもアクセスできますが、インスタンスフィールドの name には参照すべき外側のインスタンスが無く、10行目がコンパイルエラーになります。private でもアクセスできるのは、ネストクラスが外側クラスの一部としてカプセル化の内側にいるからです。main から new Catalog() と書けるのは、同じクラスの中では Library. を省略できるためです。外側のインスタンスの状態を使いたいなら static を外して内部クラスにします。",
  },
  {
    id: 10203,
    topic: "functional",
    variantOf: "gold-functional-inner-shadowing",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Shadow",
    code: [
      "public class Shadow {",
      "    int x = 10;",
      "",
      "    class Inner {",
      "        int x = 20;",
      "",
      "        void show(int x) {",
      '            System.out.println(x + " " + this.x + " " + Shadow.this.x);',
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new Shadow().new Inner().show(30);",
      "    }",
      "}",
    ],
    choices: ["30 20 10", "30 30 30", "10 20 30", "30 20 20", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "30 20 10" },
    explanation:
      "同じ名前の変数が入れ子になっている場合、単純名 x は最も内側のスコープ、つまりメソッドの引数（30）を指します。this.x は現在のオブジェクトである Inner のフィールド（20）、Shadow.this.x は Inner が結び付いている外側の Shadow インスタンスのフィールド（10）です。内部クラスのインスタンスは外側のインスタンスへの参照を暗黙に持っており、「外側クラス名.this」はその参照を明示的に取り出す構文です。名前が隠れた（シャドーイングされた）変数を読み違えないよう、実務では同名を避けるのが無難です。",
  },
  {
    id: 10204,
    topic: "functional",
    variantOf: "gold-functional-anonymous-capture",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Capture",
    code: [
      "public class Capture {",
      "    public static void main(String[] args) {",
      "        int count = 0;",
      "        String label = \"n=\";",
      "        Runnable r = new Runnable() {",
      "            public void run() {",
      "                System.out.println(label + count);",
      "            }",
      "        };",
      "        count++;",
      "        r.run();",
      "    }",
      "}",
    ],
    choices: [
      "7行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
      "コンパイルは成功し、n=1 と出力される",
      "コンパイルは成功し、n=0 と出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "無名クラスやラムダ式から参照できるローカル変数は、final か実質的に final（初期化後に一度も代入されない）なものに限られます。count は 10行目で変更されているため実質的に final ではなく、それを参照している 7行目がコンパイルエラーになります（エラーは変更した行ではなく参照した行で報告されます）。無名クラスは生成時にローカル変数の値をコピーして保持するため、後から元の変数が変わるとコピーと食い違ってしまいます。その矛盾を言語仕様で禁じているのがこの規則です。",
  },
  {
    id: 10205,
    topic: "functional",
    variantOf: "gold-functional-anonymous-capture",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "LambdaCapture",
    code: [
      "import java.util.*;",
      "",
      "public class LambdaCapture {",
      "    static int total;",
      "",
      "    public static void main(String[] args) {",
      '        List<String> words = List.of("ab", "cde");',
      "        int sum = 0;",
      "        int[] box = {0};",
      "        words.forEach(w -> total += w.length());",
      "        words.forEach(w -> box[0] += w.length());",
      "        words.forEach(w -> sum += w.length());",
      "        System.out.println(total + box[0] + sum);",
      "    }",
      "}",
    ],
    choices: [
      "12行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "10行目と 11行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 12 },
    explanation:
      "ラムダ式の中から代入できないのはローカル変数だけです。12行目の sum はローカル変数なので、ラムダ式内で書き換えようとするとコンパイルエラーになります。10行目の total はローカル変数ではなく static フィールドなので、実質的に final である必要はなく、ラムダ式の中から更新できます。11行目の box は配列への参照自体は変わらず（実質的に final）、配列の中身を変えているだけなのでコンパイルは通ります。ただし配列で包む回避策は並列実行で競合を招くため、集計には Stream の sum やリダクションを使うのが本来の書き方です。",
  },
  {
    id: 10206,
    topic: "functional",
    variantOf: "gold-functional-this-lambda",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ThisRef",
    code: [
      "public class ThisRef {",
      "    public String toString() {",
      '        return "outer";',
      "    }",
      "",
      "    void run() {",
      '        Runnable lambda = () -> System.out.print(this + " ");',
      "        Runnable anon = new Runnable() {",
      "            public void run() {",
      "                System.out.print(this);",
      "            }",
      "            public String toString() {",
      '                return "anon";',
      "            }",
      "        };",
      "        lambda.run();",
      "        anon.run();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        new ThisRef().run();",
      "    }",
      "}",
    ],
    choices: ["outer anon", "anon anon", "outer outer", "anon outer", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "outer anon" },
    explanation:
      "ラムダ式は新しい名前のスコープを作らず、本体は囲んでいるメソッドと同じスコープで解釈されます（ラムダ式を評価すると関数型インタフェースのインスタンスは作られますが、本体の this はそれを指しません）。そのためラムダ式の中の this は、run() を呼んだ ThisRef のインスタンスを指し \"outer\" になります。一方、無名クラスはそれ自体が新しいクラスのインスタンスなので、その中の this は無名クラスのインスタンスを指し \"anon\" になります。ラムダ式は「インタフェースを実装したクラスの省略記法」ではなく「処理そのもの」を表すという設計の違いが、this の意味の違いに現れています。",
  },

  // -------------------------------------------------------- 関数型インタフェース
  {
    id: 10207,
    topic: "functional",
    variantOf: "gold-functional-interface-definition",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Checks",
    code: [
      "@FunctionalInterface",
      "interface Checker {",
      "    boolean check(String s);",
      "    boolean equals(Object o);",
      "    default Checker negate() {",
      "        return s -> !check(s);",
      "    }",
      "    static Checker startsWith(String prefix) {",
      "        return s -> s.startsWith(prefix);",
      "    }",
      "}",
      "",
      "public class Checks {",
      "    public static void main(String[] args) {",
      '        Checker c = Checker.startsWith("ja").negate();',
      '        System.out.println(c.check("java") + " " + c.check("kotlin"));',
      "    }",
      "}",
    ],
    choices: [
      "false true",
      "true false",
      "1行目でコンパイルエラーになる",
      "4行目でコンパイルエラーになる",
      "15行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "false true" },
    explanation:
      "関数型インタフェースの条件は「抽象メソッドがちょうど 1 つ」であることです。default メソッドと static メソッドは実装を持つので数に入りません。また equals(Object) のように java.lang.Object の public メソッドと同じシグネチャの抽象メソッドも、どの実装クラスも Object から実装を受け継ぐため数えません。したがって Checker は check だけを抽象メソッドとする関数型インタフェースで、@FunctionalInterface も問題なく付けられます。\"ja\" で始まるかの判定を negate で反転しているので、false true になります。",
  },
  {
    id: 10208,
    topic: "functional",
    variantOf: "gold-functional-interface-definition",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Shapes",
    code: [
      "interface Named {",
      "    String name();",
      "}",
      "",
      "@FunctionalInterface",
      "interface Shape extends Named {",
      "    double area();",
      "    default String describe() {",
      '        return name() + ":" + area();',
      "    }",
      "}",
      "",
      "public class Shapes {",
      "    public static void main(String[] args) {",
      '        System.out.println("shapes");',
      "    }",
      "}",
    ],
    choices: [
      "5行目でコンパイルエラーになる",
      "1行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 5 },
    explanation:
      "Shape は自身の area() に加えて、スーパーインタフェース Named から抽象メソッド name() を継承しているため、抽象メソッドが 2 つになります。関数型インタフェースは継承したものも含めて抽象メソッドが 1 つでなければならず、@FunctionalInterface を付けた 5行目でコンパイルエラーになります。@FunctionalInterface は付けなくても条件を満たせば関数型インタフェースとして使えますが、付けておくと後からメソッドを足して条件を壊したときにコンパイラが教えてくれます。ラムダ式で使う前提のインタフェースには付けておくのが安全です。",
  },

  // ------------------------------------------------------- java.util.function
  {
    id: 10209,
    topic: "functional",
    variantOf: "gold-functional-compose",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Compose",
    code: [
      "import java.util.function.*;",
      "",
      "public class Compose {",
      "    public static void main(String[] args) {",
      "        Function<Integer, Integer> plus2 = x -> x + 2;",
      "        Function<Integer, Integer> times3 = x -> x * 3;",
      "        System.out.println(plus2.andThen(times3).apply(1) + \" \"",
      "                + plus2.compose(times3).apply(1));",
      "    }",
      "}",
    ],
    choices: ["9 5", "5 9", "9 9", "5 5", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "9 5" },
    explanation:
      "f.andThen(g) は「f を適用してから、その結果に g を適用する」関数で、plus2.andThen(times3).apply(1) は (1 + 2) * 3 = 9 です。f.compose(g) は逆に「先に g を適用し、その結果に f を適用する」関数で、plus2.compose(times3).apply(1) は 1 * 3 + 2 = 5 になります。compose は数学の関数合成 f(g(x)) と同じ読み方になるよう名付けられており、andThen は処理の流れの順に読めるよう用意されています。処理を順につなげるだけなら、読み順と実行順が一致する andThen の方が誤読しにくいでしょう。",
  },
  {
    id: 10210,
    topic: "functional",
    variantOf: "gold-functional-compose",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PredicateTest",
    code: [
      "import java.util.function.*;",
      "",
      "public class PredicateTest {",
      "    public static void main(String[] args) {",
      "        Predicate<String> longWord = s -> s.length() > 4;",
      '        Predicate<String> startsA = s -> s.startsWith("a");',
      "        Predicate<String> p = longWord.negate().or(startsA);",
      "        Predicate<String> q = longWord.and(startsA.negate());",
      '        System.out.println(p.test("apple") + " " + p.test("melon") + " " + q.test("melon"));',
      "    }",
      "}",
    ],
    choices: ["true false true", "false false true", "true true false", "true false false", "false true true"],
    correct: [0],
    expected: { kind: "output", stdout: "true false true" },
    explanation:
      "p は「4 文字以下、または a で始まる」、q は「5 文字以上、かつ a で始まらない」という条件です。\"apple\" は 5 文字ですが a で始まるので p は true、\"melon\" は 5 文字で a で始まらないので p は false、q は true になります。negate / and / or は新しい Predicate を返すだけで元の Predicate は変わらないため、部品となる条件を組み合わせて使い回せます。and / or は && / || と同じく短絡評価され、左側で結果が決まれば右側の test は呼ばれません。",
  },
  {
    id: 10211,
    topic: "functional",
    variantOf: "gold-functional-builtin-types",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Builtins",
    code: [
      "import java.util.*;",
      "import java.util.function.*;",
      "",
      "public class Builtins {",
      "    public static void main(String[] args) {",
      "        Supplier<List<String>> s = ArrayList::new;",
      "        Consumer<String> c = System.out::println;",
      "        BiFunction<String, String, Integer> f = String::compareTo;",
      "        UnaryOperator<String> u = String::length;",
      "        BinaryOperator<Integer> b = Math::max;",
      '        c.accept("ok");',
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "10行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "UnaryOperator<T> は Function<T, T> の特殊形で、引数と戻り値が同じ型でなければなりません。String::length は String を受け取って int を返すため UnaryOperator<String> には適合せず、9行目がコンパイルエラーになります（Function<String, Integer> や ToIntFunction<String> なら適合します）。6行目はコンストラクタ参照で Supplier の get() に、8行目は第 1 引数をレシーバーとする String の compareTo に、10行目は Math.max(int, int) にアンボクシングを介して適合します。どの関数型インタフェースに代入できるかは、抽象メソッドの引数と戻り値の形だけで決まります。",
  },
  {
    id: 10212,
    topic: "functional",
    variantOf: "gold-functional-builtin-types",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Suppliers",
    code: [
      "import java.util.function.*;",
      "",
      "public class Suppliers {",
      "    public static void main(String[] args) {",
      "        IntSupplier one = () -> 1;",
      "        IntUnaryOperator twice = n -> n * 2;",
      "        ToIntFunction<String> len = String::length;",
      "        IntBinaryOperator sub = (a, b) -> a - b;",
      '        int r = sub.applyAsInt(twice.applyAsInt(len.applyAsInt("abcd")), one.getAsInt());',
      "        System.out.println(r);",
      "    }",
      "}",
    ],
    choices: ["7", "-7", "3", "9", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "7" },
    explanation:
      "len.applyAsInt(\"abcd\") が 4、twice で 8、sub.applyAsInt(8, 1) で 8 - 1 = 7 になります。IntSupplier / IntUnaryOperator / ToIntFunction / IntBinaryOperator はプリミティブの int を直接扱う関数型インタフェースで、抽象メソッド名も getAsInt / applyAsInt のように Supplier や Function とは異なります。総称型の型引数にプリミティブは指定できないため、Function<Integer, Integer> ではボクシングとアンボクシングが毎回発生します。数値を大量に扱う処理でそのコストを避けるために、これらの専用インタフェースが用意されています。",
  },

  // --------------------------------------------------------- ラムダ式・メソッド参照
  {
    id: 10213,
    topic: "functional",
    variantOf: "gold-functional-lambda-syntax",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "LambdaSyntax",
    code: [
      "import java.util.function.*;",
      "",
      "public class LambdaSyntax {",
      "    public static void main(String[] args) {",
      "        BinaryOperator<Integer> f1 = (a, b) -> a + b;",
      "        BinaryOperator<Integer> f2 = (var a, var b) -> a + b;",
      "        BinaryOperator<Integer> f3 = (Integer a, Integer b) -> { return a + b; };",
      "        BinaryOperator<Integer> f4 = (Integer a, var b) -> a + b;",
      "        System.out.println(f1.apply(1, 2));",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "ラムダ式の引数は「すべて型を省略」「すべて var」「すべて型を明示」のいずれかに揃える必要があり、8行目のように明示的な型と var を混在させるとコンパイルエラーになります。var を書けるようになったのは、引数に @NonNull などのアノテーションを付けたいが型名は書きたくない、という用途のためです（アノテーションは型か var が無いと付けられません）。引数ごとに書き方がばらばらだと読み手が型を追いにくくなるため、仕様で統一が求められています。本体を波括弧で囲む 7行目の形では、値を返すのに return が必要です。",
  },
  {
    id: 10214,
    topic: "functional",
    variantOf: "gold-functional-method-reference",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MethodRefs",
    code: [
      "import java.util.function.*;",
      "",
      "public class MethodRefs {",
      "    public static void main(String[] args) {",
      "        Function<String, Integer> parse = Integer::parseInt;",
      "        BiFunction<String, Integer, Character> at = String::charAt;",
      '        Supplier<String> upper = "abc"::toUpperCase;',
      '        System.out.println(parse.apply("12") + " " + at.apply("hello", 1) + " " + upper.get());',
      "    }",
      "}",
    ],
    choices: ["12 e ABC", "12 h ABC", "12 e abc", "6行目でコンパイルエラーになる", "7行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "12 e ABC" },
    explanation:
      "メソッド参照には、static メソッドの参照、不特定のオブジェクトのインスタンスメソッドの参照、特定のオブジェクトのインスタンスメソッドの参照、コンストラクタ参照の 4 種類があります。Integer::parseInt は static メソッドの参照で、引数をそのまま parseInt に渡します。String::charAt は不特定のオブジェクトのインスタンスメソッドの参照で、BiFunction の第 1 引数（\"hello\"）がレシーバーになり、第 2 引数が charAt に渡されるので 'e' になります。\"abc\"::toUpperCase は特定のオブジェクトのメソッド参照で、レシーバーが固定されているので引数なしの Supplier に適合します。同じ「クラス名::メソッド名」の形でも、static メソッドかインスタンスメソッドかで引数の割り当てが変わる点が要点です。",
  },
  {
    id: 10215,
    topic: "functional",
    variantOf: "gold-functional-method-reference",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "AmbiguousRef",
    code: [
      "import java.util.function.*;",
      "",
      "public class AmbiguousRef {",
      "    public static void main(String[] args) {",
      "        Function<String, Integer> len = String::length;",
      "        Supplier<Object> make = Object::new;",
      "        Function<Integer, String> text = Integer::toString;",
      '        System.out.println(len.apply("abc"));',
      "    }",
      "}",
    ],
    choices: [
      "7行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "コンパイルは成功し、3 と出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "Integer には static な toString(int) と、インスタンスメソッドの toString() の両方があります。Function<Integer, String> の apply(Integer) に対しては、「引数をアンボクシングして static な toString(int) に渡す」解釈と、「引数をレシーバーにして toString() を呼ぶ」解釈の両方が成り立つため、あいまいとしてコンパイルエラーになります。メソッド参照は引数の割り当て方をコンパイラが推測する仕組みなので、候補が複数成り立つと決められません。こうした場合は i -> Integer.toString(i) のようにラムダ式で意図を明示します。",
  },
  {
    id: 10216,
    topic: "functional",
    variantOf: "gold-functional-default-conflict",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "Robot",
    code: [
      "interface Walker {",
      '    default String move() { return "walk"; }',
      "}",
      "",
      "interface Swimmer {",
      '    default String move() { return "swim"; }',
      "}",
      "",
      "public class Robot implements Walker, Swimmer {",
      "    public static void main(String[] args) {",
      "        System.out.println(new Robot().move());",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "11行目でコンパイルエラーになる",
      "コンパイルは成功し、walk と出力される",
      "コンパイルは成功し、swim と出力される",
      "コンパイルは成功し、実行時に例外がスローされる",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "Robot は同じシグネチャの default メソッド move() を持つ 2 つのインタフェースを実装しており、どちらを継承すべきか決まらないため、クラス宣言の 9行目でコンパイルエラーになります。implements の並び順で優先順位を決めないのは、宣言の順序という偶然で振る舞いが変わるのを避けるためです。解消するには Robot で move() をオーバーライドし、必要なら Walker.super.move() のように「インタフェース名.super」で使いたい実装を明示的に呼び出します。",
  },
];
