import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: ファイル I/O（id 10601-10699）。
 * コンソールの入出力、I/O ストリーム、シリアライズ、Path / Files、Stream API によるファイル操作。
 *
 * 検証時のカレントディレクトリは問題ごとの作業ディレクトリで、resources のファイルもそこに置かれる。
 * パスの区切り文字は OS で異なるため、Path を文字列として出力する問題は作らない（名前要素の単位で扱う）。
 */
export const goldIoQuestions: GoldQuestion[] = [
  // ------------------------------------------------------------------ コンソール
  {
    id: 10601,
    topic: "io",
    variantOf: "gold-io-console",
    question:
      "次のコードを、標準入力と標準出力をリダイレクトした（端末に接続していない）状態で実行した場合の結果はどれか。1つ選びなさい。",
    className: "ConsoleTest",
    code: [
      "import java.io.*;",
      "",
      "public class ConsoleTest {",
      "    public static void main(String[] args) {",
      "        Console console = System.console();",
      '        String name = console.readLine("name: ");',
      '        console.printf("Hello, %s%n", name);',
      "    }",
      "}",
    ],
    choices: [
      "実行時に NullPointerException がスローされる",
      "name: と表示されて入力待ちになる",
      "Hello, null と出力される",
      "6行目でコンパイルエラーになる",
      "実行時に IOException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException" },
    explanation:
      "Java 17 の System.console() は、JVM が対話的な端末（コンソール）に接続されている場合にだけ Console オブジェクトを返し、入出力がファイルやパイプにリダイレクトされている場合や、IDE・バックグラウンドから起動した場合には null を返します。そのため console.readLine の呼び出しで NullPointerException になります。Console はパスワードの非表示入力（readPassword）など端末に固有の機能を提供するクラスなので、端末が無い環境では存在自体を null で表す設計です。バッチ処理のように端末が無い可能性がある場面では、null を確認するか、System.in を BufferedReader で読む方法を使います。",
  },
  {
    id: 10602,
    topic: "io",
    variantOf: "gold-io-console",
    question:
      "次のコードを実行し、キーボードから 10 と 20 をそれぞれ Enter キーで区切って入力し、入力を終了した場合の結果はどれか。1つ選びなさい。",
    className: "SumInput",
    code: [
      "import java.io.*;",
      "",
      "public class SumInput {",
      "    public static void main(String[] args) throws IOException {",
      "        BufferedReader in = new BufferedReader(new InputStreamReader(System.in));",
      "        int sum = 0;",
      "        String line;",
      "        while ((line = in.readLine()) != null) {",
      "            sum += Integer.parseInt(line);",
      "        }",
      "        System.out.println(sum);",
      "    }",
      "}",
    ],
    stdin: "10\n20\n",
    choices: ["30", "1020", "10", "実行時に NumberFormatException がスローされる", "4行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "30" },
    explanation:
      "System.in はバイト単位の InputStream なので、InputStreamReader で文字のストリームに変換し、さらに BufferedReader で包むと 1 行ずつ readLine() で読めます。readLine() は行末の改行文字を含まない文字列を返し、入力の終わり（EOF）に達すると null を返すため、while 文で null になるまで読むのが定型です。\"10\" と \"20\" を parseInt して足すので 30 になります。バイトと文字を明確に分けたうえで、変換（InputStreamReader）やバッファリング（BufferedReader）を部品として重ねていくのが java.io の設計（デコレータパターン）です。",
  },
  {
    id: 10603,
    topic: "io",
    variantOf: "gold-io-console",
    question: "次のコードを実行し、キーボードから A と入力して Enter キーを押した場合の結果はどれか。1つ選びなさい。",
    className: "ReadByte",
    code: [
      "import java.io.*;",
      "",
      "public class ReadByte {",
      "    public static void main(String[] args) throws IOException {",
      "        int c = System.in.read();",
      "        System.out.println(c);",
      "    }",
      "}",
    ],
    stdin: "A\n",
    choices: ["65", "A", "1", "4行目でコンパイルエラーになる", "5行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "65" },
    explanation:
      "System.in は InputStream で、read() は次の 1 バイトを 0〜255 の int として返します（入力の終わりなら -1）。A の文字コードは 65 なので、出力は 65 です。戻り値が byte ではなく int なのは、有効なデータの 0〜255 に加えて「終わり」を表す -1 を区別して返すためです。文字として扱うには (char) でキャストするか、InputStreamReader を介して文字のストリームとして読みます。",
  },

  // -------------------------------------------------------------- I/O ストリーム
  {
    id: 10604,
    topic: "io",
    variantOf: "gold-io-writer-flush",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlushTest",
    code: [
      "import java.io.*;",
      "import java.nio.file.*;",
      "",
      "public class FlushTest {",
      "    public static void main(String[] args) throws IOException {",
      '        BufferedWriter w = new BufferedWriter(new FileWriter("out.txt"));',
      '        w.write("hello");',
      '        System.out.print(Files.size(Path.of("out.txt")) + " ");',
      "        w.close();",
      '        System.out.println(Files.size(Path.of("out.txt")));',
      "    }",
      "}",
    ],
    choices: ["0 5", "5 5", "0 0", "5 0", "実行時に IOException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "0 5" },
    explanation:
      "BufferedWriter は書き込まれた文字をいったん内部のバッファに溜め、バッファが一杯になるか flush() / close() が呼ばれたときにまとめて下位のストリームへ書き出します。そのため write(\"hello\") の直後はまだファイルに何も書かれておらずサイズは 0 で、close() によってバッファが書き出されて 5 バイトになります。小さな書き込みのたびにディスクへアクセスするのを避けて性能を上げるための仕組みです（FileWriter 自体も文字をバイトに変換する内部バッファを持つため、BufferedWriter が無くても flush() / close() までは書き出されないことがあります）。close() を忘れるとデータが失われます。try-with-resources で確実に閉じるのが基本です。",
  },
  {
    id: 10605,
    topic: "io",
    variantOf: "gold-io-writer-flush",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AppendTest",
    code: [
      "import java.io.*;",
      "import java.nio.file.*;",
      "",
      "public class AppendTest {",
      "    public static void main(String[] args) throws IOException {",
      '        try (Writer w = new FileWriter("log.txt")) {',
      '            w.write("ab");',
      "        }",
      '        try (Writer w = new FileWriter("log.txt", true)) {',
      '            w.write("cd");',
      "        }",
      '        System.out.print(Files.readString(Path.of("log.txt")) + " ");',
      '        try (Writer w = new FileWriter("log.txt")) {',
      '            w.write("e");',
      "        }",
      '        System.out.println(Files.readString(Path.of("log.txt")));',
      "    }",
      "}",
    ],
    choices: ["abcd e", "abcd abcde", "cd e", "ab e", "abcd eabcd"],
    correct: [0],
    expected: { kind: "output", stdout: "abcd e" },
    explanation:
      "FileWriter(ファイル名) はファイルを新規作成するか、既にあれば内容を空にしてから書き込みます。第 2 引数に true を渡した FileWriter(ファイル名, true) は追記モードで、既存の内容の末尾に書き足します。そのため ab のあとに cd が追記されて abcd になり、最後に追記なしで開き直すと内容が消えて e だけが残ります。ログファイルのように書き足していくつもりで第 2 引数を付け忘れると、過去の内容をすべて失う点に注意が必要です。",
  },
  {
    id: 10606,
    topic: "io",
    variantOf: "gold-io-reader",
    question: "カレントディレクトリに次の fruits.txt がある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SkipTest",
    code: [
      "import java.io.*;",
      "",
      "public class SkipTest {",
      "    public static void main(String[] args) throws IOException {",
      '        try (BufferedReader r = new BufferedReader(new FileReader("fruits.txt"))) {',
      "            r.readLine();",
      "            r.skip(2);",
      "            System.out.println(r.readLine() + \" \" + (char) r.read());",
      "        }",
      "    }",
      "}",
    ],
    resources: [{ path: "fruits.txt", content: ["apple", "banana", "cherry"] }],
    choices: ["nana c", "banana c", "nana h", "ana c", "banana cherry"],
    correct: [0],
    expected: { kind: "output", stdout: "nana c" },
    explanation:
      "最初の readLine() で 1 行目の apple とその改行を読み飛ばし、skip(2) で 2 行目の先頭 2 文字 ba を読み飛ばします。続く readLine() は現在位置から行末までの nana を返し、read() は次の 1 文字である 3 行目先頭の c を返します（read() の戻り値は int なので char にキャストして表示しています）。Reader は読み取り位置を 1 つだけ持ち、readLine / skip / read のどれを呼んでもその位置が進むだけ、というストリームの基本的な性質を押さえておけば、このような混在も追跡できます。",
  },
  {
    id: 10607,
    topic: "io",
    variantOf: "gold-io-reader",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MissingFile",
    code: [
      "import java.io.*;",
      "",
      "public class MissingFile {",
      "    public static void main(String[] args) {",
      '        try (FileInputStream in = new FileInputStream("none.dat")) {',
      "            System.out.println(in.read());",
      "        } catch (FileNotFoundException e) {",
      '            System.out.println("not found");',
      "        } catch (IOException e) {",
      '            System.out.println("io error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["not found", "io error", "-1", "0", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "not found" },
    explanation:
      "FileInputStream のコンストラクタは、指定したファイルが存在しない（または開けない）と FileNotFoundException をスローします。FileNotFoundException は IOException のサブクラスなので、サブクラスの catch を先に書けば、より具体的な catch ブロックで捕捉されて not found と出力されます。catch の順序を逆にすると、先の IOException ですべて捕捉されて後の catch に到達できないため、コンパイルエラーになります。空のファイルなら read() は -1 を返しますが、ファイル自体が無い場合は開く時点で例外になる点が異なります。",
  },

  // -------------------------------------------------------------- シリアライズ
  {
    id: 10608,
    topic: "io",
    variantOf: "gold-io-serialization",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SerialTest",
    code: [
      "import java.io.*;",
      "",
      "class Base {",
      "    int base = 1;",
      "    Base() {",
      '        System.out.print("B");',
      "    }",
      "}",
      "",
      "class Item extends Base implements Serializable {",
      '    String name = "pen";',
      "    transient int qty = 5;",
      "    Item() {",
      '        System.out.print("I");',
      "    }",
      "}",
      "",
      "public class SerialTest {",
      "    public static void main(String[] args) throws Exception {",
      "        Item item = new Item();",
      "        item.base = 9;",
      '        item.name = "ink";',
      "        item.qty = 7;",
      '        try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("item.ser"))) {',
      "            out.writeObject(item);",
      "        }",
      '        System.out.print(" ");',
      '        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("item.ser"))) {',
      "            Item copy = (Item) in.readObject();",
      '            System.out.println(" " + copy.base + " " + copy.name + " " + copy.qty);',
      "        }",
      "    }",
      "}",
    ],
    choices: ["BI B 1 ink 0", "BI BI 9 ink 7", "BI  9 ink 0", "BI B 9 ink 0", "BI BI 1 pen 5"],
    correct: [0],
    expected: { kind: "output", stdout: "BI B 1 ink 0" },
    explanation:
      "デシリアライズでは、Serializable なクラス（Item）のコンストラクタやフィールドの初期化子は実行されず、フィールドの値はストリームから復元されます。そのため name は保存時の ink になり、transient を付けた qty は保存されないので int の既定値 0 になります。一方、Serializable でないスーパークラス（Base）の状態は保存されないため、その引数なしコンストラクタが実行されて B が出力され、base は初期化子の 1 に戻ります。保存しなかった部分をスーパークラスのコンストラクタで作り直すという仕組みなので、Serializable でないスーパークラスには引数なしコンストラクタが必要です。",
  },
  {
    id: 10609,
    topic: "io",
    variantOf: "gold-io-serialization",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NotSerial",
    code: [
      "import java.io.*;",
      "",
      "class Engine {",
      "    int power = 100;",
      "}",
      "",
      "class Car implements Serializable {",
      "    String model = \"A1\";",
      "    Engine engine = new Engine();",
      "}",
      "",
      "public class NotSerial {",
      "    public static void main(String[] args) throws IOException {",
      "        try (ObjectOutputStream out = new ObjectOutputStream(new ByteArrayOutputStream())) {",
      "            out.writeObject(new Car());",
      '            System.out.println("saved");',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "実行時に NotSerializableException がスローされる",
      "saved",
      "7行目でコンパイルエラーになる",
      "15行目でコンパイルエラーになる",
      "saved と出力され、engine フィールドは null として保存される",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NotSerializableException" },
    explanation:
      "オブジェクトをシリアライズすると、そのオブジェクトが参照している他のオブジェクトも（transient でない限り）たどって一緒に保存されます。Car 自体は Serializable ですが、フィールドの Engine が Serializable を実装していないため、writeObject の実行中に NotSerializableException がスローされます。writeObject の引数は Object 型なので、この誤りはコンパイル時には検出されません。保存する必要のないフィールドには transient を付け、保存が必要なら参照先のクラスにも Serializable を実装します。",
  },

  // --------------------------------------------------------------- Path の操作
  {
    id: 10610,
    topic: "io",
    variantOf: "gold-io-path",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PathTest",
    code: [
      "import java.nio.file.*;",
      "",
      "public class PathTest {",
      "    public static void main(String[] args) {",
      '        Path p = Path.of("a", "b", "..", "c", "d.txt");',
      "        Path n = p.normalize();",
      '        System.out.println(p.getNameCount() + " " + n.getNameCount() + " "',
      '                + p.getName(2) + " " + n.getFileName());',
      "    }",
      "}",
    ],
    choices: ["5 3 .. d.txt", "5 5 .. d.txt", "3 3 c d.txt", "5 3 c d.txt", "4 3 .. d.txt"],
    correct: [0],
    expected: { kind: "output", stdout: "5 3 .. d.txt" },
    explanation:
      "Path は区切り文字で分けた名前要素の並びとして扱われ、a, b, .., c, d.txt の 5 要素なので getNameCount() は 5、getName(2) は 0 始まりで 3 番目の .. です。normalize() は . や .. といった冗長な要素を取り除き、b/.. が打ち消し合って a/c/d.txt の 3 要素になります。Path の多くの操作は実際のファイルシステムを参照しない純粋な文字列上の計算で、b が存在するかどうかやシンボリックリンクかどうかは考慮されません。実在のファイルに基づいて解決したい場合は toRealPath() を使います。",
  },
  {
    id: 10611,
    topic: "io",
    variantOf: "gold-io-path",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Relativize",
    code: [
      "import java.nio.file.*;",
      "",
      "public class Relativize {",
      "    public static void main(String[] args) {",
      '        Path from = Path.of("a", "b");',
      '        Path to = Path.of("a", "c", "d");',
      "        Path r = from.relativize(to);",
      "        for (Path part : r) {",
      '            System.out.print(part + " ");',
      "        }",
      '        System.out.println(from.resolve(r).normalize().getNameCount());',
      "    }",
      "}",
    ],
    choices: [".. c d 3", "c d 2", ".. .. c d 4", "c d 3", "実行時に IllegalArgumentException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: ".. c d 3" },
    explanation:
      "relativize は「from から to へたどるための相対パス」を求めます。a/b から a/c/d へ行くには、1 つ上（..）に戻ってから c/d へ進めばよいので、結果は ../c/d です。Path は Iterable<Path> なので、拡張 for 文で名前要素を 1 つずつ取り出せます。from.resolve(r) は a/b/../c/d となり、normalize すると a/c/d の 3 要素に戻ります。resolve と relativize は互いに逆の操作になるよう設計されていますが、絶対パスと相対パスを混ぜて relativize すると IllegalArgumentException になる点には注意します。",
  },

  // ------------------------------------------------------------ Files による操作
  {
    id: 10612,
    topic: "io",
    variantOf: "gold-io-files-ops",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CreateDirs",
    code: [
      "import java.nio.file.*;",
      "",
      "public class CreateDirs {",
      "    public static void main(String[] args) throws Exception {",
      '        Files.createDirectories(Path.of("x", "y"));',
      '        Files.createDirectories(Path.of("x", "y"));',
      '        System.out.print("ok ");',
      '        Files.createDirectory(Path.of("x", "y"));',
      "    }",
      "}",
    ],
    choices: [
      "ok と出力された後、FileAlreadyExistsException がスローされる",
      "ok",
      "6行目で FileAlreadyExistsException がスローされる",
      "5行目で NoSuchFileException がスローされる",
      "ok と出力された後、NoSuchFileException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "FileAlreadyExistsException", stdout: "ok" },
    explanation:
      "Files.createDirectories は、途中の親ディレクトリも含めて必要なものをすべて作成し、既にディレクトリが存在していてもエラーにしません。そのため 2 回呼んでも問題なく ok が出力されます。一方 Files.createDirectory は 1 階層だけを作成するメソッドで、既に存在すると FileAlreadyExistsException を、親ディレクトリが無いと NoSuchFileException をスローします。「確実にこのディレクトリがある状態にしたい」なら createDirectories、「新しく作ったことを保証したい」なら createDirectory と使い分けます。",
  },
  {
    id: 10613,
    topic: "io",
    variantOf: "gold-io-files-ops",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DeleteDir",
    code: [
      "import java.nio.file.*;",
      "",
      "public class DeleteDir {",
      "    public static void main(String[] args) throws Exception {",
      '        Path dir = Files.createDirectories(Path.of("work"));',
      '        Files.writeString(dir.resolve("a.txt"), "data");',
      '        System.out.print(Files.deleteIfExists(Path.of("none.txt")) + " ");',
      "        Files.delete(dir);",
      "    }",
      "}",
    ],
    choices: [
      "false と出力された後、DirectoryNotEmptyException がスローされる",
      "false",
      "true と出力された後、DirectoryNotEmptyException がスローされる",
      "7行目で NoSuchFileException がスローされる",
      "false と出力され、work ディレクトリと a.txt が削除される",
    ],
    correct: [0],
    expected: { kind: "exception", type: "DirectoryNotEmptyException", stdout: "false" },
    explanation:
      "Files.deleteIfExists は、対象が存在しなければ何もせずに false を返します（存在して削除できれば true）。一方 Files.delete は、対象が無ければ NoSuchFileException、空でないディレクトリなら DirectoryNotEmptyException をスローします。work ディレクトリには a.txt があるため、削除できずに例外になります。Files にはディレクトリを中身ごと削除するメソッドが無いため、Files.walk で得たパスを深い方から順に削除する必要があります。再帰的な削除は影響範囲が大きいので、どこまで消すかをコードで明示する形になっていると捉えるとよいでしょう。",
  },
  {
    id: 10614,
    topic: "io",
    variantOf: "gold-io-files-ops",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CopyTest",
    code: [
      "import java.nio.file.*;",
      "",
      "public class CopyTest {",
      "    public static void main(String[] args) throws Exception {",
      '        Path src = Files.writeString(Path.of("src.txt"), "new");',
      '        Path dst = Files.writeString(Path.of("dst.txt"), "old");',
      "        Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);",
      '        System.out.print(Files.readString(dst) + " ");',
      "        Files.copy(src, dst);",
      "    }",
      "}",
    ],
    choices: [
      "new と出力された後、FileAlreadyExistsException がスローされる",
      "new",
      "old と出力された後、FileAlreadyExistsException がスローされる",
      "new と出力された後、dst.txt の内容は newnew になる",
      "7行目で FileAlreadyExistsException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "FileAlreadyExistsException", stdout: "new" },
    explanation:
      "Files.copy は、コピー先が既に存在すると既定では FileAlreadyExistsException をスローします。StandardCopyOption.REPLACE_EXISTING を指定したときだけ既存のファイルを置き換えるので、1 回目のコピーで dst.txt は new になります。オプションを付けない 2 回目のコピーは、コピー先があるため例外になります。既存のファイルを黙って上書きしないのを既定の動作にすることで、意図しないデータの消失を防いでいます。Files.move も同じ規則に従います。",
  },
  {
    id: 10615,
    topic: "io",
    variantOf: "gold-io-files-ops",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AppendOption",
    code: [
      "import java.nio.file.*;",
      "",
      "public class AppendOption {",
      "    public static void main(String[] args) throws Exception {",
      '        Path p = Path.of("memo.txt");',
      '        Files.writeString(p, "a", StandardOpenOption.CREATE, StandardOpenOption.APPEND);',
      '        Files.writeString(p, "b", StandardOpenOption.APPEND);',
      '        System.out.print(Files.readString(p) + " ");',
      '        Files.writeString(Path.of("other.txt"), "c", StandardOpenOption.APPEND);',
      "    }",
      "}",
    ],
    choices: [
      "ab と出力された後、NoSuchFileException がスローされる",
      "ab",
      "b と出力された後、NoSuchFileException がスローされる",
      "6行目で NoSuchFileException がスローされる",
      "ab と出力された後、FileAlreadyExistsException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NoSuchFileException", stdout: "ab" },
    explanation:
      "Files.writeString はオプションを省略すると CREATE、TRUNCATE_EXISTING、WRITE を指定したものとして動き、ファイルを作成するか中身を空にしてから書き込みます。オプションを 1 つでも指定すると、この既定の組み合わせ（特に CREATE）は適用されません（書き込み用に開く WRITE は指定しなくても付きます）。6行目は CREATE と APPEND でファイルを作って a を書き、7行目は既存の memo.txt に b を追記するので ab になります。9行目は APPEND だけで CREATE が無いため、存在しない other.txt を作成できず NoSuchFileException になります。",
  },

  // ------------------------------------------------- Stream API によるファイル操作
  {
    id: 10616,
    topic: "io",
    variantOf: "gold-io-files-stream",
    question: "カレントディレクトリに次の scores.csv がある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CsvSum",
    code: [
      "import java.nio.file.*;",
      "import java.util.stream.*;",
      "",
      "public class CsvSum {",
      "    public static void main(String[] args) throws Exception {",
      '        try (Stream<String> lines = Files.lines(Path.of("scores.csv"))) {',
      "            int sum = lines.skip(1)",
      '                    .map(line -> line.split(","))',
      "                    .filter(cols -> cols[0].startsWith(\"t\"))",
      "                    .mapToInt(cols -> Integer.parseInt(cols[1]))",
      "                    .sum();",
      "            System.out.println(sum);",
      "        }",
      "    }",
      "}",
    ],
    resources: [{ path: "scores.csv", content: ["name,score", "taro,70", "hanako,85", "tomo,60"] }],
    choices: ["130", "215", "145", "実行時に NumberFormatException がスローされる", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "130" },
    explanation:
      "Files.lines はファイルを 1 行ずつ要素とする Stream<String> を返します。skip(1) で見出し行を読み飛ばし、名前が t で始まる taro（70）と tomo（60）の点数を合計するので 130 です。見出し行を飛ばさないと \"score\" を parseInt して NumberFormatException になります。Files.lines はファイル全体を一度にメモリへ読み込まず、必要に応じて行を読み進めるため巨大なファイルにも使えますが、その間ファイルを開いたままにするので try-with-resources で必ず閉じます。",
  },
  {
    id: 10617,
    topic: "io",
    variantOf: "gold-io-files-stream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "WalkTest",
    code: [
      "import java.nio.file.*;",
      "import java.util.stream.*;",
      "",
      "public class WalkTest {",
      "    public static void main(String[] args) throws Exception {",
      '        Path root = Path.of("root");',
      '        Files.createDirectories(root.resolve("sub"));',
      '        Files.writeString(root.resolve("a.txt"), "a");',
      '        Files.writeString(root.resolve("sub").resolve("b.txt"), "b");',
      "        try (Stream<Path> all = Files.walk(root);",
      "             Stream<Path> depth1 = Files.walk(root, 1);",
      "             Stream<Path> list = Files.list(root)) {",
      '            System.out.println(all.count() + " " + depth1.count() + " " + list.count());',
      "        }",
      "    }",
      "}",
    ],
    choices: ["4 3 2", "3 2 2", "2 2 2", "4 2 2", "3 3 2"],
    correct: [0],
    expected: { kind: "output", stdout: "4 3 2" },
    explanation:
      "Files.walk は指定したディレクトリ自身を最初の要素として含め、その配下を深さ優先でたどります。root、a.txt、sub、sub/b.txt の 4 つなので 4 です。walk(root, 1) は深さ 1 まで（root 自身とその直下）なので root、a.txt、sub の 3 つになります。Files.list はディレクトリ直下の項目だけを返し、ディレクトリ自身を含まないので a.txt と sub の 2 つです。walk が起点を含むのは、起点自身もたどった結果の 1 つとして扱うためで、ファイルだけを数えたい場合は filter(Files::isRegularFile) で絞り込みます。",
  },
  {
    id: 10618,
    topic: "io",
    variantOf: "gold-io-files-stream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FindTest",
    code: [
      "import java.nio.file.*;",
      "import java.util.stream.*;",
      "",
      "public class FindTest {",
      "    public static void main(String[] args) throws Exception {",
      '        Path docs = Files.createDirectories(Path.of("docs", "img"));',
      '        Files.writeString(Path.of("docs", "a.md"), "12345");',
      '        Files.writeString(Path.of("docs", "b.md"), "1");',
      '        Files.writeString(docs.resolve("c.md"), "123");',
      '        try (Stream<Path> s = Files.find(Path.of("docs"), 10,',
      '                (path, attr) -> path.toString().endsWith(".md") && attr.size() > 2)) {',
      "            System.out.println(s.map(p -> p.getFileName().toString()).sorted()",
      '                    .collect(Collectors.joining(",")));',
      "        }",
      "    }",
      "}",
    ],
    choices: ["a.md,c.md", "a.md", "a.md,b.md,c.md", "c.md", "a.md,b.md"],
    correct: [0],
    expected: { kind: "output", stdout: "a.md,c.md" },
    explanation:
      "Files.find(起点, 最大の深さ, 条件) は、walk と同様にディレクトリをたどりながら、パスとファイル属性（BasicFileAttributes）の 2 つを受け取る BiPredicate で絞り込みます。拡張子が .md で、サイズが 2 バイトを超える a.md（5 バイト）と img の下の c.md（3 バイト）が該当し、1 バイトの b.md は除外されます。walk で得たパスに対して Files.size を呼ぶ方法と違い、たどる途中で読み取った属性を再利用できるので、ファイルごとに改めて属性を問い合わせる必要がありません。走査の順序は保証されないため、ここでは sorted で並べてから出力しています。",
  },
];
