import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: ファイル I/O の追加問題（id 10619-10699）。
 * バイト・ストリーム、Data ストリーム、mark / reset、シリアライズの詳細、Path の操作、Files のオプションなど。
 * Path は OS によって区切り文字が異なるので、文字列として出力せず名前要素の単位で扱う。
 */
export const goldIoQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ バイト・ストリーム
  {
    id: 10619,
    topic: "io",
    variantOf: "gold-io-byte-stream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ByteRead",
    code: [
      "import java.io.*;",
      "",
      "public class ByteRead {",
      "    public static void main(String[] args) throws IOException {",
      "        try (OutputStream out = new FileOutputStream(\"data.bin\")) {",
      "            out.write(65);",
      "            out.write(322);",
      "        }",
      "        try (InputStream in = new FileInputStream(\"data.bin\")) {",
      "            int b;",
      "            while ((b = in.read()) != -1) {",
      "                System.out.print(b + \" \");",
      "            }",
      "            System.out.println(in.read());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["65 66 -1", "65 322 -1", "A B -1", "65 66 と出力された後、EOFException がスローされる", "7行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "65 66 -1" },
    explanation:
      "OutputStream.write(int) は int を受け取りますが、書き込むのは下位 8 ビットの 1 バイトだけです。322 は 0x142 なので下位 8 ビットの 0x42（66）が書き込まれます。InputStream.read() は読み込んだ 1 バイトを 0〜255 の int で返し、ストリームの終わりに達すると -1 を返します（何度呼んでも -1 で、例外にはなりません）。戻り値が byte ではなく int なのは、0〜255 のすべての値と「終わり」を表す -1 を区別するためです。char にキャストして表示しない限り、数値として出力されます。",
  },
  {
    id: 10620,
    topic: "io",
    variantOf: "gold-io-data-stream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DataRoundTrip",
    code: [
      "import java.io.*;",
      "",
      "public class DataRoundTrip {",
      "    public static void main(String[] args) throws IOException {",
      "        ByteArrayOutputStream bytes = new ByteArrayOutputStream();",
      "        try (DataOutputStream out = new DataOutputStream(bytes)) {",
      "            out.writeInt(7);",
      "            out.writeUTF(\"hi\");",
      "            out.writeBoolean(true);",
      "        }",
      "        System.out.print(bytes.size() + \" \");",
      "        try (DataInputStream in = new DataInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {",
      "            System.out.println(in.readInt() + \" \" + in.readUTF() + \" \" + in.readBoolean());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["9 7 hi true", "7 7 hi true", "4 7 hi true", "9 7 true hi", "13行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "9 7 hi true" },
    explanation:
      "DataOutputStream は Java のプリミティブ値や文字列を、機種に依存しない決まったバイト表現で書き込みます。int は 4 バイト、writeUTF は「2 バイトの長さ + 修正 UTF-8 の文字列（hi は 2 バイト）」、boolean は 1 バイトなので、合計 4 + 4 + 1 = 9 バイトです。DataInputStream で書いたときと同じ順序・同じ型で読み出すと元の値に戻ります。ファイルには型の情報が書かれていないので、読み出す順序や型を間違えると意味の無い値になる点に注意します。",
  },
  {
    id: 10621,
    topic: "io",
    variantOf: "gold-io-data-stream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DataEof",
    code: [
      "import java.io.*;",
      "",
      "public class DataEof {",
      "    public static void main(String[] args) throws IOException {",
      "        byte[] data = {0, 0, 0, 5, 1};",
      "        try (DataInputStream in = new DataInputStream(new ByteArrayInputStream(data))) {",
      "            System.out.print(in.readInt() + \" \");",
      "            System.out.print(in.readInt() + \" \");",
      "        } catch (EOFException e) {",
      "            System.out.println(\"eof\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["5 eof", "5 1", "5 -1", "0 eof", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "5 eof" },
    explanation:
      "readInt は 4 バイトを読んで 1 つの int を組み立てます。最初の 4 バイト 0, 0, 0, 5 から 5 が得られますが、残りは 1 バイトしかないため、2 回目の readInt は途中でストリームの終わりに達し EOFException をスローします。InputStream.read() が終わりを -1 で表すのに対し、DataInputStream の readInt などは -1 も正当な int 値なので、終わりを戻り値で表せず例外を使います。EOFException は IOException のサブクラスで、catch の順序もサブクラスを先に書く必要があります。",
  },

  // ------------------------------------------------------------ mark / reset
  {
    id: 10622,
    topic: "io",
    variantOf: "gold-io-reader",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MarkReset",
    code: [
      "import java.io.*;",
      "",
      "public class MarkReset {",
      "    public static void main(String[] args) throws IOException {",
      "        try (BufferedReader r = new BufferedReader(new StringReader(\"abcdef\"))) {",
      "            StringBuilder sb = new StringBuilder();",
      "            sb.append((char) r.read());",
      "            if (r.markSupported()) r.mark(10);",
      "            sb.append((char) r.read());",
      "            sb.append((char) r.read());",
      "            r.reset();",
      "            sb.append((char) r.read());",
      "            r.skip(2);",
      "            sb.append((char) r.read());",
      "            System.out.println(sb);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["abcbe", "abcde", "abcaf", "abcbd", "実行時に IOException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "abcbe" },
    explanation:
      "mark は現在の読み取り位置に印を付け、reset でその位置に戻ります。a を読んだ後の位置（b の前）に印を付けて b・c を読み、reset で b の前に戻るので次の read は b です。そこから skip(2) で c・d を読み飛ばし、次の read は e になります。mark の引数は「印を保持したまま読み進めてよい最大文字数」で、それを超えて読むと reset が失敗することがあります。BufferedReader や BufferedInputStream はバッファを持つので mark をサポートしますが、FileInputStream などはサポートしないため、markSupported() で確認してから使います。",
  },

  // ------------------------------------------------------------ PrintWriter
  {
    id: 10623,
    topic: "io",
    variantOf: "gold-io-printwriter",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PrintWriterTest",
    code: [
      "import java.io.*;",
      "",
      "public class PrintWriterTest {",
      "    public static void main(String[] args) {",
      "        StringWriter sw = new StringWriter();",
      "        PrintWriter pw = new PrintWriter(sw);",
      "        pw.printf(\"%s=%03d\", \"id\", 7);",
      "        pw.print(true);",
      "        pw.flush();",
      "        System.out.print(sw + \" \" + pw.checkError() + \" \");",
      "        pw.close();",
      "        pw.print(\"x\");",
      "        System.out.println(pw.checkError());",
      "    }",
      "}",
    ],
    choices: [
      "id=007true false true",
      "id=7true false true",
      "id=007true false と出力された後、IOException がスローされる",
      "id=007 true false true",
      "4行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "id=007true false true" },
    explanation:
      "PrintWriter の print / printf / println は IOException をスローせず、エラーが起きたかどうかを内部のフラグに記録するだけです。そのため main は throws IOException を宣言しなくてもコンパイルでき、閉じた後に print しても例外にはなりません。代わりに checkError() がフラグを調べて true を返します。%03d は 3 桁に満たない部分を 0 で埋める指定です。System.out（PrintStream）も同じ設計で、画面への出力のたびに例外処理を書かずに済む反面、ファイルへの出力では checkError を確認しないと書き込みの失敗に気付けません。",
  },

  // ------------------------------------------------------------ ラッパー・ストリームのクローズ
  {
    id: 10624,
    topic: "io",
    variantOf: "gold-io-close-wrapper",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CloseWrapper",
    code: [
      "import java.io.*;",
      "import java.nio.file.*;",
      "",
      "public class CloseWrapper {",
      "    public static void main(String[] args) throws IOException {",
      "        FileWriter fw = new FileWriter(\"memo.txt\");",
      "        BufferedWriter bw = new BufferedWriter(fw);",
      "        bw.write(\"abc\");",
      "        bw.close();",
      "        System.out.print(Files.readString(Path.of(\"memo.txt\")) + \" \");",
      "        fw.write(\"d\");",
      "        System.out.println(\"end\");",
      "    }",
      "}",
    ],
    choices: [
      "abc と出力された後、IOException がスローされる",
      "abc end",
      " と出力された後、IOException がスローされる",
      "abcd end",
      "11行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IOException", stdout: "abc" },
    explanation:
      "BufferedWriter などのラッパー（フィルタ）ストリームを close すると、バッファの内容をフラッシュしてから、包んでいる下位のストリーム（FileWriter）も close します。そのため abc はファイルに書き込まれていますが、その後に fw へ書き込むと「Stream closed」という IOException がスローされます。下位のストリームを個別に閉じる必要は無く、最も外側のラッパーだけを閉じればよい、というのが入れ子のストリームの基本的な扱いです。try-with-resources では外側のラッパーを宣言すれば十分です。",
  },

  // ------------------------------------------------------------ シリアライズの詳細
  {
    id: 10625,
    topic: "io",
    variantOf: "gold-io-serialization-static",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SerialStatic",
    code: [
      "import java.io.*;",
      "",
      "public class SerialStatic {",
      "    static class Config implements Serializable {",
      "        static String mode = \"dev\";",
      "        String name = \"app\";",
      "        transient String token = \"secret\";",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        ByteArrayOutputStream bytes = new ByteArrayOutputStream();",
      "        try (ObjectOutputStream out = new ObjectOutputStream(bytes)) {",
      "            out.writeObject(new Config());",
      "        }",
      "        Config.mode = \"prod\";",
      "        try (ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {",
      "            Config c = (Config) in.readObject();",
      "            System.out.println(c.name + \" \" + c.mode + \" \" + c.token);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["app prod null", "app dev null", "app dev secret", "app prod secret", "17行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "app prod null" },
    explanation:
      "シリアライズの対象はオブジェクトの状態、つまりインスタンス・フィールドだけです。static フィールドはクラスに属するのでストリームに書き込まれず、読み込んだオブジェクトから参照すると、その時点のクラスの値（prod）が見えます。transient を付けたフィールドも書き込まれず、復元時には型の既定値（参照型なら null）になります。フィールド初期化子の \"secret\" が使われないのは、Serializable なクラスのコンストラクタや初期化子は復元時に実行されないためです。パスワードなど保存・送信したくない値には transient を付けます。",
  },
  {
    id: 10626,
    topic: "io",
    variantOf: "gold-io-serialization-static",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RecordSerial",
    code: [
      "import java.io.*;",
      "",
      "public class RecordSerial {",
      "    record Point(int x, int y) implements Serializable {",
      "        Point {",
      "            System.out.print(\"C\");",
      "        }",
      "    }",
      "",
      "    static class Box implements Serializable {",
      "        int size;",
      "        Box(int size) {",
      "            this.size = size;",
      "            System.out.print(\"B\");",
      "        }",
      "    }",
      "",
      "    static Object copy(Object o) throws Exception {",
      "        ByteArrayOutputStream bytes = new ByteArrayOutputStream();",
      "        try (ObjectOutputStream out = new ObjectOutputStream(bytes)) {",
      "            out.writeObject(o);",
      "        }",
      "        try (ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {",
      "            return in.readObject();",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        Point p = (Point) copy(new Point(1, 2));",
      "        Box b = (Box) copy(new Box(3));",
      "        System.out.println(\" \" + p.y() + \" \" + b.size);",
      "    }",
      "}",
    ],
    choices: ["CCB 2 3", "CB 2 3", "CCBB 2 3", "CB 0 0", "4行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "CCB 2 3" },
    explanation:
      "通常の Serializable なクラスは、復元時にコンストラクタを実行せず、ストリームのデータをフィールドに直接書き戻します。そのため Box のコンストラクタは new のときの 1 回だけ（B）です。一方レコードは特別扱いされ、復元時にはストリームから読んだコンポーネントの値で正準コンストラクタが呼ばれます。そのため Point のコンパクト・コンストラクタは生成時と復元時の 2 回実行され、C が 2 つ出力されます。コンストラクタでの検証（不正な値の拒否）を迂回されないので、改ざんされたデータから不正なオブジェクトが作られる危険を減らせるのがレコードのシリアライズの利点です。",
  },
  {
    id: 10627,
    topic: "io",
    variantOf: "gold-io-serialization-custom",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CustomSerial",
    code: [
      "import java.io.*;",
      "",
      "public class CustomSerial {",
      "    static class Session implements Serializable {",
      "        String user;",
      "        transient int length;",
      "",
      "        Session(String user) {",
      "            this.user = user;",
      "            this.length = user.length();",
      "        }",
      "",
      "        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {",
      "            in.defaultReadObject();",
      "            length = user.length() * 10;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        ByteArrayOutputStream bytes = new ByteArrayOutputStream();",
      "        try (ObjectOutputStream out = new ObjectOutputStream(bytes)) {",
      "            out.writeObject(new Session(\"ann\"));",
      "        }",
      "        try (ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {",
      "            Session s = (Session) in.readObject();",
      "            System.out.println(s.user + \" \" + s.length);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["ann 30", "ann 3", "ann 0", "null 0", "13行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "ann 30" },
    explanation:
      "Serializable なクラスに private void readObject(ObjectInputStream) を定義すると、復元時に既定の処理の代わりにそのメソッドが呼ばれます（private でも ObjectInputStream がリフレクションで呼び出します）。defaultReadObject() で transient でないフィールド（user）を既定どおり復元し、その後で transient の length を自分で計算し直しているので ann 30 になります。readObject を定義しなければ length は既定値の 0 です。保存しなくても再計算できる値を transient にして復元時に作り直すのが、このフックの典型的な使い方です。書き込み側には対になる writeObject を定義できます。",
  },

  // ------------------------------------------------------------ Path の操作
  {
    id: 10628,
    topic: "io",
    variantOf: "gold-io-path-parts",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PathParts",
    code: [
      "import java.nio.file.*;",
      "",
      "public class PathParts {",
      "    public static void main(String[] args) {",
      "        Path p = Path.of(\"home\", \"user\", \"docs\", \"memo.txt\");",
      "        Path sub = p.subpath(1, 3);",
      "        Path sibling = p.resolveSibling(\"todo.txt\");",
      "        System.out.println(p.getRoot() + \" \" + p.getParent().getFileName() + \" \"",
      "                + sub.getNameCount() + \" \" + sub.getFileName() + \" \"",
      "                + sibling.getFileName() + \" \" + sibling.getNameCount());",
      "    }",
      "}",
    ],
    choices: [
      "null docs 2 docs todo.txt 4",
      "null docs 3 memo.txt todo.txt 4",
      "home docs 2 docs todo.txt 4",
      "null docs 2 user todo.txt 5",
      "null user 2 docs todo.txt 4",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "null docs 2 docs todo.txt 4" },
    explanation:
      "Path.of にディレクトリ名を並べて作ったパスは相対パスなので、ルート要素は無く getRoot() は null です。getParent() は最後の名前要素を除いたパス（home/user/docs）で、その getFileName() は docs です。subpath(1, 3) はインデックス 1 以上 3 未満の名前要素（user/docs）を取り出すので、要素数 2、最後の要素は docs です。resolveSibling は親ディレクトリに対して名前を解決する、つまり「同じディレクトリの別のファイル」を指すパスを作るので、要素数は元と同じ 4 です。これらの操作はファイルが存在しなくても、パスの文字列上だけで計算されます。",
  },
  {
    id: 10629,
    topic: "io",
    variantOf: "gold-io-path-parts",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PathMatch",
    code: [
      "import java.nio.file.*;",
      "",
      "public class PathMatch {",
      "    public static void main(String[] args) {",
      "        Path p = Path.of(\"project\", \"src\", \"Main.java\");",
      "        System.out.println(p.startsWith(\"proj\") + \" \"",
      "                + p.startsWith(Path.of(\"project\", \"src\")) + \" \"",
      "                + p.endsWith(\"Main.java\") + \" \"",
      "                + p.endsWith(\".java\"));",
      "    }",
      "}",
    ],
    choices: ["false true true false", "true true true true", "false true true true", "true true true false", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "false true true false" },
    explanation:
      "Path の startsWith / endsWith は文字列の前方一致・後方一致ではなく、名前要素の単位で比較します。\"proj\" は先頭の名前要素 project と一致しないので false、project/src は先頭の 2 要素と一致するので true です。endsWith(\"Main.java\") は最後の要素と完全に一致するので true ですが、\".java\" は要素の一部にすぎないので false です。拡張子で判定したいときは、p.getFileName().toString().endsWith(\".java\") のように文字列に変換してから String のメソッドを使います。",
  },
  {
    id: 10630,
    topic: "io",
    variantOf: "gold-io-path",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PathEquals",
    code: [
      "import java.nio.file.*;",
      "",
      "public class PathEquals {",
      "    public static void main(String[] args) {",
      "        Path a = Path.of(\"data\", \".\", \"logs\");",
      "        Path b = Path.of(\"data\", \"logs\");",
      "        Path c = Path.of(\"data\", \"tmp\", \"..\", \"logs\");",
      "        System.out.println(a.equals(b) + \" \" + a.normalize().equals(b) + \" \"",
      "                + c.normalize().equals(b) + \" \" + c.getNameCount());",
      "    }",
      "}",
    ],
    choices: ["false true true 4", "true true true 4", "false true true 2", "false false false 4", "false true false 4"],
    correct: [0],
    expected: { kind: "output", stdout: "false true true 4" },
    explanation:
      "Path.equals はパスの名前要素をそのまま比較するだけで、. や .. を解釈したり、ファイル・システム上の実体を調べたりはしません。そのため data/./logs と data/logs は別のパスとして false になります。normalize() は冗長な要素を取り除き、. を消し、名前 .. でその直前の要素を打ち消すので、どちらも data/logs になって true です。c は正規化する前は 4 つの名前要素を持ちます。同じファイルを指すかどうかをパスの比較で判定する前には、normalize するか、実在するファイルなら Files.isSameFile を使います。",
  },

  // ------------------------------------------------------------ Files の操作とオプション
  {
    id: 10631,
    topic: "io",
    variantOf: "gold-io-files-options",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MoveTest",
    code: [
      "import java.nio.file.*;",
      "",
      "public class MoveTest {",
      "    public static void main(String[] args) throws Exception {",
      "        Path a = Files.writeString(Path.of(\"a.txt\"), \"A\");",
      "        Path b = Files.writeString(Path.of(\"b.txt\"), \"B\");",
      "        Path c = Path.of(\"c.txt\");",
      "        Files.move(a, c);",
      "        System.out.print(Files.exists(a) + \" \" + Files.readString(c) + \" \");",
      "        Files.move(b, c);",
      "        System.out.println(Files.readString(c));",
      "    }",
      "}",
    ],
    choices: [
      "false A と出力された後、FileAlreadyExistsException がスローされる",
      "false A B",
      "true A B",
      "false A A",
      "true A と出力された後、FileAlreadyExistsException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "FileAlreadyExistsException", stdout: "false A" },
    explanation:
      "Files.move はファイルを移動（名前の変更）するので、移動元の a.txt は無くなり、c.txt が A の内容を持ちます。移動先に既にファイルがあると、既定では上書きせずに FileAlreadyExistsException をスローします。上書きしたい場合は StandardCopyOption.REPLACE_EXISTING を指定し、途中の状態を他から見せたくない場合は ATOMIC_MOVE を指定します。Files.copy も同じく既定では上書きしないので、「既存のファイルを黙って失わない」ことが Files の操作の基本方針だと覚えておくと混乱しません。",
  },
  {
    id: 10632,
    topic: "io",
    variantOf: "gold-io-files-options",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "WriterOptions",
    code: [
      "import java.io.*;",
      "import java.nio.file.*;",
      "",
      "public class WriterOptions {",
      "    public static void main(String[] args) throws IOException {",
      "        Path p = Path.of(\"note.txt\");",
      "        Files.writeString(p, \"12345\");",
      "        try (BufferedWriter w = Files.newBufferedWriter(p)) {",
      "            w.write(\"ab\");",
      "        }",
      "        System.out.print(Files.readString(p) + \" \");",
      "        try (BufferedWriter w = Files.newBufferedWriter(p, StandardOpenOption.CREATE_NEW)) {",
      "            w.write(\"cd\");",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "ab と出力された後、FileAlreadyExistsException がスローされる",
      "ab345 と出力された後、FileAlreadyExistsException がスローされる",
      "ab cd",
      "12345ab と出力された後、FileAlreadyExistsException がスローされる",
      "ab と出力され、正常終了する",
    ],
    correct: [0],
    expected: { kind: "exception", type: "FileAlreadyExistsException", stdout: "ab" },
    explanation:
      "Files.newBufferedWriter や Files.writeString でオプションを省略すると、CREATE・TRUNCATE_EXISTING・WRITE を指定したものとして扱われます。つまりファイルが無ければ作り、あれば中身を空にしてから書くので、12345 は消えて ab だけが残ります（先頭から上書きして ab345 になるわけではありません）。CREATE_NEW は「新しく作る場合に限る」という指定で、既にファイルがあると FileAlreadyExistsException をスローします。オプションを 1 つでも明示すると既定の組み合わせは使われないので、追記したいときは CREATE と APPEND を合わせて指定します。",
  },
  {
    id: 10633,
    topic: "io",
    variantOf: "gold-io-files-read",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ReadLines",
    code: [
      "import java.nio.file.*;",
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ReadLines {",
      "    public static void main(String[] args) throws Exception {",
      "        Path p = Path.of(\"items.txt\");",
      "        Files.write(p, List.of(\"pen\", \"\", \"ink\"));",
      "        List<String> lines = Files.readAllLines(p);",
      "        long nonEmpty;",
      "        try (Stream<String> s = Files.lines(p)) {",
      "            nonEmpty = s.filter(line -> !line.isEmpty()).count();",
      "        }",
      "        System.out.println(lines.size() + \" \" + nonEmpty + \" \" + lines.get(2));",
      "    }",
      "}",
    ],
    choices: ["3 2 ink", "2 2 ink", "3 3 ink", "4 2 ink", "3 2 と出力された後、IndexOutOfBoundsException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 2 ink" },
    explanation:
      "Files.write(Path, Iterable) は各要素を 1 行として、行ごとに行区切り文字を付けて書き込みます。空文字列の要素も空の 1 行として書かれるので、ファイルは 3 行です。Files.readAllLines は全行を List<String> として一度にメモリに読み込み、行区切り文字は取り除かれます。Files.lines は同じ内容を遅延評価のストリームとして読むので、巨大なファイルでも少しずつ処理できますが、ファイルを開いたままにしないよう try-with-resources で閉じる必要があります。空行を除くと 2 行です。",
  },
  {
    id: 10634,
    topic: "io",
    variantOf: "gold-io-files-attributes",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "AttrTest",
    code: [
      "import java.nio.file.*;",
      "import java.nio.file.attribute.*;",
      "",
      "public class AttrTest {",
      "    public static void main(String[] args) throws Exception {",
      "        Path dir = Files.createDirectories(Path.of(\"store\"));",
      "        Path file = Files.writeString(dir.resolve(\"a.txt\"), \"hello\");",
      "        Path none = dir.resolve(\"none.txt\");",
      "        BasicFileAttributes attr = Files.readAttributes(file, BasicFileAttributes.class);",
      "        System.out.print(Files.isDirectory(dir) + \" \" + attr.isRegularFile() + \" \" + attr.size() + \" \");",
      "        System.out.print(Files.exists(none) + \" \" + Files.notExists(none) + \" \");",
      "        System.out.println(Files.size(none));",
      "    }",
      "}",
    ],
    choices: [
      "true true 5 false true と出力された後、NoSuchFileException がスローされる",
      "true true 5 false true 0",
      "true true 5 false false 0",
      "true false 5 false true と出力された後、NoSuchFileException がスローされる",
      "true true 5 false true -1",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NoSuchFileException", stdout: "true true 5 false true" },
    explanation:
      "Files.readAttributes にBasicFileAttributes.class を渡すと、種類・サイズ・日時などの基本的な属性を 1 回の問い合わせでまとめて取得できます。a.txt は通常のファイルで、サイズは 5 バイトです。存在しないファイルに対して exists は false、notExists は true を返します（アクセス権が無く判定できない場合は両方 false になるので、互いの否定ではありません）。一方 Files.size のように属性を読み取るメソッドは、ファイルが無いと 0 や -1 を返すのではなく NoSuchFileException をスローします。存在確認と読み取りの間にファイルが消えることもあるので、例外を前提にした処理にしておくのが安全です。",
  },
  {
    id: 10635,
    topic: "io",
    variantOf: "gold-io-files-stream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ListFilter",
    code: [
      "import java.nio.file.*;",
      "import java.util.stream.*;",
      "",
      "public class ListFilter {",
      "    public static void main(String[] args) throws Exception {",
      "        Path base = Files.createDirectories(Path.of(\"box\", \"inner\"));",
      "        Files.writeString(Path.of(\"box\", \"b.log\"), \"\");",
      "        Files.writeString(Path.of(\"box\", \"a.log\"), \"\");",
      "        Files.writeString(base.resolve(\"c.log\"), \"\");",
      "        try (Stream<Path> s = Files.list(Path.of(\"box\"))) {",
      "            String r = s.filter(Files::isRegularFile)",
      "                    .map(p -> p.getFileName().toString())",
      "                    .sorted()",
      "                    .collect(Collectors.joining(\",\"));",
      "            System.out.println(r);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["a.log,b.log", "a.log,b.log,c.log", "a.log,b.log,inner", "b.log,a.log", "11行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "a.log,b.log" },
    explanation:
      "Files.list はディレクトリの直下にあるエントリ（ファイルとサブディレクトリ）だけを列挙し、サブディレクトリの中までは降りません。そのため inner の中の c.log は含まれず、Files::isRegularFile で通常のファイルに絞ると a.log と b.log が残ります（ディレクトリ inner は除かれます）。列挙の順序はファイル・システム次第で保証されないので、sorted() で並べ替えています。サブディレクトリまで再帰的にたどりたい場合は Files.walk や Files.find を使います。",
  },
];
