import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: JDBC（id 10701-10799）。
 * DriverManager / DataSource による接続、Statement / PreparedStatement による CRUD、CallableStatement。
 *
 * 実機検証では H2 Database（インメモリ）の JDBC ドライバをクラスパスに載せて実際に SQL を実行する（libraries: ["h2"]）。
 * ベンダーの実装に依存する挙動（例外のサブクラスやメッセージ、仕様より寛容な実装）は問わず、
 * JDBC の仕様として定まっている振る舞いだけを出題する。
 */
const DB_NOTE = "H2 Database の JDBC ドライバがクラスパスに含まれているものとする。";

export const goldJdbcQuestions: GoldQuestion[] = [
  // ------------------------------------------------------------------ 接続
  {
    id: 10701,
    topic: "jdbc",
    variantOf: "gold-jdbc-connect",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ConnectTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ConnectTest {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop")) {',
      '            System.out.print(con.isClosed() ? "closed " : "open ");',
      "        } catch (SQLException e) {",
      '            System.out.print("error1 ");',
      "        }",
      '        try (Connection con = DriverManager.getConnection("jdbc:unknown:shop")) {',
      '            System.out.println("open");',
      "        } catch (SQLException e) {",
      '            System.out.println("error2");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["open error2", "error1 error2", "open open", "error1 open", "5行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "open error2" },
    explanation:
      "JDBC 4.0 以降のドライバは、JAR の META-INF/services に自身を登録しており、DriverManager が ServiceLoader の仕組みで自動的に読み込みます。そのため Class.forName でドライバクラスを読み込まなくても、H2 の URL で接続でき open と出力されます。DriverManager は登録済みのドライバに URL を順に渡し、受け入れたドライバで接続します。jdbc:unknown: を受け入れるドライバは無いので「No suitable driver found」という SQLException になり error2 が出力されます。",
  },
  {
    id: 10702,
    topic: "jdbc",
    variantOf: "gold-jdbc-connect",
    question: "次のコードのうち、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "CountRows",
    code: [
      "import java.sql.*;",
      "",
      "public class CountRows {",
      "    static int count(Connection con) {",
      '        String sql = "SELECT COUNT(*) FROM item";',
      "        try (Statement st = con.createStatement()) {",
      "            ResultSet rs = st.executeQuery(sql);",
      "            rs.next();",
      "            return rs.getInt(1);",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println("count");',
      "    }",
      "}",
    ],
    choices: [
      "6行目でコンパイルエラーになる",
      "4行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "13行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "JDBC の API はほとんどのメソッドが検査例外の SQLException をスローすると宣言しています。count メソッドは SQLException を catch も throws もしていないため、最初に SQLException を発生しうる 6行目の createStatement() でコンパイルエラーになります（try-with-resources でも、暗黙に呼ばれる close() の例外を含めて処理が必要です）。データベースとの通信はネットワークやデータの状態によって失敗しうるので、呼び出し側に対処を強制する検査例外になっているのです。メソッドに throws SQLException を付けるか、catch して処理します。",
  },
  {
    id: 10703,
    topic: "jdbc",
    variantOf: "gold-jdbc-datasource",
    question: `${DB_NOTE}次のコードに関する説明として正しいものはどれか。1つ選びなさい。`,
    className: "DataSourceTest",
    libraries: ["h2"],
    runAsSourceFile: true,
    code: [
      "import java.sql.*;",
      "import javax.sql.DataSource;",
      "import org.h2.jdbcx.JdbcDataSource;",
      "",
      "public class DataSourceTest {",
      "    static DataSource createDataSource() {",
      "        JdbcDataSource ds = new JdbcDataSource();",
      '        ds.setURL("jdbc:h2:mem:app;DB_CLOSE_DELAY=-1");',
      "        return ds;",
      "    }",
      "",
      "    public static void main(String[] args) throws SQLException {",
      "        DataSource ds = createDataSource();",
      "        try (Connection con = ds.getConnection();",
      "             Statement st = con.createStatement();",
      '             ResultSet rs = st.executeQuery("SELECT 1 + 2")) {',
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "3 と出力される。main は接続先の設定を知らずに、DataSource インタフェースだけで接続を取得している",
      "DataSource から接続するには、先に DriverManager.registerDriver を呼ぶ必要があるため、実行時に SQLException がスローされる",
      "DataSource.getConnection() には URL を引数として渡す必要があるため、14行目でコンパイルエラーになる",
      "DataSource はインタフェースなので、13行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "3" },
    explanation:
      "javax.sql.DataSource は接続の取得方法を抽象化したインタフェースで、接続先の URL や認証情報、接続プールの設定などは DataSource の実装（ここでは H2 の JdbcDataSource）の側に持たせます。利用側は getConnection() を呼ぶだけでよく、DriverManager のように URL を毎回コードに書く必要がありません。実務ではアプリケーションサーバーやフレームワークが DataSource を構成し、JNDI や DI で利用側に渡すのが一般的です。接続プールを使う実装なら、close() は接続を切断せずプールに返却するだけになり、その違いを利用側が意識しなくて済むのも利点です。",
  },

  // ------------------------------------------------------------ ResultSet
  {
    id: 10704,
    topic: "jdbc",
    variantOf: "gold-jdbc-resultset-cursor",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CursorTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class CursorTest {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, name VARCHAR(20))");',
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 'pen'), (2, 'ink')\");",
      '            ResultSet rs = st.executeQuery("SELECT name FROM item ORDER BY id");',
      "            System.out.println(rs.getString(1));",
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["error", "pen", "ink", "null", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "error" },
    explanation:
      "executeQuery が返した直後の ResultSet のカーソルは、最初の行の「手前」を指しています。next() を呼んで最初の行に移動する前に getString を呼ぶと、読み取るべき現在行が無いため SQLException がスローされ、error が出力されます。next() は次の行へ移動し、行があれば true、もう無ければ false を返すので、while (rs.next()) { ... } と書くだけで「0 行の場合」も含めて全行を処理できます。カーソルが最初の行の手前から始まるのは、この定型で結果の有無の判定と移動を 1 回の呼び出しで済ませるための設計です。",
  },
  {
    id: 10705,
    topic: "jdbc",
    variantOf: "gold-jdbc-resultset-cursor",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ColumnIndex",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ColumnIndex {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, name VARCHAR(20))");',
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 'pen'), (2, 'ink')\");",
      '            ResultSet rs = st.executeQuery("SELECT id, name FROM item ORDER BY id");',
      "            while (rs.next()) {",
      '                System.out.print(rs.getString(1) + ":");',
      '                System.out.print(rs.getString(0) + " ");',
      "            }",
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["1:error", "1:1 2:2", "1:pen 2:ink", "pen:1 ink:2", "error"],
    correct: [0],
    expected: { kind: "output", stdout: "1:error" },
    explanation:
      "ResultSet の列番号は 0 ではなく 1 から始まります。1 行目で getString(1) は id 列の値 1 を文字列として返しますが、getString(0) は存在しない列を指すため SQLException がスローされ、catch で error が出力されます。getString は数値の列にも使え、値を文字列に変換して返します。PreparedStatement のパラメータ番号も同じく 1 始まりで、SQL の世界の番号付けに合わせた設計です。列の順序変更に強いコードにするには、rs.getString(\"name\") のように列名（ラベル）で指定する方法もあります。",
  },
  {
    id: 10706,
    topic: "jdbc",
    variantOf: "gold-jdbc-resultset-null",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "NullColumn",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class NullColumn {",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, price INT)");',
      '            st.executeUpdate("INSERT INTO item VALUES (1, NULL)");',
      '            ResultSet rs = st.executeQuery("SELECT price AS item_price FROM item");',
      "            rs.next();",
      '            int price = rs.getInt("ITEM_PRICE");',
      '            System.out.println(price + " " + rs.wasNull() + " " + rs.getObject(1));',
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "0 true null",
      "null true null",
      "0 false 0",
      "実行時に NullPointerException がスローされる",
      "実行時に SQLException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "0 true null" },
    explanation:
      "getInt の戻り値はプリミティブの int なので、列の値が SQL の NULL でも null を返せず、0 を返します。本当に 0 なのか NULL だったのかは、直前に読んだ値が NULL だったかを返す wasNull() で判定します。getObject は参照型で値を返すので、NULL はそのまま null になります。また列ラベルの指定は大文字・小文字を区別しないため、AS item_price と付けた列を \"ITEM_PRICE\" で読めます。NULL を 0 と取り違えると集計や判定を誤るため、NULL を許す列はラッパー型で受けるか wasNull() で確かめます。",
  },

  // --------------------------------------------------------- Statement の実行
  {
    id: 10707,
    topic: "jdbc",
    variantOf: "gold-jdbc-execute",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ExecuteTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ExecuteTest {",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, price INT)");',
      '            st.executeUpdate("INSERT INTO item VALUES (1, 100), (2, 300), (3, 150)");',
      '            int n = st.executeUpdate("UPDATE item SET price = price * 2 WHERE price > 120");',
      '            boolean a = st.execute("DELETE FROM item WHERE id = 1");',
      '            boolean b = st.execute("SELECT * FROM item");',
      '            System.out.println(n + " " + a + " " + st.getUpdateCount() + " " + b);',
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 false -1 true", "2 true 1 false", "1 false -1 true", "2 false 1 true", "3 false -1 true"],
    correct: [0],
    expected: { kind: "output", stdout: "2 false -1 true" },
    explanation:
      "executeUpdate は INSERT / UPDATE / DELETE の影響を受けた行数を返し、price が 120 を超える 2 行が更新されるので 2 です。execute は任意の SQL を実行でき、結果が ResultSet なら true、更新件数なら false を返します。DELETE は false、SELECT は true です。getUpdateCount() は直前の結果が更新件数ならその件数を、ResultSet なら -1 を返すため、最後に SELECT を実行した後は -1 になります。実行する SQL の種類が事前に分からない場合に、execute の戻り値で結果の取り出し方を切り替えられるようにした設計です。",
  },
  {
    id: 10708,
    topic: "jdbc",
    variantOf: "gold-jdbc-execute",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "WrongMethod",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class WrongMethod {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, price INT)");',
      '            st.executeUpdate("INSERT INTO item VALUES (1, 100)");',
      '            System.out.print("inserted ");',
      '            int n = st.executeUpdate("SELECT * FROM item");',
      '            System.out.println(n);',
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["inserted error", "inserted 1", "inserted 0", "error", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "inserted error" },
    explanation:
      "executeUpdate は更新件数を返す SQL（INSERT / UPDATE / DELETE や DDL）のためのメソッドで、ResultSet を返す SELECT を渡すと SQLException がスローされます。逆に executeQuery に更新系の SQL を渡しても SQLException になります。どちらも引数は単なる String なので、この誤りはコンパイル時には検出されず、実行して初めて分かります。SQL の種類に合ったメソッドを使い分け、種類が決まらない場合は execute を使います。",
  },

  // ---------------------------------------------------------- PreparedStatement
  {
    id: 10709,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "PreparedTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class PreparedTest {",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, name VARCHAR(20), price INT)");',
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 'pen', 100), (2, 'ink', 300), (3, 'cap', 150)\");",
      '            String sql = "SELECT name FROM item WHERE price >= ? AND price <= ? ORDER BY id";',
      "            try (PreparedStatement ps = con.prepareStatement(sql)) {",
      "                ps.setInt(2, 200);",
      "                ps.setInt(1, 100);",
      "                ResultSet rs = ps.executeQuery();",
      "                while (rs.next()) {",
      '                    System.out.print(rs.getString("name") + " ");',
      "                }",
      "            }",
      "        }",
      "    }",
      "}",
    ],
    choices: ["pen cap", "pen ink cap", "ink", "何も出力されない", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "pen cap" },
    explanation:
      "PreparedStatement の ? はパラメータのプレースホルダで、setXxx(番号, 値) の番号は SQL 中の ? の出現順に 1 から数えます。値を設定する順序は自由なので、先に 2 番目の ? に 200、次に 1 番目の ? に 100 を設定しても、条件は price >= 100 AND price <= 200 になり、pen と cap が該当します。値は SQL の文字列に埋め込まれるのではなく、SQL の構造とは別にデータとしてドライバに渡されます。そのため値に ' などが含まれていても SQL インジェクションが起きず、同じ SQL を値だけ変えて効率よく繰り返し実行できます。",
  },
  {
    id: 10710,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "MissingParam",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class MissingParam {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT, name VARCHAR(20))");',
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 'pen'), (2, 'ink')\");",
      '            PreparedStatement ps = con.prepareStatement("SELECT name FROM item WHERE id = ? OR id = ?");',
      "            ps.setInt(1, 2);",
      "            ResultSet rs = ps.executeQuery();",
      "            while (rs.next()) {",
      '                System.out.print(rs.getString(1) + " ");',
      "            }",
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["error", "ink", "pen ink", "ink null", "何も出力されない"],
    correct: [0],
    expected: { kind: "output", stdout: "error" },
    explanation:
      "PreparedStatement は、SQL 中のすべての ? に値を設定してからでないと実行できません。2 番目の ? に値を設定しないまま executeQuery を呼ぶと SQLException がスローされ、error が出力されます。未設定のパラメータを暗黙に NULL として扱わないのは、設定漏れがあっても「たまたま 0 件」のように見えて気付けない事態を防ぐためです。NULL を渡したい場合は setNull(番号, Types.INTEGER) のように明示します。",
  },
  {
    id: 10711,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "TableParam",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class TableParam {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT)");',
      '            st.executeUpdate("INSERT INTO item VALUES (1), (2)");',
      '            PreparedStatement ps = con.prepareStatement("SELECT COUNT(*) FROM ?");',
      '            ps.setString(1, "item");',
      "            ResultSet rs = ps.executeQuery();",
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["error", "2", "0", "1", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "error" },
    explanation:
      "プレースホルダの ? で置き換えられるのは SQL 中の「値」の位置だけで、テーブル名や列名、キーワードのような SQL の構造には使えません。PreparedStatement は ? を含んだまま SQL を解析（プリコンパイル）するため、FROM の後に ? がある SQL は構文として成り立たず、prepareStatement の時点で SQLException になります。値と構造を分離することが SQL インジェクションを防ぐ仕組みの核心なので、構造の部分を外から差し替えられないのは意図どおりの制約です。テーブル名を動的に選ぶ必要がある場合は、許可したものの一覧と照合してから文字列として組み立てます。",
  },

  // ------------------------------------------------------------ トランザクション
  {
    id: 10712,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "SavepointTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class SavepointTest {",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE log(id INT)");',
      "            con.setAutoCommit(false);",
      '            st.executeUpdate("INSERT INTO log VALUES (1)");',
      "            Savepoint sp = con.setSavepoint();",
      '            st.executeUpdate("INSERT INTO log VALUES (2)");',
      "            con.rollback(sp);",
      '            st.executeUpdate("INSERT INTO log VALUES (3)");',
      "            con.commit();",
      '            ResultSet rs = st.executeQuery("SELECT SUM(id) FROM log");',
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["4", "6", "1", "0", "3"],
    correct: [0],
    expected: { kind: "output", stdout: "4" },
    explanation:
      "setAutoCommit(false) にすると、SQL の実行ごとの自動コミットが止まり、commit() か rollback() を呼ぶまでが 1 つのトランザクションになります。rollback(sp) はトランザクション全体ではなく、セーブポイント sp を設定した時点以降の変更（id = 2 の挿入）だけを取り消します。その後に 3 を挿入してコミットするので、残るのは 1 と 3 で合計は 4 です。セーブポイントは、長い処理の一部だけが失敗したときに、そこまでの成果を捨てずにやり直すための仕組みです。",
  },
  {
    id: 10713,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "AutoCommitTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class AutoCommitTest {",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE log(id INT)");',
      "            System.out.print(con.getAutoCommit() + \" \");",
      "            con.setAutoCommit(false);",
      '            st.executeUpdate("INSERT INTO log VALUES (1)");',
      "            con.rollback();",
      '            st.executeUpdate("INSERT INTO log VALUES (2)");',
      "            con.setAutoCommit(true);",
      '            ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM log");',
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["true 1", "true 0", "true 2", "false 1", "false 0"],
    correct: [0],
    expected: { kind: "output", stdout: "true 1" },
    explanation:
      "取得した直後の Connection は自動コミットモードで、getAutoCommit() は true です。自動コミットを無効にして 1 を挿入したあと rollback() するので、1 の挿入は取り消されます。次に 2 を挿入した状態で setAutoCommit(true) を呼ぶと、JDBC の仕様により、その時点で保留中のトランザクションがコミットされるため、2 は確定して件数は 1 になります。モードの切り替えが暗黙のコミットを伴うことを知らないと、取り消すつもりの変更を確定させてしまうので注意が必要です。",
  },

  // ------------------------------------------------ スクロール可能な ResultSet
  {
    id: 10714,
    topic: "jdbc",
    variantOf: "gold-jdbc-scroll",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ScrollTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ScrollTest {",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,",
      "                     ResultSet.CONCUR_READ_ONLY)) {",
      '            st.execute("CREATE TABLE item(id INT)");',
      '            st.executeUpdate("INSERT INTO item VALUES (10), (20), (30)");',
      '            ResultSet rs = st.executeQuery("SELECT id FROM item ORDER BY id");',
      "            rs.last();",
      "            System.out.print(rs.getRow() + \" \");",
      "            rs.absolute(2);",
      "            System.out.print(rs.getInt(1) + \" \");",
      "            rs.previous();",
      "            rs.previous();",
      "            System.out.println(rs.isBeforeFirst());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["3 20 true", "30 20 true", "3 30 false", "3 20 false", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 20 true" },
    explanation:
      "TYPE_SCROLL_INSENSITIVE を指定した Statement から得た ResultSet は、前後に自由に移動できます。last() で最後の行に移動すると getRow() はその行番号 3 を返し、absolute(2) で 2 行目に移動すると値は 20 です。previous() を 2 回呼ぶと 1 行目を通り過ぎて「最初の行の手前」に移るので、isBeforeFirst() は true になります。既定の TYPE_FORWARD_ONLY では next() による前進しかできず、previous() などを呼ぶと SQLException になります。件数を数えるためだけに last() を使うより、SELECT COUNT(*) を発行する方が効率的です。",
  },
  {
    id: 10715,
    topic: "jdbc",
    variantOf: "gold-jdbc-scroll",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ForwardOnly",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ForwardOnly {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      '            st.execute("CREATE TABLE item(id INT)");',
      '            st.executeUpdate("INSERT INTO item VALUES (10), (20), (30)");',
      '            ResultSet rs = st.executeQuery("SELECT id FROM item ORDER BY id");',
      "            rs.next();",
      "            rs.next();",
      "            System.out.print(rs.getInt(1) + \" \");",
      "            rs.previous();",
      "            System.out.println(rs.getInt(1));",
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["20 error", "20 10", "10 error", "20 20", "error"],
    correct: [0],
    expected: { kind: "output", stdout: "20 error" },
    explanation:
      "createStatement() を引数なしで呼ぶと、ResultSet の種類は既定の TYPE_FORWARD_ONLY になります。next() を 2 回呼んで 2 行目の 20 を読むところまでは問題ありませんが、前方向にしか移動できない ResultSet で previous() を呼ぶと SQLException がスローされ、error が出力されます。前方向専用にすると、ドライバは読み終えた行を保持せずデータベースから順に受け取るだけで済むため、大量の行を扱ってもメモリを節約できます。行を行き来する必要があるときだけ TYPE_SCROLL_INSENSITIVE などを指定します。",
  },

  // ---------------------------------------------------------- CallableStatement
  {
    id: 10716,
    topic: "jdbc",
    variantOf: "gold-jdbc-callable",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CallTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class CallTest {",
      "    public static int twice(int x) {",
      "        return x * 2;",
      "    }",
      "",
      "    public static void main(String[] args) throws SQLException {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop");',
      "             Statement st = con.createStatement()) {",
      "            // 準備: ストアド・ファンクション TWICE を定義する（H2 固有の構文）",
      '            st.execute("CREATE ALIAS TWICE FOR \\"CallTest.twice\\"");',
      "",
      '            try (CallableStatement cs = con.prepareCall("{? = call TWICE(?)}")) {',
      "                cs.registerOutParameter(1, Types.INTEGER);",
      "                cs.setInt(2, 21);",
      "                cs.execute();",
      "                System.out.println(cs.getInt(1));",
      "            }",
      "        }",
      "    }",
      "}",
    ],
    choices: ["42", "21", "0", "実行時に SQLException がスローされる", "14行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "42" },
    explanation:
      "CallableStatement はデータベースに定義されたストアド・プロシージャやファンクションを呼び出すためのインタフェースで、Connection.prepareCall で作成します。{? = call 名前(?)} は JDBC のエスケープ構文で、ドライバがデータベース固有の呼び出し構文に変換します。戻り値や OUT パラメータを受け取る ? には、実行前に registerOutParameter で SQL の型を登録し、実行後に getInt などで取り出します。パラメータ番号は ? の出現順に 1 から数えるので、戻り値が 1 番、引数が 2 番になり、結果は 42 です。",
  },
  {
    id: 10717,
    topic: "jdbc",
    variantOf: "gold-jdbc-callable",
    question: "次のコードのうち、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "StatementTypes",
    code: [
      "import java.sql.*;",
      "",
      "public class StatementTypes {",
      "    static void prepare(Connection con) throws SQLException {",
      '        PreparedStatement a = con.prepareCall("{call proc(?)}");',
      '        Statement b = con.prepareStatement("SELECT 1");',
      '        CallableStatement c = con.prepareStatement("{call proc(?)}");',
      '        Statement d = con.prepareCall("{call proc()}");',
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        System.out.println("ok");',
      "    }",
      "}",
    ],
    choices: [
      "7行目でコンパイルエラーになる",
      "5行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 7 },
    explanation:
      "3 つの Statement 系インタフェースは、CallableStatement が PreparedStatement を継承し、PreparedStatement が Statement を継承するという関係にあります。prepareCall は CallableStatement を返すので、スーパーインタフェースの PreparedStatement や Statement の変数には代入できます（5・8行目）。一方 prepareStatement の戻り値は PreparedStatement なので、サブインタフェースの CallableStatement 型の変数には代入できず、7行目がコンパイルエラーになります。パラメータを扱う機能を PreparedStatement が、OUT パラメータを扱う機能を CallableStatement が段階的に追加していく設計です。",
  },

  // --------------------------------------------------------------- リソースの解放
  {
    id: 10718,
    topic: "jdbc",
    variantOf: "gold-jdbc-close",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ClosedResult",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ClosedResult {",
      "    public static void main(String[] args) {",
      '        try (Connection con = DriverManager.getConnection("jdbc:h2:mem:shop")) {',
      "            ResultSet rs;",
      "            try (Statement st = con.createStatement()) {",
      '                st.execute("CREATE TABLE item(name VARCHAR(20))");',
      "                st.executeUpdate(\"INSERT INTO item VALUES ('pen')\");",
      '                rs = st.executeQuery("SELECT name FROM item");',
      "            }",
      "            rs.next();",
      "            System.out.println(rs.getString(1));",
      "        } catch (SQLException e) {",
      '            System.out.println("error");',
      "        }",
      "    }",
      "}",
    ],
    choices: ["error", "pen", "null", "12行目でコンパイルエラーになる", "実行時に NullPointerException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "error" },
    explanation:
      "Statement を閉じると、その Statement から得た ResultSet も自動的に閉じられます。try-with-resources のブロックを抜けた時点で st が閉じられるため、12行目で閉じた ResultSet の next() を呼ぶと SQLException がスローされ、error が出力されます。同様に Connection を閉じるとそこから作った Statement も閉じられ、1 つの Statement で次の SQL を実行すると前の ResultSet は閉じられます。ResultSet はデータベース側のカーソルと結び付いているため、それを生み出したリソースより長く使うことはできないのです。",
  },
];
