import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: JDBC の追加問題（id 10719-10799）。
 * ResultSet の寿命と列の指定、PreparedStatement の再利用とバッチ、生成キー、トランザクション、メタデータなど。
 *
 * jdbc.ts と同じく H2 Database（インメモリ）で実際に SQL を実行して検証し、
 * JDBC の仕様として定まっている振る舞いだけを出題する。
 */
const DB_NOTE = "H2 Database の JDBC ドライバがクラスパスに含まれているものとする。";

export const goldJdbcQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ ResultSet の寿命
  {
    id: 10719,
    topic: "jdbc",
    variantOf: "gold-jdbc-close",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ReExecute",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ReExecute {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1), (2)\");",
      "            ResultSet a = st.executeQuery(\"SELECT id FROM item ORDER BY id\");",
      "            ResultSet b = st.executeQuery(\"SELECT COUNT(*) FROM item\");",
      "            b.next();",
      "            System.out.print(b.getInt(1) + \" \" + a.isClosed() + \" \");",
      "            a.next();",
      "            System.out.println(a.getInt(1));",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 true error", "2 false 1", "2 false error", "2 true 1", "error"],
    correct: [0],
    expected: { kind: "output", stdout: "2 true error" },
    explanation:
      "JDBC の仕様では、Statement の実行メソッドは、その Statement が以前に返した ResultSet が開いていれば暗黙に閉じます。1 つの Statement が同時に持てる ResultSet は 1 つだけなので、10行目で 2 つ目のクエリを実行した時点で a は閉じられ、isClosed() は true です。閉じた ResultSet の next() は SQLException をスローするので error が出力されます。複数の結果を同時に読み進めたい場合は、クエリごとに別の Statement を作ります。",
  },
  {
    id: 10720,
    topic: "jdbc",
    variantOf: "gold-jdbc-close",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CloseCascade",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class CloseCascade {",
      "    public static void main(String[] args) throws SQLException {",
      "        Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "        Statement st = con.createStatement();",
      "        ResultSet rs = st.executeQuery(\"SELECT 1\");",
      "        st.close();",
      "        System.out.print(rs.isClosed() + \" \" + con.isClosed() + \" \");",
      "        Statement st2 = con.createStatement();",
      "        ResultSet rs2 = st2.executeQuery(\"SELECT 2\");",
      "        rs2.close();",
      "        System.out.println(st2.isClosed());",
      "        con.close();",
      "    }",
      "}",
    ],
    choices: ["true false false", "false false false", "true false true", "false false true", "true true true"],
    correct: [0],
    expected: { kind: "output", stdout: "true false false" },
    explanation:
      "JDBC のオブジェクトは Connection → Statement → ResultSet の親子関係にあり、親を閉じると子も閉じられますが、子を閉じても親は閉じられません。Statement を閉じるとその ResultSet も閉じられるので rs.isClosed() は true ですが、Connection は開いたままです。逆に ResultSet を閉じても、それを作った Statement は開いたままなので st2.isClosed() は false です。Statement は再利用できる一方でデータベース側の資源を保持し続けるので、実務では ResultSet・Statement・Connection のそれぞれを try-with-resources で確実に閉じます。",
  },

  // ------------------------------------------------------------ 列の指定と型の変換
  {
    id: 10721,
    topic: "jdbc",
    variantOf: "gold-jdbc-column-access",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ConvertColumn",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ConvertColumn {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(code VARCHAR(10))\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES ('12'), ('x3')\");",
      "            ResultSet rs = st.executeQuery(\"SELECT code FROM item ORDER BY code\");",
      "            while (rs.next()) {",
      "                System.out.print(rs.getInt(1) + \" \");",
      "            }",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["12 error", "12 0", "12 3", "error", "11行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "12 error" },
    explanation:
      "JDBC の getter は、列の SQL 型と Java の型の間で仕様が定めた範囲の変換を行います。VARCHAR の列に getInt を使うことも許されており、値 '12' は数値の 12 に変換されます。しかし 'x3' は数値として解釈できないので、変換に失敗して SQLException がスローされ、error が出力されます。0 を返したり、数字の部分だけを取り出したりはしません。getter の選択はコンパイル時には検査されず、実際の値によって実行時に失敗することがあるので、列の型に合った getter（ここでは getString）を使うのが基本です。",
  },
  {
    id: 10722,
    topic: "jdbc",
    variantOf: "gold-jdbc-column-access",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "MetaTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class MetaTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, name VARCHAR(20), price INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 'pen', 120)\");",
      "            ResultSet rs = st.executeQuery(\"SELECT name, price * 2 AS doubled FROM item\");",
      "            ResultSetMetaData meta = rs.getMetaData();",
      "            rs.next();",
      "            int col = rs.findColumn(\"DOUBLED\");",
      "            System.out.println(meta.getColumnCount() + \" \" + col + \" \" + rs.getString(col));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 2 240", "3 2 240", "2 3 240", "2 2 120", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 2 240" },
    explanation:
      "ResultSetMetaData は、結果の列数や各列の名前・型といった「結果の形」の情報を提供します。SELECT で指定したのは name と price * 2 の 2 列なので、テーブルの列数（3）ではなく 2 です。findColumn は列ラベルから列番号を求めるメソッドで、別名 DOUBLED は 2 列目です。getString は数値型の列にも使え、値を文字列に変換した \"240\" を返します。JDBC の getter は列の SQL 型と Java の型の間で仕様が定める範囲の変換を行うので、画面表示用に getString でまとめて取り出すこともできます。",
  },

  // ------------------------------------------------------------ PreparedStatement の再利用
  {
    id: 10723,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared-reuse",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ReusePrepared",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ReusePrepared {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(name VARCHAR(20), price INT)\");",
      "            try (PreparedStatement ps = con.prepareStatement(\"INSERT INTO item VALUES (?, ?)\")) {",
      "                ps.setString(1, \"pen\");",
      "                ps.setInt(2, 100);",
      "                ps.executeUpdate();",
      "                ps.setString(1, \"ink\");",
      "                ps.executeUpdate();",
      "            }",
      "            ResultSet rs = st.executeQuery(\"SELECT COUNT(*), SUM(price) FROM item\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1) + \" \" + rs.getInt(2));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 200", "2 100", "1 100", "実行時に SQLException がスローされる", "2 0"],
    correct: [0],
    expected: { kind: "output", stdout: "2 200" },
    explanation:
      "PreparedStatement に設定したパラメータの値は、実行した後もクリアされずに保持されます。2 回目の実行では 1 番目のパラメータだけ ink に変えていますが、2 番目は前回の 100 のままなので、2 行とも price は 100 で合計 200 になります。値を明示的に消したい場合は clearParameters() を呼びます。同じ SQL を異なる値で繰り返し実行できるのが PreparedStatement の利点ですが、前回の値が残ることを忘れると、意図しない値で登録してしまうバグになります。",
  },
  {
    id: 10724,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared-reuse",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ClearParams",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ClearParams {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(name VARCHAR(20), price INT)\");",
      "            PreparedStatement ps = con.prepareStatement(\"INSERT INTO item VALUES (?, ?)\");",
      "            ps.setString(1, \"pen\");",
      "            ps.setInt(2, 100);",
      "            ps.executeUpdate();",
      "            System.out.print(\"first \");",
      "            ps.clearParameters();",
      "            ps.setString(1, \"ink\");",
      "            ps.executeUpdate();",
      "            System.out.println(\"second\");",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "first error",
      "first second",
      "error",
      "first second と出力され、ink の price には 100 が登録される",
      "13行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "first error" },
    explanation:
      "PreparedStatement に設定した値は実行後も保持されるので、通常は変えたいパラメータだけを設定し直して再実行できます。clearParameters() は、その保持されている値をすべて消去するメソッドです。消去した後は 1 番目にだけ ink を設定しているので、2 番目は未設定のまま実行することになり、SQLException がスローされて error が出力されます（前回の 100 が使われるわけではありません）。前回の値を持ち越してしまう不具合を防ぎたいときは clearParameters() で明示的に消去し、すべてのパラメータを毎回設定する、という書き方が安全です。",
  },

  // ------------------------------------------------------------ バッチ更新
  {
    id: 10725,
    topic: "jdbc",
    variantOf: "gold-jdbc-batch",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BatchTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class BatchTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, price INT)\");",
      "            try (PreparedStatement ps = con.prepareStatement(\"INSERT INTO item VALUES (?, ?)\")) {",
      "                for (int i = 1; i <= 3; i++) {",
      "                    ps.setInt(1, i);",
      "                    ps.setInt(2, i * 100);",
      "                    ps.addBatch();",
      "                }",
      "                System.out.print(ps.executeBatch().length + \" \");",
      "            }",
      "            st.addBatch(\"UPDATE item SET price = price + 1 WHERE id >= 2\");",
      "            st.addBatch(\"DELETE FROM item WHERE id = 9\");",
      "            System.out.print(st.executeBatch().length + \" \");",
      "            ResultSet rs = st.executeQuery(\"SELECT SUM(price) FROM item\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["3 2 602", "1 1 602", "3 2 600", "3 2 603", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 2 602" },
    explanation:
      "addBatch は SQL（PreparedStatement では現在のパラメータの組）を実行せずにためておき、executeBatch でまとめて送信します。戻り値の int 配列は追加したコマンドごとに 1 要素なので、3 組のパラメータの INSERT では長さ 3、2 つの SQL では長さ 2 です（バッチ全体で 1 つの結果になるわけではありません）。各要素は更新件数ですが、件数を数えられないドライバは代わりに Statement.SUCCESS_NO_INFO（-2）を返してよいと仕様で定められているので、件数の値そのものに頼る処理は移植性がありません。UPDATE で id 2 と 3 の価格が 1 ずつ増え、該当行の無い DELETE は何も変えないので、合計は 100 + 201 + 301 = 602 です。バッチには結果を返す SELECT を入れることはできません。",
  },

  // ------------------------------------------------------------ 生成キー
  {
    id: 10726,
    topic: "jdbc",
    variantOf: "gold-jdbc-generated-keys",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "GeneratedKey",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class GeneratedKey {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE member(id INT GENERATED ALWAYS AS IDENTITY, name VARCHAR(20))\");",
      "            st.executeUpdate(\"INSERT INTO member(name) VALUES ('ann')\");",
      "            String sql = \"INSERT INTO member(name) VALUES (?)\";",
      "            try (PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {",
      "                ps.setString(1, \"bob\");",
      "                int n = ps.executeUpdate();",
      "                ResultSet keys = ps.getGeneratedKeys();",
      "                keys.next();",
      "                System.out.println(n + \" \" + keys.getInt(1));",
      "            }",
      "        }",
      "    }",
      "}",
    ],
    choices: ["1 2", "1 1", "2 2", "1 0", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 2" },
    explanation:
      "prepareStatement の第 2 引数に Statement.RETURN_GENERATED_KEYS を指定すると、実行後に getGeneratedKeys() でデータベースが自動生成したキー（ここでは IDENTITY 列の値）を ResultSet として受け取れます。最初の ann に 1 が割り当てられているので、bob の id は 2 です。executeUpdate の戻り値 1 は更新件数で、キーの値ではありません。登録した行の ID を使って続けて関連データを登録するとき、改めて SELECT で探さずに済むのがこの機能の利点です。",
  },

  // ------------------------------------------------------------ トランザクション
  {
    id: 10727,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CommitRollback",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class CommitRollback {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE log(id INT)\");",
      "            con.setAutoCommit(false);",
      "            st.executeUpdate(\"INSERT INTO log VALUES (1)\");",
      "            con.commit();",
      "            st.executeUpdate(\"INSERT INTO log VALUES (2)\");",
      "            st.executeUpdate(\"INSERT INTO log VALUES (3)\");",
      "            con.rollback();",
      "            st.executeUpdate(\"INSERT INTO log VALUES (4)\");",
      "            con.setAutoCommit(true);",
      "            ResultSet rs = st.executeQuery(\"SELECT SUM(id) FROM log\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["5", "1", "10", "0", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "5" },
    explanation:
      "自動コミットを無効にすると、commit か rollback を呼ぶまでの更新が 1 つのトランザクションになります。1 は commit で確定したので、後の rollback では取り消されません。rollback が取り消すのは、直前の commit 以降の 2 と 3 だけです。その後の 4 は新しいトランザクションに属し、トランザクションの途中で setAutoCommit(true) を呼ぶとそのトランザクションがコミットされる（JDBC の仕様）ので確定します。合計は 1 + 4 = 5 です。",
  },

  // ------------------------------------------------------------ execute 系メソッドの使い分け
  {
    id: 10728,
    topic: "jdbc",
    variantOf: "gold-jdbc-execute",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "WrongExecute",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class WrongExecute {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT)\");",
      "            int n = st.executeUpdate(\"INSERT INTO item VALUES (1), (2)\");",
      "            System.out.print(n + \" \");",
      "            ResultSet rs = st.executeQuery(\"DELETE FROM item WHERE id = 1\");",
      "            System.out.println(\"deleted\");",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 error", "2 deleted", "1 error", "error", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 error" },
    explanation:
      "executeUpdate は INSERT / UPDATE / DELETE や DDL を実行し、更新件数を int で返します。2 行を挿入したので 2 です。一方 executeQuery は 1 つの ResultSet を返す SQL（SELECT）専用で、ResultSet を生成しない DELETE を渡すと SQLException がスローされます。コンパイル時には SQL の中身は検査されない（ただの文字列）ので、誤りは実行時に初めてわかります。SQL の種類が事前にわからない場合は execute を使い、戻り値の boolean で ResultSet か更新件数かを判別します。",
  },

  // ------------------------------------------------------------ SQL インジェクション
  {
    id: 10729,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "InjectionTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class InjectionTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE account(name VARCHAR(20))\");",
      "            st.executeUpdate(\"INSERT INTO account VALUES ('ann'), ('bob')\");",
      "            String input = \"x' OR '1'='1\";",
      "            ResultSet a = st.executeQuery(\"SELECT COUNT(*) FROM account WHERE name = '\" + input + \"'\");",
      "            a.next();",
      "            System.out.print(a.getInt(1) + \" \");",
      "            PreparedStatement ps = con.prepareStatement(\"SELECT COUNT(*) FROM account WHERE name = ?\");",
      "            ps.setString(1, input);",
      "            ResultSet b = ps.executeQuery();",
      "            b.next();",
      "            System.out.println(b.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 0", "0 0", "2 2", "0 2", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 0" },
    explanation:
      "文字列連結で SQL を組み立てると、入力値の中の ' が SQL の区切りとして解釈され、WHERE name = 'x' OR '1'='1' という「常に真」の条件になって全件の 2 が数えられます。これが SQL インジェクションです。PreparedStatement では、SQL の構造を先に確定させてから ? に値を渡すので、入力値はどんな文字を含んでいても 1 つの文字列リテラルとして扱われ、その名前の行は無いので 0 になります。外部からの入力を SQL に含めるときは、必ず PreparedStatement のパラメータを使います。",
  },

  // ------------------------------------------------------------ ResultSet の走査
  {
    id: 10730,
    topic: "jdbc",
    variantOf: "gold-jdbc-resultset-cursor",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "EmptyResult",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class EmptyResult {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, price INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 100), (2, 250), (3, 300)\");",
      "            ResultSet rs = st.executeQuery(\"SELECT id FROM item WHERE price > 1000\");",
      "            System.out.print(rs.next() + \" \");",
      "            rs = st.executeQuery(\"SELECT id FROM item WHERE price > 200 ORDER BY id\");",
      "            int count = 0;",
      "            while (rs.next()) {",
      "                count++;",
      "                System.out.print(rs.getInt(\"id\") + \" \");",
      "            }",
      "            System.out.println(count);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["false 2 3 2", "true 2 3 2", "false 2 3 3", "null 2 3 2", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "false 2 3 2" },
    explanation:
      "ResultSet は取得直後、カーソルが最初の行の「前」にあり、next() を呼ぶと次の行へ進んで、行があれば true を返します。該当行が 1 つも無い結果でも ResultSet は null ではなく空の ResultSet が返り、最初の next() が false になるだけです。そのため while (rs.next()) の形で書けば、0 件でも複数件でも同じコードで処理できます。条件に合う id 2 と 3 が出力され、件数は 2 です。1 件だけを期待する場合も、if (rs.next()) で行の有無を確認してから値を読みます。",
  },

  // ------------------------------------------------------------ トランザクションの原子性
  {
    id: 10731,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "TransferTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class TransferTest {",
      "    static void transfer(Connection con, int amount) throws SQLException {",
      "        con.setAutoCommit(false);",
      "        try (Statement st = con.createStatement()) {",
      "            st.executeUpdate(\"UPDATE wallet SET money = money - \" + amount + \" WHERE id = 1\");",
      "            if (amount > 100) throw new SQLException(\"limit\");",
      "            st.executeUpdate(\"UPDATE wallet SET money = money + \" + amount + \" WHERE id = 2\");",
      "            con.commit();",
      "        } catch (SQLException e) {",
      "            con.rollback();",
      "            System.out.print(e.getMessage() + \" \");",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE wallet(id INT, money INT)\");",
      "            st.executeUpdate(\"INSERT INTO wallet VALUES (1, 500), (2, 0)\");",
      "            transfer(con, 50);",
      "            transfer(con, 200);",
      "            ResultSet rs = st.executeQuery(\"SELECT money FROM wallet ORDER BY id\");",
      "            while (rs.next()) System.out.print(rs.getInt(1) + \" \");",
      "            System.out.println();",
      "        }",
      "    }",
      "}",
    ],
    choices: ["limit 450 50", "limit 250 50", "limit 250 250", "450 50", "limit 300 50"],
    correct: [0],
    expected: { kind: "output", stdout: "limit 450 50" },
    explanation:
      "transfer は出金と入金を 1 つのトランザクションにまとめています。50 の送金は両方の UPDATE が成功して commit されるので 450 と 50 になります。200 の送金では出金の UPDATE を実行した後に例外が起き、catch で rollback するので、既に実行した出金も取り消されます。結果として残高は 450 と 50 のままです。自動コミットのままだと 1 文ごとに確定してしまい、出金だけが反映された不整合な状態が残ります。「全部成功するか、何も起きなかったことにするか」をまとめて扱うのがトランザクションの役割です。",
  },
  {
    id: 10732,
    topic: "jdbc",
    variantOf: "gold-jdbc-batch",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ClearBatch",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ClearBatch {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE log(id INT)\");",
      "            st.addBatch(\"INSERT INTO log VALUES (1)\");",
      "            st.addBatch(\"INSERT INTO log VALUES (2)\");",
      "            st.clearBatch();",
      "            st.addBatch(\"INSERT INTO log VALUES (3)\");",
      "            int[] r = st.executeBatch();",
      "            int[] again = st.executeBatch();",
      "            ResultSet rs = st.executeQuery(\"SELECT SUM(id) FROM log\");",
      "            rs.next();",
      "            System.out.println(r.length + \" \" + again.length + \" \" + rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["1 0 3", "3 3 6", "1 1 6", "3 0 6", "1 1 3"],
    correct: [0],
    expected: { kind: "output", stdout: "1 0 3" },
    explanation:
      "clearBatch はためておいたコマンドをすべて捨てるので、1 と 2 の INSERT は実行されません。executeBatch は残っている 3 の INSERT だけを実行し、結果の配列の長さは 1 です。executeBatch を実行するとバッチは空にリセットされるため、続けて呼ぶと何も実行されず、長さ 0 の配列が返ります。そのため合計は 3 です。バッチは「送信待ちのコマンドの一覧」で、送信するたびに空に戻ると理解しておくと、同じコマンドを二重に送る心配をせずにループの中で使えます。",
  },

  // ------------------------------------------------------------ 更新可能な ResultSet / 型を指定した getObject / Savepoint の解放
  {
    id: 10733,
    topic: "jdbc",
    variantOf: "gold-jdbc-updatable",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "UpdatableTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class UpdatableTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,",
      "                     ResultSet.CONCUR_UPDATABLE)) {",
      "            st.execute(\"CREATE TABLE item(id INT PRIMARY KEY, price INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 100), (2, 200)\");",
      "            ResultSet rs = st.executeQuery(\"SELECT id, price FROM item ORDER BY id\");",
      "            while (rs.next()) {",
      "                rs.updateInt(\"price\", rs.getInt(\"price\") + 5);",
      "                if (rs.getInt(\"id\") == 1) rs.updateRow();",
      "            }",
      "            rs.moveToInsertRow();",
      "            rs.updateInt(\"id\", 3);",
      "            rs.updateInt(\"price\", 300);",
      "            rs.insertRow();",
      "            ResultSet sum = con.createStatement().executeQuery(\"SELECT SUM(price) FROM item\");",
      "            sum.next();",
      "            System.out.println(sum.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["605", "610", "600", "305", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "605" },
    explanation:
      "createStatement に ResultSet.CONCUR_UPDATABLE を指定すると、ResultSet から直接データベースの行を更新できます。updateXxx は現在行の値を ResultSet 上で書き換えるだけで、updateRow を呼んだ時点で初めてデータベースに反映されます。id 2 の行は updateInt の後に updateRow を呼ばずに次の行へ移動したので、変更は捨てられて 200 のままです。行の追加は、特別な挿入行に moveToInsertRow で移動し、値を設定して insertRow を呼びます。合計は 105 + 200 + 300 = 605 です。SQL を組み立てずに済む反面、updateRow の呼び忘れで変更が黙って失われる点に注意します。",
  },
  {
    id: 10734,
    topic: "jdbc",
    variantOf: "gold-jdbc-column-access",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "DateColumn",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "import java.time.*;",
      "",
      "public class DateColumn {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE event(name VARCHAR(20), held DATE)\");",
      "            try (PreparedStatement ps = con.prepareStatement(\"INSERT INTO event VALUES (?, ?)\")) {",
      "                ps.setString(1, \"launch\");",
      "                ps.setObject(2, LocalDate.of(2024, 4, 1));",
      "                ps.executeUpdate();",
      "            }",
      "            ResultSet rs = st.executeQuery(\"SELECT held FROM event\");",
      "            rs.next();",
      "            LocalDate day = rs.getObject(\"held\", LocalDate.class);",
      "            System.out.println(day.plusDays(1) + \" \" + day.getDayOfWeek());",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2024-04-02 MONDAY", "2024-04-02 TUESDAY", "2024-04-01 MONDAY", "実行時に ClassCastException がスローされる", "16行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2024-04-02 MONDAY" },
    explanation:
      "JDBC 4.2 以降では、java.time の型を setObject でそのままパラメータに渡し、getObject(列, 型.class) で取り出せます。DATE 型の列は LocalDate に対応するので、古い java.sql.Date を経由する必要がありません。getObject の第 2 引数で受け取る型を指定するのでキャストも不要で、戻り値は最初から LocalDate です。取り出した値の翌日は 2024-04-02、2024-04-01 自体は月曜日です。java.sql.Date はタイムゾーンや時刻の扱いが紛らわしいため、新しいコードでは LocalDate / LocalDateTime を使うのが推奨されます。",
  },
  {
    id: 10735,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "NamedSavepoint",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class NamedSavepoint {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE log(id INT)\");",
      "            con.setAutoCommit(false);",
      "            st.executeUpdate(\"INSERT INTO log VALUES (1)\");",
      "            Savepoint a = con.setSavepoint(\"A\");",
      "            st.executeUpdate(\"INSERT INTO log VALUES (2)\");",
      "            Savepoint b = con.setSavepoint(\"B\");",
      "            st.executeUpdate(\"INSERT INTO log VALUES (4)\");",
      "            con.rollback(a);",
      "            System.out.print(a.getSavepointName() + \" \");",
      "            st.executeUpdate(\"INSERT INTO log VALUES (8)\");",
      "            con.commit();",
      "            ResultSet rs = st.executeQuery(\"SELECT SUM(id) FROM log\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["A 9", "A 11", "A 15", "A 1", "B 9"],
    correct: [0],
    expected: { kind: "output", stdout: "A 9" },
    explanation:
      "setSavepoint(名前) で名前付きのセーブポイントを作れ、getSavepointName で名前を取得できます。rollback(a) はセーブポイント A より後の変更、つまり 2 と 4 の挿入を取り消し、A より前の 1 は残します。A より後に作ったセーブポイント B も、この巻き戻しによって無効になります。その後の 8 は同じトランザクションの続きとして commit で確定するので、合計は 1 + 8 = 9 です。セーブポイントは「トランザクション全体をやり直すほどではない部分的な失敗」を取り消すための仕組みで、commit すると全てのセーブポイントが解放されます。",
  },
];
