import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: JDBC の追加問題（id 10719-10799）。
 * ResultSet の寿命と列の指定、PreparedStatement の再利用とバッチ、生成キー、トランザクション、メタデータなど。
 *
 * jdbc.ts と同じく H2 Database（インメモリ）で実際に SQL を実行して検証し、
 * JDBC の仕様として定まっている振る舞いだけを出題する。
 */
const DB_NOTE = "H2 Database の JDBC ドライバがクラスパスに含まれているものとする。";

export const goldJdbcQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ ResultSet の寿命
  {
    id: 10719,
    topic: "jdbc",
    variantOf: "gold-jdbc-close",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ReExecute",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ReExecute {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1), (2)\");",
      "            ResultSet a = st.executeQuery(\"SELECT id FROM item ORDER BY id\");",
      "            ResultSet b = st.executeQuery(\"SELECT COUNT(*) FROM item\");",
      "            b.next();",
      "            System.out.print(b.getInt(1) + \" \" + a.isClosed() + \" \");",
      "            a.next();",
      "            System.out.println(a.getInt(1));",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 true error", "2 false 1", "2 false error", "2 true 1", "error"],
    correct: [0],
    expected: { kind: "output", stdout: "2 true error" },
    explanation:
      "JDBC の仕様では、Statement の実行メソッドは、その Statement が以前に返した ResultSet が開いていれば暗黙に閉じます。1 つの Statement が同時に持てる ResultSet は 1 つだけなので、10行目で 2 つ目のクエリを実行した時点で a は閉じられ、isClosed() は true です。閉じた ResultSet の next() は SQLException をスローするので error が出力されます。複数の結果を同時に読み進めたい場合は、クエリごとに別の Statement を作ります。",
  },
  {
    id: 10720,
    topic: "jdbc",
    variantOf: "gold-jdbc-close",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CloseCascade",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class CloseCascade {",
      "    public static void main(String[] args) throws SQLException {",
      "        Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "        Statement st = con.createStatement();",
      "        ResultSet rs = st.executeQuery(\"SELECT 1\");",
      "        st.close();",
      "        System.out.print(rs.isClosed() + \" \" + con.isClosed() + \" \");",
      "        Statement st2 = con.createStatement();",
      "        ResultSet rs2 = st2.executeQuery(\"SELECT 2\");",
      "        rs2.close();",
      "        System.out.println(st2.isClosed());",
      "        con.close();",
      "    }",
      "}",
    ],
    choices: ["true false false", "false false false", "true false true", "false false true", "true true true"],
    correct: [0],
    expected: { kind: "output", stdout: "true false false" },
    explanation:
      "JDBC のオブジェクトは Connection → Statement → ResultSet の親子関係にあり、親を閉じると子も閉じられますが、子を閉じても親は閉じられません。Statement を閉じるとその ResultSet も閉じられるので rs.isClosed() は true ですが、Connection は開いたままです。逆に ResultSet を閉じても、それを作った Statement は開いたままなので st2.isClosed() は false です。Statement は再利用できる一方でデータベース側の資源を保持し続けるので、実務では ResultSet・Statement・Connection のそれぞれを try-with-resources で確実に閉じます。",
  },

  // ------------------------------------------------------------ 列の指定と型の変換
  {
    id: 10721,
    topic: "jdbc",
    variantOf: "gold-jdbc-column-access",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ColumnIndex",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ColumnIndex {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, name VARCHAR(20))\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (7, 'pen')\");",
      "            ResultSet rs = st.executeQuery(\"SELECT id, name FROM item\");",
      "            rs.next();",
      "            System.out.print(rs.getInt(1) + \" \" + rs.getString(2) + \" \");",
      "            System.out.println(rs.getString(0));",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["7 pen error", "7 pen 7", "7 pen null", "error", "12行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "7 pen error" },
    explanation:
      "ResultSet の列番号は 0 ではなく 1 から始まります（PreparedStatement のパラメータ番号も同じです）。1 列目の id と 2 列目の name は正しく取得できますが、存在しない列番号 0 を指定すると SQLException がスローされ error が出力されます。列番号はコンパイル時には検査できない単なる int なので、誤りは実行時まで見つかりません。SQL の列の並びを変えても壊れにくいよう、列ラベル（rs.getString(\"name\")）で指定する書き方もよく使われます。",
  },
  {
    id: 10722,
    topic: "jdbc",
    variantOf: "gold-jdbc-column-access",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "MetaTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class MetaTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, name VARCHAR(20), price INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 'pen', 120)\");",
      "            ResultSet rs = st.executeQuery(\"SELECT name, price * 2 AS doubled FROM item\");",
      "            ResultSetMetaData meta = rs.getMetaData();",
      "            rs.next();",
      "            int col = rs.findColumn(\"DOUBLED\");",
      "            System.out.println(meta.getColumnCount() + \" \" + col + \" \" + rs.getString(col));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 2 240", "3 2 240", "2 3 240", "2 2 120", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 2 240" },
    explanation:
      "ResultSetMetaData は、結果の列数や各列の名前・型といった「結果の形」の情報を提供します。SELECT で指定したのは name と price * 2 の 2 列なので、テーブルの列数（3）ではなく 2 です。findColumn は列ラベルから列番号を求めるメソッドで、別名 DOUBLED は 2 列目です。getString は数値型の列にも使え、値を文字列に変換した \"240\" を返します。JDBC の getter は列の SQL 型と Java の型の間で仕様が定める範囲の変換を行うので、画面表示用に getString でまとめて取り出すこともできます。",
  },

  // ------------------------------------------------------------ PreparedStatement の再利用
  {
    id: 10723,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared-reuse",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ReusePrepared",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ReusePrepared {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(name VARCHAR(20), price INT)\");",
      "            try (PreparedStatement ps = con.prepareStatement(\"INSERT INTO item VALUES (?, ?)\")) {",
      "                ps.setString(1, \"pen\");",
      "                ps.setInt(2, 100);",
      "                ps.executeUpdate();",
      "                ps.setString(1, \"ink\");",
      "                ps.executeUpdate();",
      "            }",
      "            ResultSet rs = st.executeQuery(\"SELECT COUNT(*), SUM(price) FROM item\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1) + \" \" + rs.getInt(2));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 200", "2 100", "1 100", "実行時に SQLException がスローされる", "2 0"],
    correct: [0],
    expected: { kind: "output", stdout: "2 200" },
    explanation:
      "PreparedStatement に設定したパラメータの値は、実行した後もクリアされずに保持されます。2 回目の実行では 1 番目のパラメータだけ ink に変えていますが、2 番目は前回の 100 のままなので、2 行とも price は 100 で合計 200 になります。値を明示的に消したい場合は clearParameters() を呼びます。同じ SQL を異なる値で繰り返し実行できるのが PreparedStatement の利点ですが、前回の値が残ることを忘れると、意図しない値で登録してしまうバグになります。",
  },
  {
    id: 10724,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared-reuse",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "MissingParam",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class MissingParam {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(name VARCHAR(20), price INT)\");",
      "            PreparedStatement ps = con.prepareStatement(\"INSERT INTO item VALUES (?, ?)\");",
      "            ps.setString(1, \"pen\");",
      "            System.out.print(\"prepared \");",
      "            ps.executeUpdate();",
      "            System.out.println(\"inserted\");",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["prepared error", "prepared inserted", "error", "8行目でコンパイルエラーになる", "prepared inserted と出力され、price には 0 が登録される"],
    correct: [0],
    expected: { kind: "output", stdout: "prepared error" },
    explanation:
      "PreparedStatement のすべての ? には、実行前に値を設定しなければなりません。2 番目のパラメータに値を設定しないまま executeUpdate を呼ぶと SQLException がスローされます。値が設定されていないパラメータに 0 や NULL が自動で入ることはありません。NULL を登録したい場合は setNull(2, Types.INTEGER) のように明示します。準備（prepareStatement）の時点では値が無くてよいので、エラーになるのは実行した時点です。",
  },

  // ------------------------------------------------------------ バッチ更新
  {
    id: 10725,
    topic: "jdbc",
    variantOf: "gold-jdbc-batch",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BatchTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "import java.util.*;",
      "",
      "public class BatchTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, price INT)\");",
      "            try (PreparedStatement ps = con.prepareStatement(\"INSERT INTO item VALUES (?, ?)\")) {",
      "                for (int i = 1; i <= 3; i++) {",
      "                    ps.setInt(1, i);",
      "                    ps.setInt(2, i * 100);",
      "                    ps.addBatch();",
      "                }",
      "                int[] counts = ps.executeBatch();",
      "                System.out.print(Arrays.toString(counts) + \" \");",
      "            }",
      "            st.addBatch(\"UPDATE item SET price = price + 1 WHERE id >= 2\");",
      "            st.addBatch(\"DELETE FROM item WHERE id = 9\");",
      "            System.out.println(Arrays.toString(st.executeBatch()));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["[1, 1, 1] [2, 0]", "[3] [2, 0]", "[1, 1, 1] [2]", "3 2", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 1, 1] [2, 0]" },
    explanation:
      "addBatch は SQL（PreparedStatement では現在のパラメータの組）を実行せずにためておき、executeBatch でまとめて送信します。戻り値の int 配列は、追加した順に各コマンドの更新件数を表します。3 回の INSERT はそれぞれ 1 件、UPDATE は id が 2 と 3 の 2 件、該当行の無い DELETE は 0 件です。データベースとの往復がコマンドごとではなく 1 回で済むため、大量の登録や更新を高速化できます。バッチには結果を返す SELECT を入れることはできません。",
  },

  // ------------------------------------------------------------ 生成キー
  {
    id: 10726,
    topic: "jdbc",
    variantOf: "gold-jdbc-generated-keys",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "GeneratedKey",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class GeneratedKey {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE member(id INT GENERATED ALWAYS AS IDENTITY, name VARCHAR(20))\");",
      "            st.executeUpdate(\"INSERT INTO member(name) VALUES ('ann')\");",
      "            String sql = \"INSERT INTO member(name) VALUES (?)\";",
      "            try (PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {",
      "                ps.setString(1, \"bob\");",
      "                int n = ps.executeUpdate();",
      "                ResultSet keys = ps.getGeneratedKeys();",
      "                keys.next();",
      "                System.out.println(n + \" \" + keys.getInt(1));",
      "            }",
      "        }",
      "    }",
      "}",
    ],
    choices: ["1 2", "1 1", "2 2", "1 0", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 2" },
    explanation:
      "prepareStatement の第 2 引数に Statement.RETURN_GENERATED_KEYS を指定すると、実行後に getGeneratedKeys() でデータベースが自動生成したキー（ここでは IDENTITY 列の値）を ResultSet として受け取れます。最初の ann に 1 が割り当てられているので、bob の id は 2 です。executeUpdate の戻り値 1 は更新件数で、キーの値ではありません。登録した行の ID を使って続けて関連データを登録するとき、改めて SELECT で探さずに済むのがこの機能の利点です。",
  },

  // ------------------------------------------------------------ トランザクション
  {
    id: 10727,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CommitRollback",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class CommitRollback {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE log(id INT)\");",
      "            con.setAutoCommit(false);",
      "            st.executeUpdate(\"INSERT INTO log VALUES (1)\");",
      "            con.commit();",
      "            st.executeUpdate(\"INSERT INTO log VALUES (2)\");",
      "            st.executeUpdate(\"INSERT INTO log VALUES (3)\");",
      "            con.rollback();",
      "            st.executeUpdate(\"INSERT INTO log VALUES (4)\");",
      "            con.setAutoCommit(true);",
      "            ResultSet rs = st.executeQuery(\"SELECT SUM(id) FROM log\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["5", "1", "10", "0", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "5" },
    explanation:
      "自動コミットを無効にすると、commit か rollback を呼ぶまでの更新が 1 つのトランザクションになります。1 は commit で確定したので、後の rollback では取り消されません。rollback が取り消すのは、直前の commit 以降の 2 と 3 だけです。その後の 4 は新しいトランザクションに属し、トランザクションの途中で setAutoCommit(true) を呼ぶとそのトランザクションがコミットされる（JDBC の仕様）ので確定します。合計は 1 + 4 = 5 です。",
  },

  // ------------------------------------------------------------ execute 系メソッドの使い分け
  {
    id: 10728,
    topic: "jdbc",
    variantOf: "gold-jdbc-execute",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "WrongExecute",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class WrongExecute {",
      "    public static void main(String[] args) {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT)\");",
      "            int n = st.executeUpdate(\"INSERT INTO item VALUES (1), (2)\");",
      "            System.out.print(n + \" \");",
      "            ResultSet rs = st.executeQuery(\"DELETE FROM item WHERE id = 1\");",
      "            System.out.println(\"deleted\");",
      "        } catch (SQLException e) {",
      "            System.out.println(\"error\");",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 error", "2 deleted", "1 error", "error", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 error" },
    explanation:
      "executeUpdate は INSERT / UPDATE / DELETE や DDL を実行し、更新件数を int で返します。2 行を挿入したので 2 です。一方 executeQuery は 1 つの ResultSet を返す SQL（SELECT）専用で、ResultSet を生成しない DELETE を渡すと SQLException がスローされます。コンパイル時には SQL の中身は検査されない（ただの文字列）ので、誤りは実行時に初めてわかります。SQL の種類が事前にわからない場合は execute を使い、戻り値の boolean で ResultSet か更新件数かを判別します。",
  },

  // ------------------------------------------------------------ SQL インジェクション
  {
    id: 10729,
    topic: "jdbc",
    variantOf: "gold-jdbc-prepared",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "InjectionTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class InjectionTest {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE account(name VARCHAR(20))\");",
      "            st.executeUpdate(\"INSERT INTO account VALUES ('ann'), ('bob')\");",
      "            String input = \"x' OR '1'='1\";",
      "            ResultSet a = st.executeQuery(\"SELECT COUNT(*) FROM account WHERE name = '\" + input + \"'\");",
      "            a.next();",
      "            System.out.print(a.getInt(1) + \" \");",
      "            PreparedStatement ps = con.prepareStatement(\"SELECT COUNT(*) FROM account WHERE name = ?\");",
      "            ps.setString(1, input);",
      "            ResultSet b = ps.executeQuery();",
      "            b.next();",
      "            System.out.println(b.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["2 0", "0 0", "2 2", "0 2", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "2 0" },
    explanation:
      "文字列連結で SQL を組み立てると、入力値の中の ' が SQL の区切りとして解釈され、WHERE name = 'x' OR '1'='1' という「常に真」の条件になって全件の 2 が数えられます。これが SQL インジェクションです。PreparedStatement では、SQL の構造を先に確定させてから ? に値を渡すので、入力値はどんな文字を含んでいても 1 つの文字列リテラルとして扱われ、その名前の行は無いので 0 になります。外部からの入力を SQL に含めるときは、必ず PreparedStatement のパラメータを使います。",
  },

  // ------------------------------------------------------------ ResultSet の走査
  {
    id: 10730,
    topic: "jdbc",
    variantOf: "gold-jdbc-resultset-cursor",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "EmptyResult",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class EmptyResult {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE item(id INT, price INT)\");",
      "            st.executeUpdate(\"INSERT INTO item VALUES (1, 100), (2, 250), (3, 300)\");",
      "            ResultSet rs = st.executeQuery(\"SELECT id FROM item WHERE price > 1000\");",
      "            System.out.print(rs.next() + \" \");",
      "            rs = st.executeQuery(\"SELECT id FROM item WHERE price > 200 ORDER BY id\");",
      "            int count = 0;",
      "            while (rs.next()) {",
      "                count++;",
      "                System.out.print(rs.getInt(\"id\") + \" \");",
      "            }",
      "            System.out.println(count);",
      "        }",
      "    }",
      "}",
    ],
    choices: ["false 2 3 2", "true 2 3 2", "false 2 3 3", "null 2 3 2", "実行時に SQLException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "false 2 3 2" },
    explanation:
      "ResultSet は取得直後、カーソルが最初の行の「前」にあり、next() を呼ぶと次の行へ進んで、行があれば true を返します。該当行が 1 つも無い結果でも ResultSet は null ではなく空の ResultSet が返り、最初の next() が false になるだけです。そのため while (rs.next()) の形で書けば、0 件でも複数件でも同じコードで処理できます。条件に合う id 2 と 3 が出力され、件数は 2 です。1 件だけを期待する場合も、if (rs.next()) で行の有無を確認してから値を読みます。",
  },

  // ------------------------------------------------------------ トランザクションの原子性
  {
    id: 10731,
    topic: "jdbc",
    variantOf: "gold-jdbc-transaction",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "TransferTest",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class TransferTest {",
      "    static void transfer(Connection con, int amount) throws SQLException {",
      "        con.setAutoCommit(false);",
      "        try (Statement st = con.createStatement()) {",
      "            st.executeUpdate(\"UPDATE wallet SET money = money - \" + amount + \" WHERE id = 1\");",
      "            if (amount > 100) throw new SQLException(\"limit\");",
      "            st.executeUpdate(\"UPDATE wallet SET money = money + \" + amount + \" WHERE id = 2\");",
      "            con.commit();",
      "        } catch (SQLException e) {",
      "            con.rollback();",
      "            System.out.print(e.getMessage() + \" \");",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE wallet(id INT, money INT)\");",
      "            st.executeUpdate(\"INSERT INTO wallet VALUES (1, 500), (2, 0)\");",
      "            transfer(con, 50);",
      "            transfer(con, 200);",
      "            ResultSet rs = st.executeQuery(\"SELECT money FROM wallet ORDER BY id\");",
      "            while (rs.next()) System.out.print(rs.getInt(1) + \" \");",
      "            System.out.println();",
      "        }",
      "    }",
      "}",
    ],
    choices: ["limit 450 50", "limit 250 50", "limit 250 250", "450 50", "limit 300 50"],
    correct: [0],
    expected: { kind: "output", stdout: "limit 450 50" },
    explanation:
      "transfer は出金と入金を 1 つのトランザクションにまとめています。50 の送金は両方の UPDATE が成功して commit されるので 450 と 50 になります。200 の送金では出金の UPDATE を実行した後に例外が起き、catch で rollback するので、既に実行した出金も取り消されます。結果として残高は 450 と 50 のままです。自動コミットのままだと 1 文ごとに確定してしまい、出金だけが反映された不整合な状態が残ります。「全部成功するか、何も起きなかったことにするか」をまとめて扱うのがトランザクションの役割です。",
  },
  {
    id: 10732,
    topic: "jdbc",
    variantOf: "gold-jdbc-batch",
    question: `${DB_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ClearBatch",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class ClearBatch {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE log(id INT)\");",
      "            st.addBatch(\"INSERT INTO log VALUES (1)\");",
      "            st.addBatch(\"INSERT INTO log VALUES (2)\");",
      "            st.clearBatch();",
      "            st.addBatch(\"INSERT INTO log VALUES (3)\");",
      "            int[] r = st.executeBatch();",
      "            int[] again = st.executeBatch();",
      "            ResultSet rs = st.executeQuery(\"SELECT SUM(id) FROM log\");",
      "            rs.next();",
      "            System.out.println(r.length + \" \" + again.length + \" \" + rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: ["1 0 3", "3 3 6", "1 1 6", "3 0 6", "1 1 3"],
    correct: [0],
    expected: { kind: "output", stdout: "1 0 3" },
    explanation:
      "clearBatch はためておいたコマンドをすべて捨てるので、1 と 2 の INSERT は実行されません。executeBatch は残っている 3 の INSERT だけを実行し、結果の配列の長さは 1 です。executeBatch を実行するとバッチは空にリセットされるため、続けて呼ぶと何も実行されず、長さ 0 の配列が返ります。そのため合計は 3 です。バッチは「送信待ちのコマンドの一覧」で、送信するたびに空に戻ると理解しておくと、同じコマンドを二重に送る心配をせずにループの中で使えます。",
  },
];
