import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: ローカライズの追加問題（id 10820-10899）。
 * Locale.Builder と表示名、リソース・バンドルの親子関係、MessageFormat の引用符、数値・日付の書式と解析。
 *
 * localization.ts と同じく、実機検証は既定ロケール ja_JP・タイムゾーン Asia/Tokyo で行う。
 */
const JA_NOTE = "デフォルトロケールは ja_JP とする。";

export const goldLocalizationQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------------- Locale
  {
    id: 10820,
    topic: "localization",
    variantOf: "gold-localization-locale-builder",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "BuilderTest",
    code: [
      "import java.util.*;",
      "",
      "public class BuilderTest {",
      "    public static void main(String[] args) {",
      "        Locale a = new Locale.Builder().setLanguage(\"EN\").setRegion(\"gb\").build();",
      "        System.out.print(a + \" \" + a.toLanguageTag() + \" \");",
      "        Locale b = new Locale.Builder().setLanguage(\"ja\").setRegion(\"Japan\").build();",
      "        System.out.println(b);",
      "    }",
      "}",
    ],
    choices: [
      "en_GB en-GB と出力された後、IllformedLocaleException がスローされる",
      "en_GB en-GB ja_JAPAN",
      "EN_gb EN-gb と出力された後、IllformedLocaleException がスローされる",
      "en_GB en_GB ja_JAPAN",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllformedLocaleException", stdout: "en_GB en-GB" },
    explanation:
      "Locale.Builder は言語・地域などを 1 つずつ設定して Locale を組み立てるクラスで、大文字・小文字を正規化し（言語は小文字、地域は大文字）、値の形式を検証します。toString は en_GB とアンダースコア区切り、toLanguageTag は BCP 47 形式の en-GB とハイフン区切りになる点も区別が必要です。地域コードは英字 2 文字か数字 3 文字でなければならず、\"Japan\" は不正なので build の前の setRegion で IllformedLocaleException がスローされます。new Locale(...) は値を検証せずに受け入れるので、外部からの値でロケールを作るときは Builder か forLanguageTag を使うと誤りに早く気付けます。",
  },
  {
    id: 10821,
    topic: "localization",
    variantOf: "gold-localization-locale-builder",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DisplayName",
    code: [
      "import java.util.*;",
      "",
      "public class DisplayName {",
      "    public static void main(String[] args) {",
      "        Locale fr = Locale.FRANCE;",
      "        System.out.println(fr.getLanguage() + \" \" + fr.getCountry() + \" \"",
      "                + fr.getDisplayLanguage(Locale.US) + \" \"",
      "                + fr.getDisplayCountry(Locale.JAPAN) + \" \"",
      "                + fr.getDisplayLanguage(fr));",
      "    }",
      "}",
    ],
    choices: [
      "fr FR French フランス français",
      "fr FR French France French",
      "FR fr French フランス français",
      "fr FR French France français",
      "fr FR フランス語 フランス français",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "fr FR French フランス français" },
    explanation:
      "getLanguage と getCountry は ISO のコード（小文字の言語 fr、大文字の地域 FR）をそのまま返します。getDisplayLanguage / getDisplayCountry は人間向けの名前を返し、引数で「どの言語で表示するか」を指定します。英語なら French、日本語ならフランス、フランス語自身なら français です。引数を省略するとデフォルトの表示ロケールが使われるので、実行環境によって結果が変わります。ロケールの選択肢を画面に並べるときは、利用者の言語で表示するか、そのロケール自身の言語で表示するかを意識して引数を選びます。",
  },

  // ------------------------------------------------------------------- リソース・バンドルの検索
  {
    id: 10822,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "DefaultFallback",
    code: [
      "import java.util.*;",
      "",
      "public class DefaultFallback {",
      "    public static void main(String[] args) {",
      "        ResourceBundle de = ResourceBundle.getBundle(\"Menu\", Locale.GERMANY);",
      "        ResourceBundle root = ResourceBundle.getBundle(\"Menu\", Locale.ROOT);",
      "        System.out.println(de.getString(\"title\") + \" \" + root.getString(\"title\") + \" \"",
      "                + de.getLocale() + \"|\" + root.getLocale() + \"|\");",
      "    }",
      "}",
    ],
    resources: [
      { path: "Menu.properties", content: ["title=Menu"] },
      { path: "Menu_ja.properties", content: ["title=メニュー"] },
    ],
    choices: [
      "メニュー Menu ja||",
      "Menu Menu ||",
      "メニュー メニュー ja|ja|",
      "Menu メニュー |ja|",
      "実行時に MissingResourceException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "メニュー Menu ja||" },
    explanation:
      "Locale.GERMANY を指定すると Menu_de_DE → Menu_de の順に探しますが、どちらも無いので、基底の Menu に進む前にデフォルトロケール（ja_JP）の候補 Menu_ja_JP → Menu_ja を探し、Menu_ja が見つかります。そのため「ドイツ語が無ければ英語（基底）」ではなく日本語が選ばれる点に注意します。Locale.ROOT は「特定の言語を持たない」ロケールで、候補は基底の Menu だけになり、デフォルトロケールへの切り替えも行われません。getLocale() は実際に選ばれたバンドルのロケールで、基底のバンドルでは空のロケールです。",
  },
  {
    id: 10823,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次の 3 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ParentChain",
    code: [
      "import java.util.*;",
      "",
      "public class ParentChain {",
      "    public static void main(String[] args) {",
      "        ResourceBundle rb = ResourceBundle.getBundle(\"Shop\", Locale.CANADA_FRENCH);",
      "        System.out.println(rb.getString(\"cart\") + \" \" + rb.getString(\"pay\") + \" \"",
      "                + rb.getString(\"help\"));",
      "    }",
      "}",
    ],
    resources: [
      { path: "Shop.properties", content: ["cart=Cart", "pay=Pay", "help=Help"] },
      { path: "Shop_fr.properties", content: ["cart=Panier", "pay=Payer"] },
      { path: "Shop_fr_CA.properties", content: ["cart=Chariot"] },
    ],
    choices: [
      "Chariot Payer Help",
      "Chariot Pay Help",
      "Panier Payer Help",
      "Chariot と出力された後、MissingResourceException がスローされる",
      "Cart Pay Help",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Chariot Payer Help" },
    explanation:
      "getBundle は最も具体的に一致する Shop_fr_CA を返しますが、そのバンドルは Shop_fr を親に、Shop_fr は基底の Shop を親に持つ親子の連鎖になっています。getString はまず自身でキーを探し、無ければ親、さらにその親へと順にたどります。cart は Shop_fr_CA、pay は Shop_fr、help は Shop で見つかります。この仕組みにより、地域ごとの差分だけを具体的なファイルに書き、共通の訳は言語のファイル、既定の文言は基底のファイルにまとめる、という管理ができます。",
  },
  {
    id: 10824,
    topic: "localization",
    variantOf: "gold-localization-bundle-parent",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BundleKeys",
    code: [
      "import java.util.*;",
      "",
      "public class BundleKeys {",
      "    public static void main(String[] args) {",
      "        ResourceBundle rb = ResourceBundle.getBundle(\"Labels\", Locale.JAPAN);",
      "        Set<String> keys = new TreeSet<>(rb.keySet());",
      "        System.out.println(keys + \" \" + rb.containsKey(\"ok\") + \" \" + rb.getString(\"ok\"));",
      "    }",
      "}",
    ],
    resources: [
      { path: "Labels.properties", content: ["ok=OK", "cancel=Cancel"] },
      { path: "Labels_ja.properties", content: ["cancel=取消", "save=保存"] },
    ],
    choices: [
      "[cancel, ok, save] true OK",
      "[cancel, save] false OK",
      "[cancel, save] true OK",
      "[cancel, ok, save] true null",
      "[cancel, ok, cancel, save] true OK",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[cancel, ok, save] true OK" },
    explanation:
      "ResourceBundle.keySet() と containsKey は、そのバンドル自身だけでなく親のバンドルのキーも含めて扱います。Labels_ja には ok がありませんが、親の Labels にあるので keySet に含まれ、containsKey も true、getString(\"ok\") も親から OK を取得します。cancel は両方にありますが、Set なので 1 つにまとまり、値は子の Labels_ja（取消）が優先されます。画面の全ラベルを一覧にするときなども、子に無いキーが親から補われる前提で扱えます。",
  },

  // ------------------------------------------------------------------- MessageFormat
  {
    id: 10825,
    topic: "localization",
    variantOf: "gold-localization-messageformat",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ChoiceMessage",
    code: [
      "import java.text.*;",
      "",
      "public class ChoiceMessage {",
      "    public static void main(String[] args) {",
      "        String p = \"{0,choice,0#no files|1#one file|1<{0,number,integer} files}\";",
      "        System.out.println(MessageFormat.format(p, 0) + \" / \" + MessageFormat.format(p, 1) + \" / \"",
      "                + MessageFormat.format(p, 3));",
      "    }",
      "}",
    ],
    choices: [
      "no files / one file / 3 files",
      "no files / one file / one file",
      "0 files / 1 files / 3 files",
      "no files / one file / {0,number,integer} files",
      "実行時に IllegalArgumentException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "no files / one file / 3 files" },
    explanation:
      "MessageFormat の {0,choice,...} は、引数の数値の範囲に応じて表示する文言を選ぶ書式（ChoiceFormat）です。0# は「0 以上」、1# は「1 以上」、1< は「1 より大きい」を表し、値が当てはまる最後の範囲の文言が選ばれるので、0 は no files、1 は one file、3 は 3 files になります。選ばれた文言の中に {0,number,integer} のようなパターンを入れ子にすると、その部分も引数で置き換えられます。英語の \"1 file\" と \"2 files\" のように、数によって語形が変わる言語の文言を、条件分岐のコードを書かずにリソース・バンドルの訳文だけで表現するための仕組みです。",
  },

  // ------------------------------------------------------------------- 数値の書式
  {
    id: 10826,
    topic: "localization",
    variantOf: "gold-localization-numberformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "RoundingTest",
    code: [
      "import java.math.RoundingMode;",
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class RoundingTest {",
      "    public static void main(String[] args) {",
      "        NumberFormat even = NumberFormat.getInstance(Locale.US);",
      "        even.setMaximumFractionDigits(1);",
      "        NumberFormat up = NumberFormat.getInstance(Locale.US);",
      "        up.setMaximumFractionDigits(1);",
      "        up.setRoundingMode(RoundingMode.HALF_UP);",
      "        System.out.println(even.format(1.25) + \" \" + even.format(1.75) + \" \"",
      "                + up.format(1.25) + \" \" + up.format(1.75));",
      "    }",
      "}",
    ],
    choices: ["1.2 1.8 1.3 1.8", "1.3 1.8 1.3 1.8", "1.2 1.7 1.3 1.8", "1.25 1.75 1.3 1.8", "1.2 1.8 1.2 1.8"],
    correct: [0],
    expected: { kind: "output", stdout: "1.2 1.8 1.3 1.8" },
    explanation:
      "setMaximumFractionDigits(1) で小数部を 1 桁までに制限すると、それより下の桁は丸められます。NumberFormat の既定の丸めは RoundingMode.HALF_EVEN で、ちょうど中間の値は「丸めた結果の末尾が偶数になる方」に寄せるので、1.25 は 1.2、1.75 は 1.8 になります。setRoundingMode(RoundingMode.HALF_UP) を指定すると一般的な四捨五入になり、1.25 は 1.3 です。1.25 や 1.75 は 2 進数でも正確に表せる値なので、中間値として丸め規則の違いがそのまま結果に現れます（1.35 のように 2 進数で正確に表せない値は、ちょうど中間ではないので規則の違いが現れないことがあります）。帳票などで四捨五入が求められるなら、丸めのモードを明示します。",
  },
  {
    id: 10827,
    topic: "localization",
    variantOf: "gold-localization-numberformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FractionDigits",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class FractionDigits {",
      "    public static void main(String[] args) {",
      "        NumberFormat de = NumberFormat.getInstance(Locale.GERMANY);",
      "        NumberFormat us = NumberFormat.getInstance(Locale.US);",
      "        us.setMinimumFractionDigits(2);",
      "        System.out.println(de.format(1234567.891) + \" \" + us.format(1234.5) + \" \" + us.format(0.12345));",
      "    }",
      "}",
    ],
    choices: [
      "1.234.567,891 1,234.50 0.123",
      "1,234,567.891 1,234.50 0.123",
      "1.234.567,891 1,234.5 0.12",
      "1.234.567,89 1,234.50 0.12",
      "1 234 567,891 1,234.50 0.12345",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1.234.567,891 1,234.50 0.123" },
    explanation:
      "NumberFormat.getInstance はロケールに応じた桁区切りと小数点の記号を使います。ドイツでは桁区切りがピリオド、小数点がカンマなので 1.234.567,891 です。汎用の数値書式は既定で小数部を最大 3 桁まで表示するので、0.12345 は 0.123 に丸められます。setMinimumFractionDigits(2) は小数部を最低 2 桁表示する設定で、1234.5 は 0 を補って 1,234.50 になります。記号を文字列に直接書かずに NumberFormat に任せることで、同じコードのままロケールごとの表記に対応できます。",
  },

  // ------------------------------------------------------------------- 日付・時刻の書式
  {
    id: 10828,
    topic: "localization",
    variantOf: "gold-localization-datetime-pattern",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TimePattern",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class TimePattern {",
      "    public static void main(String[] args) {",
      "        LocalDateTime t = LocalDateTime.of(2024, 3, 9, 15, 7, 5);",
      "        String a = DateTimeFormatter.ofPattern(\"HH:mm\", Locale.US).format(t);",
      "        String b = DateTimeFormatter.ofPattern(\"h:mm a\", Locale.US).format(t);",
      "        String c = DateTimeFormatter.ofPattern(\"yy-M-d MM\", Locale.US).format(t);",
      "        System.out.println(a + \" | \" + b + \" | \" + c);",
      "    }",
      "}",
    ],
    choices: [
      "15:07 | 3:07 PM | 24-3-9 03",
      "15:07 | 03:07 PM | 24-3-9 07",
      "15:07 | 3:07 PM | 2024-3-9 03",
      "03:07 | 3:07 PM | 24-3-9 03",
      "実行時に DateTimeParseException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "15:07 | 3:07 PM | 24-3-9 03" },
    explanation:
      "パターン文字は大文字・小文字で意味が異なります。HH は 0〜23 の時、h は 1〜12 の時（1 文字なので桁埋めなし）、a は午前・午後の表示（Locale.US では PM）です。mm は分、MM は月で、取り違えると日付の中に分が入るような誤りになります。文字の数は桁数を表し、M は 1 桁の月をそのまま、MM は 2 桁に 0 埋め、yy は西暦の下 2 桁です。午前・午後や曜日の表記は言語によって変わるので、ofPattern にもロケールを指定しておくと実行環境に左右されません。",
  },
  {
    id: 10829,
    topic: "localization",
    variantOf: "gold-localization-datetime-pattern",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "UnsupportedField",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "",
      "public class UnsupportedField {",
      "    public static void main(String[] args) {",
      "        DateTimeFormatter f = DateTimeFormatter.ofPattern(\"yyyy/MM/dd HH:mm\");",
      "        LocalDateTime dt = LocalDateTime.of(2024, 5, 1, 9, 30);",
      "        System.out.print(f.format(dt) + \" \");",
      "        LocalDate d = LocalDate.of(2024, 5, 1);",
      "        System.out.println(f.format(d));",
      "    }",
      "}",
    ],
    choices: [
      "2024/05/01 09:30 と出力された後、UnsupportedTemporalTypeException がスローされる",
      "2024/05/01 09:30 2024/05/01 00:00",
      "2024/05/01 09:30 2024/05/01",
      "10行目でコンパイルエラーになる",
      "2024/05/01 09:30 と出力された後、DateTimeParseException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedTemporalTypeException", stdout: "2024/05/01 09:30" },
    explanation:
      "DateTimeFormatter.format の引数は TemporalAccessor 型なので、LocalDate を渡してもコンパイルは通ります。しかし LocalDate は日付だけの型で「時」や「分」のフィールドを持たないため、パターンの HH を処理しようとした時点で UnsupportedTemporalTypeException がスローされます。00:00 を補ってくれることはありません。書式化できるかどうかは、パターンが要求するフィールドを対象の型が持っているかで決まるので、LocalDate には日付だけのパターン、時刻も表示したいなら atStartOfDay() などで LocalDateTime に変換してから書式化します。",
  },
  {
    id: 10830,
    topic: "localization",
    variantOf: "gold-localization-datetime-parse",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ParseDate",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "",
      "public class ParseDate {",
      "    public static void main(String[] args) {",
      "        LocalDate a = LocalDate.parse(\"2024/1/5\", DateTimeFormatter.ofPattern(\"yyyy/M/d\"));",
      "        LocalDate b = LocalDate.parse(\"2024-01-05\");",
      "        System.out.print(a.equals(b) + \" \" + a.getDayOfWeek() + \" \");",
      "        LocalDate c = LocalDate.parse(\"2024/1/5\", DateTimeFormatter.ofPattern(\"yyyy/MM/dd\"));",
      "        System.out.println(c);",
      "    }",
      "}",
    ],
    choices: [
      "true FRIDAY と出力された後、DateTimeParseException がスローされる",
      "true FRIDAY 2024-01-05",
      "false FRIDAY 2024-01-05",
      "true 金曜日 と出力された後、DateTimeParseException がスローされる",
      "7行目で DateTimeParseException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "DateTimeParseException", stdout: "true FRIDAY" },
    explanation:
      "解析（parse）でも書式化と同じパターン文字を使います。M や d は 1 桁でも 2 桁でも受け付けるので \"2024/1/5\" を解析でき、引数を 1 つだけ取る parse は ISO 形式（yyyy-MM-dd）で解析するので、a と b は同じ日付です。getDayOfWeek は DayOfWeek 列挙型を返し、toString は FRIDAY というロケールに依存しない定数名です。一方 MM や dd は解析時にちょうど 2 桁を要求するので、1 桁の \"1\" や \"5\" は解析できず DateTimeParseException がスローされます。利用者の入力を解析するときは、パターンの桁数が受け付ける形式を決めることに注意します。",
  },
  {
    id: 10831,
    topic: "localization",
    variantOf: "gold-localization-localized-style",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LocalizedTime",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class LocalizedTime {",
      "    public static void main(String[] args) {",
      "        LocalTime t = LocalTime.of(15, 5);",
      "        DateTimeFormatter f = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT);",
      "        System.out.println(f.withLocale(Locale.US).format(t) + \" | \" + f.withLocale(Locale.JAPAN).format(t));",
      "    }",
      "}",
    ],
    choices: ["3:05 PM | 15:05", "15:05 | 15:05", "3:05 PM | 午後3:05", "03:05 PM | 15:05", "3:05 PM | 3:05 PM"],
    correct: [0],
    expected: { kind: "output", stdout: "3:05 PM | 15:05" },
    explanation:
      "ofLocalizedTime は、パターンを自分で書く代わりに FormatStyle（SHORT / MEDIUM / LONG / FULL）で詳しさだけを指定し、具体的な表記はロケールに任せる書式です。同じ SHORT でも、米国では 12 時間制の 3:05 PM、日本では 24 時間制の 15:05 になります。withLocale は元の書式を変更せずにロケールだけを差し替えた新しい DateTimeFormatter を返します（DateTimeFormatter は不変）。国ごとの慣習をコードに書き込まずに済むのが、ローカライズされたスタイルを使う利点です。",
  },
  {
    id: 10832,
    topic: "localization",
    variantOf: "gold-localization-default-locale",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "DefaultChange",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class DefaultChange {",
      "    public static void main(String[] args) {",
      "        NumberFormat before = NumberFormat.getInstance();",
      "        Locale.setDefault(Locale.GERMANY);",
      "        NumberFormat after = NumberFormat.getInstance();",
      "        System.out.println(before.format(1234.5) + \" \" + after.format(1234.5) + \" \" + Locale.getDefault());",
      "    }",
      "}",
    ],
    choices: [
      "1,234.5 1.234,5 de_DE",
      "1.234,5 1.234,5 de_DE",
      "1,234.5 1,234.5 ja_JP",
      "1,234.5 1.234,5 ja_JP",
      "1.234,5 1,234.5 de_DE",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1,234.5 1.234,5 de_DE" },
    explanation:
      "ロケールを指定しない NumberFormat.getInstance() は、呼び出した時点のデフォルトロケールで書式を作ります。before は ja_JP の書式（桁区切りカンマ、小数点ピリオド）で作られ、その後に Locale.setDefault でデフォルトを変えても、作成済みの before は影響を受けません。after はドイツの書式で作られるので 1.234,5 です。Locale.setDefault は JVM 全体の既定値を変える（同じ JVM の他の処理にも影響する）ので、特定の処理だけロケールを変えたいなら、setDefault を使わずに getInstance(Locale) のようにロケールを引数で渡します。",
  },

  // ------------------------------------------------------------ .properties の書式
  {
    id: 10833,
    topic: "localization",
    variantOf: "gold-localization-properties-format",
    question: `${JA_NOTE}クラスパス上に次のプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "PropsFormat",
    code: [
      "import java.util.*;",
      "",
      "public class PropsFormat {",
      "    public static void main(String[] args) {",
      "        ResourceBundle rb = ResourceBundle.getBundle(\"Config\", Locale.ROOT);",
      "        System.out.println(\"[\" + rb.getString(\"a\") + \"][\" + rb.getString(\"b\") + \"][\"",
      "                + rb.getString(\"c\") + \"][\" + rb.getString(\"d\") + \"]\");",
      "    }",
      "}",
    ],
    resources: [
      {
        path: "Config.properties",
        content: ["# comment", "a = one", "b:two", "c three", "d=long \\", "    text", "! also comment"],
      },
    ],
    choices: [
      "[one][two][three][long text]",
      "[ one][two][three][long \\]",
      "[one][two][three][long ]",
      "[one][two] と出力された後、MissingResourceException がスローされる",
      "[one][b:two] と出力された後、MissingResourceException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[one][two][three][long text]" },
    explanation:
      "プロパティファイルでは、キーと値の区切りに = だけでなく : や空白も使え、区切りの前後の空白は無視されます。そのため a = one、b:two、c three はどれもキーと値の組として読み込まれます。行末の \\ は行の継続を表し、次の行の先頭の空白を取り除いてつなげるので、d は long text になります。# や ! で始まる行はコメントです。リソース・バンドルのプロパティファイルは java.util.Properties と同じ規則で読まれるので、値の中で = や : を文字として使いたい場合や、行末に \\ を書きたい場合はエスケープが必要です。",
  },

  // ------------------------------------------------------------ タイムゾーンを伴う書式
  {
    id: 10834,
    topic: "localization",
    variantOf: "gold-localization-datetime-unsupported",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ZoneFormat",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class ZoneFormat {",
      "    public static void main(String[] args) {",
      "        ZonedDateTime z = ZonedDateTime.of(2024, 1, 2, 3, 4, 0, 0, ZoneId.of(\"Asia/Tokyo\"));",
      "        System.out.print(DateTimeFormatter.ofPattern(\"yyyy-MM-dd HH:mm VV xxx\").format(z) + \" | \");",
      "        DateTimeFormatter full = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.FULL).withLocale(Locale.US);",
      "        System.out.println(full.format(z.toLocalDateTime()));",
      "    }",
      "}",
    ],
    choices: [
      "2024-01-02 03:04 Asia/Tokyo +09:00 | と出力された後、DateTimeException がスローされる",
      "2024-01-02 03:04 Asia/Tokyo +09:00 | Tuesday, January 2, 2024 at 3:04:00 AM",
      "2024-01-02 03:04 JST +0900 | と出力された後、DateTimeException がスローされる",
      "2024-01-02 03:04 Asia/Tokyo +09:00 | Tuesday, January 2, 2024 at 3:04:00 AM Japan Standard Time",
      "8行目で DateTimeException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "DateTimeException", stdout: "2024-01-02 03:04 Asia/Tokyo +09:00 |" },
    explanation:
      "パターン文字 VV はタイムゾーン ID（Asia/Tokyo）、xxx は UTC からの時差（+09:00）を表し、ZonedDateTime はこれらの情報を持っているので書式化できます。一方 ofLocalizedDateTime の FULL（と LONG）スタイルは、ロケールによってはタイムゾーン名を含む書式になるため、タイムゾーンを持たない LocalDateTime を渡すと「ZoneId を取り出せない」という DateTimeException がスローされます。MEDIUM や SHORT ならタイムゾーンを含まないので LocalDateTime でも書式化できます。日時を詳しく表示するなら、タイムゾーンを伴う ZonedDateTime で扱うのが確実です。",
  },
  {
    id: 10835,
    topic: "localization",
    variantOf: "gold-localization-string-format",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FormatLocale",
    code: [
      "import java.util.*;",
      "",
      "public class FormatLocale {",
      "    public static void main(String[] args) {",
      "        String a = String.format(Locale.GERMANY, \"%,.2f\", 1234.5);",
      "        String b = String.format(Locale.US, \"%08.3f|%-5s|%5s|\", 3.14159, \"ab\", \"cd\");",
      "        System.out.println(a + \" \" + b);",
      "    }",
      "}",
    ],
    choices: [
      "1.234,50 0003.142|ab   |   cd|",
      "1,234.50 0003.142|ab   |   cd|",
      "1.234,50 3.142000|ab   |   cd|",
      "1.234,50 0003.142|   ab|cd   |",
      "1.234,5 00003.14|ab   |   cd|",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1.234,50 0003.142|ab   |   cd|" },
    explanation:
      "String.format の第 1 引数に Locale を渡すと、桁区切りや小数点の記号がそのロケールの慣習になります。%,.2f の , は桁区切りを入れる指定、.2 は小数点以下 2 桁なので、ドイツでは 1.234,50 です。%08.3f は小数点以下 3 桁で四捨五入し、全体（小数点を含む）を 8 桁の幅にして不足分を 0 で埋めるので 0003.142 です。%-5s は幅 5 で左寄せ、%5s は右寄せです。ロケールを省略するとデフォルトロケール（書式用のカテゴリ）が使われ、実行環境で結果が変わるので、ファイル出力など形式を固定したい処理では Locale.ROOT などを明示します。",
  },
];
