import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: ローカライズ（id 10801-10899）。
 * Locale、リソース・バンドル、メッセージ・日付・数値のフォーマット。
 *
 * 実機検証は既定ロケール ja_JP・タイムゾーン Asia/Tokyo で行う（scripts/verify-java.mts の RUNTIME_PROPS）。
 * 既定ロケールに依存する問題では、問題文にその前提を必ず書く。
 */
const JA_NOTE = "デフォルトロケールは ja_JP とする。";

export const goldLocalizationQuestions: GoldQuestion[] = [
  // ------------------------------------------------------------------- Locale
  {
    id: 10801,
    topic: "localization",
    variantOf: "gold-localization-locale",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LocaleTest",
    code: [
      "import java.util.*;",
      "",
      "public class LocaleTest {",
      "    public static void main(String[] args) {",
      '        Locale a = new Locale("EN", "us");',
      '        Locale b = Locale.forLanguageTag("fr-CA");',
      "        Locale c = Locale.JAPANESE;",
      '        System.out.println(a + " " + b + " " + c + " " + b.getLanguage());',
      "    }",
      "}",
    ],
    choices: ["en_US fr_CA ja fr", "EN_us fr-CA ja fr", "en_US fr_CA ja_JP fr", "en_US fr-CA ja fr_CA", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "en_US fr_CA ja fr" },
    explanation:
      "Locale のコンストラクタは言語コードを小文字に、国コードを大文字に正規化するため、new Locale(\"EN\", \"us\") は en_US になります。forLanguageTag は IETF の言語タグ（ハイフン区切り）を解釈するもので、\"fr-CA\" は言語 fr・国 CA のロケールになります。Locale の toString() はタグの形式ではなく言語_国のアンダースコア区切りで表示されます。Locale.JAPANESE は言語だけのロケール ja で、国まで含む ja_JP は Locale.JAPAN です。言語だけを指定したロケールは「国に依存しない日本語」を表し、リソース・バンドルの検索などで国付きのロケールの親として使われます。",
  },
  {
    id: 10802,
    topic: "localization",
    variantOf: "gold-localization-locale",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LanguageTag",
    code: [
      "import java.util.*;",
      "",
      "public class LanguageTag {",
      "    public static void main(String[] args) {",
      '        Locale a = Locale.forLanguageTag("ja-JP");',
      '        Locale b = Locale.forLanguageTag("ja_JP");',
      '        System.out.println("[" + a + "] [" + b + "] " + a.equals(Locale.JAPAN));',
      "    }",
      "}",
    ],
    choices: [
      "[ja_JP] [] true",
      "[ja_JP] [ja_JP] true",
      "[ja-JP] [ja_JP] false",
      "[ja_JP] [ja] true",
      "実行時に IllformedLocaleException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[ja_JP] [] true" },
    explanation:
      "forLanguageTag が受け付けるのは BCP 47 形式の言語タグで、区切り文字はハイフンです。\"ja-JP\" は Locale.JAPAN と等しいロケールになりますが、アンダースコアを使った \"ja_JP\" は正しい言語タグではないため、解釈できた部分が何も無く、空のロケール（Locale.ROOT）が返されて空文字列として表示されます。forLanguageTag は不正な入力でも例外をスローしない点に注意が必要です（厳密に検査したい場合は Locale.Builder を使います）。toString() の形式（ja_JP）と言語タグの形式（ja-JP、toLanguageTag() で得られる）を取り違えないことが大切です。",
  },
  {
    id: 10803,
    topic: "localization",
    variantOf: "gold-localization-default-locale",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "CategoryTest",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class CategoryTest {",
      "    public static void main(String[] args) {",
      "        Locale.setDefault(Locale.Category.FORMAT, Locale.GERMANY);",
      "        System.out.println(Locale.getDefault() + \" \"",
      "                + Locale.getDefault(Locale.Category.FORMAT) + \" \"",
      "                + NumberFormat.getInstance().format(1234.5));",
      "    }",
      "}",
    ],
    choices: ["ja_JP de_DE 1.234,5", "de_DE de_DE 1.234,5", "ja_JP de_DE 1,234.5", "ja_JP ja_JP 1,234.5", "de_DE ja_JP 1,234.5"],
    correct: [0],
    expected: { kind: "output", stdout: "ja_JP de_DE 1.234,5" },
    explanation:
      "既定のロケールは、画面表示の言語などに使う DISPLAY と、数値・日付の書式に使う FORMAT の 2 つのカテゴリに分けて設定できます。setDefault(Locale.Category.FORMAT, ...) は FORMAT カテゴリだけを変更するので、カテゴリを指定しない getDefault() は元の ja_JP のままです。NumberFormat.getInstance() は FORMAT カテゴリの既定ロケールを使うため、ドイツ式の 1.234,5（桁区切りがピリオド、小数点がカンマ）になります。「メッセージは日本語で表示しつつ、数値はドイツの書式で出す」といった使い分けのための仕組みです。",
  },

  // ------------------------------------------------------------ リソース・バンドル
  {
    id: 10804,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BundleTest",
    code: [
      "import java.util.*;",
      "",
      "public class BundleTest {",
      "    public static void main(String[] args) {",
      '        ResourceBundle rb = ResourceBundle.getBundle("Messages", Locale.FRANCE);',
      '        System.out.println(rb.getString("greet") + " " + rb.getString("bye"));',
      "    }",
      "}",
    ],
    resources: [
      { path: "Messages.properties", content: ["greet=Hello", "bye=Bye"] },
      { path: "Messages_ja.properties", content: ["greet=こんにちは"] },
    ],
    choices: [
      "こんにちは Bye",
      "Hello Bye",
      "こんにちは と出力された後、MissingResourceException がスローされる",
      "実行時に MissingResourceException がスローされる",
      "こんにちは null",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "こんにちは Bye" },
    explanation:
      "getBundle は、指定したロケールの候補（Messages_fr_FR → Messages_fr）が見つからないと、基底のバンドルに進む前にデフォルトロケールの候補（Messages_ja_JP → Messages_ja）を探します。そのため Locale.FRANCE を指定しても Messages_ja が選ばれ、greet は こんにちは になります。見つかったバンドルは Messages_ja → Messages という親子関係でつながっており、Messages_ja に無いキー bye は親の基底バンドルから取得されます。指定ロケールの訳が無いときに基底（多くは英語）ではなく実行環境の言語が使われるのは、利用者が読める可能性の高い言語を優先するための設計です。",
  },
  {
    id: 10805,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次の 3 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BundleFallback",
    code: [
      "import java.util.*;",
      "",
      "public class BundleFallback {",
      "    public static void main(String[] args) {",
      '        ResourceBundle rb = ResourceBundle.getBundle("Messages", Locale.CANADA_FRENCH);',
      '        System.out.println(rb.getString("greet") + " " + rb.getString("bye"));',
      "    }",
      "}",
    ],
    resources: [
      { path: "Messages.properties", content: ["greet=Hello", "bye=Bye"] },
      { path: "Messages_ja.properties", content: ["greet=こんにちは", "bye=さようなら"] },
      { path: "Messages_fr.properties", content: ["greet=Bonjour"] },
    ],
    choices: [
      "Bonjour Bye",
      "Bonjour さようなら",
      "こんにちは さようなら",
      "Hello Bye",
      "Bonjour と出力された後、MissingResourceException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Bonjour Bye" },
    explanation:
      "Locale.CANADA_FRENCH は fr_CA なので、Messages_fr_CA → Messages_fr の順に探し、Messages_fr が見つかります。指定ロケールの候補が見つかった場合、デフォルトロケール（ja）の候補は検索されません。キーが見つからないときにたどる親は、ロケールの候補を一般化していった Messages_fr → Messages という連鎖であり、Messages_ja は含まれないため、bye は基底バンドルの Bye になります。デフォルトロケールが使われるのは「指定ロケールのバンドルが 1 つも無かったとき」の代替に限られる、という点が前問との違いです。",
  },
  {
    id: 10806,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次のプロパティファイルだけがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BundleMissing",
    code: [
      "import java.util.*;",
      "",
      "public class BundleMissing {",
      "    public static void main(String[] args) {",
      '        ResourceBundle rb = ResourceBundle.getBundle("Labels", Locale.GERMANY);',
      '        System.out.println(rb.getString("title"));',
      "    }",
      "}",
    ],
    resources: [{ path: "Labels_en.properties", content: ["title=Menu"] }],
    choices: [
      "実行時に MissingResourceException がスローされる",
      "Menu",
      "null",
      "title",
      "5行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "MissingResourceException" },
    explanation:
      "getBundle の検索順は、指定ロケールの Labels_de_DE → Labels_de、デフォルトロケールの Labels_ja_JP → Labels_ja、最後に基底の Labels です。Labels_en はこの候補のどれにも当たらないため、英語のバンドルがあっても使われず、getBundle の時点で MissingResourceException がスローされます。「何か 1 つでもあれば使う」わけではなく、候補の名前に一致するものだけが検索されるのです。どのロケールでも必ず見つかるよう、基底バンドル（Labels.properties）を用意しておくのが基本です。",
  },
  {
    id: 10807,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BundleKey",
    code: [
      "import java.util.*;",
      "",
      "public class BundleKey {",
      "    public static void main(String[] args) {",
      '        ResourceBundle rb = ResourceBundle.getBundle("App", Locale.JAPAN);',
      '        System.out.print(rb.getString("name") + " ");',
      '        System.out.println(rb.getString("version"));',
      "    }",
      "}",
    ],
    resources: [
      { path: "App.properties", content: ["name=Shop"] },
      { path: "App_ja_JP.properties", content: ["name=ショップ"] },
    ],
    choices: [
      "ショップ と出力された後、MissingResourceException がスローされる",
      "ショップ null",
      "ショップ version",
      "Shop と出力された後、MissingResourceException がスローされる",
      "ショップ Shop",
    ],
    correct: [0],
    expected: { kind: "exception", type: "MissingResourceException", stdout: "ショップ" },
    explanation:
      "Locale.JAPAN（ja_JP）を指定したので App_ja_JP が選ばれ、name は ショップ になります。version は App_ja_JP にも親の App にも無いため、getString は null を返すのではなく MissingResourceException をスローします。キーの誤りや訳の追加漏れを null として画面に出してしまうより、例外で早期に気付かせる方針です。キーが無い可能性を扱う場合は、rb.containsKey(\"version\") で事前に確かめます。",
  },
  {
    id: 10808,
    topic: "localization",
    variantOf: "gold-localization-list-bundle",
    question: `${JA_NOTE}クラスパス上に次のプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ClassBundle",
    code: [
      "import java.util.*;",
      "",
      "class Greeting_ja extends ListResourceBundle {",
      "    public Greeting_ja() {}",
      "",
      "    protected Object[][] getContents() {",
      "        return new Object[][] {",
      '            {"msg", "from class"},',
      '            {"max", 10},',
      "        };",
      "    }",
      "}",
      "",
      "public class ClassBundle {",
      "    public static void main(String[] args) {",
      '        ResourceBundle rb = ResourceBundle.getBundle("Greeting", Locale.JAPANESE);',
      '        Integer max = (Integer) rb.getObject("max");',
      '        System.out.println(rb.getString("msg") + " " + (max + 1));',
      "    }",
      "}",
    ],
    resources: [{ path: "Greeting_ja.properties", content: ["msg=from properties"] }],
    choices: [
      "from class 11",
      "from properties 11",
      "from class 101",
      "実行時に ClassCastException がスローされる",
      "実行時に MissingResourceException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "from class 11" },
    explanation:
      "リソース・バンドルは、プロパティファイルだけでなく ListResourceBundle を継承した Java クラスとしても作れます。同じ名前（Greeting_ja）のクラスとプロパティファイルの両方がある場合は、クラスの方が優先して使われるため、msg は from class になります。クラスで作るバンドルは値に文字列以外のオブジェクトも持てるので、getObject で取り出した Integer の 10 に 1 を足して 11 です（getString は値を String にキャストするため、\"max\" に使うと ClassCastException になります）。翻訳の文字列はプロパティファイル、計算が必要な値やオブジェクトはクラス、と使い分けられます。",
  },

  // ------------------------------------------------------------- MessageFormat
  {
    id: 10809,
    topic: "localization",
    variantOf: "gold-localization-messageformat",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "MessageTest",
    code: [
      "import java.text.*;",
      "",
      "public class MessageTest {",
      "    public static void main(String[] args) {",
      '        String s = MessageFormat.format("{1}の価格は{0}円（税抜 {0,number,#.0}）", 1234.56, "本");',
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: [
      "本の価格は1,234.56円（税抜 1234.6）",
      "本の価格は1234.56円（税抜 1234.6）",
      "1234.56の価格は本円（税抜 1234.6）",
      "本の価格は1,234.56円（税抜 1,234.56）",
      "実行時に IllegalArgumentException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "本の価格は1,234.56円（税抜 1234.6）" },
    explanation:
      "MessageFormat の {n} は、引数の n 番目（0 始まり）の値に置き換えられるので、パターン内の出現順と引数の順序は一致していなくてかまいません。書式を指定しない {0} に数値を渡すと、ロケールの既定の数値書式が使われ、ja_JP では桁区切り付きの 1,234.56 になります。{0,number,#.0} は DecimalFormat のパターン #.0 で書式化するので、小数第 1 位に丸められた 1234.6 です。語順が言語ごとに異なっても、翻訳者がパターン内の {n} の位置を入れ替えるだけで対応できるようにするための仕組みです。",
  },
  {
    id: 10810,
    topic: "localization",
    variantOf: "gold-localization-messageformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "QuoteTest",
    code: [
      "import java.text.*;",
      "",
      "public class QuoteTest {",
      "    public static void main(String[] args) {",
      '        System.out.println(MessageFormat.format("It\'s {0}", "ok") + " / "',
      '                + MessageFormat.format("It\'\'s {0}", "ok") + " / "',
      '                + MessageFormat.format("\'{0}\' is {0}", "x"));',
      "    }",
      "}",
    ],
    choices: [
      "Its {0} / It's ok / {0} is x",
      "It's ok / It''s ok / 'x' is x",
      "It's ok / It's ok / {0} is x",
      "Its ok / It's ok / x is x",
      "実行時に IllegalArgumentException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Its {0} / It's ok / {0} is x" },
    explanation:
      "MessageFormat のパターンでは、単一引用符 ' は「ここから次の ' までを文字どおりに扱う」という引用の記号です。\"It's {0}\" では ' 以降がすべて引用されたとみなされるため、' は消え、{0} も置き換えられずにそのまま Its {0} となります。引用符そのものを出力するには '' と 2 つ重ね、'{0}' のように囲むと波括弧を文字として出力できます。英語の翻訳文には It's や don't のようにアポストロフィが頻出するため、プロパティファイルに訳を書くときに '' と書き忘れる不具合がよく起こります。",
  },

  // ------------------------------------------------------------ NumberFormat
  {
    id: 10811,
    topic: "localization",
    variantOf: "gold-localization-numberformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CurrencyTest",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class CurrencyTest {",
      "    public static void main(String[] args) {",
      "        NumberFormat jp = NumberFormat.getCurrencyInstance(Locale.JAPAN);",
      "        NumberFormat us = NumberFormat.getCurrencyInstance(Locale.US);",
      '        System.out.println(jp.format(1234.5) + " " + jp.format(1235.5) + " " + us.format(1234.5));',
      "    }",
      "}",
    ],
    choices: [
      "￥1,234 ￥1,236 $1,234.50",
      "￥1,235 ￥1,236 $1,234.50",
      "￥1,234.5 ￥1,235.5 $1,234.5",
      "￥1,235 ￥1,235 $1,234.50",
      "￥1,234 ￥1,235 $1,234.5",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "￥1,234 ￥1,236 $1,234.50" },
    explanation:
      "通貨の書式では、その通貨の補助単位に合わせて小数の桁数が決まり、円は小数なし、米ドルはセント単位の小数 2 桁で表示されます。NumberFormat の丸めは既定で RoundingMode.HALF_EVEN（偶数への丸め、銀行家の丸め）なので、ちょうど半分の 1234.5 は偶数側の 1234 に、1235.5 は偶数側の 1236 になります。四捨五入で毎回切り上げると、大量の値を合計したときに誤差が一方向に偏るため、統計的に偏りの少ない方式が既定になっています。四捨五入が必要な場合は setRoundingMode(RoundingMode.HALF_UP) を指定します。",
  },
  {
    id: 10812,
    topic: "localization",
    variantOf: "gold-localization-numberformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "NumberStyles",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class NumberStyles {",
      "    public static void main(String[] args) {",
      "        System.out.println(NumberFormat.getPercentInstance(Locale.JAPAN).format(0.256) + \" \"",
      "                + NumberFormat.getInstance(Locale.GERMANY).format(1234.567) + \" \"",
      "                + NumberFormat.getIntegerInstance(Locale.US).format(2.5));",
      "    }",
      "}",
    ],
    choices: ["26% 1.234,567 2", "25.6% 1.234,567 3", "26% 1,234.567 2", "26% 1.234,567 3", "0.256% 1.234,567 2"],
    correct: [0],
    expected: { kind: "output", stdout: "26% 1.234,567 2" },
    explanation:
      "getPercentInstance は値を 100 倍して % を付け、既定では小数を表示しないので 0.256 は 25.6 を丸めた 26% になります。getInstance(Locale.GERMANY) はドイツの慣習に従い、桁区切りにピリオド、小数点にカンマを使うので 1.234,567 です。getIntegerInstance は整数として書式化し、丸めは HALF_EVEN なので 2.5 は偶数側の 2 になります。数値の区切り記号は国によって正反対になることがあるため、数値を文字列にするときは必ずロケールを意識した NumberFormat を使うことが重要です。",
  },
  {
    id: 10813,
    topic: "localization",
    variantOf: "gold-localization-numberformat-parse",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ParseTest",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class ParseTest {",
      "    public static void main(String[] args) throws ParseException {",
      "        NumberFormat nf = NumberFormat.getInstance(Locale.US);",
      '        Number a = nf.parse("1,234.5kg");',
      '        Number b = nf.parse("42");',
      '        System.out.print(a + " " + b.getClass().getSimpleName() + " ");',
      '        nf.parse("kg12");',
      "    }",
      "}",
    ],
    choices: [
      "1234.5 Long と出力された後、ParseException がスローされる",
      "1234.5 Integer と出力された後、ParseException がスローされる",
      "実行時に ParseException がスローされる",
      "1,234.5 Long と出力された後、ParseException がスローされる",
      "1234.5 Long 12",
    ],
    correct: [0],
    expected: { kind: "exception", type: "ParseException", stdout: "1234.5 Long" },
    explanation:
      "NumberFormat.parse は文字列の先頭から数値として解釈できる部分だけを読み取り、その後ろに続く文字（kg）は無視します。そのため \"1,234.5kg\" は桁区切りを取り除いた 1234.5 になります。戻り値の型は Number で、整数として表せる値なら Long、そうでなければ Double が返るため、\"42\" は Long です。一方、先頭から数値として読めない \"kg12\" は ParseException になります。後ろの余計な文字を許してしまうので、入力全体が数値であることを確かめたい場合は ParsePosition を使って読み取った位置を確認します。",
  },
  {
    id: 10814,
    topic: "localization",
    variantOf: "gold-localization-compact",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "CompactTest",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class CompactTest {",
      "    public static void main(String[] args) {",
      "        NumberFormat shortUs = NumberFormat.getCompactNumberInstance(Locale.US, NumberFormat.Style.SHORT);",
      "        NumberFormat longUs = NumberFormat.getCompactNumberInstance(Locale.US, NumberFormat.Style.LONG);",
      "        NumberFormat shortJp = NumberFormat.getCompactNumberInstance(Locale.JAPAN, NumberFormat.Style.SHORT);",
      "        System.out.println(shortUs.format(1_250_000) + \" / \" + longUs.format(1_250_000) + \" / \"",
      "                + shortJp.format(12_345_678));",
      "    }",
      "}",
    ],
    choices: [
      "1M / 1 million / 1235万",
      "1.25M / 1.25 million / 1234.5678万",
      "1M / 1 million / 12M",
      "1.3M / 1.3 million / 1235万",
      "1,250,000 / 1,250,000 / 12,345,678",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1M / 1 million / 1235万" },
    explanation:
      "Java 12 で追加された CompactNumberFormat は、大きな数を「1M」「1 million」「1235万」のような短い形式で表します。SHORT は記号による短縮、LONG は単語による表記です。どの単位で区切るかはロケールごとに決まっており、英語は千・百万（K、M）、日本語は万・億の単位を使います。既定では小数部を表示せず HALF_EVEN で丸めるので、1.25M は 1M、1234.5678万 は 1235万 になります。SNS のフォロワー数のように概数で伝えたい値を、各国の慣習に沿って表示するための書式です。",
  },
  {
    id: 10815,
    topic: "localization",
    variantOf: "gold-localization-decimalformat",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "PatternTest",
    code: [
      "import java.text.*;",
      "",
      "public class PatternTest {",
      "    public static void main(String[] args) {",
      '        System.out.println(new DecimalFormat("#,##0.00").format(1234.5) + " "',
      '                + new DecimalFormat("0000.#").format(12.34) + " "',
      '                + new DecimalFormat("#.##").format(0.5));',
      "    }",
      "}",
    ],
    choices: ["1,234.50 0012.3 0.5", "1,234.5 12.3 .5", "1,234.50 0012.34 0.50", "1234.50 0012.3 .5", "1,234.50 12.3 0.5"],
    correct: [0],
    expected: { kind: "output", stdout: "1,234.50 0012.3 0.5" },
    explanation:
      "DecimalFormat のパターンで、0 は「その桁が無ければ 0 で埋める」、# は「その桁が無ければ何も出さない」を意味し、, は桁区切りの位置を表します。#,##0.00 は小数 2 桁を必ず表示するので 1,234.50、0000.# は整数部を 4 桁に 0 埋めし小数は最大 1 桁なので 0012.3 です。#.## で 0.5 を書式化すると、整数部の # は本来省略可能ですが、整数部が空になるときは 0 が 1 桁補われて 0.5 になります。帳票のように桁をそろえたい位置には 0、不要なら省略したい位置には # と使い分けます。",
  },

  // --------------------------------------------------------- 日付・時刻の書式
  {
    id: 10816,
    topic: "localization",
    variantOf: "gold-localization-datetime-pattern",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DatePattern",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class DatePattern {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2024, 1, 1);",
      '        String jp = DateTimeFormatter.ofPattern("yyyy/MM/dd (E)", Locale.JAPAN).format(date);',
      '        String us = DateTimeFormatter.ofPattern("MMM d, yyyy EEEE", Locale.US).format(date);',
      '        System.out.println(jp + " | " + us);',
      "    }",
      "}",
    ],
    choices: [
      "2024/01/01 (月) | Jan 1, 2024 Monday",
      "2024/01/01 (Mon) | Jan 1, 2024 Monday",
      "2024/1/1 (月) | January 1, 2024 Mon",
      "2024/01/01 (月曜日) | Jan 01, 2024 Monday",
      "実行時に UnsupportedTemporalTypeException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "2024/01/01 (月) | Jan 1, 2024 Monday" },
    explanation:
      "パターン文字は、繰り返す数で表示形式が変わります。MM は 2 桁の月（01）、d は 1 桁で表せればそのまま（1）、MMM は月の短縮名（Jan）です。E は曜日の短縮形、EEEE は完全な名前で、日本語では 月 と 月曜日、英語では Mon と Monday になります。月名や曜日名のような文字の部分はロケールによって変わるため、ofPattern にロケールを渡すことで同じパターンを各国の言語で出力できます。ロケールを省略すると既定の FORMAT ロケールが使われるので、実行環境によって出力が変わる点に注意が必要です。",
  },
  {
    id: 10817,
    topic: "localization",
    variantOf: "gold-localization-datetime-pattern",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MinutePattern",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "",
      "public class MinutePattern {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2024, 3, 9);",
      '        System.out.print(DateTimeFormatter.ofPattern("yyyy-MM-dd").format(date) + " ");',
      '        System.out.println(DateTimeFormatter.ofPattern("yyyy-mm-dd").format(date));',
      "    }",
      "}",
    ],
    choices: [
      "2024-03-09 と出力された後、UnsupportedTemporalTypeException がスローされる",
      "2024-03-09 2024-03-09",
      "2024-03-09 2024-00-09",
      "実行時に IllegalArgumentException がスローされる",
      "8行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedTemporalTypeException", stdout: "2024-03-09" },
    explanation:
      "パターン文字は大文字と小文字で意味が異なり、MM は月、mm は分（minute of hour）です。LocalDate は日付だけを持ち時刻の情報が無いため、分を要求する yyyy-mm-dd で書式化しようとすると UnsupportedTemporalTypeException がスローされます。パターンの誤りがコンパイル時ではなく、実際に書式化したときに初めて分かる点に注意が必要です。同様に HH（0〜23 時）と hh（1〜12 時）、yyyy（暦年）と YYYY（週基準年）も取り違えやすい組み合わせです。",
  },
  {
    id: 10818,
    topic: "localization",
    variantOf: "gold-localization-localized-style",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LocalizedStyle",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class LocalizedStyle {",
      "    public static void main(String[] args) {",
      "        LocalDate date = LocalDate.of(2024, 1, 1);",
      "        DateTimeFormatter full = DateTimeFormatter.ofLocalizedDate(FormatStyle.FULL);",
      "        DateTimeFormatter shortStyle = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT);",
      '        System.out.println(full.withLocale(Locale.JAPAN).format(date) + " | "',
      '                + shortStyle.withLocale(Locale.US).format(date));',
      "    }",
      "}",
    ],
    choices: [
      "2024年1月1日月曜日 | 1/1/24",
      "2024年1月1日 | 1/1/2024",
      "2024/01/01 | 01/01/2024",
      "2024年1月1日月曜日 | 2024-01-01",
      "実行時に UnsupportedTemporalTypeException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "2024年1月1日月曜日 | 1/1/24" },
    explanation:
      "ofLocalizedDate は、パターンを自分で書く代わりに FULL / LONG / MEDIUM / SHORT の 4 段階のスタイルを指定し、具体的な形式はロケールに任せる書式です。日本の FULL は 2024年1月1日月曜日、米国の SHORT は月/日/年の順で年を 2 桁にした 1/1/24 になります。日付の並び順（年月日・月日年・日月年）や区切り文字は国によって異なるため、固定のパターンを書くより、スタイルを指定してロケールごとの慣習に従わせる方が国際化に適しています。withLocale は元の書式を変えずに、ロケールだけを差し替えた新しい書式を返します。",
  },
  {
    id: 10819,
    topic: "localization",
    variantOf: "gold-localization-localized-style",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LocalizedTime",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class LocalizedTime {",
      "    public static void main(String[] args) {",
      "        LocalTime time = LocalTime.of(15, 5);",
      '        System.out.print(DateTimeFormatter.ofPattern("a h:mm", Locale.JAPAN).format(time) + " | ");',
      "        DateTimeFormatter f = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM);",
      "        System.out.println(f.format(time));",
      "    }",
      "}",
    ],
    choices: [
      "午後 3:05 | と出力された後、UnsupportedTemporalTypeException がスローされる",
      "午後 3:05 | 15:05:00",
      "PM 3:05 | と出力された後、UnsupportedTemporalTypeException がスローされる",
      "午後 15:05 | 15:05:00",
      "8行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedTemporalTypeException", stdout: "午後 3:05 |" },
    explanation:
      "パターン文字 a は午前・午後の表示で、日本語のロケールでは 午前 / 午後 になり、h は 1〜12 の時なので 15 時は 3 になります。ofLocalizedDateTime は日付と時刻の両方を書式化するスタイルなので、時刻だけを持つ LocalTime には年月日の情報が無く、UnsupportedTemporalTypeException がスローされます。書式が要求する項目を、値の型が持っているかどうかが実行時に照合されるのです。時刻だけなら ofLocalizedTime、日付だけなら ofLocalizedDate と、値の型に合ったメソッドを選びます。",
  },
];
