import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: ローカライズの追加問題（id 10820-10899）。
 * Locale.Builder と表示名、リソース・バンドルの親子関係、MessageFormat の引用符、数値・日付の書式と解析。
 *
 * localization.ts と同じく、実機検証は既定ロケール ja_JP・タイムゾーン Asia/Tokyo で行う。
 */
const JA_NOTE = "デフォルトロケールは ja_JP とする。";

export const goldLocalizationQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------------- Locale
  {
    id: 10820,
    topic: "localization",
    variantOf: "gold-localization-locale-builder",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "BuilderTest",
    code: [
      "import java.util.*;",
      "",
      "public class BuilderTest {",
      "    public static void main(String[] args) {",
      "        Locale a = new Locale.Builder().setLanguage(\"EN\").setRegion(\"gb\").build();",
      "        System.out.print(a + \" \" + a.toLanguageTag() + \" \");",
      "        Locale b = new Locale.Builder().setLanguage(\"ja\").setRegion(\"Japan\").build();",
      "        System.out.println(b);",
      "    }",
      "}",
    ],
    choices: [
      "en_GB en-GB と出力された後、IllformedLocaleException がスローされる",
      "en_GB en-GB ja_JAPAN",
      "EN_gb EN-gb と出力された後、IllformedLocaleException がスローされる",
      "en_GB en_GB ja_JAPAN",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllformedLocaleException", stdout: "en_GB en-GB" },
    explanation:
      "Locale.Builder は言語・地域などを 1 つずつ設定して Locale を組み立てるクラスで、大文字・小文字を正規化し（言語は小文字、地域は大文字）、値の形式を検証します。toString は en_GB とアンダースコア区切り、toLanguageTag は BCP 47 形式の en-GB とハイフン区切りになる点も区別が必要です。地域コードは英字 2 文字か数字 3 文字でなければならず、\"Japan\" は不正なので build の前の setRegion で IllformedLocaleException がスローされます。new Locale(...) は値を検証せずに受け入れるので、外部からの値でロケールを作るときは Builder か forLanguageTag を使うと誤りに早く気付けます。",
  },
  {
    id: 10821,
    topic: "localization",
    variantOf: "gold-localization-locale-builder",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "DisplayName",
    code: [
      "import java.util.*;",
      "",
      "public class DisplayName {",
      "    public static void main(String[] args) {",
      "        Locale fr = Locale.FRANCE;",
      "        System.out.println(fr.getLanguage() + \" \" + fr.getCountry() + \" \"",
      "                + fr.getDisplayLanguage(Locale.US) + \" \"",
      "                + fr.getDisplayCountry(Locale.JAPAN) + \" \"",
      "                + fr.getDisplayLanguage(fr));",
      "    }",
      "}",
    ],
    choices: [
      "fr FR French フランス français",
      "fr FR French France French",
      "FR fr French フランス français",
      "fr FR French France français",
      "fr FR フランス語 フランス français",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "fr FR French フランス français" },
    explanation:
      "getLanguage と getCountry は ISO のコード（小文字の言語 fr、大文字の地域 FR）をそのまま返します。getDisplayLanguage / getDisplayCountry は人間向けの名前を返し、引数で「どの言語で表示するか」を指定します。英語なら French、日本語ならフランス、フランス語自身なら français です。引数を省略するとデフォルトの表示ロケールが使われるので、実行環境によって結果が変わります。ロケールの選択肢を画面に並べるときは、利用者の言語で表示するか、そのロケール自身の言語で表示するかを意識して引数を選びます。",
  },

  // ------------------------------------------------------------------- リソース・バンドルの検索
  {
    id: 10822,
    topic: "localization",
    variantOf: "gold-localization-bundle-lookup",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "DefaultFallback",
    code: [
      "import java.util.*;",
      "",
      "public class DefaultFallback {",
      "    public static void main(String[] args) {",
      "        ResourceBundle de = ResourceBundle.getBundle(\"Menu\", Locale.GERMANY);",
      "        ResourceBundle root = ResourceBundle.getBundle(\"Menu\", Locale.ROOT);",
      "        System.out.println(de.getString(\"title\") + \" \" + root.getString(\"title\") + \" \"",
      "                + de.getLocale() + \"|\" + root.getLocale() + \"|\");",
      "    }",
      "}",
    ],
    resources: [
      { path: "Menu.properties", content: ["title=Menu"] },
      { path: "Menu_ja.properties", content: ["title=メニュー"] },
    ],
    choices: [
      "メニュー Menu ja||",
      "Menu Menu ||",
      "メニュー メニュー ja|ja|",
      "Menu メニュー |ja|",
      "実行時に MissingResourceException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "メニュー Menu ja||" },
    explanation:
      "Locale.GERMANY を指定すると Menu_de_DE → Menu_de の順に探しますが、どちらも無いので、基底の Menu に進む前にデフォルトロケール（ja_JP）の候補 Menu_ja_JP → Menu_ja を探し、Menu_ja が見つかります。そのため「ドイツ語が無ければ英語（基底）」ではなく日本語が選ばれる点に注意します。Locale.ROOT は「特定の言語を持たない」ロケールで、候補は基底の Menu だけになり、デフォルトロケールへの切り替えも行われません。getLocale() は実際に選ばれたバンドルのロケールで、基底のバンドルでは空のロケールです。",
  },
  {
    id: 10823,
    topic: "localization",
    variantOf: "gold-localization-bundle-parent",
    question: `${JA_NOTE}クラスパス上に次の 3 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "ParentChain",
    code: [
      "import java.util.*;",
      "",
      "public class ParentChain {",
      "    public static void main(String[] args) {",
      "        ResourceBundle rb = ResourceBundle.getBundle(\"Shop\", Locale.CANADA_FRENCH);",
      "        System.out.println(rb.getString(\"cart\") + \" \" + rb.getString(\"pay\") + \" \"",
      "                + rb.getString(\"help\"));",
      "    }",
      "}",
    ],
    resources: [
      { path: "Shop.properties", content: ["cart=Cart", "pay=Pay", "help=Help"] },
      { path: "Shop_fr.properties", content: ["cart=Panier", "pay=Payer"] },
      { path: "Shop_fr_CA.properties", content: ["cart=Chariot"] },
    ],
    choices: [
      "Chariot Payer Help",
      "Chariot Pay Help",
      "Panier Payer Help",
      "Chariot と出力された後、MissingResourceException がスローされる",
      "Cart Pay Help",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Chariot Payer Help" },
    explanation:
      "getBundle は最も具体的に一致する Shop_fr_CA を返しますが、そのバンドルは Shop_fr を親に、Shop_fr は基底の Shop を親に持つ親子の連鎖になっています。getString はまず自身でキーを探し、無ければ親、さらにその親へと順にたどります。cart は Shop_fr_CA、pay は Shop_fr、help は Shop で見つかります。この仕組みにより、地域ごとの差分だけを具体的なファイルに書き、共通の訳は言語のファイル、既定の文言は基底のファイルにまとめる、という管理ができます。",
  },
  {
    id: 10824,
    topic: "localization",
    variantOf: "gold-localization-bundle-parent",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがある。次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "BundleKeys",
    code: [
      "import java.util.*;",
      "",
      "public class BundleKeys {",
      "    public static void main(String[] args) {",
      "        ResourceBundle rb = ResourceBundle.getBundle(\"Labels\", Locale.JAPAN);",
      "        Set<String> keys = new TreeSet<>(rb.keySet());",
      "        System.out.println(keys + \" \" + rb.containsKey(\"ok\") + \" \" + rb.getString(\"ok\"));",
      "    }",
      "}",
    ],
    resources: [
      { path: "Labels.properties", content: ["ok=OK", "cancel=Cancel"] },
      { path: "Labels_ja.properties", content: ["cancel=取消", "save=保存"] },
    ],
    choices: [
      "[cancel, ok, save] true OK",
      "[cancel, save] false OK",
      "[cancel, save] true OK",
      "[cancel, ok, save] true null",
      "[cancel, ok, cancel, save] true OK",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[cancel, ok, save] true OK" },
    explanation:
      "ResourceBundle.keySet() と containsKey は、そのバンドル自身だけでなく親のバンドルのキーも含めて扱います。Labels_ja には ok がありませんが、親の Labels にあるので keySet に含まれ、containsKey も true、getString(\"ok\") も親から OK を取得します。cancel は両方にありますが、Set なので 1 つにまとまり、値は子の Labels_ja（取消）が優先されます。画面の全ラベルを一覧にするときなども、子に無いキーが親から補われる前提で扱えます。",
  },

  // ------------------------------------------------------------------- MessageFormat
  {
    id: 10825,
    topic: "localization",
    variantOf: "gold-localization-messageformat",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "QuoteTest",
    code: [
      "import java.text.*;",
      "",
      "public class QuoteTest {",
      "    public static void main(String[] args) {",
      "        String a = MessageFormat.format(\"It's {0}\", \"ok\");",
      "        String b = MessageFormat.format(\"It''s {0}\", \"ok\");",
      "        String c = MessageFormat.format(\"'{0}' = {0}\", \"x\");",
      "        System.out.println(a + \" | \" + b + \" | \" + c);",
      "    }",
      "}",
    ],
    choices: [
      "Its {0} | It's ok | {0} = x",
      "It's ok | It's ok | x = x",
      "It's ok | It''s ok | {0} = x",
      "Its ok | It's ok | '{0}' = x",
      "実行時に IllegalArgumentException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "Its {0} | It's ok | {0} = x" },
    explanation:
      "MessageFormat のパターンでは、単一引用符 ' が「引用の開始・終了」を表す特別な文字で、引用された部分は {0} も含めてそのままの文字として扱われます。a では It の後の ' から文字列の終わりまでが引用とみなされ、' は消え、{0} も置換されずに残ります。引用符そのものを出力するには '' と 2 つ重ねる必要があり、b は It's ok になります。c のように '{0}' と書くと中括弧を文字として出力できます。英語の文言には It's のような引用符が頻繁に現れるので、リソース・バンドルに MessageFormat 用の文言を書くときの典型的な落とし穴です。",
  },

  // ------------------------------------------------------------------- 数値の書式
  {
    id: 10826,
    topic: "localization",
    variantOf: "gold-localization-numberformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PercentTest",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class PercentTest {",
      "    public static void main(String[] args) {",
      "        NumberFormat pct = NumberFormat.getPercentInstance(Locale.US);",
      "        NumberFormat integer = NumberFormat.getIntegerInstance(Locale.US);",
      "        System.out.println(pct.format(0.256) + \" \" + integer.format(2.5) + \" \"",
      "                + integer.format(3.5) + \" \" + integer.format(12345.6));",
      "    }",
      "}",
    ],
    choices: [
      "26% 2 4 12,346",
      "25.6% 3 4 12,346",
      "26% 3 4 12,346",
      "0.26% 2 4 12346",
      "26% 2 3 12,345",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "26% 2 4 12,346" },
    explanation:
      "getPercentInstance は値を 100 倍して % を付け、既定では小数部を表示しないので 0.256 は 26% になります。getIntegerInstance は整数として表示する書式で、丸めには NumberFormat の既定である RoundingMode.HALF_EVEN（偶数への丸め、銀行丸め）が使われます。ちょうど中間の 2.5 は偶数の 2 に、3.5 は偶数の 4 に丸められ、四捨五入とは結果が異なります。12345.6 は中間ではないので通常どおり 12,346 です。金額計算で端数処理を厳密に決めたい場合は setRoundingMode で明示するか、BigDecimal で計算してから書式化します。",
  },
  {
    id: 10827,
    topic: "localization",
    variantOf: "gold-localization-numberformat",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FractionDigits",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class FractionDigits {",
      "    public static void main(String[] args) {",
      "        NumberFormat de = NumberFormat.getInstance(Locale.GERMANY);",
      "        NumberFormat us = NumberFormat.getInstance(Locale.US);",
      "        us.setMinimumFractionDigits(2);",
      "        System.out.println(de.format(1234567.891) + \" \" + us.format(1234.5) + \" \" + us.format(0.12345));",
      "    }",
      "}",
    ],
    choices: [
      "1.234.567,891 1,234.50 0.123",
      "1,234,567.891 1,234.50 0.123",
      "1.234.567,891 1,234.5 0.12",
      "1.234.567,89 1,234.50 0.12",
      "1 234 567,891 1,234.50 0.12345",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1.234.567,891 1,234.50 0.123" },
    explanation:
      "NumberFormat.getInstance はロケールに応じた桁区切りと小数点の記号を使います。ドイツでは桁区切りがピリオド、小数点がカンマなので 1.234.567,891 です。汎用の数値書式は既定で小数部を最大 3 桁まで表示するので、0.12345 は 0.123 に丸められます。setMinimumFractionDigits(2) は小数部を最低 2 桁表示する設定で、1234.5 は 0 を補って 1,234.50 になります。記号を文字列に直接書かずに NumberFormat に任せることで、同じコードのままロケールごとの表記に対応できます。",
  },

  // ------------------------------------------------------------------- 日付・時刻の書式
  {
    id: 10828,
    topic: "localization",
    variantOf: "gold-localization-datetime-pattern",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TimePattern",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class TimePattern {",
      "    public static void main(String[] args) {",
      "        LocalDateTime t = LocalDateTime.of(2024, 3, 9, 15, 7, 5);",
      "        String a = DateTimeFormatter.ofPattern(\"HH:mm\", Locale.US).format(t);",
      "        String b = DateTimeFormatter.ofPattern(\"h:mm a\", Locale.US).format(t);",
      "        String c = DateTimeFormatter.ofPattern(\"yy-M-d MM\", Locale.US).format(t);",
      "        System.out.println(a + \" | \" + b + \" | \" + c);",
      "    }",
      "}",
    ],
    choices: [
      "15:07 | 3:07 PM | 24-3-9 03",
      "15:07 | 03:07 PM | 24-3-9 07",
      "15:07 | 3:07 PM | 2024-3-9 03",
      "03:07 | 3:07 PM | 24-3-9 03",
      "実行時に DateTimeParseException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "15:07 | 3:07 PM | 24-3-9 03" },
    explanation:
      "パターン文字は大文字・小文字で意味が異なります。HH は 0〜23 の時、h は 1〜12 の時（1 文字なので桁埋めなし）、a は午前・午後の表示（Locale.US では PM）です。mm は分、MM は月で、取り違えると日付の中に分が入るような誤りになります。文字の数は桁数を表し、M は 1 桁の月をそのまま、MM は 2 桁に 0 埋め、yy は西暦の下 2 桁です。午前・午後や曜日の表記は言語によって変わるので、ofPattern にもロケールを指定しておくと実行環境に左右されません。",
  },
  {
    id: 10829,
    topic: "localization",
    variantOf: "gold-localization-datetime-unsupported",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "UnsupportedField",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "",
      "public class UnsupportedField {",
      "    public static void main(String[] args) {",
      "        DateTimeFormatter f = DateTimeFormatter.ofPattern(\"yyyy/MM/dd HH:mm\");",
      "        LocalDateTime dt = LocalDateTime.of(2024, 5, 1, 9, 30);",
      "        System.out.print(f.format(dt) + \" \");",
      "        LocalDate d = LocalDate.of(2024, 5, 1);",
      "        System.out.println(f.format(d));",
      "    }",
      "}",
    ],
    choices: [
      "2024/05/01 09:30 と出力された後、UnsupportedTemporalTypeException がスローされる",
      "2024/05/01 09:30 2024/05/01 00:00",
      "2024/05/01 09:30 2024/05/01",
      "10行目でコンパイルエラーになる",
      "2024/05/01 09:30 と出力された後、DateTimeParseException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedTemporalTypeException", stdout: "2024/05/01 09:30" },
    explanation:
      "DateTimeFormatter.format の引数は TemporalAccessor 型なので、LocalDate を渡してもコンパイルは通ります。しかし LocalDate は日付だけの型で「時」や「分」のフィールドを持たないため、パターンの HH を処理しようとした時点で UnsupportedTemporalTypeException がスローされます。00:00 を補ってくれることはありません。書式化できるかどうかは、パターンが要求するフィールドを対象の型が持っているかで決まるので、LocalDate には日付だけのパターン、時刻も表示したいなら atStartOfDay() などで LocalDateTime に変換してから書式化します。",
  },
  {
    id: 10830,
    topic: "localization",
    variantOf: "gold-localization-datetime-parse",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ParseDate",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "",
      "public class ParseDate {",
      "    public static void main(String[] args) {",
      "        LocalDate a = LocalDate.parse(\"2024/1/5\", DateTimeFormatter.ofPattern(\"yyyy/M/d\"));",
      "        LocalDate b = LocalDate.parse(\"2024-01-05\");",
      "        System.out.print(a.equals(b) + \" \" + a.getDayOfWeek() + \" \");",
      "        LocalDate c = LocalDate.parse(\"2024/1/5\", DateTimeFormatter.ofPattern(\"yyyy/MM/dd\"));",
      "        System.out.println(c);",
      "    }",
      "}",
    ],
    choices: [
      "true FRIDAY と出力された後、DateTimeParseException がスローされる",
      "true FRIDAY 2024-01-05",
      "false FRIDAY 2024-01-05",
      "true 金曜日 と出力された後、DateTimeParseException がスローされる",
      "7行目で DateTimeParseException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "DateTimeParseException", stdout: "true FRIDAY" },
    explanation:
      "解析（parse）でも書式化と同じパターン文字を使います。M や d は 1 桁でも 2 桁でも受け付けるので \"2024/1/5\" を解析でき、引数を 1 つだけ取る parse は ISO 形式（yyyy-MM-dd）で解析するので、a と b は同じ日付です。getDayOfWeek は DayOfWeek 列挙型を返し、toString は FRIDAY というロケールに依存しない定数名です。一方 MM や dd は解析時にちょうど 2 桁を要求するので、1 桁の \"1\" や \"5\" は解析できず DateTimeParseException がスローされます。利用者の入力を解析するときは、パターンの桁数が受け付ける形式を決めることに注意します。",
  },
  {
    id: 10831,
    topic: "localization",
    variantOf: "gold-localization-localized-style",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LocalizedTime",
    code: [
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class LocalizedTime {",
      "    public static void main(String[] args) {",
      "        LocalTime t = LocalTime.of(15, 5);",
      "        DateTimeFormatter f = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT);",
      "        System.out.println(f.withLocale(Locale.US).format(t) + \" | \" + f.withLocale(Locale.JAPAN).format(t));",
      "    }",
      "}",
    ],
    choices: ["3:05 PM | 15:05", "15:05 | 15:05", "3:05 PM | 午後3:05", "03:05 PM | 15:05", "3:05 PM | 3:05 PM"],
    correct: [0],
    expected: { kind: "output", stdout: "3:05 PM | 15:05" },
    explanation:
      "ofLocalizedTime は、パターンを自分で書く代わりに FormatStyle（SHORT / MEDIUM / LONG / FULL）で詳しさだけを指定し、具体的な表記はロケールに任せる書式です。同じ SHORT でも、米国では 12 時間制の 3:05 PM、日本では 24 時間制の 15:05 になります。withLocale は元の書式を変更せずにロケールだけを差し替えた新しい DateTimeFormatter を返します（DateTimeFormatter は不変）。国ごとの慣習をコードに書き込まずに済むのが、ローカライズされたスタイルを使う利点です。",
  },
  {
    id: 10832,
    topic: "localization",
    variantOf: "gold-localization-default-locale",
    question: `${JA_NOTE}次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。`,
    className: "DefaultChange",
    code: [
      "import java.text.*;",
      "import java.util.*;",
      "",
      "public class DefaultChange {",
      "    public static void main(String[] args) {",
      "        NumberFormat before = NumberFormat.getInstance();",
      "        Locale.setDefault(Locale.GERMANY);",
      "        NumberFormat after = NumberFormat.getInstance();",
      "        System.out.println(before.format(1234.5) + \" \" + after.format(1234.5) + \" \" + Locale.getDefault());",
      "    }",
      "}",
    ],
    choices: [
      "1,234.5 1.234,5 de_DE",
      "1.234,5 1.234,5 de_DE",
      "1,234.5 1,234.5 ja_JP",
      "1,234.5 1.234,5 ja_JP",
      "1.234,5 1,234.5 de_DE",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1,234.5 1.234,5 de_DE" },
    explanation:
      "ロケールを指定しない NumberFormat.getInstance() は、呼び出した時点のデフォルトロケールで書式を作ります。before は ja_JP の書式（桁区切りカンマ、小数点ピリオド）で作られ、その後に Locale.setDefault でデフォルトを変えても、作成済みの before は影響を受けません。after はドイツの書式で作られるので 1.234,5 です。Locale.setDefault は JVM 全体の既定値を変える（同じ JVM の他の処理にも影響する）ので、特定の処理だけロケールを変えたいなら、setDefault を使わずに getInstance(Locale) のようにロケールを引数で渡します。",
  },
];
