import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: 複数選択問題。
 *
 * 本試験は「2つ選びなさい」「3つ選びなさい」のような複数選択問題も出題されるため、各分野に 2〜3 問ずつ補った。
 * id は各分野の番号帯の続きから振る（collections 10151- / functional 10240- / streams 10358- / modules 10439- /
 * concurrency 10540- / io 10640- / jdbc 10736- / localization 10836-）。
 *
 * コード自体の実行結果は expected で実機検証するが、各選択肢の記述の正誤は検証スクリプトの対象外
 * （choice-mismatch は正解が 1 つの問題にしか適用されない）なので、選択肢と解説の対応は目視で確認すること。
 */
const DB_NOTE = "H2 Database の JDBC ドライバがクラスパスに含まれているものとする。";
const JA_NOTE = "デフォルトロケールは ja_JP とする。";

export const goldMultiQuestions: GoldQuestion[] = [
  // ============================================================ コレクションとジェネリクス
  {
    id: 10151,
    topic: "collections",
    variantOf: "gold-collections-multi-treeset",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiTreeSet",
    code: [
      "import java.util.*;",
      "",
      "public class MultiTreeSet {",
      "    public static void main(String[] args) {",
      "        Set<String> set = new TreeSet<>(",
      "                Comparator.comparing(String::length).thenComparing(Comparator.reverseOrder()));",
      "        set.addAll(List.of(\"bb\", \"a\", \"cc\", \"ddd\", \"a\"));",
      "        System.out.println(set);",
      "    }",
      "}",
    ],
    choices: [
      "出力は [a, cc, bb, ddd] になる",
      "重複した \"a\" は 1 つだけ格納される",
      "長さが同じ bb と cc は、どちらか一方しか格納されない",
      "出力は [a, bb, cc, ddd] になる",
      "addAll に重複した要素を渡すと IllegalArgumentException がスローされる",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "[a, cc, bb, ddd]" },
    explanation:
      "TreeSet は Comparator の結果で並べ、比較結果が 0 になる要素を重複とみなします。この Comparator はまず長さで比べ、長さが同じなら thenComparing(Comparator.reverseOrder()) で文字列の降順に比べます。bb と cc は長さが同じでも文字列としては異なるので両方格納され、降順なので cc が先に来ます。2 つ目の \"a\" は比較結果が 0 になるので格納されず、Set の add は重複に対して例外ではなく false を返すだけです。thenComparing で順序を決めきると、長さだけで比べたときに起きる「別の要素が消える」問題を防げます。",
  },
  {
    id: 10152,
    topic: "collections",
    variantOf: "gold-collections-multi-wildcard",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiWildcard",
    code: [
      "import java.util.*;",
      "",
      "public class MultiWildcard {",
      "    static double sum(List<? extends Number> list) {",
      "        double total = 0;",
      "        for (Number n : list) total += n.doubleValue();",
      "        return total;",
      "    }",
      "",
      "    static void fill(List<? super Integer> list) {",
      "        list.add(1);",
      "        list.add(2);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Number> nums = new ArrayList<>();",
      "        fill(nums);",
      "        nums.add(0.5);",
      "        System.out.println(sum(nums));",
      "    }",
      "}",
    ],
    choices: [
      "出力は 3.5 になる",
      "fill には List<Object> も渡せる",
      "sum には List<Integer> も渡せる",
      "sum の中で list.add(1) と書ける",
      "fill の中で Integer n = list.get(0); と書ける",
      "fill には List<Double> も渡せる",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "3.5" },
    explanation:
      "List<? super Integer> は「Integer かそのスーパータイプの要素を持つリスト」なので、List<Number> や List<Object> を渡せ、Integer を追加できます。ただし取り出した要素の型は Object としか分からないので、Integer 変数に代入することはできません。List<? extends Number> は「Number かそのサブタイプの要素を持つリスト」で、List<Integer> も渡せ、要素を Number として読めますが、実体の要素型が分からないので追加はできません。List<Double> の要素型 Double は Integer のスーパータイプではないので fill には渡せません。読み出し専用なら extends、書き込み専用なら super という PECS の原則どおりの結果で、1 + 2 + 0.5 = 3.5 が出力されます。",
  },
  {
    id: 10153,
    topic: "collections",
    variantOf: "gold-collections-multi-map-return",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiMapReturn",
    code: [
      "import java.util.*;",
      "",
      "public class MultiMapReturn {",
      "    public static void main(String[] args) {",
      "        Map<String, Integer> m = new HashMap<>();",
      "        m.put(\"a\", 1);",
      "        Integer r1 = m.putIfAbsent(\"a\", 2);",
      "        Integer r2 = m.merge(\"b\", 5, Integer::sum);",
      "        Integer r3 = m.put(\"a\", 9);",
      "        System.out.println(r1 + \" \" + r2 + \" \" + r3 + \" \" + new TreeMap<>(m));",
      "    }",
      "}",
    ],
    choices: [
      "putIfAbsent は、キーが既にあると既存の値を返し、値を変更しない",
      "put は、置き換える前の値を返す",
      "merge は、キーが無かった場合は null を返す",
      "出力は 1 5 1 {a=2, b=5} になる",
      "putIfAbsent は、キーが既にあると IllegalStateException をスローする",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "1 5 1 {a=9, b=5}" },
    explanation:
      "Map の更新メソッドは、戻り値で「操作の前後の値」を知らせます。putIfAbsent はキーが既にあれば何もせず既存の値（1）を返し、put は置き換える前の値（1）を返します。merge はキーが無ければ渡した値をそのまま登録し、登録後の値（5）を返すので null にはなりません。最終的に a は 9 に置き換わり {a=9, b=5} です。戻り値を見れば「前の値があったか」を 1 回の呼び出しで判定できるので、containsKey と get を組み合わせる必要がありません。",
  },

  // ============================================================ 関数型インタフェースとラムダ式
  {
    id: 10240,
    topic: "functional",
    variantOf: "gold-functional-multi-targets",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行を2つ選びなさい。",
    className: "MultiTargets",
    code: [
      "import java.util.function.*;",
      "",
      "public class MultiTargets {",
      "    public static void main(String[] args) {",
      "        Supplier<String> a = () -> \"x\";",
      "        Runnable b = () -> \"x\";",
      "        Function<String, Integer> c = String::length;",
      "        Predicate<String> d = String::toUpperCase;",
      "        Consumer<String> e = s -> System.out.println(s);",
      "        BiFunction<String, String, Boolean> f = String::equals;",
      "    }",
      "}",
    ],
    choices: ["6行目", "8行目", "5行目", "7行目", "9行目", "10行目"],
    correct: [0, 1],
    expected: { kind: "compile-error", line: 6 },
    explanation:
      "ラムダ式やメソッド参照が代入できるかは、関数型インタフェースの抽象メソッドの引数と戻り値の形で決まります。Runnable.run() は戻り値が void なので、本体が値だけの式 \"x\" のラムダ式は適合せず6行目がエラーになります（本体がメソッド呼び出しなら、戻り値を捨てて void として扱えます）。Predicate.test は boolean を返す必要があるのに、String::toUpperCase は String を返すので8行目もエラーです。String::length は String を受け取って int（Integer にボクシング）を返すので Function に、String::equals は 2 つの String から boolean を返すので BiFunction に適合します。",
  },
  {
    id: 10241,
    topic: "functional",
    variantOf: "gold-functional-multi-interface",
    question: "次のコードについて、関数型インタフェースであるものを3つ選びなさい。",
    className: "MultiInterface",
    code: [
      "interface A { void run(); }",
      "interface B extends A { default void stop() { } }",
      "interface C { void run(); boolean equals(Object o); }",
      "interface D extends A { void pause(); }",
      "interface E { static void util() { } }",
      "",
      "public class MultiInterface {",
      "    public static void main(String[] args) {",
      "        A a = () -> { };",
      "        B b = () -> { };",
      "        C c = () -> { };",
      "        System.out.println(\"ok\");",
      "    }",
      "}",
    ],
    choices: ["A", "B", "C", "D", "E"],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "ok" },
    explanation:
      "関数型インタフェースは、抽象メソッドがちょうど 1 つのインタフェースです。A は run だけ、B は継承した run に default メソッドを足しただけ（default は実装を持つので数えない）、C は run と、Object の public メソッドと同じシグネチャの equals（どの実装クラスも Object から受け継ぐので数えない）で、いずれも抽象メソッドは 1 つです。そのためラムダ式を代入でき、コードは ok と出力します。D は継承した run と自身の pause の 2 つを持つので関数型インタフェースではなく、E は static メソッドだけで抽象メソッドが 0 個なので同じく該当しません。",
  },
  {
    id: 10242,
    topic: "functional",
    variantOf: "gold-functional-multi-compose",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiCompose",
    code: [
      "import java.util.function.*;",
      "",
      "public class MultiCompose {",
      "    public static void main(String[] args) {",
      "        Function<Integer, Integer> inc = x -> x + 1;",
      "        Function<Integer, Integer> dbl = x -> x * 2;",
      "        System.out.println(inc.andThen(dbl).apply(3) + \" \" + inc.compose(dbl).apply(3) + \" \"",
      "                + Function.<Integer>identity().andThen(inc).apply(0));",
      "    }",
      "}",
    ],
    choices: [
      "出力は 8 7 1 になる",
      "inc.andThen(dbl) は、先に inc を適用してから dbl を適用する",
      "inc.compose(dbl) は、先に dbl を適用してから inc を適用する",
      "inc.compose(dbl) は、先に inc を適用してから dbl を適用する",
      "Function.identity() は、引数を 2 倍にして返す",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "8 7 1" },
    explanation:
      "f.andThen(g) は「f の後に g」、f.compose(g) は「g の後に f」を適用する関数を作ります。inc.andThen(dbl).apply(3) は (3 + 1) × 2 = 8、inc.compose(dbl).apply(3) は 3 × 2 + 1 = 7 です。Function.identity() は受け取った値をそのまま返す関数で、andThen(inc) と合成すると 0 + 1 = 1 になります。compose は数学の関数合成 f(g(x)) と同じ読み順になるよう名付けられているので、処理の流れの順に書きたいときは andThen を使うと読み違えにくくなります。",
  },

  // ============================================================ ストリーム API
  {
    id: 10358,
    topic: "streams",
    variantOf: "gold-streams-multi-operations",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiOperations",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class MultiOperations {",
      "    public static void main(String[] args) {",
      "        List<Integer> r = Stream.of(5, 3, 8, 1)",
      "                .filter(n -> n > 2)",
      "                .sorted()",
      "                .map(n -> n * 10)",
      "                .toList();",
      "        long c = Stream.of(5, 3, 8, 1).filter(n -> n > 2).count();",
      "        System.out.println(r + \" \" + c);",
      "    }",
      "}",
    ],
    choices: [
      "filter・sorted・map は中間操作である",
      "toList と count は終端操作である",
      "出力は [30, 50, 80] 3 になる",
      "sorted は終端操作である",
      "終端操作を実行した後も、同じストリームに対して map を続けて呼べる",
      "出力は [50, 30, 80] 3 になる",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "[30, 50, 80] 3" },
    explanation:
      "中間操作（filter、sorted、map など）はストリームを返して処理を登録するだけで、終端操作（toList、count、collect、forEach など）を呼んだ時点で初めて要素が流れます。2 より大きい 5・3・8 を昇順に並べてから 10 倍するので [30, 50, 80]、同じ条件の件数は 3 です。sorted はすべての要素を受け取ってから並べ替える中間操作であり、結果をストリームとして返すので後ろに map を続けられます。終端操作を実行したストリームは消費済みになり、さらに操作を呼ぶと IllegalStateException になります。",
  },
  {
    id: 10359,
    topic: "streams",
    variantOf: "gold-streams-multi-partition",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiPartition",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class MultiPartition {",
      "    public static void main(String[] args) {",
      "        Map<Boolean, Long> p = Stream.of(1, 2, 3, 4, 5)",
      "                .collect(Collectors.partitioningBy(n -> n > 10, Collectors.counting()));",
      "        Map<Boolean, Long> g = Stream.of(1, 2, 3, 4, 5)",
      "                .collect(Collectors.groupingBy(n -> n > 10, Collectors.counting()));",
      "        System.out.println(p + \" \" + g);",
      "    }",
      "}",
    ],
    choices: [
      "partitioningBy の結果には、該当する要素が無くても true のキーが含まれる",
      "groupingBy の結果には、該当する要素が無いキーは含まれない",
      "p と g はどちらも {false=5, true=0} と出力される",
      "Collectors.counting() の結果は Integer 型である",
      "partitioningBy は条件を満たす要素だけを集め、満たさない要素は捨てる",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "{false=5, true=0} {false=5}" },
    explanation:
      "partitioningBy は条件の真偽で要素を 2 つに分けるコレクタで、結果のマップは該当する要素の有無にかかわらず false と true の両方のキーを持ちます。10 より大きい要素は無いので true には counting の初期値 0 が入ります。groupingBy は実際に現れた分類キーだけをマップに入れるので、true のキーは存在しません。counting() の結果は Long 型です。2 分割の結果を扱う側が get(true) で null を受け取る心配をせずに済むよう、partitioningBy は常に両方のキーを用意する設計になっています。",
  },
  {
    id: 10360,
    topic: "streams",
    variantOf: "gold-streams-multi-optional",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiOptional",
    code: [
      "import java.util.*;",
      "",
      "public class MultiOptional {",
      "    public static void main(String[] args) {",
      "        Optional<String> a = Optional.of(\"java\");",
      "        Optional<String> b = Optional.empty();",
      "        System.out.println(a.map(String::length).orElse(0) + \" \"",
      "                + b.map(String::length).orElse(0) + \" \" + b.isPresent());",
      "    }",
      "}",
    ],
    choices: [
      "空の Optional に対して map を呼ぶと、関数は実行されず空の Optional が返る",
      "出力は 4 0 false になる",
      "b.map(String::length) は NullPointerException をスローする",
      "Optional.of(null) は空の Optional を返す",
      "orElse の引数は、Optional に値があるときは評価されない",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "4 0 false" },
    explanation:
      "Optional.map は値があるときだけ関数を適用して結果を Optional に包み直し、空のときは関数を呼ばずに空の Optional を返します。そのため a からは長さ 4、b からは orElse の 0 が得られ、b.isPresent() は false です。Optional.of(null) は空の Optional ではなく NullPointerException になり、null を受け付けるのは ofNullable です。また orElse の引数は普通のメソッド引数なので、値があっても呼び出し前に評価されます。評価を値が無いときだけにしたい場合は orElseGet に Supplier を渡します。",
  },

  // ============================================================ モジュール・システム
  {
    id: 10439,
    topic: "modules",
    variantOf: "gold-modules-multi-exports-opens",
    question:
      "次のモジュール構成で、com.example.app/com.example.app.Main を実行すると api secret と出力される。この構成について正しい記述を2つ選びなさい。",
    choices: [
      "com.example.app は、com.example.lib.api パッケージの public 型をコンパイル時に参照できる",
      "com.example.app は、リフレクションで com.example.lib.model パッケージの private フィールドを読める",
      "com.example.app は、com.example.lib.model パッケージの型を import してコンパイル時に参照できる",
      "opens を宣言したパッケージは、exports も宣言したものとして扱われる",
      "com.example.app は、リフレクションで com.example.lib.api パッケージの private フィールドも読める",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "api secret" },
    moduleSetup: {
      main: "com.example.app/com.example.app.Main",
      sources: [
        {
          module: "com.example.lib",
          path: "module-info.java",
          content: ["module com.example.lib {", "    exports com.example.lib.api;", "    opens com.example.lib.model;", "}"],
        },
        { module: "com.example.lib", path: "com/example/lib/api/Api.java", content: ["package com.example.lib.api;", "", "public class Api {", "    public static String name() {", "        return \"api\";", "    }", "}"] },
        { module: "com.example.lib", path: "com/example/lib/model/Secret.java", content: ["package com.example.lib.model;", "", "public class Secret {", "    private String value = \"secret\";", "}"] },
        { module: "com.example.app", path: "module-info.java", content: ["module com.example.app {", "    requires com.example.lib;", "}"] },
        {
          module: "com.example.app",
          path: "com/example/app/Main.java",
          content: [
            "package com.example.app;",
            "",
            "import java.lang.reflect.Field;",
            "import com.example.lib.api.Api;",
            "",
            "public class Main {",
            "    public static void main(String[] args) throws Exception {",
            "        Class<?> c = Class.forName(\"com.example.lib.model.Secret\");",
            "        Object secret = c.getConstructor().newInstance();",
            "        Field f = c.getDeclaredField(\"value\");",
            "        f.setAccessible(true);",
            "        System.out.println(Api.name() + \" \" + f.get(secret));",
            "    }",
            "}",
          ],
        },
      ],
    },
    explanation:
      "exports と opens は別々の権限です。exports は指定したパッケージの public 型をコンパイル時と実行時の通常のアクセスに公開し、opens は実行時のリフレクションによるアクセス（private メンバーを含む深いリフレクション）を許可します。app は exports された api の Api をコンパイル時に参照でき、opens された model の Secret はリフレクションで生成して private フィールドを読めます。一方 model は exports されていないので import してコンパイル時に参照することはできず、api は opens されていないので private フィールドへの setAccessible は InaccessibleObjectException になります。フレームワーク向けに opens だけを付け、API として公開するパッケージには exports を付ける、と使い分けるための仕組みです。",
  },
  {
    id: 10440,
    topic: "modules",
    variantOf: "gold-modules-multi-automatic",
    question:
      "module-info.java を持たない legacy-util-1.0.jar（com.legacy.util.Strings を含む）をモジュールパスに置き、次のモジュール com.example.app を実行すると HELLO と出力される。この構成について正しい記述を2つ選びなさい。",
    choices: [
      "モジュールパスに置いた module-info.java の無い JAR は、自動モジュールとして扱われる",
      "自動モジュールの名前は、JAR ファイル名から導出される",
      "legacy-util-1.0.jar をクラスパスに置いても、requires legacy.util; で読み込める",
      "自動モジュールは、名前に対応するパッケージしか公開しない",
      "自動モジュールを読み込むには、requires static と書かなければならない",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "HELLO" },
    moduleSetup: {
      main: "com.example.app/com.example.app.Main",
      jars: [
        {
          fileName: "legacy-util-1.0.jar",
          placement: "module-path",
          sources: [
            {
              path: "com/legacy/util/Strings.java",
              content: ["package com.legacy.util;", "", "public class Strings {", "    public static String shout(String s) {", "        return s.toUpperCase();", "    }", "}"],
            },
          ],
        },
      ],
      sources: [
        { module: "com.example.app", path: "module-info.java", content: ["module com.example.app {", "    requires legacy.util;", "}"] },
        {
          module: "com.example.app",
          path: "com/example/app/Main.java",
          content: [
            "package com.example.app;",
            "",
            "import com.legacy.util.Strings;",
            "",
            "public class Main {",
            "    public static void main(String[] args) {",
            "        System.out.println(Strings.shout(\"hello\"));",
            "    }",
            "}",
          ],
        },
      ],
    },
    explanation:
      "module-info.java を持たない JAR をモジュールパスに置くと自動モジュールになり、マニフェストに Automatic-Module-Name が無ければ名前は JAR ファイル名から導出されます（legacy-util-1.0.jar はバージョン部分を除いて legacy.util）。自動モジュールは含まれるすべてのパッケージを公開し、通常の requires で読み込めます。一方クラスパスに置いた JAR は名前の無い無名モジュールに属し、名前付きモジュールからは requires で指定できません。自動モジュールは、まだモジュール化されていないライブラリを名前付きモジュールから使うための橋渡しです。",
  },

  // ============================================================ 並列処理
  {
    id: 10540,
    topic: "concurrency",
    variantOf: "gold-concurrency-multi-executor",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiExecutor",
    code: [
      "import java.util.concurrent.*;",
      "",
      "public class MultiExecutor {",
      "    public static void main(String[] args) throws Exception {",
      "        ExecutorService ex = Executors.newFixedThreadPool(2);",
      "        Future<Integer> f = ex.submit(() -> 6 * 7);",
      "        Future<?> g = ex.submit(() -> System.out.print(\"\"));",
      "        System.out.print(f.get() + \" \" + g.get() + \" \");",
      "        ex.shutdown();",
      "        System.out.println(ex.awaitTermination(1, TimeUnit.SECONDS) + \" \" + ex.isShutdown());",
      "    }",
      "}",
    ],
    choices: [
      "f.get() は 42 を返す",
      "Runnable として submit したタスクの Future の get() は、完了後に null を返す",
      "shutdown() を呼んだ後、isShutdown() は true を返す",
      "shutdown() は、実行中のタスクに割り込んで直ちに停止させる",
      "submit に Runnable を渡した場合は Future を返さない",
      "7行目のラムダ式は値を返すので Callable として扱われる",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "42 null true true" },
    explanation:
      "submit は Callable でも Runnable でも Future を返します。6行目のラムダ式は値を返すので Callable<Integer> となり、get() で 42 が得られます。7行目の System.out.print は void なので Runnable として扱われ、その Future の get() は完了を待ってから null を返します。shutdown() は新しいタスクの受け付けを止めるだけで、投入済みのタスクは最後まで実行させます（割り込んで止めようとするのは shutdownNow() です）。呼んだ後の isShutdown() は true で、awaitTermination は全タスクが終わっていれば true を返します。",
  },
  {
    id: 10541,
    topic: "concurrency",
    variantOf: "gold-concurrency-multi-collections",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiConcurrent",
    code: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class MultiConcurrent {",
      "    public static void main(String[] args) {",
      "        List<Integer> cow = new CopyOnWriteArrayList<>(List.of(1, 2));",
      "        for (Integer n : cow) {",
      "            cow.add(n * 10);",
      "        }",
      "        Map<String, Integer> chm = new ConcurrentHashMap<>();",
      "        chm.merge(\"k\", 1, Integer::sum);",
      "        chm.merge(\"k\", 1, Integer::sum);",
      "        System.out.println(cow + \" \" + chm);",
      "    }",
      "}",
    ],
    choices: [
      "CopyOnWriteArrayList は、拡張 for 文で反復中に要素を追加しても例外をスローしない",
      "出力は [1, 2, 10, 20] {k=2} になる",
      "ループは追加された要素も反復し続けるため、終了しない",
      "ConcurrentHashMap は、値として null を格納できる",
      "出力は [1, 2] {k=2} になる",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "[1, 2, 10, 20] {k=2}" },
    explanation:
      "CopyOnWriteArrayList は変更のたびに内部の配列を複製して差し替え、イテレータは作成時点の配列（スナップショット）を反復します。そのため反復中に add しても ConcurrentModificationException にならず、反復されるのは元の 1 と 2 だけなのでループは終了し、追加した 10 と 20 はループ後のリストに現れます。ConcurrentHashMap の merge は「読み出し・合成・書き込み」を不可分に行い、2 回の加算で k=2 になります。ConcurrentHashMap は、並行処理で「キーが無い」と「値が null」を区別できなくなるのを避けるため、null のキーも値も受け付けません。",
  },
  {
    id: 10542,
    topic: "concurrency",
    variantOf: "gold-concurrency-multi-atomic",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiAtomic",
    code: [
      "import java.util.concurrent.atomic.*;",
      "",
      "public class MultiAtomic {",
      "    public static void main(String[] args) throws InterruptedException {",
      "        AtomicInteger count = new AtomicInteger();",
      "        Runnable task = () -> {",
      "            for (int i = 0; i < 1000; i++) count.incrementAndGet();",
      "        };",
      "        Thread t1 = new Thread(task);",
      "        Thread t2 = new Thread(task);",
      "        t1.start();",
      "        t2.start();",
      "        t1.join();",
      "        t2.join();",
      "        System.out.println(count.get());",
      "    }",
      "}",
    ],
    choices: [
      "出力は必ず 2000 になる",
      "incrementAndGet は、値の読み出しから書き込みまでを不可分な 1 つの操作として行う",
      "join を呼ばなくても、出力は必ず 2000 になる",
      "count を int のフィールドに替えて count++ にしても、出力は必ず 2000 になる",
      "incrementAndGet は、増やす前の値を返す",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "2000" },
    explanation:
      "AtomicInteger.incrementAndGet は「読み出し・加算・書き込み」を CAS などの不可分な操作で行うので、2 つのスレッドが同時に呼んでも更新が失われず、合計は必ず 2000 になります。int の count++ はこの 3 段階が分かれているため、同時に実行すると更新が失われて 2000 未満になりえます。join は両スレッドの終了を待つためのもので、これを省くと加算の途中で値を読んでしまう可能性があります。incrementAndGet は前置の ++i に相当し、増やした後の値を返します（増やす前の値を返すのは getAndIncrement です）。",
  },

  // ============================================================ ファイル I/O
  {
    id: 10640,
    topic: "io",
    variantOf: "gold-io-multi-path",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiPath",
    code: [
      "import java.nio.file.*;",
      "",
      "public class MultiPath {",
      "    public static void main(String[] args) {",
      "        Path p = Path.of(\"a\", \"b\", \"..\", \"c.txt\");",
      "        Path n = p.normalize();",
      "        System.out.println(p.getNameCount() + \" \" + n.getNameCount() + \" \"",
      "                + n.getFileName() + \" \" + (p.getRoot() == null));",
      "    }",
      "}",
    ],
    choices: [
      "normalize は、名前要素 .. とその直前の要素を取り除く",
      "相対パスの getRoot() は null を返す",
      "p.getNameCount() は 4 を返す",
      "normalize はファイル・システムを調べ、b が存在しなければ例外をスローする",
      "Path.of を呼ぶと、そのパスのファイルが作成される",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "4 2 c.txt true" },
    explanation:
      "Path は名前要素の並びで、a, b, .., c.txt の 4 要素なので getNameCount() は 4 です。normalize() は . を消し、.. でその直前の要素を打ち消すので a/c.txt の 2 要素になります。この計算はパスの文字列の上だけで行われ、ファイルが実在するかは調べません（実在のファイルに基づいて解決したい場合は toRealPath を使います）。Path.of もパスを表すオブジェクトを作るだけで、ファイルは作成しません。ルート要素を持たない相対パスの getRoot() は null を返します。",
  },
  {
    id: 10641,
    topic: "io",
    variantOf: "gold-io-multi-options",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiOptions",
    code: [
      "import java.nio.file.*;",
      "",
      "public class MultiOptions {",
      "    public static void main(String[] args) throws Exception {",
      "        Path p = Path.of(\"x.txt\");",
      "        Files.writeString(p, \"ab\");",
      "        Files.writeString(p, \"c\", StandardOpenOption.APPEND);",
      "        System.out.print(Files.readString(p) + \" \");",
      "        Files.writeString(p, \"d\");",
      "        System.out.println(Files.readString(p));",
      "    }",
      "}",
    ],
    choices: [
      "StandardOpenOption.APPEND を指定すると、既存の内容の末尾に追記される",
      "オプションを省略すると、既存の内容を空にしてから書き込む",
      "出力は abc abcd になる",
      "既存のファイルに対してオプションなしで writeString を呼ぶと、FileAlreadyExistsException がスローされる",
      "オプションを省略すると、既存のファイルには書き込まずに何もしない",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "abc d" },
    explanation:
      "Files.writeString でオプションを省略すると、CREATE・TRUNCATE_EXISTING・WRITE を指定したものとして扱われます。つまりファイルが無ければ作り、あれば中身を空にしてから書き込むので、9行目の後は d だけが残ります。APPEND を指定すると既存の内容の末尾に書き足すので、7行目の後は abc です。既存のファイルがあると例外にするのは CREATE_NEW を指定した場合だけです。上書きか追記かで結果がまったく変わるので、ログのように書き足すファイルでは APPEND（無ければ作るなら CREATE も）を明示します。",
  },
  {
    id: 10642,
    topic: "io",
    variantOf: "gold-io-multi-serialization",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiSerial",
    code: [
      "import java.io.*;",
      "",
      "public class MultiSerial {",
      "    static class Item implements Serializable {",
      "        static int count = 1;",
      "        String name = \"pen\";",
      "        transient int qty = 5;",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        Item item = new Item();",
      "        item.name = \"ink\";",
      "        item.qty = 7;",
      "        ByteArrayOutputStream bytes = new ByteArrayOutputStream();",
      "        try (ObjectOutputStream out = new ObjectOutputStream(bytes)) {",
      "            out.writeObject(item);",
      "        }",
      "        Item.count = 2;",
      "        try (ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {",
      "            Item copy = (Item) in.readObject();",
      "            System.out.println(copy.name + \" \" + copy.qty + \" \" + Item.count);",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "transient を付けたフィールドは、復元後に型の既定値になる",
      "static フィールドはシリアライズの対象にならない",
      "Serializable なクラスのフィールド初期化子は、復元時には実行されない",
      "復元時には Item のコンストラクタが実行される",
      "出力は ink 7 1 になる",
      "Serializable は、実装クラスが実装すべき抽象メソッドを 1 つ持つ",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "ink 0 2" },
    explanation:
      "シリアライズの対象はインスタンス・フィールドの状態だけです。transient を付けた qty は書き込まれないので、復元後は int の既定値 0 になります。フィールド初期化子の 5 にならないのは、Serializable なクラスは復元時にコンストラクタも初期化子も実行せず、ストリームのデータを直接フィールドに戻すためです。static フィールドはクラスに属するので書き込まれず、復元後に参照すると現在の値 2 が見えます。Serializable はメソッドを持たない目印のインタフェース（マーカー・インタフェース）で、「このクラスは直列化してよい」と宣言する役割だけを担います。",
  },

  // ============================================================ JDBC
  {
    id: 10736,
    topic: "jdbc",
    variantOf: "gold-jdbc-multi-execute",
    question: `${DB_NOTE}次のコードについて、正しい記述を3つ選びなさい。`,
    className: "MultiExecute",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class MultiExecute {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.executeUpdate(\"CREATE TABLE t(id INT)\");",
      "            int b = st.executeUpdate(\"INSERT INTO t VALUES (1), (2)\");",
      "            boolean c = st.execute(\"SELECT * FROM t\");",
      "            boolean d = st.execute(\"DELETE FROM t\");",
      "            System.out.println(b + \" \" + c + \" \" + d + \" \" + st.getUpdateCount());",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "executeUpdate は、INSERT などで影響を受けた行数を返す",
      "execute は、結果が ResultSet のときに true を返す",
      "execute で DELETE を実行した後、getUpdateCount() で削除した件数を得られる",
      "execute は SELECT 専用で、DELETE を渡すと SQLException がスローされる",
      "executeQuery に DELETE を渡しても、削除した件数を得られる",
      "出力は 2 true true 2 になる",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "2 true false 2" },
    explanation:
      "executeUpdate は更新系の SQL を実行して影響を受けた行数を返すので、2 行の INSERT では 2 です。execute はどんな SQL でも実行でき、結果が ResultSet なら true、更新件数なら false を返します。SELECT は true、DELETE は false で、DELETE の件数は getUpdateCount() で取得でき 2 です。executeQuery は ResultSet を返す SQL 専用で、DELETE を渡すと SQLException になります。実行する SQL の種類が事前に分からない場合に、execute の戻り値で結果の取り出し方を切り替えるのが本来の使い方です。",
  },
  {
    id: 10737,
    topic: "jdbc",
    variantOf: "gold-jdbc-multi-transaction",
    question: `${DB_NOTE}次のコードについて、正しい記述を2つ選びなさい。`,
    className: "MultiTransaction",
    libraries: ["h2"],
    code: [
      "import java.sql.*;",
      "",
      "public class MultiTransaction {",
      "    public static void main(String[] args) throws SQLException {",
      "        try (Connection con = DriverManager.getConnection(\"jdbc:h2:mem:shop\");",
      "             Statement st = con.createStatement()) {",
      "            st.execute(\"CREATE TABLE log(id INT)\");",
      "            con.setAutoCommit(false);",
      "            st.executeUpdate(\"INSERT INTO log VALUES (1)\");",
      "            con.commit();",
      "            st.executeUpdate(\"INSERT INTO log VALUES (2)\");",
      "            con.rollback();",
      "            ResultSet rs = st.executeQuery(\"SELECT COUNT(*) FROM log\");",
      "            rs.next();",
      "            System.out.println(rs.getInt(1));",
      "        }",
      "    }",
      "}",
    ],
    choices: [
      "commit した変更は、その後の rollback では取り消されない",
      "setAutoCommit(false) の後は、commit を呼ぶまで変更が確定しない",
      "rollback を呼ぶと Connection が閉じられる",
      "出力は 0 になる",
      "取得した直後の Connection は、自動コミットが無効になっている",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "1" },
    explanation:
      "取得した直後の Connection は自動コミットが有効で、SQL を 1 文実行するたびに確定します。setAutoCommit(false) にすると、commit か rollback を呼ぶまでの変更が 1 つのトランザクションになります。1 の挿入は commit で確定したので、後の rollback では取り消されません。rollback が取り消すのは直前の commit 以降の 2 の挿入だけなので、件数は 1 です。rollback はトランザクションを終わらせるだけで Connection は開いたままなので、続けて SELECT を実行できます。",
  },

  // ============================================================ ローカライズ
  {
    id: 10836,
    topic: "localization",
    variantOf: "gold-localization-multi-bundle",
    question: `${JA_NOTE}クラスパス上に次の 2 つのプロパティファイルがあり、次のコードを実行すると Bonjour Bye と出力される。正しい記述を2つ選びなさい。`,
    className: "MultiBundle",
    code: [
      "import java.util.*;",
      "",
      "public class MultiBundle {",
      "    public static void main(String[] args) {",
      "        ResourceBundle rb = ResourceBundle.getBundle(\"Msg\", Locale.FRANCE);",
      "        System.out.println(rb.getString(\"greet\") + \" \" + rb.getString(\"bye\"));",
      "    }",
      "}",
    ],
    resources: [
      { path: "Msg.properties", content: ["greet=Hello", "bye=Bye"] },
      { path: "Msg_fr.properties", content: ["greet=Bonjour"] },
    ],
    choices: [
      "Locale.FRANCE（fr_FR）に対して、Msg_fr_FR が無いので Msg_fr が選ばれる",
      "Msg_fr に無いキー bye は、親である基底の Msg から取得される",
      "指定したロケールよりデフォルトロケール（ja_JP）のバンドルが優先して探される",
      "Msg_fr に bye が無いため、MissingResourceException がスローされる",
      "Locale.FRANCE は、国を含まない言語 fr だけのロケールである",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "Bonjour Bye" },
    explanation:
      "getBundle は指定したロケールから候補を作り、Msg_fr_FR → Msg_fr の順に探して Msg_fr を見つけます。デフォルトロケールの候補（Msg_ja_JP → Msg_ja）が探されるのは、指定したロケールの候補が 1 つも見つからなかったときだけです。見つかったバンドルは Msg_fr → Msg という親子関係でつながっており、Msg_fr に無いキー bye は親の Msg から Bye が取得されます。Locale.FRANCE は言語 fr・国 FR の fr_FR で、言語だけのロケールは Locale.FRENCH です。訳の差分だけを具体的なファイルに書けば、残りは基底のバンドルで補える仕組みです。",
  },
  {
    id: 10837,
    topic: "localization",
    variantOf: "gold-localization-multi-format",
    question: "次のコードについて、正しい記述を3つ選びなさい。",
    className: "MultiFormat",
    code: [
      "import java.text.*;",
      "import java.time.*;",
      "import java.time.format.*;",
      "import java.util.*;",
      "",
      "public class MultiFormat {",
      "    public static void main(String[] args) {",
      "        NumberFormat c = NumberFormat.getCurrencyInstance(Locale.US);",
      "        NumberFormat g = NumberFormat.getInstance(Locale.GERMANY);",
      "        String d = DateTimeFormatter.ofPattern(\"yyyy/MM/dd\", Locale.JAPAN).format(LocalDate.of(2024, 3, 5));",
      "        System.out.println(c.format(1234.5) + \" \" + g.format(1234.5) + \" \" + d);",
      "    }",
      "}",
    ],
    choices: [
      "米国の通貨書式では、ドルの金額は小数 2 桁で表示される",
      "ドイツの数値書式では、桁区切りにピリオド、小数点にカンマが使われる",
      "パターン文字 MM は、2 桁に 0 埋めした月を表す",
      "パターン文字 mm は、月を表す",
      "出力は $1,234.5 1,234.5 2024/3/5 になる",
    ],
    correct: [0, 1, 2],
    expected: { kind: "output", stdout: "$1,234.50 1.234,5 2024/03/05" },
    explanation:
      "NumberFormat はロケールの慣習に従って数値を書式化します。米国の通貨書式はドルの補助単位（セント）に合わせて小数 2 桁で表示するので $1,234.50、ドイツの汎用の数値書式は桁区切りがピリオド、小数点がカンマなので 1.234,5 です。DateTimeFormatter のパターン文字は数と大文字小文字で意味が変わり、MM は 2 桁に 0 埋めした月、dd は 2 桁の日なので 2024/03/05 になります。mm は月ではなく分（minute）を表し、日付だけの LocalDate に使うと例外になります。記号をコードに書き込まずロケールに任せることで、同じコードで各国の表記に対応できます。",
  },
  {
    id: 10838,
    topic: "localization",
    variantOf: "gold-localization-multi-locale",
    question: "次のコードについて、正しい記述を2つ選びなさい。",
    className: "MultiLocale",
    code: [
      "import java.util.*;",
      "",
      "public class MultiLocale {",
      "    public static void main(String[] args) {",
      "        Locale a = new Locale(\"ja\", \"JP\");",
      "        Locale b = Locale.forLanguageTag(\"ja-JP\");",
      "        System.out.println(a.equals(b) + \" \" + a + \" \" + b.toLanguageTag() + \" \" + Locale.JAPANESE);",
      "    }",
      "}",
    ],
    choices: [
      "toString() はアンダースコア区切り、toLanguageTag() はハイフン区切りの形式を返す",
      "Locale.JAPANESE は、国を含まない言語だけのロケールである",
      "new Locale と forLanguageTag で作ったロケールは、同じ言語と国でも equals で false になる",
      "Locale.forLanguageTag(\"ja_JP\") は、ja_JP のロケールを返す",
      "出力は true ja-JP ja_JP ja になる",
    ],
    correct: [0, 1],
    expected: { kind: "output", stdout: "true ja_JP ja-JP ja" },
    explanation:
      "Locale は作り方にかかわらず、言語や国などの値が同じなら equals で true になります。toString() は ja_JP のようにアンダースコアで区切った形式、toLanguageTag() は IETF の言語タグ（BCP 47）である ja-JP のようにハイフンで区切った形式を返します。forLanguageTag はハイフン区切りの言語タグを解釈するメソッドなので、\"ja_JP\" のようにアンダースコアで書くと正しく解釈できず、空のロケールになります。Locale.JAPANESE は言語 ja だけのロケールで、国を含む ja_JP は Locale.JAPAN です。2 つの形式を取り違えると、ロケールが静かに空になる不具合につながります。",
  },
];
