import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: Java ストリーム API（id 10301-10399）。
 * 中間操作、リダクション（reduce / collect / Collectors）、集計、探索、Optional、並列ストリーム。
 */
export const goldStreamsQuestions: GoldQuestion[] = [
  // ------------------------------------------------------------- 遅延評価
  {
    id: 10301,
    topic: "streams",
    variantOf: "gold-streams-lazy",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LazyPeek",
    code: [
      "import java.util.stream.*;",
      "",
      "public class LazyPeek {",
      "    public static void main(String[] args) {",
      '        Stream<String> s = Stream.of("a", "b", "c")',
      "                .peek(System.out::print)",
      "                .map(String::toUpperCase);",
      '        System.out.println("end");',
      "    }",
      "}",
    ],
    choices: ["end", "abcend", "ABCend", "abcABCend", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "end" },
    explanation:
      "Stream の中間操作（peek、map、filter など）は、呼び出した時点では処理を登録するだけで何も実行しません。要素が実際に流れるのは forEach や collect などの終端操作が呼ばれたときです。このコードには終端操作が無いため、peek に渡した出力処理は一度も実行されず、end だけが出力されます。遅延評価によって、findFirst のように必要な分だけ処理を打ち切ったり、無限ストリームを扱ったりできます。逆に、中間操作の副作用に頼ったコードは終端操作が無いと動かない点に注意が必要です。",
  },
  {
    id: 10302,
    topic: "streams",
    variantOf: "gold-streams-lazy",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Vertical",
    code: [
      "import java.util.stream.*;",
      "",
      "public class Vertical {",
      "    public static void main(String[] args) {",
      '        Stream.of("a", "b", "c")',
      "                .peek(System.out::print)",
      "                .map(String::toUpperCase)",
      "                .forEach(System.out::print);",
      "    }",
      "}",
    ],
    choices: ["aAbBcC", "abcABC", "ABCabc", "AaBbCc", "abc"],
    correct: [0],
    expected: { kind: "output", stdout: "aAbBcC" },
    explanation:
      "Stream は「各段階を全要素に適用してから次の段階へ進む」のではなく、「1 つの要素をパイプラインの最後まで流してから次の要素に移る」という順で処理します。そのため \"a\" が peek で出力され、大文字にされて forEach で A が出力され、次に \"b\" の処理へ進みます。この縦方向の処理によって、途中の結果を溜めるための一時的なコレクションが不要になります。ただし sorted のように全要素がそろわないと結果を出せない中間操作が挟まると、そこで一度すべての要素が溜め込まれます。",
  },
  {
    id: 10303,
    topic: "streams",
    variantOf: "gold-streams-lazy",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ShortCircuit",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ShortCircuit {",
      "    public static void main(String[] args) {",
      "        Optional<Integer> r = Stream.of(1, 2, 3, 4, 5)",
      "                .peek(System.out::print)",
      "                .filter(n -> n % 2 == 0)",
      "                .findFirst();",
      '        System.out.println(" " + r.get());',
      "    }",
      "}",
    ],
    choices: ["12 2", "12345 2", "2 2", "12345 4", "1 2"],
    correct: [0],
    expected: { kind: "output", stdout: "12 2" },
    explanation:
      "findFirst は条件に合う最初の要素が見つかった時点で結果が決まる短絡（ショートサーキット）終端操作です。要素は 1 つずつパイプラインを流れるので、1 は peek で出力されて filter で除外され、2 は peek で出力されて filter を通過し、findFirst がそこで処理を打ち切ります。そのため 3 以降は peek にすら到達せず、出力は 12 と結果の 2 になります。遅延評価と短絡評価の組み合わせにより、要素が非常に多い（あるいは無限の）ストリームでも必要な分だけ処理できます。",
  },
  {
    id: 10304,
    topic: "streams",
    variantOf: "gold-streams-reuse",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Reuse",
    code: [
      "import java.util.stream.*;",
      "",
      "public class Reuse {",
      "    public static void main(String[] args) {",
      "        Stream<Integer> s = Stream.of(1, 2, 3);",
      "        System.out.print(s.count() + \" \");",
      "        System.out.println(s.mapToInt(n -> n).sum());",
      "    }",
      "}",
    ],
    choices: [
      "3 と出力された後、IllegalStateException がスローされる",
      "3 6",
      "3 0",
      "7行目でコンパイルエラーになる",
      "実行時に NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalStateException", stdout: "3" },
    explanation:
      "Stream は一度しか使えません。count() という終端操作を実行した時点でストリームは消費済みとなり、同じ Stream に対して mapToInt などの操作を呼ぶと「stream has already been operated upon or closed」という IllegalStateException がスローされます。Stream はデータを保持するコレクションではなく、データ源から要素を 1 回だけ流すパイプラインだからです。同じデータを何度も処理したい場合は、元のコレクションから stream() を呼び直すか、Supplier<Stream<T>> を用意して毎回新しいストリームを作ります。",
  },

  // ------------------------------------------------------------- リダクション
  {
    id: 10305,
    topic: "streams",
    variantOf: "gold-streams-reduce",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ReduceTest",
    code: [
      "import java.util.stream.*;",
      "",
      "public class ReduceTest {",
      "    public static void main(String[] args) {",
      "        System.out.println(Stream.of(1, 2, 3).reduce(10, Integer::sum) + \" \"",
      "                + Stream.of(1, 2, 3).reduce(Integer::sum));",
      "    }",
      "}",
    ],
    choices: ["16 Optional[6]", "16 6", "6 Optional[6]", "16 Optional[16]", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "16 Optional[6]" },
    explanation:
      "reduce(identity, accumulator) は初期値 10 から始めて要素を順に足し込むので 10 + 1 + 2 + 3 = 16 です。初期値を指定しない reduce(accumulator) は、ストリームが空だと結果を決められないため Optional を返し、ここでは Optional[6] と出力されます。初期値付きの形は「空なら初期値」という答えを持てるので値そのものを返せる、という違いです。なお初期値は本来「足しても結果を変えない値」（加算なら 0）であるべきで、並列ストリームでは初期値が部分ごとに何度も使われるため、10 のような値を渡すと結果が変わってしまいます。",
  },
  {
    id: 10306,
    topic: "streams",
    variantOf: "gold-streams-reduce",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "EmptyReduce",
    code: [
      "import java.util.stream.*;",
      "",
      "public class EmptyReduce {",
      "    public static void main(String[] args) {",
      "        System.out.println(Stream.<Integer>empty().reduce(0, Integer::sum) + \" \"",
      "                + Stream.<Integer>empty().reduce(Integer::sum) + \" \"",
      "                + Stream.of(\"a\", \"b\", \"c\").reduce(\"\", (x, y) -> y + x));",
      "    }",
      "}",
    ],
    choices: [
      "0 Optional.empty cba",
      "0 null cba",
      "0 Optional.empty abc",
      "null Optional.empty cba",
      "実行時に NoSuchElementException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "0 Optional.empty cba" },
    explanation:
      "初期値付きの reduce は、要素が 1 つも無ければ初期値 0 をそのまま返します。初期値なしの reduce は空のストリームに対して結果を作れないため、Optional.empty を返します（例外にはなりません）。3 つ目は累積値 x の前に新しい要素 y をつなぐので、\"\" → \"a\" → \"ba\" → \"cba\" となります。reduce の累積関数は (これまでの結果, 次の要素) の順に引数を受け取るという約束を押さえておくと、このような並びの問題を正しく追えます。",
  },
  {
    id: 10307,
    topic: "streams",
    variantOf: "gold-streams-grouping",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Grouping",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class Grouping {",
      "    public static void main(String[] args) {",
      "        Map<Character, Long> m = Stream.of(\"apple\", \"avocado\", \"banana\", \"blueberry\", \"cherry\")",
      "                .collect(Collectors.groupingBy(s -> s.charAt(0), TreeMap::new, Collectors.counting()));",
      "        System.out.println(m);",
      "    }",
      "}",
    ],
    choices: [
      "{a=2, b=2, c=1}",
      "{a=[apple, avocado], b=[banana, blueberry], c=[cherry]}",
      "{2=[a, b], 1=[c]}",
      "{a=1, b=1, c=1}",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{a=2, b=2, c=1}" },
    explanation:
      "groupingBy(分類関数, マップの生成, 下流コレクタ) は、分類関数の結果ごとに要素をまとめ、各グループに下流コレクタを適用します。ここでは先頭文字でグループ化し、counting() で各グループの件数（Long）を数えています。下流コレクタを省略すると各グループは要素の List になり、マップの生成を省略した場合のマップは型も順序も保証されません（現在の実装は HashMap）。第 2 引数に TreeMap::new を渡すことで、キーの昇順で並んだ結果が得られます。",
  },
  {
    id: 10308,
    topic: "streams",
    variantOf: "gold-streams-grouping",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "GroupJoin",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class GroupJoin {",
      "    public static void main(String[] args) {",
      "        Map<Integer, String> m = Stream.of(\"cat\", \"dog\", \"horse\", \"cow\", \"sheep\")",
      "                .collect(Collectors.groupingBy(String::length, TreeMap::new,",
      "                        Collectors.mapping(s -> s.substring(0, 1), Collectors.joining(\"/\"))));",
      "        System.out.println(m);",
      "    }",
      "}",
    ],
    choices: [
      "{3=c/d/c, 5=h/s}",
      "{3=[c, d, c], 5=[h, s]}",
      "{3=cat/dog/cow, 5=horse/sheep}",
      "{3=c/d, 5=h/s}",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{3=c/d/c, 5=h/s}" },
    explanation:
      "文字列の長さでグループ化し、各グループの要素を mapping で先頭 1 文字に変換してから、joining(\"/\") で連結しています。mapping は「グループの要素を変換してから、さらに別の下流コレクタに渡す」ためのコレクタで、groupingBy の下流でよく使われます。joining は重複を取り除かないので、長さ 3 のグループは c/d/c になります。Collectors はこのように入れ子にして組み立てることで、SQL の GROUP BY と集計関数に近い処理を宣言的に書けるよう設計されています。",
  },
  {
    id: 10309,
    topic: "streams",
    variantOf: "gold-streams-partitioning",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Partition",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class Partition {",
      "    public static void main(String[] args) {",
      "        Map<Boolean, List<Integer>> m = Stream.of(1, 3, 5)",
      "                .collect(Collectors.partitioningBy(n -> n % 2 == 0));",
      "        System.out.println(m);",
      "    }",
      "}",
    ],
    choices: ["{false=[1, 3, 5], true=[]}", "{false=[1, 3, 5]}", "{true=[], false=[1, 3, 5]}", "{true=[1, 3, 5]}", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "{false=[1, 3, 5], true=[]}" },
    explanation:
      "partitioningBy は述語の結果で要素を true と false の 2 グループに分けるコレクタで、該当する要素が無くても結果のマップには必ず true と false の両方のキーが含まれます。そのため偶数が 1 つも無くても true=[] が出力されます。groupingBy(n -> n % 2 == 0) で同じことをすると、要素が無いグループのキーは現れません。「2 分割」の結果を扱う側が、キーの有無を確認せずに get(true) / get(false) できるようにした設計です。",
  },
  {
    id: 10310,
    topic: "streams",
    variantOf: "gold-streams-tomap",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ToMapTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ToMapTest {",
      "    public static void main(String[] args) {",
      "        Map<Integer, String> m = Stream.of(\"aa\", \"bb\", \"c\")",
      "                .collect(Collectors.toMap(String::length, s -> s));",
      "        System.out.println(m);",
      "    }",
      "}",
    ],
    choices: [
      "実行時に IllegalStateException がスローされる",
      "{1=c, 2=bb}",
      "{1=c, 2=aa}",
      "{1=c, 2=aabb}",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "IllegalStateException" },
    explanation:
      "Collectors.toMap(キー関数, 値関数) は、キーが重複すると「Duplicate key」という IllegalStateException をスローします。\"aa\" と \"bb\" はどちらも長さ 2 なので、同じキーに 2 つの値が対応してしまいます。どちらを残すべきかはライブラリには判断できないため、黙って上書きせずに例外で知らせる設計です。キーが重複しうる場合は、第 3 引数にマージ関数（例: (a, b) -> a + b）を渡して、重複時の扱いを明示します。",
  },
  {
    id: 10311,
    topic: "streams",
    variantOf: "gold-streams-tomap",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ToMapMerge",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ToMapMerge {",
      "    public static void main(String[] args) {",
      "        Map<Integer, String> m = Stream.of(\"aa\", \"bb\", \"c\", \"dd\")",
      "                .collect(Collectors.toMap(String::length, s -> s, (a, b) -> b + a, TreeMap::new));",
      "        System.out.println(m);",
      "    }",
      "}",
    ],
    choices: [
      "{1=c, 2=ddbbaa}",
      "{1=c, 2=aabbdd}",
      "{1=c, 2=dd}",
      "{2=ddbbaa, 1=c}",
      "実行時に IllegalStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{1=c, 2=ddbbaa}" },
    explanation:
      "第 3 引数のマージ関数は、キーが重複したときに (既存の値, 新しい値) を受け取り、格納する値を決めます。(a, b) -> b + a は新しい値を前につなぐので、長さ 2 の値は \"aa\" → \"bbaa\" → \"ddbbaa\" と変化します。第 4 引数でマップの実装に TreeMap::new を指定しているため、キーは昇順に並びます。toMap で重複を許すかどうか、どう合成するかを明示させるのは、データの取りこぼしを呼び出し側の責任で判断させるためです。",
  },

  // ----------------------------------------------------------- 中間操作
  {
    id: 10312,
    topic: "streams",
    variantOf: "gold-streams-flatmap",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlatMapTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class FlatMapTest {",
      "    public static void main(String[] args) {",
      "        List<List<Integer>> nested = List.of(List.of(1, 2), List.of(3), List.of());",
      "        List<Integer> flat = nested.stream()",
      "                .flatMap(List::stream)",
      "                .map(n -> n * 10)",
      "                .collect(Collectors.toList());",
      "        System.out.println(flat);",
      "    }",
      "}",
    ],
    choices: ["[10, 20, 30]", "[[10, 20], [30], []]", "[10, 20, 30, 0]", "[30, 10, 0]", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[10, 20, 30]" },
    explanation:
      "flatMap は各要素をストリームに変換し、得られたストリームをすべて連結して 1 本のストリームにします。そのため入れ子のリストが平らになり、空のリストは要素を 1 つも生みません。map で List::stream を使うと「ストリームのストリーム」になってしまい、要素に n * 10 を適用することもできません。flatMap は「1 つの要素から 0 個以上の要素を生み出す」変換を表すもので、1 対 1 の変換である map とはこの点が異なります。",
  },
  {
    id: 10313,
    topic: "streams",
    variantOf: "gold-streams-distinct-sorted-limit",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Pipeline",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class Pipeline {",
      "    public static void main(String[] args) {",
      "        List<Integer> a = Stream.of(5, 3, 5, 1, 3)",
      "                .distinct()",
      "                .sorted(Comparator.reverseOrder())",
      "                .limit(2)",
      "                .collect(Collectors.toList());",
      "        List<Integer> b = Stream.iterate(1, n -> n * 2).skip(2).limit(3)",
      "                .collect(Collectors.toList());",
      "        System.out.println(a + \" \" + b);",
      "    }",
      "}",
    ],
    choices: [
      "[5, 3] [4, 8, 16]",
      "[5, 5] [4, 8, 16]",
      "[5, 3] [1, 2, 4]",
      "[1, 3] [4, 8, 16]",
      "[5, 3] [2, 4, 8]",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[5, 3] [4, 8, 16]" },
    explanation:
      "distinct で重複を除いた 5, 3, 1 を降順に並べ、limit(2) で先頭 2 つを取るので [5, 3] になります。Stream.iterate(1, n -> n * 2) は 1, 2, 4, 8, 16... と続く無限ストリームで、skip(2) で先頭の 1 と 2 を捨て、limit(3) で 3 つに打ち切るので [4, 8, 16] です。無限ストリームは limit のような打ち切りの操作が無いと終わりません。distinct や sorted は、それまでに流れた要素を覚えておく必要がある「状態を持つ中間操作」である点も押さえておきます。",
  },
  {
    id: 10314,
    topic: "streams",
    variantOf: "gold-streams-distinct-sorted-limit",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "IterateTest",
    code: [
      "import java.util.stream.*;",
      "",
      "public class IterateTest {",
      "    public static void main(String[] args) {",
      "        String s = Stream.iterate(1, n -> n <= 20, n -> n * 3)",
      "                .map(String::valueOf)",
      "                .collect(Collectors.joining(\",\", \"[\", \"]\"));",
      "        System.out.println(s);",
      "    }",
      "}",
    ],
    choices: ["[1,3,9]", "[1,3,9,27]", "[3,9]", "1,3,9", "[1, 3, 9]"],
    correct: [0],
    expected: { kind: "output", stdout: "[1,3,9]" },
    explanation:
      "3 引数の Stream.iterate(初期値, 継続条件, 次の値) は、for 文の (初期化; 条件; 更新) と同じ形で有限のストリームを作ります（Java 9 で追加）。1, 3, 9 は条件 n <= 20 を満たし、次の 27 で条件が偽になって終了します。joining(区切り文字, 接頭辞, 接尾辞) は要素を \",\" でつなぎ、全体を [ と ] で囲むので [1,3,9] です。2 引数の iterate と limit の組み合わせと違い、「何個取るか」ではなく「いつ止めるか」で終わりを決められます。",
  },

  // ------------------------------------------------------ プリミティブ型のストリーム
  {
    id: 10315,
    topic: "streams",
    variantOf: "gold-streams-primitive",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "IntStreams",
    code: [
      "import java.util.stream.*;",
      "",
      "public class IntStreams {",
      "    public static void main(String[] args) {",
      "        System.out.println(IntStream.range(1, 4).sum() + \" \"",
      "                + IntStream.rangeClosed(1, 4).average());",
      "    }",
      "}",
    ],
    choices: ["6 OptionalDouble[2.5]", "10 OptionalDouble[2.5]", "6 2.5", "6 OptionalDouble[2.0]", "10 Optional[2.5]"],
    correct: [0],
    expected: { kind: "output", stdout: "6 OptionalDouble[2.5]" },
    explanation:
      "IntStream.range(1, 4) は終端を含まない 1, 2, 3 で合計 6、rangeClosed(1, 4) は終端を含む 1〜4 で平均は 2.5 です。average() は要素が無い場合に平均を定義できないため OptionalDouble を返し、toString すると OptionalDouble[2.5] と表示されます。一方 sum() は空なら 0 と決められるので int をそのまま返します。IntStream などのプリミティブ特化ストリームは、ボクシングを避けつつ sum / average / summaryStatistics といった数値専用の集計を提供するためにあります。",
  },
  {
    id: 10316,
    topic: "streams",
    variantOf: "gold-streams-primitive",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "SumTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class SumTest {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = List.of(1, 2, 3);",
      "        int a = list.stream().mapToInt(Integer::intValue).sum();",
      "        long b = list.stream().count();",
      "        int c = list.stream().sum();",
      "        System.out.println(a + b + c);",
      "    }",
      "}",
    ],
    choices: [
      "9行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "8行目でコンパイルエラーになる",
      "コンパイルは成功し、15 と出力される",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 9 },
    explanation:
      "sum() は IntStream / LongStream / DoubleStream にだけあるメソッドで、Stream<Integer> にはありません。Stream<T> は要素が数値かどうかを型として知らないため、足し算という操作を提供できないのです。そのため 9行目はコンパイルエラーになり、7行目のように mapToInt でプリミティブのストリームに変換してから sum() を呼ぶ必要があります。count() はすべての Stream にあり、戻り値は long です。",
  },
  {
    id: 10317,
    topic: "streams",
    variantOf: "gold-streams-aggregate",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Stats",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class Stats {",
      "    public static void main(String[] args) {",
      "        IntSummaryStatistics st = IntStream.of(4, 8, 6).summaryStatistics();",
      "        System.out.println(st.getMin() + \" \" + st.getMax() + \" \"",
      "                + st.getAverage() + \" \" + st.getSum() + \" \" + st.getCount());",
      "    }",
      "}",
    ],
    choices: ["4 8 6.0 18 3", "4 8 6 18 3", "4 8 6.0 18.0 3", "8 4 6.0 18 3", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "4 8 6.0 18 3" },
    explanation:
      "summaryStatistics() は 1 回の走査で最小値・最大値・平均・合計・件数をまとめて求めます。getMin / getMax は int、getSum と getCount は long、getAverage は double を返すため、平均だけが 6.0 と小数で表示されます。min() や max() を別々に呼ぶとストリームを作り直して何度も走査することになり、そもそもストリームは再利用できません。複数の統計値が必要なときに、ストリームを 1 回だけ流して済ませるための仕組みです。",
  },
  {
    id: 10318,
    topic: "streams",
    variantOf: "gold-streams-aggregate",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MaxEmpty",
    code: [
      "import java.util.stream.*;",
      "",
      "public class MaxEmpty {",
      "    public static void main(String[] args) {",
      "        System.out.print(IntStream.of(3, 9, 4).max().getAsInt() + \" \");",
      "        System.out.print(IntStream.empty().max() + \" \");",
      "        System.out.println(IntStream.empty().max().getAsInt());",
      "    }",
      "}",
    ],
    choices: [
      "9 OptionalInt.empty と出力された後、NoSuchElementException がスローされる",
      "9 OptionalInt.empty 0",
      "9 0 0",
      "9 と出力された後、NoSuchElementException がスローされる",
      "9 OptionalInt.empty と出力された後、NullPointerException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NoSuchElementException", stdout: "9 OptionalInt.empty" },
    explanation:
      "IntStream の max() は、要素が無ければ最大値を決められないので OptionalInt を返します。値がある場合は getAsInt() で 9 が取り出せ、空の場合の OptionalInt は OptionalInt.empty と表示されます。空の OptionalInt に getAsInt() を呼ぶと NoSuchElementException になります。「0 を返す」としなかったのは、0 が本当の最大値なのか要素が無いのかを区別できなくなるからです。空の可能性があるなら orElse(0) などで既定値を明示します。",
  },

  // ------------------------------------------------------------- 探索・マッチング
  {
    id: 10319,
    topic: "streams",
    variantOf: "gold-streams-match",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MatchEmpty",
    code: [
      "import java.util.stream.*;",
      "",
      "public class MatchEmpty {",
      "    public static void main(String[] args) {",
      "        System.out.println(Stream.empty().allMatch(x -> false) + \" \"",
      "                + Stream.empty().anyMatch(x -> true) + \" \"",
      "                + Stream.empty().noneMatch(x -> true));",
      "    }",
      "}",
    ],
    choices: ["true false true", "false false false", "false true false", "true true true", "実行時に例外がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "true false true" },
    explanation:
      "空のストリームに対して allMatch は true、anyMatch は false、noneMatch は true を返します。allMatch は「条件を満たさない要素が 1 つも無い」、noneMatch は「条件を満たす要素が 1 つも無い」という意味なので、要素が無ければ条件の内容にかかわらず成り立ちます（論理学でいう空虚な真）。anyMatch は「条件を満たす要素が少なくとも 1 つある」なので偽です。入力が空のときに「全件 OK」と判定されてしまうことがあるため、バリデーションで allMatch を使うときは空の場合の扱いを別途考える必要があります。",
  },
  {
    id: 10320,
    topic: "streams",
    variantOf: "gold-streams-match",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MatchPeek",
    code: [
      "import java.util.stream.*;",
      "",
      "public class MatchPeek {",
      "    public static void main(String[] args) {",
      "        boolean r = Stream.of(2, 4, 5, 6)",
      "                .peek(System.out::print)",
      "                .allMatch(n -> n % 2 == 0);",
      "        System.out.println(\" \" + r);",
      "    }",
      "}",
    ],
    choices: ["245 false", "2456 false", "2456 true", "24 false", "5 false"],
    correct: [0],
    expected: { kind: "output", stdout: "245 false" },
    explanation:
      "allMatch は短絡終端操作で、条件を満たさない要素が見つかった時点で false と確定し、残りの要素を処理しません。2 と 4 は偶数なので処理が続き、5 で条件を満たさないことが分かって打ち切られるため、6 は peek に到達しません。同様に anyMatch は条件を満たす要素が見つかった時点で、noneMatch は満たす要素が見つかった時点で終了します。結果を決めるのに必要な要素だけを調べるので、先頭付近で結果が決まれば大量の要素があっても高速に終わります。",
  },

  // --------------------------------------------------------------- Optional
  {
    id: 10321,
    topic: "streams",
    variantOf: "gold-streams-optional",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OptionalChain",
    code: [
      "import java.util.*;",
      "",
      "public class OptionalChain {",
      "    public static void main(String[] args) {",
      '        Optional<String> o = Optional.of("java");',
      "        int a = o.map(String::length).filter(n -> n > 5).orElse(0);",
      '        String b = Optional.ofNullable((String) null).map(String::toUpperCase).orElse("none");',
      '        System.out.println(a + " " + b + " " + o.isPresent());',
      "    }",
      "}",
    ],
    choices: ["0 none true", "4 none true", "0 null true", "4 NONE true", "実行時に NullPointerException がスローされる"],
    correct: [0],
    expected: { kind: "output", stdout: "0 none true" },
    explanation:
      "\"java\" を map で長さ 4 に変換したあと、filter の条件 n > 5 を満たさないので空の Optional になり、orElse(0) で 0 になります。ofNullable(null) は空の Optional を作り、空の Optional に対する map は関数を呼ばずに空のまま返すため、NullPointerException は起きずに orElse の \"none\" が使われます。Optional は「値が無いかもしれない」ことを型で表し、null チェックの if 文を map / filter / orElse の連鎖に置き換えるための型です。元の o は不変なので、処理後も isPresent() は true です。",
  },
  {
    id: 10322,
    topic: "streams",
    variantOf: "gold-streams-optional",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OptionalNull",
    code: [
      "import java.util.*;",
      "",
      "public class OptionalNull {",
      "    public static void main(String[] args) {",
      "        String name = null;",
      '        System.out.print(Optional.ofNullable(name).isEmpty() + " ");',
      "        Optional<String> o = Optional.of(name);",
      "        System.out.println(o.isPresent());",
      "    }",
      "}",
    ],
    choices: [
      "true と出力された後、NullPointerException がスローされる",
      "true false",
      "false false",
      "true true",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "true" },
    explanation:
      "Optional.ofNullable は null を受け取ると空の Optional を返すので、isEmpty() は true です（isEmpty は Java 11 で追加）。一方 Optional.of は「必ず値がある」ことを前提とするファクトリで、null を渡すとその場で NullPointerException をスローします。of と ofNullable を分けているのは、null になるはずのない値が null だった場合に、後で空の Optional として紛れ込ませず即座に発見できるようにするためです。null の可能性がある値を包むときだけ ofNullable を使います。",
  },
  {
    id: 10323,
    topic: "streams",
    variantOf: "gold-streams-optional-orelse",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OrElseTest",
    code: [
      "import java.util.*;",
      "",
      "public class OrElseTest {",
      "    static String make() {",
      '        System.out.print("make ");',
      '        return "B";',
      "    }",
      "",
      "    public static void main(String[] args) {",
      '        String x = Optional.of("A").orElse(make());',
      '        String y = Optional.of("A").orElseGet(OrElseTest::make);',
      "        System.out.println(x + y);",
      "    }",
      "}",
    ],
    choices: ["make AA", "AA", "make make AA", "make AB", "BA"],
    correct: [0],
    expected: { kind: "output", stdout: "make AA" },
    explanation:
      "orElse の引数は通常のメソッド引数なので、Optional に値があるかどうかにかかわらず、呼び出す前に make() が評価されます。そのため値が \"A\" で既定値が使われなくても make が 1 回出力されます。orElseGet は Supplier を受け取り、値が無いときだけそれを呼ぶので、make() は実行されません。既定値の生成に DB アクセスやオブジェクトの生成など重い処理・副作用を伴う場合は、orElseGet を使って必要なときだけ実行させるのが安全です。",
  },

  // --------------------------------------------------------------- 並列ストリーム
  {
    id: 10324,
    topic: "streams",
    variantOf: "gold-streams-parallel-order",
    question: "次のコードを実行した場合に、必ず得られる出力はどれか。1つ選びなさい。",
    className: "ParallelOrder",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ParallelOrder {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = List.of(1, 2, 3, 4);",
      "        list.parallelStream().map(n -> n * n).forEachOrdered(System.out::print);",
      "        List<Integer> squares = list.parallelStream().map(n -> n * n)",
      "                .collect(Collectors.toList());",
      "        System.out.println(\" \" + squares);",
      "    }",
      "}",
    ],
    choices: [
      "14916 [1, 4, 9, 16]",
      "出力される数字の順序は実行するたびに変わりうる",
      "14916 と出力されるが、リストの要素の順序は実行するたびに変わりうる",
      "16941 [16, 9, 4, 1]",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "14916 [1, 4, 9, 16]" },
    explanation:
      "並列ストリームでは要素が複数のスレッドで同時に処理されるため、forEach で出力すると順序は保証されません。しかし forEachOrdered は、元のデータ源の出現順序（List なら先頭から）に従ってアクションを実行することを保証します。collect(Collectors.toList()) も、並列に処理した部分結果を出現順序どおりに結合するので、結果のリストは [1, 4, 9, 16] になります。並列化で順序が崩れるのは副作用の実行タイミングであり、正しく書かれたリダクションの結果は順次実行と同じになるように設計されています。",
  },
  {
    id: 10325,
    topic: "streams",
    variantOf: "gold-streams-parallel-order",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ParallelFlag",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ParallelFlag {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = List.of(1, 2, 3);",
      "        Stream<Integer> a = list.parallelStream();",
      "        Stream<Integer> b = list.stream().parallel().filter(n -> n > 1).sequential();",
      "        System.out.println(a.isParallel() + \" \" + b.isParallel());",
      "    }",
      "}",
    ],
    choices: ["true false", "true true", "false false", "false true", "コンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "true false" },
    explanation:
      "parallelStream() は最初から並列のストリームを返すので a.isParallel() は true です。parallel() / sequential() はストリーム全体の実行方式を切り替えるフラグで、パイプラインの途中で呼んでも「ここから並列」にはならず、最後に呼んだものがパイプライン全体に適用されます。そのため parallel() の後に sequential() を呼んだ b は順次ストリームになり false です。並列にするかどうかは処理の一部分ではなく、終端操作を実行するときのパイプライン全体の性質として決まります。",
  },
  {
    id: 10326,
    topic: "streams",
    variantOf: "gold-streams-tolist",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ToListTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ToListTest {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = Stream.of(3, 1, 2).sorted().toList();",
      "        System.out.print(list + \" \");",
      "        list.add(4);",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[1, 2, 3] と出力された後、UnsupportedOperationException がスローされる",
      "[1, 2, 3] [1, 2, 3, 4]",
      "[3, 1, 2] [3, 1, 2, 4]",
      "6行目でコンパイルエラーになる",
      "[1, 2, 3] と出力された後、IllegalStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedOperationException", stdout: "[1, 2, 3]" },
    explanation:
      "Java 16 で追加された Stream.toList() は、変更不可のリストを返します。そのため sorted() で並べ替えた [1, 2, 3] は出力できますが、add を呼ぶと UnsupportedOperationException がスローされます。collect(Collectors.toList()) は返すリストの変更可否を仕様で保証しておらず（現在の実装は ArrayList）、どちらに頼るべきか曖昧でした。toList() は「ストリームの結果は読み取り専用の値として扱う」ことを明確にしたメソッドで、結果を変更したいなら new ArrayList<>(...) でコピーするか Collectors.toCollection(ArrayList::new) を使います。",
  },
  {
    id: 10327,
    topic: "streams",
    variantOf: "gold-streams-collectors-numeric",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "Averaging",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class Averaging {",
      "    record Item(String category, int price) {}",
      "",
      "    public static void main(String[] args) {",
      "        List<Item> items = List.of(new Item(\"food\", 100), new Item(\"food\", 250),",
      "                new Item(\"book\", 800));",
      "        Map<String, Double> avg = items.stream()",
      "                .collect(Collectors.groupingBy(Item::category, TreeMap::new,",
      "                        Collectors.averagingInt(Item::price)));",
      "        int total = items.stream().collect(Collectors.summingInt(Item::price));",
      "        System.out.println(avg + \" \" + total);",
      "    }",
      "}",
    ],
    choices: [
      "{book=800.0, food=175.0} 1150",
      "{book=800, food=175} 1150",
      "{food=175.0, book=800.0} 1150",
      "{book=800.0, food=175.0} 1150.0",
      "コンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{book=800.0, food=175.0} 1150" },
    explanation:
      "averagingInt は要素を int として取り出して平均を求めるコレクタで、結果は常に Double です（整数どうしの平均でも小数になりうるため）。summingInt は合計を Integer で返すので 1150 と表示されます。groupingBy の下流に置くとグループごとの平均が求まり、TreeMap::new を指定しているのでキーは book, food の辞書順に並びます。集計の目的に応じて counting（Long）、summingInt（Integer）、averagingInt（Double）と戻り値の型が異なる点を押さえておくと、代入先の型の誤りに気付けます。",
  },
];
