import type { GoldQuestion } from "../quizTypes";

/**
 * Gold SE 17（1Z0-826-JPN）: Java ストリーム API の追加問題（id 10328-10399）。
 * ステートフルな中間操作、takeWhile / dropWhile、Collectors の組み合わせ、Optional の変換など。
 */
export const goldStreamsQuestions2: GoldQuestion[] = [
  // ------------------------------------------------------------ ステートフルな中間操作
  {
    id: 10328,
    topic: "streams",
    variantOf: "gold-streams-stateful-op",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SortedPeek",
    code: [
      "import java.util.stream.*;",
      "",
      "public class SortedPeek {",
      "    public static void main(String[] args) {",
      "        Stream.of(3, 1, 2)",
      "              .peek(n -> System.out.print(\"a\" + n + \" \"))",
      "              .sorted()",
      "              .forEach(n -> System.out.print(\"b\" + n + \" \"));",
      "        System.out.println();",
      "    }",
      "}",
    ],
    choices: [
      "a3 a1 a2 b1 b2 b3",
      "a3 b3 a1 b1 a2 b2",
      "a1 b1 a2 b2 a3 b3",
      "a3 a1 a2 b3 b1 b2",
      "b1 b2 b3",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "a3 a1 a2 b1 b2 b3" },
    explanation:
      "ストリームの要素は通常 1 つずつパイプライン全体を流れます（a3 b3 a1 b1 … の順）。しかし sorted は、すべての要素を見るまで最初の要素を決められない「ステートフル」な中間操作なので、上流の要素をいったんすべて受け取って並べ替えてから下流に流します。そのため peek の出力が 3 つ先に並び、その後に並べ替えた順で forEach が実行されます。sorted や distinct はこのように要素をため込むため、無限ストリームに対して使うと終わらず、巨大なストリームではメモリを消費する点に注意します。",
  },
  {
    id: 10329,
    topic: "streams",
    variantOf: "gold-streams-stateful-op",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "LimitPeek",
    code: [
      "import java.util.stream.*;",
      "",
      "public class LimitPeek {",
      "    public static void main(String[] args) {",
      "        long n = Stream.of(\"d\", \"a\", \"c\", \"b\")",
      "                .peek(s -> System.out.print(s))",
      "                .filter(s -> !s.equals(\"c\"))",
      "                .limit(2)",
      "                .count();",
      "        System.out.println(\" \" + n);",
      "    }",
      "}",
    ],
    choices: ["da 2", "dacb 2", "dac 2", "da 3", " 2"],
    correct: [0],
    expected: { kind: "output", stdout: "da 2" },
    explanation:
      "limit(2) は 2 つの要素を下流へ渡した時点で上流からの取り出しを止める「短絡操作」です。d と a が filter を通過して 2 件になった時点でストリームは打ち切られ、c と b は peek にすら到達しません。そのため出力は da で、count は 2 です。なお Java 9 以降の count は、要素数がストリームの元から直接わかる場合は中間操作を実行せずに数を返すことがありますが、ここでは filter があるので要素を実際に流して数えています。peek は要素の流れを観察するデバッグ用の操作で、処理の結果を peek の副作用に頼ってはいけない理由もここにあります。",
  },

  // ------------------------------------------------------------ takeWhile / dropWhile
  {
    id: 10330,
    topic: "streams",
    variantOf: "gold-streams-takewhile",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TakeDrop",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class TakeDrop {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = List.of(1, 3, 6, 2, 8, 5);",
      "        List<Integer> a = list.stream().takeWhile(n -> n < 5).toList();",
      "        List<Integer> b = list.stream().dropWhile(n -> n < 5).toList();",
      "        List<Integer> c = list.stream().filter(n -> n < 5).toList();",
      "        System.out.println(a + \" \" + b + \" \" + c);",
      "    }",
      "}",
    ],
    choices: [
      "[1, 3] [6, 2, 8, 5] [1, 3, 2]",
      "[1, 3, 2] [6, 8, 5] [1, 3, 2]",
      "[1, 3] [6, 8, 5] [1, 3, 2]",
      "[1, 3, 2] [6, 2, 8, 5] [1, 3]",
      "[1, 3] [2, 8, 5] [1, 3, 2]",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 3] [6, 2, 8, 5] [1, 3, 2]" },
    explanation:
      "takeWhile は先頭から条件を満たす間だけ要素を取り、最初に条件を満たさない要素（6）が来た時点で打ち切ります。後ろにある 2 は条件を満たしますが取られません。dropWhile は逆に、条件を満たす間の先頭部分を捨て、6 以降をすべて（条件を満たす 2 も含めて）残します。filter は全要素を 1 つずつ判定するので、条件を満たす 1・3・2 が残ります。takeWhile / dropWhile は「並び順に意味がある」データ（ソート済みのデータやログの時系列など）の先頭部分を扱うための操作で、打ち切れるので無限ストリームにも使えます。",
  },
  {
    id: 10331,
    topic: "streams",
    variantOf: "gold-streams-takewhile",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "IterateTake",
    code: [
      "import java.util.stream.*;",
      "",
      "public class IterateTake {",
      "    public static void main(String[] args) {",
      "        String a = Stream.iterate(1, n -> n * 3)",
      "                .takeWhile(n -> n < 100)",
      "                .map(String::valueOf)",
      "                .collect(Collectors.joining(\",\"));",
      "        String b = IntStream.iterate(1, n -> n < 10, n -> n + 4)",
      "                .mapToObj(String::valueOf)",
      "                .collect(Collectors.joining(\",\"));",
      "        System.out.println(a + \" \" + b);",
      "    }",
      "}",
    ],
    choices: [
      "1,3,9,27,81 1,5,9",
      "1,3,9,27,81,243 1,5,9",
      "1,3,9,27,81 1,5,9,13",
      "3,9,27,81 5,9",
      "何も出力されず、プログラムが終了しない",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1,3,9,27,81 1,5,9" },
    explanation:
      "Stream.iterate(seed, f) は seed、f(seed)、f(f(seed)) … と無限に続くストリームを作りますが、takeWhile が 243（100 以上）に出会った時点で打ち切るので、1,3,9,27,81 で終わります。Java 9 で追加された 3 引数の iterate(seed, hasNext, next) は for 文と同じ形で、条件 n < 10 を満たす間だけ 1, 5, 9 を生成し、13 は条件を満たさないので含まれません。無限ストリームは短絡操作（takeWhile、limit、findFirst など）と組み合わせて初めて終了するので、終了条件をどこに置くかを必ず確認します。",
  },

  // ------------------------------------------------------------ joining
  {
    id: 10332,
    topic: "streams",
    variantOf: "gold-streams-joining",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "JoinTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class JoinTest {",
      "    public static void main(String[] args) {",
      "        String a = Stream.of(\"x\", \"y\").collect(Collectors.joining(\"-\", \"[\", \"]\"));",
      "        String b = Stream.<String>empty().collect(Collectors.joining(\"-\", \"[\", \"]\"));",
      "        String c = String.join(\"/\", List.of(\"p\", \"q\", \"r\"));",
      "        System.out.println(a + b + c);",
      "    }",
      "}",
    ],
    choices: ["[x-y][]p/q/r", "[x-y]p/q/r", "[x]-[y][]p/q/r", "[x-y]nullp/q/r", "7行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "[x-y][]p/q/r" },
    explanation:
      "Collectors.joining(区切り文字, 接頭辞, 接尾辞) は、要素の間に区切り文字を入れ、全体の前後に接頭辞と接尾辞を 1 回ずつ付けます。要素ごとに括弧が付くわけではないので [x-y] です。要素が 1 つも無い場合でも接頭辞と接尾辞は付くので、空のストリームからは [] ができます（null や空文字列にはなりません）。String.join は既にあるコレクションを連結する簡便なメソッドで、区切り文字だけを指定できます。空の結果でも括弧が付くのは、JSON 風の出力を組み立てるときに便利な仕様です。",
  },

  // ------------------------------------------------------------ groupingBy の下流コレクタ
  {
    id: 10333,
    topic: "streams",
    variantOf: "gold-streams-grouping-downstream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "GroupMapping",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class GroupMapping {",
      "    record Book(String genre, String title, int pages) {}",
      "",
      "    public static void main(String[] args) {",
      "        List<Book> books = List.of(",
      "                new Book(\"novel\", \"A\", 300),",
      "                new Book(\"tech\", \"B\", 500),",
      "                new Book(\"novel\", \"C\", 200));",
      "        Map<String, List<String>> titles = books.stream()",
      "                .collect(Collectors.groupingBy(Book::genre, TreeMap::new,",
      "                        Collectors.mapping(Book::title, Collectors.toList())));",
      "        Map<String, Integer> pages = books.stream()",
      "                .collect(Collectors.groupingBy(Book::genre, TreeMap::new,",
      "                        Collectors.summingInt(Book::pages)));",
      "        System.out.println(titles + \" \" + pages);",
      "    }",
      "}",
    ],
    choices: [
      "{novel=[A, C], tech=[B]} {novel=500, tech=500}",
      "{novel=[A, C], tech=[B]} {novel=300, tech=500}",
      "{tech=[B], novel=[A, C]} {tech=500, novel=500}",
      "{novel=[Book[genre=novel, title=A, pages=300], Book[genre=novel, title=C, pages=200]], tech=[Book[genre=tech, title=B, pages=500]]} {novel=500, tech=500}",
      "13行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{novel=[A, C], tech=[B]} {novel=500, tech=500}" },
    explanation:
      "groupingBy の 3 引数版は（分類関数, マップの生成方法, 下流コレクタ）を取ります。TreeMap::new を指定したのでキーは辞書順に並び、下流コレクタで「グループごとに何を集めるか」を決められます。mapping(Book::title, toList()) は要素を題名に変換してからリストにし、summingInt(Book::pages) はページ数を合計します（novel は 300 + 200 = 500）。下流コレクタを省略すると要素そのもののリストになるので、変換や集計をグループ化と同時に済ませたいときに下流コレクタを使います。",
  },
  {
    id: 10334,
    topic: "streams",
    variantOf: "gold-streams-grouping-downstream",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "GroupCount",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class GroupCount {",
      "    public static void main(String[] args) {",
      "        Map<Character, Long> counts = Stream.of(\"apple\", \"avocado\", \"banana\", \"blueberry\", \"cherry\")",
      "                .collect(Collectors.groupingBy(s -> s.charAt(0), TreeMap::new, Collectors.counting()));",
      "        Map<Boolean, Set<Integer>> lengths = Stream.of(\"apple\", \"avocado\", \"banana\", \"blueberry\", \"cherry\")",
      "                .collect(Collectors.partitioningBy(s -> s.length() > 6,",
      "                        Collectors.mapping(String::length, Collectors.toCollection(TreeSet::new))));",
      "        System.out.println(counts + \" \" + lengths);",
      "    }",
      "}",
    ],
    choices: [
      "{a=2, b=2, c=1} {false=[5, 6], true=[7, 9]}",
      "{a=2, b=2, c=1} {false=[5, 6, 6], true=[7, 9]}",
      "{a=2, b=2, c=1} {true=[7, 9], false=[5, 6]}",
      "{a=2, b=2, c=1} {true=[7, 9]}",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{a=2, b=2, c=1} {false=[5, 6], true=[7, 9]}" },
    explanation:
      "counting() は各グループの件数を Long で数える下流コレクタで、先頭の文字ごとに a=2, b=2, c=1 となります。partitioningBy は条件の真偽で 2 つに分け、結果のマップには false と true の両方のキーが（該当が無くても）必ず含まれ、false、true の順に表示されます。下流コレクタに mapping と toCollection(TreeSet::new) を組み合わせたので、長さが TreeSet に集められ、banana と cherry の 6 は重複として 1 つにまとまります。下流コレクタを入れ子にすることで、変換・集約・格納先の選択を 1 回の collect で表現できます。",
  },

  // ------------------------------------------------------------ collectingAndThen / teeing
  {
    id: 10335,
    topic: "streams",
    variantOf: "gold-streams-collector-finisher",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FinisherTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class FinisherTest {",
      "    public static void main(String[] args) {",
      "        List<String> list = Stream.of(\"b\", \"a\")",
      "                .collect(Collectors.collectingAndThen(Collectors.toList(),",
      "                        Collections::unmodifiableList));",
      "        System.out.print(list + \" \");",
      "        list.add(\"c\");",
      "        System.out.println(list);",
      "    }",
      "}",
    ],
    choices: [
      "[b, a] と出力された後、UnsupportedOperationException がスローされる",
      "[b, a] [b, a, c]",
      "[a, b] と出力された後、UnsupportedOperationException がスローされる",
      "[b, a] [b, a]",
      "8行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "UnsupportedOperationException", stdout: "[b, a]" },
    explanation:
      "collectingAndThen(下流コレクタ, 仕上げの関数) は、下流コレクタで集めた結果に最後に関数を適用するコレクタです。ここでは toList() で作ったリストを Collections::unmodifiableList で変更不可のビューに包んで返すので、add を呼ぶと UnsupportedOperationException になります。Collectors.toList() 自体は変更可能性を保証しない（実装上は ArrayList）ため、変更不可にしたい意図をはっきり示すのに使われてきた書き方です。Java 10 以降は Collectors.toUnmodifiableList()、Java 16 以降は Stream.toList() でも変更不可のリストを得られます。",
  },
  {
    id: 10336,
    topic: "streams",
    variantOf: "gold-streams-collector-finisher",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "TeeingTest",
    code: [
      "import java.util.stream.*;",
      "",
      "public class TeeingTest {",
      "    public static void main(String[] args) {",
      "        String r = Stream.of(4, 8, 6)",
      "                .collect(Collectors.teeing(",
      "                        Collectors.summingInt(n -> n),",
      "                        Collectors.counting(),",
      "                        (sum, count) -> sum + \"/\" + count));",
      "        System.out.println(r);",
      "    }",
      "}",
    ],
    choices: ["18/3", "18.0/3", "6.0", "3/18", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "18/3" },
    explanation:
      "Collectors.teeing（Java 12 で追加）は、各要素を 2 つの下流コレクタの両方に渡し、最後に 2 つの結果を関数で 1 つにまとめます。summingInt は合計 18（Integer）を、counting は件数 3（Long）を返し、結合関数で \"18/3\" という文字列にしています。ストリームは一度しか使えないので、合計と件数のように 2 種類の集計を 1 回の走査で得たいときに便利です。平均値を自前で計算する、最小値と最大値を同時に求める、といった用途に使われます。",
  },

  // ------------------------------------------------------------ Optional の変換
  {
    id: 10337,
    topic: "streams",
    variantOf: "gold-streams-optional-map",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OptionalChain",
    code: [
      "import java.util.*;",
      "",
      "public class OptionalChain {",
      "    static Optional<String> find(String key) {",
      "        return key.startsWith(\"k\") ? Optional.of(key + \"-value\") : Optional.empty();",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        String a = Optional.of(\"key\").flatMap(OptionalChain::find).map(String::length)",
      "                .map(String::valueOf).orElse(\"none\");",
      "        String b = Optional.of(\"id\").flatMap(OptionalChain::find).map(String::toUpperCase)",
      "                .orElse(\"none\");",
      "        String c = Optional.of(\"kiwi\").filter(s -> s.length() > 5).orElse(\"short\");",
      "        System.out.println(a + \" \" + b + \" \" + c);",
      "    }",
      "}",
    ],
    choices: ["9 none short", "9 NONE short", "Optional[9] none short", "9 none kiwi", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "9 none short" },
    explanation:
      "Optional.map は中身があるときだけ関数を適用し、結果を Optional に包み直します。関数自体が Optional を返す場合に map を使うと Optional<Optional<String>> になってしまうので、flatMap を使って入れ子を平らにします。a は \"key-value\" の長さ 9 を文字列にして \"9\" です。b は find が空の Optional を返すので、その後の map は実行されず orElse の \"none\" になります（大文字化もされません）。c は filter の条件を満たさないので空になり \"short\" です。空の場合の処理を途中で書かずに最後の orElse に集約できるのが、Optional を連鎖させる利点です。",
  },
  {
    id: 10338,
    topic: "streams",
    variantOf: "gold-streams-optional-map",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "OptionalOfNull",
    code: [
      "import java.util.*;",
      "",
      "public class OptionalOfNull {",
      "    public static void main(String[] args) {",
      "        String name = null;",
      "        Optional<String> a = Optional.ofNullable(name);",
      "        System.out.print(a.isPresent() + \" \" + a.map(String::length).orElse(-1) + \" \");",
      "        Optional<String> b = Optional.of(name);",
      "        System.out.println(b.isEmpty());",
      "    }",
      "}",
    ],
    choices: [
      "false -1 と出力された後、NullPointerException がスローされる",
      "false -1 true",
      "false 0 true",
      "7行目で NullPointerException がスローされる",
      "false -1 と出力された後、NoSuchElementException がスローされる",
    ],
    correct: [0],
    expected: { kind: "exception", type: "NullPointerException", stdout: "false -1" },
    explanation:
      "Optional.ofNullable は null を受け取ると空の Optional を返すので、isPresent は false、map は実行されず orElse の -1 になります。一方 Optional.of は「値が必ずある」ことを前提にしたファクトリで、null を渡すとその場で NullPointerException をスローします。値が無い可能性があるなら ofNullable、無いはずがないなら of と使い分けることで、「本来ありえない null」を早い段階で検出できます。Optional は null の代わりに「値が無いこと」を型で表すための仕組みなので、Optional 自体に null を入れることはできません。",
  },

  // ------------------------------------------------------------ reduce の 3 引数版
  {
    id: 10339,
    topic: "streams",
    variantOf: "gold-streams-reduce-combiner",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ReduceCombiner",
    code: [
      "import java.util.stream.*;",
      "",
      "public class ReduceCombiner {",
      "    public static void main(String[] args) {",
      "        int total = Stream.of(\"ab\", \"cde\", \"f\")",
      "                .reduce(0, (sum, s) -> sum + s.length(), Integer::sum);",
      "        String joined = Stream.of(\"ab\", \"cde\", \"f\")",
      "                .reduce(\"\", (acc, s) -> acc + s.charAt(0));",
      "        System.out.println(total + \" \" + joined);",
      "    }",
      "}",
    ],
    choices: ["6 acf", "3 acf", "6 abcdef", "6 fca", "6行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "6 acf" },
    explanation:
      "2 引数の reduce(identity, accumulator) は、結果の型が要素の型と同じ場合にしか使えません（BinaryOperator<T> を取るため）。String のストリームから int の合計を作りたい場合は、3 引数の reduce(identity, accumulator, combiner) を使います。accumulator は「途中結果（Integer）と要素（String）」から新しい途中結果を作り、combiner は並列処理で分割された途中結果同士をまとめるために使われます（逐次ストリームでは呼ばれません）。文字数の合計は 2 + 3 + 1 = 6 です。8行目は結果も String なので 2 引数版で書け、各要素の先頭文字をつないで acf になります。実務では mapToInt(String::length).sum() と書くほうが読みやすいでしょう。",
  },

  // ------------------------------------------------------------ プリミティブ・ストリームの結果の型
  {
    id: 10340,
    topic: "streams",
    variantOf: "gold-streams-primitive-result",
    question: "次のコードをコンパイルした場合、コンパイルエラーになる行はどれか。1つ選びなさい。",
    className: "AverageType",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class AverageType {",
      "    public static void main(String[] args) {",
      "        int sum = IntStream.of(1, 2, 3).sum();",
      "        OptionalInt max = IntStream.of(1, 2, 3).max();",
      "        double avg = IntStream.of(1, 2, 3).average();",
      "        long count = IntStream.of(1, 2, 3).count();",
      "        System.out.println(sum + \" \" + max.getAsInt() + \" \" + count);",
      "    }",
      "}",
    ],
    choices: [
      "8行目でコンパイルエラーになる",
      "6行目でコンパイルエラーになる",
      "7行目でコンパイルエラーになる",
      "9行目でコンパイルエラーになる",
      "コンパイルは成功する",
    ],
    correct: [0],
    expected: { kind: "compile-error", line: 8 },
    explanation:
      "IntStream の終端操作は、空のストリームに対して意味のある値を返せるかどうかで戻り値の型が変わります。sum は空なら 0 と定義できるので int、count は long を返します。一方 max や average は空のストリームでは値が存在しないため、OptionalInt / OptionalDouble を返します。average() の結果を double 型の変数に代入する8行目は型が合わずコンパイルエラーです。average().orElse(0.0) や getAsDouble() で値を取り出します。空の場合を型で強制的に意識させるのが Optional 系の型の役割です。",
  },
  {
    id: 10341,
    topic: "streams",
    variantOf: "gold-streams-primitive-result",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "StatsTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class StatsTest {",
      "    public static void main(String[] args) {",
      "        IntSummaryStatistics s = Stream.of(\"aa\", \"b\", \"cccc\")",
      "                .mapToInt(String::length)",
      "                .summaryStatistics();",
      "        IntSummaryStatistics empty = IntStream.empty().summaryStatistics();",
      "        System.out.println(s.getMin() + \" \" + s.getMax() + \" \" + s.getAverage() + \" \"",
      "                + empty.getCount() + \" \" + empty.getAverage());",
      "    }",
      "}",
    ],
    choices: [
      "1 4 2.3333333333333335 0 0.0",
      "1 4 2 0 0.0",
      "1 4 2.3333333333333335 0 NaN",
      "1 4 2.3333333333333335 と出力された後、NoSuchElementException がスローされる",
      "8行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "1 4 2.3333333333333335 0 0.0" },
    explanation:
      "summaryStatistics() は件数・合計・最小・最大・平均を 1 回の走査でまとめて求めます。長さは 2, 1, 4 なので最小 1、最大 4、平均は 7 / 3 = 2.333…（double）です。IntSummaryStatistics は Optional を使わずに空の場合の値を決めており、件数は 0、平均は 0.0 になります（最小値は Integer.MAX_VALUE、最大値は Integer.MIN_VALUE）。average() が OptionalDouble を返すのとは扱いが異なるので、空になりうるデータでは件数を確認してから値を使います。",
  },

  // ------------------------------------------------------------ Comparator による並べ替え
  {
    id: 10342,
    topic: "streams",
    variantOf: "gold-streams-sorted-comparator",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "SortPeople",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class SortPeople {",
      "    record Person(String name, int age) {}",
      "",
      "    public static void main(String[] args) {",
      "        String r = Stream.of(new Person(\"Ken\", 30), new Person(\"Amy\", 25), new Person(\"Bob\", 30))",
      "                .sorted(Comparator.comparingInt(Person::age).reversed()",
      "                        .thenComparing(Person::name, Comparator.reverseOrder()))",
      "                .map(Person::name)",
      "                .collect(Collectors.joining(\" \"));",
      "        System.out.println(r);",
      "    }",
      "}",
    ],
    choices: ["Ken Bob Amy", "Bob Ken Amy", "Amy Bob Ken", "Amy Ken Bob", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "Ken Bob Amy" },
    explanation:
      "comparingInt(Person::age).reversed() で年齢の降順に並べ、年齢が同じ場合は thenComparing の第 2 引数 Comparator.reverseOrder() によって名前の降順で並べます。30 歳の Ken と Bob は名前の降順で Ken → Bob、その後に 25 歳の Amy が来ます。reversed() はそれまでに組み立てた比較全体を反転させるので、thenComparing の後に reversed() を付けると 2 つ目の条件まで反転してしまいます。条件ごとに向きを変えたい場合は、このように条件ごとに Comparator を指定するのが確実です。",
  },

  // ------------------------------------------------------------ 配列からのストリーム
  {
    id: 10343,
    topic: "streams",
    variantOf: "gold-streams-array-source",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ArrayStream",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ArrayStream {",
      "    public static void main(String[] args) {",
      "        int[] nums = {5, 6, 7, 8};",
      "        long a = Stream.of(nums).count();",
      "        long b = Arrays.stream(nums).count();",
      "        int c = Arrays.stream(nums, 1, 3).sum();",
      "        System.out.println(a + \" \" + b + \" \" + c);",
      "    }",
      "}",
    ],
    choices: ["1 4 13", "4 4 13", "4 4 18", "1 4 18", "7行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "1 4 13" },
    explanation:
      "Stream.of(T... values) の T は参照型なので、int[] を渡すと配列そのものが 1 つの要素になり、Stream<int[]> の要素数は 1 です。Arrays.stream(int[]) は int 配列専用のオーバーロードで、要素を並べた IntStream を返すので 4 件になります。Arrays.stream(配列, 開始, 終了) は開始を含み終了を含まない範囲なので、インデックス 1 と 2 の 6 + 7 = 13 です。プリミティブ型の配列からストリームを作るときは、Arrays.stream か IntStream.of を使います。",
  },

  // ------------------------------------------------------------ 並列ストリームと forEachOrdered
  {
    id: 10344,
    topic: "streams",
    variantOf: "gold-streams-parallel-order",
    question: "次のコードをコンパイルおよび実行した場合の結果として正しいものはどれか。1つ選びなさい。",
    className: "ParallelOrdered",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ParallelOrdered {",
      "    public static void main(String[] args) {",
      "        List<Integer> list = List.of(1, 2, 3, 4, 5, 6, 7, 8);",
      "        StringBuilder sb = new StringBuilder();",
      "        list.parallelStream()",
      "            .map(n -> n * 10)",
      "            .forEachOrdered(n -> sb.append(n).append(\" \"));",
      "        String r = list.parallelStream().map(String::valueOf).collect(Collectors.joining(\",\"));",
      "        System.out.println(sb.toString().trim() + \" \" + r);",
      "    }",
      "}",
    ],
    choices: [
      "10 20 30 40 50 60 70 80 1,2,3,4,5,6,7,8",
      "実行のたびに 10 から 80 の並び順が変わり、1,2,3,4,5,6,7,8 は常に同じ順で出力される",
      "実行のたびに両方の並び順が変わる",
      "10 20 30 40 50 60 70 80 と出力され、後半は実行のたびに並び順が変わる",
      "並列ストリームで StringBuilder を使っているため、実行時に ConcurrentModificationException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "10 20 30 40 50 60 70 80 1,2,3,4,5,6,7,8" },
    explanation:
      "forEachOrdered は、並列ストリームでも「出現順序」を持つストリーム（List から作ったものなど）であれば、その順序どおりに 1 つずつ処理を実行します。map は並列に実行されても、forEachOrdered の動作は順番に（同時に実行されずに）行われるので StringBuilder への追記も安全です。collect(Collectors.joining) のようなリダクションも、分割した部分結果を元の順序どおりに結合するので結果の順序は保たれます。順序が保証されないのは forEach や findAny のように順序を気にしないと明示した操作で、並列ストリームでは結果を副作用で集めずにリダクションで得るのが安全です。",
  },

  // ------------------------------------------------------------ collect の 3 引数版
  {
    id: 10345,
    topic: "streams",
    variantOf: "gold-streams-collect-supplier",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MutableCollect",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class MutableCollect {",
      "    public static void main(String[] args) {",
      "        StringBuilder sb = Stream.of(\"a\", \"b\", \"c\")",
      "                .collect(StringBuilder::new, StringBuilder::append, StringBuilder::append);",
      "        ArrayList<Integer> list = Stream.of(3, 1, 2)",
      "                .collect(ArrayList::new, ArrayList::add, ArrayList::addAll);",
      "        System.out.println(sb + \" \" + list);",
      "    }",
      "}",
    ],
    choices: ["abc [3, 1, 2]", "abc [1, 2, 3]", "cba [3, 1, 2]", "7行目でコンパイルエラーになる", "9行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "abc [3, 1, 2]" },
    explanation:
      "3 引数の collect(supplier, accumulator, combiner) は、可変の入れ物を作り（supplier）、各要素をその入れ物に追加し（accumulator）、並列処理で作られた入れ物同士を統合する（combiner）という「可変リダクション」です。StringBuilder::new で空のビルダーを作り、append で各文字列を追加するので abc になります。ArrayList でも同様に、add で追加し addAll で統合します。reduce が「新しい値を作り続ける」のに対し collect は「1 つの入れ物に詰めていく」ので、文字列の連結やコレクションの構築では collect のほうが無駄なオブジェクトを作らずに済みます。",
  },

  // ------------------------------------------------------------ flatMap と mapMulti
  {
    id: 10346,
    topic: "streams",
    variantOf: "gold-streams-flatmap",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlatOptional",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class FlatOptional {",
      "    static Optional<Integer> parse(String s) {",
      "        try {",
      "            return Optional.of(Integer.parseInt(s));",
      "        } catch (NumberFormatException e) {",
      "            return Optional.empty();",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Integer> nums = Stream.of(\"1\", \"x\", \"3\", \"\")",
      "                .map(FlatOptional::parse)",
      "                .flatMap(Optional::stream)",
      "                .toList();",
      "        System.out.println(nums);",
      "    }",
      "}",
    ],
    choices: [
      "[1, 3]",
      "[Optional[1], Optional.empty, Optional[3], Optional.empty]",
      "[1, 0, 3, 0]",
      "実行時に NumberFormatException がスローされる",
      "16行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "[1, 3]" },
    explanation:
      "Optional.stream()（Java 9 で追加）は、値があればその 1 要素だけのストリーム、空なら空のストリームを返します。これを flatMap に渡すと、空の Optional は消え、値のある Optional は中身の値に置き換わるので、「変換に成功した要素だけを残す」処理を 1 行で書けます。parse の中で NumberFormatException を捕捉しているので例外は外に出ません。filter(Optional::isPresent).map(Optional::get) と書くよりも、get を呼ばずに済み安全です。",
  },
  {
    id: 10347,
    topic: "streams",
    variantOf: "gold-streams-flatmap",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "FlatNested",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class FlatNested {",
      "    public static void main(String[] args) {",
      "        List<List<String>> nested = List.of(List.of(\"a\", \"b\"), List.of(), List.of(\"c\"));",
      "        long n = nested.stream().flatMap(List::stream).count();",
      "        int total = nested.stream().mapToInt(List::size).sum();",
      "        List<String> r = nested.stream()",
      "                .flatMap(l -> l.stream().map(s -> s + l.size()))",
      "                .toList();",
      "        System.out.println(n + \" \" + total + \" \" + r);",
      "    }",
      "}",
    ],
    choices: ["3 3 [a2, b2, c1]", "3 3 [a2, b2, c1, 0]", "3 3 [a1, b1, c1]", "2 3 [a2, b2, c1]", "10行目でコンパイルエラーになる"],
    correct: [0],
    expected: { kind: "output", stdout: "3 3 [a2, b2, c1]" },
    explanation:
      "flatMap は各要素を「ストリーム」に変換し、それらを 1 本のストリームに連結します。空のリストからは空のストリームができるので、連結後の要素数は 3 です。map を使うと Stream<Stream<String>> という入れ子ができるだけなので、要素を平らに展開したい場合は flatMap を使います。flatMap に渡すラムダ式の中では外側の要素（リスト l）を参照できるので、s + l.size() のように外側と内側の情報を組み合わせた要素を作れます。",
  },

  // ------------------------------------------------------------ partitioningBy
  {
    id: 10348,
    topic: "streams",
    variantOf: "gold-streams-partitioning",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "PartitionEmpty",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class PartitionEmpty {",
      "    public static void main(String[] args) {",
      "        Map<Boolean, Long> p = Stream.of(2, 4, 6)",
      "                .collect(Collectors.partitioningBy(n -> n % 2 != 0, Collectors.counting()));",
      "        Map<Boolean, List<Integer>> g = Stream.of(2, 4, 6)",
      "                .collect(Collectors.groupingBy(n -> n % 2 != 0));",
      "        System.out.println(p + \" \" + g);",
      "    }",
      "}",
    ],
    choices: [
      "{false=3, true=0} {false=[2, 4, 6]}",
      "{false=3} {false=[2, 4, 6]}",
      "{false=3, true=0} {false=[2, 4, 6], true=[]}",
      "{true=0, false=3} {false=[2, 4, 6]}",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{false=3, true=0} {false=[2, 4, 6]}" },
    explanation:
      "partitioningBy の結果のマップは、該当する要素があるかどうかにかかわらず、常に false と true の 2 つのキーを持ちます。奇数は 1 つも無いので true には counting の初期値 0 が入ります。一方 groupingBy は実際に現れた分類キーだけをマップに入れるので、true のキーは存在しません。条件で 2 分割する場合は partitioningBy を使うと、get(true) が null になる心配をせずに済みます。",
  },

  // ------------------------------------------------------------ toMap
  {
    id: 10349,
    topic: "streams",
    variantOf: "gold-streams-tomap",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "ToMapMerge",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class ToMapMerge {",
      "    public static void main(String[] args) {",
      "        Map<Integer, String> m = Stream.of(\"cat\", \"ox\", \"dog\", \"yak\", \"be\")",
      "                .collect(Collectors.toMap(String::length, s -> s, (a, b) -> a + \"|\" + b, TreeMap::new));",
      "        System.out.println(m + \" \" + m.getClass().getSimpleName());",
      "    }",
      "}",
    ],
    choices: [
      "{2=ox|be, 3=cat|dog|yak} TreeMap",
      "{2=be, 3=yak} TreeMap",
      "{2=ox, 3=cat} TreeMap",
      "{2=ox|be, 3=cat|dog|yak} HashMap",
      "実行時に IllegalStateException がスローされる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "{2=ox|be, 3=cat|dog|yak} TreeMap" },
    explanation:
      "toMap はキーが重複すると既定では IllegalStateException をスローしますが、第 3 引数にマージ関数を渡すと、既存の値と新しい値からどちらを残すか（あるいは結合するか）を決められます。ここでは出現順に \"|\" でつなぐので、長さ 3 の単語は cat|dog|yak になります。第 4 引数はマップの生成方法で、TreeMap::new を指定したのでキーの昇順に並び、実際のクラスも TreeMap です。groupingBy でも似た集計はできますが、「キーごとに値を 1 つにまとめる」なら toMap とマージ関数の組み合わせが直接的です。",
  },

  // ------------------------------------------------------------ min / max
  {
    id: 10350,
    topic: "streams",
    variantOf: "gold-streams-min-max",
    question: "次のコードをコンパイルおよび実行した場合の結果はどれか。1つ選びなさい。",
    className: "MinMaxTest",
    code: [
      "import java.util.*;",
      "import java.util.stream.*;",
      "",
      "public class MinMaxTest {",
      "    public static void main(String[] args) {",
      "        Optional<String> longest = Stream.of(\"pear\", \"banana\", \"kiwi\", \"cherry\")",
      "                .max(Comparator.comparing(String::length));",
      "        Optional<String> first = Stream.of(\"pear\", \"banana\", \"kiwi\")",
      "                .min(Comparator.naturalOrder());",
      "        Optional<String> none = Stream.<String>empty().max(String::compareTo);",
      "        System.out.println(longest.get() + \" \" + first.get() + \" \" + none.isPresent());",
      "    }",
      "}",
    ],
    choices: [
      "banana banana false",
      "cherry banana false",
      "banana kiwi false",
      "banana banana と出力された後、NoSuchElementException がスローされる",
      "7行目でコンパイルエラーになる",
    ],
    correct: [0],
    expected: { kind: "output", stdout: "banana banana false" },
    explanation:
      "Stream の max / min は Comparator を必ず受け取り、空のストリームに備えて Optional を返します。banana と cherry はどちらも長さ 6 で比較結果が等しいですが、max は等しい場合に先に現れた要素を返すため banana になります。min(Comparator.naturalOrder()) は辞書順で最小の banana です。空のストリームの max は空の Optional を返し、例外にはなりません。IntStream の max と違い、Stream<T> の max には要素の比較方法を知る手段が無いので、Comparator の指定が必須になっています。",
  },
];
